### ISSUE TITLE
Bug: Skylands - OTG stuck on loading screen after relogging in separate dimension

### ISSUE THREAD

**Issue by NeonRexodus** [PG85/OpenTerrainGenerator#100]
Though the server console reports a successful connection, clients cannot log off/log in a separate OTG dimension (currently tested with Skylands and a forced secondary Biome Bundle dimension/world) without becoming stuck on an infinite loading screen. The server console reports successful login, “——- has joined the game”, despite clientside loading screen. 

If allowing trying to join over a longer period time, it will slowly lag out the entirety of the server without allowing a successful login client-side.

Mods (server side)
Forge 1.12.2 (2555 recommended build) 
OTG 1.12.2 v2
OTG Biome Bundle v6.1
OTG Skylands v5

If more info is needed, let me know.

**Comment by PG85** [comment]
Skylands can take a very long time to load unfortunately and can cause a spike in memory usage, can you check if your server is running out of memory? Also, make sure to disable all pre-generators (/otg pregen 0 <dimension id>). I assume you've also tried restarting your server already?

**Comment by NeonRexodus** [comment]
I am able to generate/load the world perfectly fine as long as I don’t relog there. The error is only fixable via editing player.dat. Pregen made no difference, and I’ve restarted plenty :)

**Comment by PG85** [comment]
I'll have to chalk it up to Skylands being really laggy then, we still have to figure out what exactly is causing that. The problem is it's the terrain itself that appears to be causing the lag, not OTG. If you load a Skylands world without OTG it still lags. So if you can find any clues as to which terrain features might be causing problems, please let me know.

**Comment by NeonRexodus** [comment]
Based on my experience/testing, it seems to have had nothing to do with Skylands itself (tested with same result for other custom dimensions including a secondary “forced” biome bundle copy dimension and a “forced” vanilla-like dimension as well), but with a conflict between server/OTG/client with how server thinks a player doesn’t exist in a certain dimension (I should’ve added that the console eventually reported something along the lines of the player entity not existing/being able to be assigned during a relog attempt on an OTG dimension) 

My second hypothesis as to what’s happening has to do with another bug I encountered with OTG where a given worldconfig can be misinterpreted if it’s used to generate a secondary world/dimension. I’m planning on going into much, much more detail on this one in a separate issue with over 24-32 hours of rigourous testing on this one. (In short; How I first found out about the worldconfig bug; I duplicated biome bundle world file within OTG renamed it, made a dimension to match...just to find out that horrific interpretation of the worldconfig occurs (as well as horrifically improperly generated vanilla ocean biomes and all vanilla ocean biome variants) and I plan to gather as much detail, screenshots, and logs for interpretation of this one. Further testing of this one revealed it was not exclusive to any specific worldconfig)

Again, the server reports the player logs in successfully while client is stuck in the loading screen. 

In my experience, and please correct me if I’m in error; If the error revolves around world loading issues or lag, it’ll allow a successful login both server and clientside, allowing visible inventory without the client’s version of the world or inventory contents loading. This is not what occurs here.

Can do further/more extensive testing if desired alongside providing console results + listed variables, various resets (of OTG configs, worlds, etc.)

I will let you know if I can reproduce the console result and show the log. 

— 

PS, thanks for prompt reply! I must say that I truly love this mod and the capabilities that it brings your average player...and I truly hope this can get fixed as it’s game breaking for the things I’m trying to do with it for my server.

**Comment by NeonRexodus** [comment]
Oh I saw your edit — This is not Skylands-specific. I’ve tested with other custom dimensions to same effect no matter the worldconfig. Apologies for my poor wording in the original post.

**Comment by PG85** [comment]
Hey thanks for the kind words, will reply more later, one quick note:

> a conflict between server/OTG/client with how server thinks a player doesn’t exist in a certain dimension

That bug is likely caused by a packet not arriving on the client when connecting to the server, which is known to happen with clients using forge version 1.12.2-14.23.0.2538 and up. Is fixed in OTG 1.12.2 v3 (release asap).

**Comment by NeonRexodus** [comment]
Perfect! I really appreciate your hard work. Looking forward to v3!

**Comment by NeonRexodus** [comment]
Fixed in OTG V3!! Thanks :)

**Comment by PG85** [comment]
You're welcome, thanks for the feedback :).
