### ISSUE TITLE
Server inevitably crashes upon users exploring

### ISSUE THREAD

**Issue by darkshadow1809** [PG85/OpenTerrainGenerator#102]
So.. Unfortunately I cannot really provide any type of crash log... The user simply joins the server, goes to explore and inevitably the server runs into a memory leak error. Theres only one time where the server actually displayed this simple error however since then I've not been able to get it to parse that certain log file.

Exception in thread "Server Watchdog" Dec 14, 2017 5:50:54 PM io.netty.util.ResourceLeakDetector reportUntracedLeak
SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.

No clue why this happened... The server seemed to have run quite good at first. 

I've tried following instructions as displayed but to no avail.

Another interesting crash where I had no idea where this one came from or how to solve it. unfortunately after having so many issues I decided to remove OTG and nothing crashed anymore. Server seemed very stable and happy with the mod gone. However the vanilla generation is absolutely horrible and this mod is a must so I hope with the limited amount of information that you might be able to solve it.
[crash-2017-12-11_21.21.02-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/1584764/crash-2017-12-11_21.21.02-server.txt)

PS: As for the memory leak error I decided to dedicate as much ram as possible with steps in between ranging from 4gb's of ram up to 16.. It just instantly crashed upon loading that single chunk my user wanted to explore. 

The server itself has more then enough resources to handle it. hopefully these issues can be resolved soon.

Thanks in advance!

**Comment by PG85** [comment]
Hey, thanks for reporting this and hmm okay that's worrying. May be related to the fixes for leaks that forge did for the networking code since 1.12.2-14.23.0.2538, this also caused other problems which have been solved in 1.12.2-v3 (release asap). When v3 is available (should be later today), could you confirm if that fixes it for you? I'll give you a heads up when it's available.

**Comment by darkshadow1809** [comment]
You're wicked fast bro! Thanks :) I'll definitely test it on a whole other server! Was gonna restart for christmas anyway haha :p seems I got a bit of testing to do beforehand. really didn't think you'd get it done so fast though.

Thanks again for all the hard work you put in!

**Comment by darkshadow1809** [comment]
Tested with new version. Seems to be solved @PG85 :) Thanks! I'll re-open an issue if I find any incompatibility / memory leak.

**Comment by PG85** [comment]
Sweet, thanks for confirming!
