### ISSUE TITLE
Crash on server startup (NullPointer)

### ISSUE THREAD

**Issue by SaadArdati** [PG85/OpenTerrainGenerator#103]
https://hastebin.com/uwatixobaj.swift
mc 1.12.2
using otg v4 
with biome bundle v6.1

forge is 2560

server.properties:
level-name=world/Biome Bundle
level-type=OTG

**Comment by KorDum** [comment]
```
level-name=world/Biome Bundle
```
You can try
```
level-name=Biome Bundle
```

**Comment by SaadArdati** [comment]
That seems to have fixed it. Thank you. the wiki should update
