### ISSUE TITLE
OTG+TF - Server crashes with twilight forest (TFBiomeFireflyForest)

### ISSUE THREAD

**Issue by darkshadow1809** [PG85/OpenTerrainGenerator#104]
I know this sounds like a familiar issue however it isn't quite the same. The other crashes were related to other biomes which have been fixed according to Twilight Forest as stated here https://github.com/TeamTwilight/twilightforest/commit/1d829d06fd3f67a6326b891ca3f1e80b79f4e5a0

However I have not yet seen this error floating around also relating to biomes.. Maybe this is on your end after all? which I highly doubt but maybe you could create a work-around for it? because other mods are bound to do this. Maybe  stop OTG from conflicting with other dimensions other then the overworld/nether/end?

[crash-2017-12-28_23.12.26-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/1592220/crash-2017-12-28_23.12.26-server.txt)

**Comment by PG85** [comment]
Hey, thanks for reporting this. This looks like the exact same problem but in a different bit of code. Might be that the TF devs overlooked it, hopefully they will be kind enough to fix it there too. Unfortunately working around this on the OTG end would require a lot of work and would introduce all kinds of drawbacks and limitations for customising default biomes.

**Comment by Zygus42** [comment]
Has this been reported to the Twilight Forest devs ?  Because I didn't.

**Comment by SanityCh3ck** [comment]
From what I can see that's the exact same crash that the linked commit is going to prevent. There simply hasn't been a Twilight Forest release since then.

**Comment by PG85** [comment]
TF is reportedly working fine with v7 after a number of fixes :).
