### ISSUE TITLE
Bug - Server crashes while pregenerating

### ISSUE THREAD

**Issue by BrainStone** [PG85/OpenTerrainGenerator#106]
While pregenerating the server keeps crashing randomly. From what I've seen it's always the watchdog.  
Crashlog: https://hastebin.com/uhojamuyex.pl  
Log: https://hastebin.com/lipozivufo.md

**Comment by RikAzerion** [comment]
Hey, thanks for reporting this. Unfortunately the error is non-descriptive, it may just be that the watchdog is detecting that the server is extremely slow and shuts it down in response (although I would expect it to do it more gracefully..). Could this be a memory issue? The server log should show pre-generator status messages, if I'm not mistaken they should include information about memory usage (you may have to set log level to trace in OTG.ini to see them). I'll do some testing on my end as soon as I have the time.

**Comment by BrainStone** [comment]
From what I've been seeing memory was fine. I'm very well aware that this isn't much of a description. Though it seems like a deadlock situation occurs during chunkloading.

**Comment by PG85** [comment]
Links don't work anymore unfortunately, hope this has been fixed already for v7.
