### ISSUE TITLE
Feature: No client requirement for Forge servers

### ISSUE THREAD

**Issue by BrainStone** [PG85/OpenTerrainGenerator#107]
Changes between 1.12.2 v2 and 1.12.2 v4 vanilla clients can no longer join as the server tells them they need Forge.

This is somewhat related to #98.

As far as I understand it there have been features added to the Forge version that make it incompatible with vanilla. I'd highly apprechiate an option to disable them or have a version that doesn't have these features so that vanilla and Forge clients without the mod can join.

**Comment by PG85** [comment]
Unfortunately for 1.12 I had to make changes that broke the client, OTG-core was required to fix these. I'll see if I can remove the need for OTG-core in the future by finding another way of registering biomes. When that's done I could make a feature to allow non-OTG clients (but not let them travel dimensions etc).

**Comment by BrainStone** [comment]
An idea would also be a lite or sponge version that doesn't even have the dimensions features and other features that would make the client required. (Similar to the Spigot version but with biome colors).

**Comment by PG85** [comment]
We're designing the 1.16 implementation with this in mind, if possible. Client-side components (if any) should be modular (ideally). For 1.12.2, we won't fix this anymore. Thanks for the feedback though!

**Comment by BrainStone** [comment]
I apprechiate that 👍🏼
