### ISSUE TITLE
Compatibility issues with OTG multiverse and other modded dimensions

### ISSUE THREAD

**Issue by PersonTheCat** [PG85/OpenTerrainGenerator#108]
Forge 14.23.1.2555
OTG 1.12.2 v4
TF 274 - 296
[Crash Report](https://pastebin.com/Ew5X7GVr)

Entering other dimensions added by OTG results in a crash in the presence of TF, where vanilla dimensions and dimensions added by other mods (e.g. Aether Legacy) are unaffected. This seems like a TF bug. Posting here just in case. 

Cross posted to TF issue tracker [here.](https://github.com/TeamTwilight/twilightforest/issues/397) issue #397

**Comment by PersonTheCat** [comment]
Just updating here because one of the TF devs seems to think this is related to the way OTG calls WorldServer#init, causing issues with advancementManager. They highlighted [these lines in OTGs code](https://github.com/PG85/OpenTerrainGenerator/blob/1.12-OTG%2B/platforms/forge/src/main/java/com/pg85/otg/forge/OTGWorldServerMulti.java#L66-L87). 

Retesting this, I found that there are still multiverse issues when using Aether Legacy. Each time the world is loaded, new DIM folders are created for secondary dimensions, causing them to regenerate and resulting in a loss of progress. Not opening this in a new issue because it might be related, but I will update the title. 

Edit: deleted a redundant word.

**Comment by PG85** [comment]
Hey, thanks for the bug report, that's very helpful! Will look into this a.s.a.p.

**Comment by PersonTheCat** [comment]
Thank you! You're the best.

**Comment by PG85** [comment]
Well spotted by the TF devs, there was one line missing there, newly introduced in MC 1.12. AdvancementManager problem should be fixed in the next version of OTG.

**Comment by PG85** [comment]
And oh yeah, let's keep another issue open for the multiple DIM folders issue :).

**Comment by Kasia1403** [comment]
Could You write me if OTG conflicts with Aether Legacy ?

![2022-05-14_16 08 49](https://user-images.githubusercontent.com/54236098/168429854-5dd5fcef-8b93-4eac-ad77-33c90aa5b848.png)

Why it is like that ? Why does this happen ?

[latest.log](https://github.com/PG85/OpenTerrainGenerator/files/8693100/latest.log)
