### ISSUE TITLE
[Forge] Server Crash at Login. BiomeDict - MoCreatures

### ISSUE THREAD

**Issue by Sandriell** [PG85/OpenTerrainGenerator#11]
Getting the following crash at login https://gist.github.com/Sandriell/e4a9befbed23dcfbfdf5a818a0b9d3d8

Looks like its MoCreatures trying to check biomes for spawning. The first thing referenced is BiomeDictionary, so I am guessing this is related to the previous issues with BiomeDictionary support.

Looks like this issue over at BiomeBundle is related: https://github.com/BiomeBundle/BiomeBundle/issues/58

**Comment by PG85** [comment]
Thanks for the bug report, could you try v16 from https://minecraft.curseforge.com/projects/open-terrain-generator/files and tell me if that fixes the problem?

**Comment by Sandriell** [comment]
v16 did not fix it.

**Comment by PG85** [comment]
I've had multiple reports of the biomedict exception with different mods, have spent half a day testing but I cannot get it to crash. Do you know of a way to reproduce the bug?

**Comment by PG85** [comment]
Please try v17 at https://minecraft.curseforge.com/projects/open-terrain-generator/files/2413721 and tell me if that fixes the problem. Your existing worlds affected by the bug should work again with this build. Thanks!

**Comment by PG85** [comment]
Other users who were getting the same exception have reported it as being fixed by v17. Closing this issue, thanks for reporting!
