### ISSUE TITLE
Bug - /locate does not work on spigot, does on forge

### ISSUE THREAD

**Issue by TheForgottenKing** [PG85/OpenTerrainGenerator#110]
Tested without other plugins/mods

On forge, when running /locate Monument, the chat spits out a set of coordinates

On spigot/paperspigot, when running /locate Monument, the chat spits out an error

I believe this is because these Monuments/Mansions/etc are not marked as Structures correctly on the spigot side of things

This also breaks things in vanilla minecraft, such as the ability for guardians to respawn inside Monuments

I will do further testing and report in this thread

**Comment by TheForgottenKing** [comment]
nvm it works its my end

**Comment by TheForgottenKing** [comment]
Please help :(

**Comment by PG85** [comment]
Hey, thanks for reporting this. I've tested this with OTG v5, spigot server and forge client, new Biome Bundle world. /locate Mansion works fine, could it be that you're using multiverse?

**Comment by TheForgottenKing** [comment]
Am not using Multiverse, but I will run some checks. It might be because of the leftover old world files

**Comment by PG85** [comment]
Have had reports that /locate Stronghold causes problems, need to test.

**Comment by PG85** [comment]
Tested with v7, /locate Stronghold works. Likely also works for v6.
