### ISSUE TITLE
Modded Water Creatures Cannot Spawn

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#111]
Tested a variety of different mods that add mobs to the ocean and even though [OTG's spawn lists include them](https://media.discordapp.net/attachments/307111022257373185/399042082028912641/2018-01-06_03.29.39.png) they do not spawn at all, only vanilla ocean mobs are able to spawn.

**Comment by Misunderstood-Wookiee** [comment]
If I may add - 
They will spawn if the mob is changed from` water_creature` to any other type however they will spawn in the sky or on land depending which type you define in a custom spawner mod. However, mob mods which add new liquids to the game and use their own liquid (example: Lycnites Mobs - Ooze) will spawn in that mods custom liquid block.

**Comment by PG85** [comment]
related to https://github.com/PG85/OpenTerrainGenerator/issues/109

**Comment by PG85** [comment]
Will close this and continue with #109 .
