### ISSUE TITLE
Bug - MinHeight/MaxHeight Trees don't work

### ISSUE THREAD

**Issue by JfromHolland** [PG85/OpenTerrainGenerator#115]
Tree(5,BigTree(MinHeight=65;MaxHeight=75),20,oakf1(MinHeight=86;MaxHeight=116),50)
This setup should generate BigTrees (default Big Oak Tree) between y=65 and y=75 and generate oakf1.bo3 between y=86 and y=116. At least, that's how it works in Terrain Control, but it doesn't work in OTG.
When loading a .bc with this line in it, the game crashes and gives output like this:
[17:07:23 ERROR]: [OTG] Could not find BO2/BO3 BigTree(MinHeight=65;MaxHeight=75) in GlobalObjects and WorldObjects directory for world world.
[17:07:23 ERROR]: [OTG] Could not find BO2/BO3 oakf1(MinHeight=65;MaxHeight=75) in GlobalObjects and WorldObjects directory for world world.

**Comment by PG85** [comment]
Hey, thanks for reporting this. Hmmm, any idea when that feature was introduced for TC?

**Comment by JfromHolland** [comment]
@Pg85 2.4.4
https://github.com/MCTCP/TerrainControl/wiki/Version-history

**Comment by JfromHolland** [comment]
@Pg85 Any idea when this will be fixed?

**Comment by PG85** [comment]
![2019-08-19_20 00 52](https://user-images.githubusercontent.com/6781444/63288066-1b597b00-c2bc-11e9-9a5b-c4297f5535ca.png)
Fixed for v8_r2, should work for default trees, BO2's and BO3's.
