### ISSUE TITLE
Biomes can be populated up to 4 times

### ISSUE THREAD

**Issue by JfromHolland** [PG85/OpenTerrainGenerator#116]
I just proved that ReplaceBlocks (RB) indeed works twice. Or actually, four times. Read along, I’d say.
For the experiment, this was the SurfaceAndGroundControl setting:
SPONGE, STONE, 0.0, SAND, SAND, 10.0

And this was the ReplaceBlocks setting:
(GRASS,SAND),(SPONGE,GRASS)

1. If chunks are only populated once, half of the biome should be covered in Sand and half of the biome should be covered in Grass (which was originally Sponge).
2. If chunks are populated twice, the Grass from option 1 gets replaced again with Sand. The entire biome should be covered in Sand.

The entire biome was covered in Sand, so option 2 is what happens.

But actually, something more interesting happens.
The biome is populated THREE times!
I set the SurfaceBlock to be only Sponge now, with the same RB settings.
Then I used a Pumpkin plant with a very high frequency and varied the SourceBlock to be one of these tree: Sponge, Grass, Sand.
No matter what SourceBlock I selected, the Pumpkins spawned.
When I selected all of these, I got three times as many pumpkins!
Adding another block change (Sand to Snow) in front of everything else in the ReplaceBlocks settings and setting the SourceBlock for Pumpkins to Snow, yielded pumpkins yet again.
This shows that the biome can be populated at least four times.

**Comment by PG85** [comment]
Hey J, you're right, it is a bit like each chunk gets populated four times. To be more precise, each chunk gets populated once but spawns resources over a 2x2 chunk area. This allows for resources to be spawned on/across chunk borders. If it were impossible to spawn things on/across chunk borders, you'd see a grid effect with objects like trees, also no objects larger than 16x16 could be spawned (32x32 is the max for normal resources atm).
