### ISSUE TITLE
[1.12.2 - Mod compatibility] Crash involving Ancient Warfare 2 structure generation

### ISSUE THREAD

**Issue by NotAVerb** [PG85/OpenTerrainGenerator#118]
Game crashed shortly upon creating a new world with both OTG-v4 and AW2-v2.4.37 installed.
Crash log:
https://gist.github.com/NotAVerb/c03f1a9bf01710deb123cb858f57229a
Thread where one of the Ancient Warfare devs took a look at the problem:
https://github.com/P3pp3rF1y/AncientWarfare2/issues/568

**Comment by PG85** [comment]
Hey, thanks for reporting this. Just fixed it, fix will be in the next version. Also responded to the AW thread.
