### ISSUE TITLE
Crash with Twilight Forest

### ISSUE THREAD

**Issue by Zygus42** [PG85/OpenTerrainGenerator#119]
OpenTerrainGenerator-1.12.2 - v4
Biome_Bundle-1.12.2-v6.1
twilightforest-1.12.2-3.5.263-universal
forge-1.12.2-14.23.1.2565-installer-win

[crash-2018-01-16_21.50.24-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/1635360/crash-2018-01-16_21.50.24-server.txt)

Made a pool, jumped into it to go to twilight forest and crash.  

Please let me know if this ought to be posted on the Twilight Forest issues instead.

**Comment by PG85** [comment]
Hey, thanks for reporting this. This is the same as https://github.com/PG85/OpenTerrainGenerator/issues/104. Not sure if it has been reported and/or fixed by the TF devs yet.
