### ISSUE TITLE
Abyssalcraft - can not create world

### ISSUE THREAD

**Issue by Seth0067** [PG85/OpenTerrainGenerator#12]
Probably bvecause it adds new biomes, world gen with abyssalcraft locks up before the world can complete generation.  [Here's my FML log](https://pastebin.com/kxW1jxA7).  

Removed Abyssalcraft and was able to proceed with world creation

**Comment by PG85** [comment]
Thanks for the bug report, have added it to the new bugs thread at https://www.reddit.com/r/openterraingen/comments/67uzha/mod_compatibility_bugs_report_them_here/

**Comment by PG85** [comment]
This should be solved with v16, https://minecraft.curseforge.com/projects/open-terrain-generator. Closing this issue, if v16 doesn't fix this then feel free to re-open.

**Comment by Seth0067** [comment]
Hi PG85, the update does fix the crash, but does the update allow for the Abyssalcraft biome generation as the mod requires?  I pregenerated a few worlds and do not see the biomes the mod creates - Darklands, Coralium Infested Swamp, etc.  Thanks for looking in!
