### ISSUE TITLE
OTG+TF/EU2 - Dimensions Server crash 1.12.2 (TF 3.6.324)

### ISSUE THREAD

**Issue by Vitali8** [PG85/OpenTerrainGenerator#122]
Hey-hey, we have a server crash, again. There is a crash of the server if you try to get into other dimensions, for example, the twilight forest or Extra Utilities 2 dimensions, but with the dimensions of Galacticraft (and Extra Planets) there are no problems. (In a single player, everything is fine.)
Can you tell what's wrong?

Crash-log here:
https://pastebin.com/08V9Ncy9

**Comment by PG85** [comment]
Hey, sorry for the late reply. So when you're in an OTG dimension and try to go through a portal to a TF or EU2 dimension, the crash happens?

**Comment by Vitali8** [comment]
Yes.

**Comment by PG85** [comment]
Fixed with v7.
