### ISSUE TITLE
Request - Remove Chunk Cascading Prevention

### ISSUE THREAD

**Issue by Speiger** [PG85/OpenTerrainGenerator#124]
Basically when chunk cascading happens it has a reason because something tries to generate in there.
When you prevent that for example in a pregeneration these chunks don't get fully pregenerated (even with your own tool) 
What that can cause is that these chunks never can full generate in the first run since world genRNG is never Random its always the same. So if you guys prevent chunkcascading these chunks get always prevented to generate because of casacding and you need to run a Pregenerator multible times or a player always back and forth to cause these chunks to fully generate.

With that you cause Server owners or SSPs to have more trouble or have to use Pregeneration mutlible times to just get the full generation done.

**Comment by PG85** [comment]
Hey, thanks for reporting this. Will take a look at this for the next release.

**Comment by PG85** [comment]
Cascading chunk prevention has been removed, OTG does still do reduced resource spawning in affected chunks in an attempt to prevent further cascade.

**Comment by Speiger** [comment]
Cool, i might make a couple  tests to check if this is now compatible to ChunkPregen.
