### ISSUE TITLE
Bug - FrozenSurfaceHelper StackOverflowError while generating

### ISSUE THREAD

**Issue by BrainStone** [PG85/OpenTerrainGenerator#125]
While generating some chunks I get this error:

https://hastebin.com/jidikelece.sm

More of the same:  
https://openeye.openmods.info/crashes/7a6546709479697cd4dadb7e9a054d68  
https://openeye.openmods.info/crashes/30cb54a7c994d15b0f1c313a4abbc56c  
https://openeye.openmods.info/crashes/ce4cd0be83f30ad57436dbf09481136a

I happend when pregenerating the world with https://minecraft.curseforge.com/projects/chunkpregenerator. The exact see is: -774082255 and the error occured while running `/pregen startexpansion square 0 0 440 640 0 PostProcessing`

**Comment by Speiger** [comment]
To give a bit of an info:
https://github.com/PG85/OpenTerrainGenerator/blob/1.10.2/common/src/main/java/com/khorn/terraincontrol/generator/FrozenSurfaceHelper.java#L213
This current is actually never increased at all that just causes an infinte loop. (I searched with browser search where this field is used and its only reset but never increased)

**Comment by BrainStone** [comment]
Or this line in the 1.12 branch: https://github.com/PG85/OpenTerrainGenerator/blob/1.12-OTG%2B/common/src/main/java/com/pg85/otg/generator/FrozenSurfaceHelper.java#L214

**Comment by PG85** [comment]
Hey, thanks for reporting this. Fixed by @BrainStone https://github.com/PG85/OpenTerrainGenerator/pull/127 :). Will include this in the next release.
