### ISSUE TITLE
Bug - Crash on server start after copying world from SP to MP. NoSuchMethodError WorldSettings

### ISSUE THREAD

**Issue by khionu** [PG85/OpenTerrainGenerator#126]
Crash Report: https://gist.github.com/5ac308c17a4e3d21cb7eb14a60a0587a
Tree of `mods` directory: https://gist.github.com/516dabf3230d5923389cff79399991c6
Using Forge version `14.23.2.2611` and OTG version v4.

I am attempting to use a world I created in SP then moved over to a server.

Please let me know if you need anymore information.

**Comment by khionu** [comment]
Apparently [this function](https://github.com/PG85/OpenTerrainGenerator/blob/1.12-OTG%2B/platforms/forge/src/main/java/com/pg85/otg/forge/OTGWorldType.java#L70) is not exposed in Minecraft 1.12.2

A friend ran a search on MCP
```
20:07:51 <Pyker> !gm net.minecraft.world.WorldSettings.func_77166_b 1.12.2
20:07:52 -- MCPBot_Reborn: No results found.
20:07:57 <Pyker> !gm func_77166_b 1.12.2
20:07:58 -- MCPBot_Reborn: No results found.
20:08:09 <Pyker> !gm func_77166_b 1.10.2
20:08:09 -- MCPBot_Reborn: === MC 1.10.2: net/minecraft/world/WorldSettings.enableCommands (aig.b) UNLOCKED ===
20:08:10 -- MCPBot_Reborn: Name       : b => func_77166_b => enableCommands
20:08:11 -- MCPBot_Reborn: Descriptor : ()Laig; => ()Lnet/minecraft/world/WorldSettings;
20:08:11 -- MCPBot_Reborn: Comment    : Enables Commands (cheats).
20:08:12 -- MCPBot_Reborn: Last Change: 2012-08-01 00:33:36-04:00 (mabrowning)
```

**Comment by khionu** [comment]
To note, for whatever it's worth, I don't run into this issue when running it in Single Player, despite the function being called on both the Client and Server.

**Comment by PG85** [comment]
Hey, sorry for the late response, could you try v5? https://minecraft.curseforge.com/projects/open-terrain-generator/files/2530367

**Comment by CrankySupertoonArchive** [comment]
didnt make a different

**Comment by hexchain** [comment]
You can try to disable `allowCommands` (set to 0) by editing the level.dat in your world with an NBT editor. That worked for me.

**Comment by PG85** [comment]
Hey, thanks for reporting. Should be fixed with v7, you can grab a dev build from the OTG Discord at /openterraingen. Cheers.
