### ISSUE TITLE
Request - Use 1.12 Forge Biome ID Assignment

### ISSUE THREAD

**Issue by ddelaparte** [PG85/OpenTerrainGenerator#128]
Can we switch to using Forge's ID assignment for biomes as opposed to the hard-coded IDs in the configs? It's 2018 and we're somehow back to dealing with ID conflicts in Minecraft :(

I understand we need the IDs to properly configure biomes, but can we maybe switch to using lookup codes for this instead? Or just treating the IDs in the configs as lookup codes, but let Forge handle ID assignment?

**Comment by ddelaparte** [comment]
By the way, let me know if there's some option in the configs I'm missing which does this already - You also may want to make that the default if that's the case.

**Comment by PG85** [comment]
Hey, thanks for reporting this. This has been on the to-do list for a while but never had prio, unfortunately I still have some other things to fix before I'll be able to get to it.

**Comment by PG85** [comment]
v7 uses dynamic biome id's for new worlds, so players should not have to edit id's anymore.
