### ISSUE TITLE
Bug - [1.12.2] Incorrect color biome in v5

### ISSUE THREAD

**Issue by KorDum** [PG85/OpenTerrainGenerator#129]
![image](https://user-images.githubusercontent.com/1331559/36086501-dc1bdd76-0fdd-11e8-81c8-5c3190f27ce7.png)

This example of Autumnal Woods Hills from Biomes Bundle. As you can see, before update it has yellow color (right side of screenshot), after update — default vanilla green.

**Comment by PG85** [comment]
Hey. thanks for reporting this. Do you see any exceptions related to packets in the logs when connecting by any chance? In-game do you see a red warning when connecting that a packet could not be received?

**Comment by KorDum** [comment]
Yes, when stainding in that biome in console spam:
```
[20:22:30] [JM-task-4/WARN]: java.lang.NullPointerException
```
every 2-3 second 6-10 lines without stacktraces

**Comment by PG85** [comment]
I've not been able to reproduce this, can you delete OTG-Core and try again? And if that doesn't work, try a new world and see if that gives the same error?

**Comment by KorDum** [comment]
Yes, new world with same seed works fine...
Is there any idea how to fix it in an already existing world?

**Comment by KorDum** [comment]
Each chunk in affected region files (*.mca) contains wrong biome IDs.

**Comment by KorDum** [comment]
I don't know, why biome ids in level.dat become different... I'll try fix it with NBT Explorer.

**Comment by KorDum** [comment]
Hmm. level.dat generally does not affect.
I was able to fix it. Get from mca-file (from chunk) correct biome ID and put in to `WorldConfig.ini`.

**Comment by KorDum** [comment]
ForestEnder too. I changed ID in WorldConfig.ini, but ForestEnderMountains and ForestEnderValley don't colored...
