### ISSUE TITLE
Debug Messages are not in the log file

### ISSUE THREAD

**Issue by BakermanLP** [PG85/OpenTerrainGenerator#13]
Hello there (again),

I am just debugging some issues about our new world and ran into a problem. The following settings in the OpenTerrainGenerator.ini doesn't seem to work:
LogLevel: Trace
SpawnLog: true

There are no additional log messages shown up.

BTW Thanks to @PG85 and the whole @BiomeBundle Team for this great thing!

Michael (aka BakermanLP)

**Comment by PG85** [comment]
Oi, thanks for reporting this, I may have been in a bit of a hurry minimising the logging for the release. Currently solving some bugs, will look into this later. You're always welcome to create a pull request ofc :).

**Comment by PG85** [comment]
Looks like log messages do show up in the logs, but not in the MC console.

**Comment by BakermanLP** [comment]
Kind of blindness. I looked in the log. Ok. I close this
