### ISSUE TITLE
Biome Inheritance should override CustomStructure()?

### ISSUE THREAD

**Issue by LanToaster** [PG85/OpenTerrainGenerator#130]
If you inherit a Biome that already has a CustomStructure, and add one yourself, the Final Config file will have two CustomStructure() ressources, which is invalid, and throws an Error.

It would be great if OTG would Merge the CustomStructure() from both Biomes, or if OTG can handle multiple CustomStructure() ressources in a single biome.

**Comment by PG85** [comment]
Hey, thanks for reporting this, will see if I can fix this for the next release.

**Comment by PG85** [comment]
Could look at overriding the parent's customstructure with the child's.

**Comment by PG85** [comment]
For v8_r2: When using BiomeExtends with ResourceInheritance: true, if there are 2 customstructures, the child's structure overrides the parent. To override a parent structure with an empty value, use an empty CustomStructure() resource.
