### ISSUE TITLE
OTG+Lost Cities - Crash on dimension change

### ISSUE THREAD

**Issue by Zygus42** [PG85/OpenTerrainGenerator#131]
OpenTerrainGenerator-1.12.2+-+v5
Biome_Bundle-1.12.2-v6.1
lostcities-1.12-2.0.2

When trying to translate from a Biome Bundle / OTG world to the Lost Worlds dimension, I get the following crash:
[crash-2018-02-14_19.03.17-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/1734815/crash-2018-02-14_19.03.17-server.txt)

I reported this to McJty on Lost Cities mod github (https://github.com/McJty/LostCities/issues/90#issuecomment-363739592), but he recommended that I report it to you instead.

After some more testing I did manage to translate to a Lost Cities dimension once, and then while flying along it crashed again with the same error - so it seems to always be when you get in range of an Ocean biome.

**Comment by PG85** [comment]
Hey, thanks for reporting this, will test with Lost Worlds asap.

**Comment by Zygus42** [comment]
Another oddity is that any River biome created in the Lost Worlds dimension when OTG is the Overworld generator is still called a River biome, but looks like a cut-away section of extreme mountains - giant pillars of stone shaped like a river - very strange.

**Comment by Zygus42** [comment]
The Ocean crash is no longer happening with OpenTerrainGenerator-1.12.2+-+v6, but the river biomes are still the same.  Must be a Biome Bundle issue rather than OTG though, as OTG + the new Dregora pack work fine with rivers when you translate to the Lost Cities dimension.

**Comment by PG85** [comment]
Thanks for reporting! Hopefully the river problem is also solved with v7, which uses dynamic biome id's for new worlds.
