### ISSUE TITLE
Bug - Mesa (Bryce) Generation Problems

### ISSUE THREAD

**Issue by smellyonionman** [PG85/OpenTerrainGenerator#133]
I benefit from this plugin enough to maybe erase the Bryce from my image map, but hoping you can fix it.

Here is the Bryce Mesa with OTG:

![2018-02-20_17 34 50](https://user-images.githubusercontent.com/10687967/36464238-b85eb500-169c-11e8-880e-909897b67302.png)

And here's vanilla generation of the same region:

![2018-02-21_00 17 21](https://user-images.githubusercontent.com/10687967/36464252-cd613504-169c-11e8-864c-92ea72457c91.png)

I used an image map created from AMIDST to get a seed I liked, and used FromImage to generate with OTG.  So for completeness I am going to run a test now where OTG just lets loose with a seed, no image and use /otg ~~biome~~ tp to find an example for us... let's see what we get:

![2018-02-21_00 35 24](https://user-images.githubusercontent.com/10687967/36464680-23a7fd9c-169f-11e8-8c0c-e4f5f7938691.png)

Took a while to find one way out at Z 22000 but there it is... that was done with /mv create otgtest normal -s [SEED] -g OpenTerrainGenerator, when no such folder as /plugins/OpenTerrainGenerator/worlds/otgtest existed, totally fresh : (

I guess this biome is rare enough that nobody noticed yet.  Which is exactly why I'd like to have it for my players :D are you able to invest the resources in this?

PS.  I know someone must be wondering why I used OTG for a vanilla seed... remove strongholds, increase villages, tweak mineshafts and ravines... etc.  It should be used on every world, no?

Update: I've located a Mesa Bryce world in a fresh generation in my single player Forge client, both up-to-date and it came out with the same errors and no other mods enabled.  Sorry but I can't find an example where this doesn't happen.

**Comment by PG85** [comment]
Hey, thanks for reporting this. There has been some funkyness with the mesa surface generator for a while now, sometimes it gets ugly unfortunately. I've got some more important things to fix atm, may take a while before this gets prio.

**Comment by smellyonionman** [comment]
Yeah I have seen some straight lines in the surface of Mesa M specifically and a lack of trees that I don't really care about.  This actually looks like some chunks have been rotated, though I can't be sure.  All of the edges seen are on blocks 0 and 15 of the respective chunks.  Mesa M by comparison is still totally passable (and can be fixed by admins with .bc tweaks anywhoo) but this seems like more than surface gen (as if I really know) and exclusively affects biome ID 165.  I'll shut up now :D

**Comment by PG85** [comment]
For v8_r2 I've aligned the code for the mesa surface generator with vanilla's. Found a few differences that may have been causing problems, so hopefully things should look a bit better. I'm still seeing some wonkyness with mesa's though, straight lines and corners etc. I hope it's less pronounced than before though. Please try v8 and feel free to reopen or create a new issue if mesa's are still bugged.
