### ISSUE TITLE
Bug: Prevent players from spawning in oceans

### ISSUE THREAD

**Issue by PG85** [PG85/OpenTerrainGenerator#136]
Prevent players from spawning in oceans.

**Comment by PG85** [comment]
This should only happen for OTG+ worlds now (v7_r25)

**Comment by PG85** [comment]
May still occasionally happen for non-otg+ worlds too, apparently ><.

**Comment by Ezoteric** [comment]
Using 1.12.2_-_v8.3_r4 non + and still spawn in oceans 1/3 of the time on a new world.
Now i must say that i use these settings in order to get bigger biomes and better oceans:
GenerationDepth: 15
LandRarity: 98
LandSize: 2
LandFuzzy: 4
DefaultOceanBiome: Ocean

**Comment by PG85** [comment]
Fixed for v8.4_r1, to be released on the OTG discord dev channel asap. Please try it when it's available and let me know if you still see any issues, thanks!

**Comment by Ezoteric** [comment]
still happens with both the new versions 8 and 9

**Comment by PG85** [comment]
For v9 it looks for a land biome with solid blocks within 1024 blocks of 0,0. If there isn't one, you may still land in the ocean.

**Comment by Ezoteric** [comment]
thats about right as when it happens land is outside 1024 blocks :P
