### ISSUE TITLE
Suggestion: send ReplaceBiomeBlocks event during chunk generation

### ISSUE THREAD

**Issue by delvr** [PG85/OpenTerrainGenerator#137]
Currently `ChunkProviderOTG` does not publish a `ReplaceBiomeBlocks` event before block replacement like Vanilla does. This makes it difficult for some world-generation mods to hook into OTG. My mod [Streams](https://minecraft.curseforge.com/projects/streams) for example, needs a [coremod/reflection-based patch](https://github.com/delvr/Farseek/blob/1.12/src/main/scala/farseek/world/gen/OtgHook.scala) to trigger it which is of course very brittle and likely to break if OTG internals change. So for OTG to send the event on its own would help keep Streams and similar mods supported in the future.

( Implementation suggestion: at the beginning of `ChunkProviderOTG.addBiomeBlocksAndCheckWater()`, call `ForgeEventFactory.onReplaceBiomeBlock()` in a similar way to vanilla's call in `ChunkProviderOverworld.replaceBiomeBlocks()`. )

**Comment by PG85** [comment]
Hey, thanks for reporting this. There may be other Forge events OTG isn't firing, I try to keep track of them but it can be hard to find all of them :o. Will see if I can fix this for the next release. Nice work on Streams btw :).

**Comment by PG85** [comment]
Sorry for the late repsonse. Need to review ChunkGeneratorOverworld and look for any more significant differences/events that are missing. Will see if I can fix this for the next release (v7).

**Comment by PG85** [comment]
onReplaceBiomeBlocks should be being called before block replacement during terrain gen now. Will be included with v7_r24. Is there any way to test this with streams?
