### ISSUE TITLE
Iterating through biome names to hook into custom plugin

### ISSUE THREAD

**Issue by stifflered** [PG85/OpenTerrainGenerator#138]
Hello,

I have released a plugin that triggers an action when a player enters a new vanilla biome, and lists those biomes in a GUI for easy management of those actions.

One of my users uses your plugin, and so I'd like to add in support for OTG.

Is there a way for me to easily gain a list of all enabled biomes and their associated IDs so that I can list them in my plugin's GUI and then listen as players move from one biome to another?

You can see my plugin here, for reference: https://www.spigotmc.org/resources/musicalbiomes-pro-for-mcjukebox-50-off-sale.53350/

**Comment by PG85** [comment]
Hey @stifflered, thanks for the feedback and sorry for the late response. Unfortunately, I don't know of any event for when players discover a new biome, OTG doesn't implement one either. To fetch the biomes: Unlike other plugins/mods, OTG registers biomes at world creation, not at app start, so if you query the biome registry after world creation / load you should be able to find them.
