### ISSUE TITLE
java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by amalys11** [PG85/OpenTerrainGenerator#14]
I'm testing a new modpack but it is crashing a minute or so after spawning in with a "java.lang.NullPointerException: Exception in server tick loop" error seeming to come from terraincontrol.
I'm currently using v16

https://pastebin.com/nb5xDEFT

**Comment by amalys11** [comment]
I was able to reproduce the error using only:
OTG
Biome Bundle
Advanced Rocketry
Mo' Creatures
Chicken Chunks 1.8+

Based on some other tests, I believe this is related to chicken chunks + certain other mod combinations. (for instance, chicken chunks + mo' creatures didn't cause an issue on it's own)

**Comment by PG85** [comment]
Hey, thanks for reporting this. I've only seen this crash with chicken chunks, looking at its mod description it's likely that it's not compatible with OTG (OTG should decide which chunks to generate/populate when). Will put this on the mod compatibility issues list at https://www.reddit.com/r/openterraingen/comments/67uzha/mod_compatibility_bugs_report_them_here/ and look at it asap.

**Comment by PG85** [comment]
v17 is available at: https://minecraft.curseforge.com/projects/open-terrain-generator/files/2413721. An other user reported that their Chicken Chunks problems seem to be fixed, could you try v17 and confirm this? Thanks!
