### ISSUE TITLE
Index out of bounds exceptions during structuregen

### ISSUE THREAD

**Issue by kreezxil** [PG85/OpenTerrainGenerator#140]
1.12.2-v5 crashes dedicated server Forge 1.12.2 build 2624

Notes:
     just started happening on my dedicated server not sure why

crash report:
https://gist.github.com/929960e884363f0eda82dbef98c521b1

fml server latest:
https://gist.github.com/f91722bff1aec406b90d5e79b0173673

**Comment by PG85** [comment]
Hey, thanks for reporting this, should be fixed with v6/v7.
