### ISSUE TITLE
Implement the CubicChunk mod worldgen

### ISSUE THREAD

**Issue by sirati** [PG85/OpenTerrainGenerator#142]
The [CubicChunk mod](https://github.com/OpenCubicChunks/CubicChunks) allows for world infinite in all directions. OpenTerrainGenerator seems to be a perfect choice as a terrain generator.

**Comment by PG85** [comment]
Hey @sirati97, thanks for the feedback. Feel free to start a discussion about this on the OTG Discord at #openterraingen. Once CubicChunks is more mature and OTG is in better shape, I may have time to look at things like this. Lots of other priorities atm though.
