### ISSUE TITLE
Cannot load another world as dimension

### ISSUE THREAD

**Issue by samolego** [PG85/OpenTerrainGenerator#143]
I'm getting this error when I try to load world Skylands, made with OTG(better said;generator of world is OTG).
[Fri, 16. Mar 2018 16:31:54 CET WARN] [Multiverse-Core] Failed to set the generator for world 'Skylands' to 'OpenTerrainGenerator': java.lang.AssertionError: Biome ID #165 returns custom biome #987 instead of its own.
[Fri, 16. Mar 2018 16:31:54 CET WARN] [Multiverse-Core] This is a bug in the generator plugin, NOT a bug in Multiverse!
[Fri, 16. Mar 2018 16:31:54 CET INFO] Error trying to load world 'Skylands'!

It sounds like a Biome ID conflict. I'm using multiverse to manage worlds, my default one is Biome Bundle. Server is Paper Spigot, latest version.

**Comment by PG85** [comment]
Hey, thanks for reporting. This should be fixed with v7.
