### ISSUE TITLE
Feature: A way to configure which biomegroup may border which other biomegroup

### ISSUE THREAD

**Issue by Guinaro** [PG85/OpenTerrainGenerator#144]
It would be great if we had a way to control biomegroups relations to one another.
Currently if you have e.g. 4 Biomegroups by climate: Polar, Cold, Warm, Hot.
Right now a Polar Biomegroup can be situated right next to your hot biomegroup.
It would make more sense if you could control the settings like.
Polar can only be next to Cold. Cold next to warm and warm next to Hot.
This is simple example, but you could expand this to for instance the different climates of earth which each consist of a set of subclimates, which wouldn't happen being next to eachother.
Probably implementing a blacklist or a whitelist. Can border, Cannot border, Preferred Border Biomegroup(with weights)

**Comment by PG85** [comment]
Old but not dead :o. Have been brainstorming about ways to do something like this, will continue the convo in #720
