### ISSUE TITLE
NPE when preparing structure feature

### ISSUE THREAD

**Issue by oitsjustjose** [PG85/OpenTerrainGenerator#147]
# Versions

- **Minecraft**: 1.12.2
- **Forge**: 14.23.2.2624
- **OTG**: v6
- **Biome Bundle**: 5.1

# The issue

[This](https://pastebin.com/ctwnqSbz) is the crash, it looks like it's related to Mansion generation.

This crash *started* on a modpack with ~101 mods, but I took the same world it was crashing on and transferred it to an instance with only the listed mods. Even with just these few mods, it still crashes exactly the same.

Let me know if you need any other info or tests!

**Comment by oitsjustjose** [comment]
In fact, dropping back to v5 is *still* having this issue...

**Comment by oitsjustjose** [comment]
...any update on this? I made the PR, but at this point I can't load my singleplayer let's play world up with or without it... (without due to an Antique Atlas bug with biome mapping)

**Comment by oitsjustjose** [comment]
...Anything? I've submitted a PR and everything, not sure how I can make this easier, but this crash is causing issues amongst other mods until it gets fixed (i.e.: removing BB + OTG makes AntiqueAtlas have a fit).

I've been waiting for this fix for my let's play series for a while now...

**Comment by PG85** [comment]
Should be fixed with v7.
