### ISSUE TITLE
I don't know what is wrong...

### ISSUE THREAD

**Issue by ccorp2002** [PG85/OpenTerrainGenerator#149]
For some reason, it keeps crashing when ever I load up my private server, and gives me the same error...

I don't know what is wrong... I, at first, thought it was my mythicmobs installation, so I removed that.
I supposed I should have just went here in the first place.
Here is my log:
[crash-2018-03-21_21.40.10-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/1836114/crash-2018-03-21_21.40.10-server.txt)

Sorry about that... XD I have been messing with OTG for a while, and It is AMAZING!

**Comment by ccorp2002** [comment]
Oh, and btw, I'm not 100% active, so it may be a while for me to get back...

**Comment by ccorp2002** [comment]
Oh, and I am also running Spigot 1.12.2. I don't remember which build, but I think it is the latest.

Thanks in advanced!
-- C_Corp2002

**Comment by ccorp2002** [comment]
Aaand it crashed again, on another multiworld plugin...
Here's the log:
[crash-2018-03-22_16.41.34-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/1839622/crash-2018-03-22_16.41.34-server.txt)

I love this plugin, but it just wont work.

**Comment by PG85** [comment]
Hey, thanks for reporting this and sorry for the late response. If you're still having this issue, feel free to re-open this ticket or join us on the OTG discord at /openterraingen.
