### ISSUE TITLE
Bug - OTG + MicDoodleLib transformer collision

### ISSUE THREAD

**Issue by m1cr0man** [PG85/OpenTerrainGenerator#156]
## Problem

When running both MicDoodleLib (required for Galacticraft) and OTG, OTG throws an error (wrongly) stating that the incorrect version of Forge is in use. [Gist of log](https://gist.github.com/m1cr0man/f730167a0ae7e88a9cb39c7f233979f9)

## Expected Result

OTG should either not state that it is incompatible with this version of Forge, or make necessary transformations aware of what MicDoodleLib has done.

## Solutions

This probably won't be possible to fix - if so I'm happy to close this and just have it on record that OTG and MicDoodleLib/Galacticraft are incompatible.

**Comment by PG85** [comment]
Hey m1cr0man, thanks for reporting this, sorry for the late reply. Looks like a problem with OTG-Core, apparently MicDoodleLib and OTG-Core are modifying the same code. May be fixable, will need to take a look. Have to finish a big new release first though, so may take a while.

**Comment by m1cr0man** [comment]
HI PG85, it's all good. I think I chatted about this on Discord at one point and I was aware of the new release that was coming.

**Comment by PG85** [comment]
Have added some custom code for Galacticraft to OTG-Core, should be fixed, I believe for v7. Newest dev versions are available on the OTG Discord, will release v8 asap.
