### ISSUE TITLE
Sandstone instead of red sandstone appearing with GroundBlock: SAND:1

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#158]
Instead of putting red sandstone under red sand blocks when a cave/ravine cuts through red sand, OTG places normal sandstone.

https://media.discordapp.net/attachments/307111022257373185/434070382023147540/unknown.png

**Comment by PG85** [comment]
Should be fixed with v8_r2, including any other problems with red sand in caves/canyons.
