### ISSUE TITLE
"ReplaceBlocks:" does not accept blocks with data values as the block to be targetted for replacement

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#159]
Example:
ReplacedBlocks: (DIRT,DIRT:2) -- works
ReplacedBlocks: (DIRT:2,DIRT:1) -- does not work, OTG will remove the :2 from first entry if WriteEnabled, and will target DIRT (with no data)

**Comment by PG85** [comment]
Should be fixed with v7_r26
