### ISSUE TITLE
CustomStructure() ressource uses two values of Rarity. Rarity set in BC and Object

### ISSUE THREAD

**Issue by LanToaster** [PG85/OpenTerrainGenerator#160]
I came across this while making an Structure to replace the Ground with more SurfaceLayers.

The Structure in the BiomeConfig was set to 100 spawnchance, the Structure in itself much Larger than a Single Chunk.
I first wondered that it didn´t cover the whole Biome, until I tried to set the Rarity inside the Config to 100 aswell.

**Comment by PG85** [comment]
Hey LanToaster,

Depending on if you've activated OTG+ mode, the two rarities will work differently (one will work and the other won't). That's a bit confusing unfortunately, it's a legacy thing that still needs to be cleaned up.

This is a known issue so I'll close this for now. Thanks for reporting anyway :).
