### ISSUE TITLE
Request: Incorrect blockcheck syntax in bo3s causes error which does not let the user know of the cause

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#161]
It would be better if OTG could give a more informative error when there are syntax errors in block checks, right now it looks like this:

https://github.com/PG85/OpenTerrainGenerator/issues/151

**Comment by PG85** [comment]
Since this only affects BO3's with errors in them, will move this out of v7.

**Comment by PG85** [comment]
For v8_r2 this should throw an InvalidConfigException with a description that's logged, this invalidates the blockcheck but not the BO3, and doesn't crash the game.
