### ISSUE TITLE
Thaumcraft: Exception generating new chunk

### ISSUE THREAD

**Issue by Rongmario** [PG85/OpenTerrainGenerator#162]
https://gist.githubusercontent.com/Rongmario/7e23be9265468972fa78ca3fab665cb9/raw/5f0e6ce9e9a205856e109a0b9130ff5f5670bd25/gistfile1.txt

**Comment by kantsche** [comment]
I had the same error.. fixed after removing Thaumcraft.

**Comment by PG85** [comment]
Hey guys, can you tell me if this is reproducable and how?
