### ISSUE TITLE
Bug: Fromimage BO3AtSpawn

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#164]
Hello,

While preparing Dregora for use with Forge I bumped into a issue using **BO3AtSpawn:** Prior to OTG I used the comibation of **FromImage** with 100% spawn rate & a 4x4 pixel cube on the center of the **map.png** on Spigot. This resulted in a Bo3 spawning at the center of the map with branches attached.

On forge the customstructure only spawns partly using the same settings. If Bo3AtSpawn is used the customstructure does not spawn at all.

Hope I gave enough information to pinpoint the cause of this issue.

**Comment by PG85** [comment]
Hey NLBlackEagle,

BO3AtSpawn unfortunately only works for CustomObject at the moment. If you're using OTG+ mode then you can force a CustomStructure to spawn at the world spawn via IsSpawnPoint: true.

I'll have to look at why customstructures aren't spawning as they do for Spigot when using FromImageMode.

**Comment by PG85** [comment]
Im actually not sure I understand the problem:
- Is FromImage mode not spawning a CustomObject or CustomStructure where you want it?
- Is Bo3AtSpawn not working for forge and/or spigot? (should only be used with customobject, not sure if it works on spigot tbh).

**Comment by PG85** [comment]
Need more info, please reopen this issue if this is still a problem with v9, thanks!
