### ISSUE TITLE
Bo3's not generating unless they're Trees

### ISSUE THREAD

**Issue by BlackBeltPanda** [PG85/OpenTerrainGenerator#165]
I just switched from TerrainControl to OpenTerrainGenerator and followed the instructions to import my TC world to OTG.

After regenerating the world, the only Bo3s that are generating are the Tree types. None of the others appear to work.

Has anything changed with the Bo3 or biome configs that could be causing this? I can spawn them in just fine with the "/otg spawn" command.

One of the Bo3s that doesn't generate with OTG but did with TC: https://pastebin.com/raw/Fxm0iHKx
One of the biomes that the Bo3s aren't generating in: https://pastebin.com/raw/ndeqnkpd

OTG version 1.12.2 v6
Server version git-Paper-1414 (MC: 1.12.2)

**Comment by MCPitman** [comment]
I moved BBundle from TC to OTG with no issues.

I don't see a customobject() line in the biome config with the bo3 listed?

**Comment by BlackBeltPanda** [comment]
It's set to "CustomObject(UseWorld)"

**Comment by PG85** [comment]
Hey BlackBeltPanda,

Sorry for the late reply. If I recall correctly UseWorld and UseBiome have been retired. Each biomeconfig now needs to have the customobjects. The GlobalObjects and WorldObjects now also work differently: GlobalObjects contains BO3's that can be used (referenced) by all OTG worlds, WorldObjects contains BO3's that can only be referenced by a single world. If a BO3 with the same name is present in both folders then the one in the WorldObjects folder will be used.

Let me know if that fixes the problem for you :).

**Comment by MCPitman** [comment]
Closed this as it can be fixed by correcting the configs in question.
