### ISSUE TITLE
Bug: pre-generation in progess shows bugged hunger and air bar

### ISSUE THREAD

**Issue by lightlessfilms** [PG85/OpenTerrainGenerator#168]
Hi,

With version **1.12.2 - V6** (with Biome Bundle version **1.12.2-v6.1**) when I set a number to pre-generate and load the world.
The hunger and air bar are bugged. As far as I can see this happens when the info is shown in the top left corner. When I press F3 it then shows the correct bar icons.

![2018-05-18_22 51 38](https://user-images.githubusercontent.com/7137900/40257736-9ab79660-5aef-11e8-9a07-ba1f052d7319.png)
![2018-05-18_22 51 40](https://user-images.githubusercontent.com/7137900/40257737-9ad3ce98-5aef-11e8-972f-2a25a5000102.png)

**Comment by PG85** [comment]
Hey lightlessfilms,

Thanks for reporting this, I think you're the first person who has noticed this :o. WIll fix this as soon as I have the time.

**Comment by PG85** [comment]
v7 has a new ui for pregenerator progress (the "o" menu).
