### ISSUE TITLE
[FEATURE REQUEST] Make OTG configurable to not replace vanilla worldgen screen

### ISSUE THREAD

**Issue by hron84** [PG85/OpenTerrainGenerator#169]
So, I know I have a minority opinion, but I would like to configure OTG to let me use the original New World  screen. I play with modpacks with very different mods, some modpack include OTG that I personally not like but the other mods in the pack or the entire pack otherwise is fits in my favorites. However I feel OTG too obtrusive now. I not want to use any feature of OTG I just want to generate a world with "Default" terrain generator with my heart's seed. Please provide a way me to do it and do it in obvious way because your current screen is a whole mess for me. I do not know what terrain gen will be used (and no way to change it), I have no option to make a superflat creative world, etc. The screen not provides any option that vanilla screen does. No bundles no other stuffs fits my needs, I want my vanilla screen back.

Minecraft 1.12.2.

**Comment by PG85** [comment]
Hey hron48,

I'm currently working on an update which will allow users to have non-OTG overworlds, so they can have a vanilla overworld and add OTG dimensions. After that's done the vanilla world creation screen will also be brought back.

**Comment by hron84** [comment]
Thanks. Just out of curiosity, why you cannot use currently the vanilla screen to switch between different generators?

**Comment by ThePoptartCrpr** [comment]
Any update on this, @PG85?

**Comment by Amunak** [comment]
Another issue related to this is that no matter what generator you use for a world (say, you generate your world with `flat`) originally, OTG happily replaces this generator, fucks up `level.dat` and starts generating its own BS in a world it should never even touch.

This needs to stop, as it leads to ruined SP worlds by just installing the mod.

**Comment by PG85** [comment]
Hey Amunak, that should definitely not be happening, should be fixed with v7.

**Comment by PG85** [comment]
Vanilla world creation screen is accessible via the OTG world creation menu in v7 btw.

**Comment by hron84** [comment]
nice!
