### ISSUE TITLE
Bug: Sapling resource in biomeconfig doesn't work.

### ISSUE THREAD

**Issue by Guinaro** [PG85/OpenTerrainGenerator#17]
I'm looking for a way to integrate the various saplings of other mods, to generate my own custom trees.
For now it seems only default minecraft trees are supported.
However other mods like Biomes O Plenty, Natura, Forestry, Pams' Harvestcraft, Tinker's Construct all offer their own saplings.
It would be great if we could specify those saplings with a custom pattern to spawn certain custom trees.
(I haven't used this category as of yet, but I do hope this category is monitored during game time, and spawn trees according to the saplings a user places down, and not during generation)
This would be a great way to allowing the player to regrow trees at a location of it's choosing.
Also would the mod override the spawning mechanics of the mods used like Forestry's walnut needing to be in a 2x2 pattern. If too difficult we could at least work around those patterns. If possible a switch in the main config to disable all spawning of trees, except those specified in the biome configs would be great.

For info: at current counting (disregarding possible missed items) I have found for minecraft, biomes o' plenty, natura, forestry, pam's harvest craft and tinker's construct. (including same trees and variants)
75 Woodlogs
86 Leave types
118 Saplings

You see this provides use with a lot of possibilities to create very diverse forests created by the user itself. Aswell as providing us with the means to override the spawned trees of the indivual mods, so that we can combine multi mod leave types in a single tree, ... .

**Comment by PG85** [comment]
Hey Guinaro, I love the idea of custom saplings but one of the basic design principles of OTG is that it does not add any new blocks or items. There are a lot of options though for placing custom trees in the world using BO3's and the CustomObject() and CustomStructure() resources in the biomeconfigs. You could add BO3 trees to the world generator using CustomObject() (like Biome Bundle does) and then have a different mod that adds the actual saplings to the game?

**Comment by Guinaro** [comment]
I know that I can add custom BO3's using modded blocks.
What I am suggesting is allow us to also use those Mod provided saplings as a starting point for allowing players to regrow those BO3's where they want. OTG won't provide those saplings, you can only reuse what minecraft or mods offer in the form of saplings.
The kicker would be if you could also surpress the tree spawning mechanism of saplings to trees from other mods: like Harvestcraft, Forestry, ... ?

To provide more diversity having patterns would be a great benefit. Like a 3x2 pattern of Biomes O plenty willow saplings: BO3CustomBOPWillowA, 3x3 hollow pattern of BoP Willow Saplings: BO3CustomBOPWillowB, ... maybe even have something like 3x3 BoP Willow saplings with a grassblock in the center: BO3CustomBOPWillowC. It will be up to the modpack maker to provide the players with an overview of which pattern to use.

Having BO3s provides us with lots of potential as terrain generators. I would love to provide players with some tooks to reshape the world with BO3s to their liking aswell. At least for trees.

An issue could be: how fast do you spawn the object?
Also how to deal with patterns to overlap like 2x2 and 2x3. Do you take the best matching or do you do a random chance between possible matches.

**Comment by PG85** [comment]
Okay I think I understand what you mean now, the Sapling resource for biomeconfigs is currently broken as far as I know (for TC as well as OTG). It's not high on the priority list at the moment but if and when I do get to fixing it I'll see if I can make it so that it accepts any sapling.

**Comment by SamGunGraven** [comment]
Yeah, just tested this with both RedMushroom and BrownMushroom - can confirm that it does not work.

**Comment by PG85** [comment]
Fixed for v7_dev_r25.
