### ISSUE TITLE
OTG-Core: crash before launching

### ISSUE THREAD

**Issue by Fenekhu** [PG85/OpenTerrainGenerator#172]
So i added a few mods to my already working custom modpack and clicked play. nothing happened for about a minute, so i looked at the launcher log. [this it what it said.](https://pastebin.com/rUTicHBA) I couldn't get anything from that at all, except it said pg85 and OTG. so, I uninstalled otg and all other mads that i had added since it last worked and got the exact same error. It still mentions OTG, even though i removed OTG. Can someone explain what is happening here?

EDIT: Ok so i figured out why it was still giving me the error after i removed it. It made a file in the 1.12 folder in my mods folder called OTGCore.jar that i had to delete. however, the pre-launch crashes are still happening.

**Comment by PG85** [comment]
Hey TheGoldenProof, OTGCore.jar is required for OTG to work. Whenever you update OTG (get a new OTG jar) you need to delete it though so that OTG can create a new OTGCore.jar. If you delete OTGCore.jar, then run MC with only the OTG jar, do you see a new OTGCore.jar being created?
