### ISSUE TITLE
Crash on sapling grow event

### ISSUE THREAD

**Issue by rsquatre** [PG85/OpenTerrainGenerator#173]
The server started to randomly crash after a few minutes/hours due to a Null Pointer Exception on the getSaplingGen() method from SaplingListener.
The bug has been reproduced several times with and without players online, also I was able to grow Oak Saplings without any crash. I also saw someone with the same problem on OTG's CurseForge project page.

Each time a crash report is generated but it doesn't tell which sapling is causing the crash nor it's location in the world. The log doesn't tells much more.
[crash-2018-06-09_16.28.49-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/2087037/crash-2018-06-09_16.28.49-server.txt) or https://pastebin.com/LTpHbNXp

**Comment by PG85** [comment]
Hey rs4-06, what kind of OTG world are you using? Is it Biome Bundle or did you create one yourself? Did you edit any of the sapling settings in the biome configs?

**Comment by rsquatre** [comment]
Hi, thank you for the quick reply. I used the latest version of Biome Bundle with the default config.

**Comment by MercuryDoll** [comment]
Using Biome Bundle on 1.12.2, this happened to our server as well. What we suspect is Acacia saplings, though this could be an edge case. Said sapling was planted in a Magical Forest, which was formerly Tundra (changed via RFTools' Terraformer), according to OTG it's supposed to be DrylandsEdge1 / *2

**Comment by PG85** [comment]
Should (hopefully) be fixed with v7_r25.
