### ISSUE TITLE
Bug: Can't remove OTG and go back to vanilla worldgen

### ISSUE THREAD

**Issue by Carnaxus** [PG85/OpenTerrainGenerator#174]
I got tired of the immense lag and wanted to switch back to using default Minecraft worldgen.  Imagine my surprise when the game wound up hanging while trying to make a new world with a console error **referencing OTG**, which I'd removed.  I've now put it back in and am just going to use a "default" setup, but the higher memory overhead is the entire reason I tried to switch back.  Did I miss a coremod or something?

**Comment by PG85** [comment]
Hey Carnaxus, it should be possible to use worlds created with OTG without OTG installed. What's the console error when you try to load a world without OTG?

**Comment by MCPitman** [comment]
Make sure you have removed OTG-Core.jar from your mods folder (its a core mod that OTG unpacks when it runs for the first time).
