### ISSUE TITLE
Feature: /otg spawn for CustomStructure and Forge

### ISSUE THREAD

**Issue by maxiride** [PG85/OpenTerrainGenerator#177]
Since a Bo3 (Object or Structure) has a center reference point assigned during its creation it would be helpful to be capable of placing in a void world a placeholder block acting as the Bo3 center and then with a command ask OTG to attempt to generate the Object\Structure (with how many branches depth setting optional maybe) at the current location ignoring Blocks Checks and collisions.

I guess it might be most helpful for structures and try to see how they generate.

**Edit:**
As pointed out on Discord, ones can force the spawn of a **object** by setting it in the field `BO3AtSpawn:` in the `WorldConfig.ini` configuration file, given that the Blocks Checks criteria are met.

**Edit 2:**
Tried also `/otg spawn` using a Spigot setup but keep saying that it can't find the objects, either with full path from root server, Bo3 name alone, WorldObjects and GlobalObjects. Tried to browse the TC repo for similar issues but [the only close one](https://github.com/MCTCP/TerrainControl/issues/114)  was fixed so I doubt that from the fork it has been brought back.

**Comment by PG85** [comment]
For /otg spawn, see also #268

**Comment by PG85** [comment]
Hey @Maxiride thanks for the feedback and sorry for not responding btw. There is already the /otg spawn command, that should work for CustomObjects. Join us on the OTG Discord at #openterraingen if you have any questions. There's no way to do this for structures though, also /otg spawn doesn't work for Forge, so I'll keep this issue open for that.

**Comment by PG85** [comment]
Josh fixed otg spawn for forge for customobjects, will merge his changes for v9. Customstructures won't be possible unfortunately, would be too much effort to implement for now.

**Comment by PG85** [comment]
Implemented in v9.0_r1
