### ISSUE TITLE
Grass doesn't grow in night worlds

### ISSUE THREAD

**Issue by JustIvory** [PG85/OpenTerrainGenerator#178]
Light level is set to level 15 in the night worlds, but it seems that grass does not spread. 
I'm attempting to do a world where lore is based on eternal night, but my testers report that grass is not spreading even after a lengthy amount of time has passed.

**Comment by JustIvory** [comment]
It appears that this also applies to crops and trees. They will grow with torches next to them, but this is largely impractical.

**Comment by MCPitman** [comment]
All of the world provider settings are from vanilla Minecraft, OTG just lets you enable/disable them. Setting 'night world' to true enables world provider settings from the vanilla End dimension which has the same limitations you mentioned, this is not a bug.
