### ISSUE TITLE
Request: Work with Just Enough IDs

### ISSUE THREAD

**Issue by keybounce** [PG85/OpenTerrainGenerator#183]
A mod called "Just Enough IDs" is implementing cross-mod support for more than 256 biomes, and it works with other worldgen mods.

Are you able to implement support for this? The goal ultimately is that any mod that wants to find out what biome it is looking at can use a single mod that is implementing cross-mod support in the 1.13 style.

https://github.com/DimensionalDevelopment/JustEnoughIDs

**Comment by ben-mkiv** [comment]
JEID works fine with OTG, just get sure to grab the latest build as a bug with BiomeIDs was recently fixed.

**Comment by PG85** [comment]
Hey, thanks for reporting this and thanks for helping @ben-mkiv.
