### ISSUE TITLE
Crash with random mods [fix]

### ISSUE THREAD

**Issue by 34486** [PG85/OpenTerrainGenerator#184]
Ok, it seems to be that any mod I add now corrupts the level file, such as Project red lighting.... How can this be fixed, its the same issue with multiple other mods, mystcraft does it too!it come with that no biomes more than 4096 error and /fml confirm to proceed and sometimes it lets me get in the world and everything is changed, all the block ids were shifted. It has to be your end, right? Im using 2705 of forge.

**Comment by 34486** [comment]
Fix: Install the NEID mod, (Not enough ids) its not otg that is the problem, you just ran outta them ids!!!

(this can be closed, thanks!)

**Comment by maxiride** [comment]
@34486 you can close the issue yourself with the comment and close button ;)

**Comment by 34486** [comment]
Oh, thanks!
