### ISSUE TITLE
OTG + BiomeBundle + TF (Still crash)

### ISSUE THREAD

**Issue by Snez0K** [PG85/OpenTerrainGenerator#186]
Here my crashlog pls help: https://pastebin.com/Kq5Fd3Ch
I will open tikets Biome Bundle and TF too.

**Comment by ben-mkiv** [comment]
same issue as #185 

adding a null check between those two lines fixed the issue for me:

https://github.com/PG85/OpenTerrainGenerator/blob/bd09939a851456baa135e92d2329dc7b46205fbc/platforms/forge/src/main/java/com/pg85/otg/forge/events/ServerEventListener.java#L802-L803

`if(playerWorld == null || playerWorld.getConfigs() == null) 
    return;`

**Comment by PG85** [comment]
Hey, thanks for reporting this. Has been fixed for v7.
