### ISSUE TITLE
JEI stops working with BiomeBundle

### ISSUE THREAD

**Issue by Valerate** [PG85/OpenTerrainGenerator#187]
Hi

I just installed both of these mods today (OTG and its biomebundle) and ingame (even with cheats enabled) JEI's buttons are gone. If i selected Normal map gen it spawns fine, but with the bundle its gone.
I tried talking in discord with the guys there but they didnt know what would cause it.

**Comment by MCPitman** [comment]
I just tested this myself in 1.12.2 and compared JEI with OTG installed to JEI without OTG and see no differences whatsoever.

Issue closed until more information is given to be able to repeat the issue.
