### ISSUE TITLE
Clients are not sent any chunks when using OTG multi-dimension support on a Forge server

### ISSUE THREAD

**Issue by qenya** [PG85/OpenTerrainGenerator#189]
I've set up a Forge server with OTG and no other mods. When I create a new dimension using the ``/otg dim -c`` command, and then teleport to it with either the ``/forge setdim`` command or the ``/otg tp`` command, my client does not receive any chunk data or load the world. It doesn't freeze - I can move the cursor and teleport back to the overworld with no issues - but I can't move around in the new dimension, and the F3 debug screen displays the message "Waiting for chunk..." in place of the XYZ coordinates.

The dimension is definitely being generated, because a save file is produced, and I can copy it out and open it in singleplayer, getting an OTG-generated world, as expected. I've also tried pregenerating chunks in the new dimension, and this doesn't throw any errors. I just can't actually see it in my client when connecting to the server.

* OTG version: 1.12.2 v6
* Tested on Forge versions 14.23.2.2611; 14.23.3.2655; 14.23.4.2705; 14.23.4.2728

**Comment by PG85** [comment]
Hey, thanks for reporting this and sorry for the delay. Please try v7 from the OTG discord dev channel at /openterraingen. If the issue still exists, feel free to re-open this ticket. Thanks!
