### ISSUE TITLE
Extremely Long World Load Times

### ISSUE THREAD

**Issue by Boingboingsplat** [PG85/OpenTerrainGenerator#19]
This isn't really a bug per say, and I wasn't sure if it's something that should be submitted here or at Biome Bundle's issue tracker.

When loading a world with Biome Bundle, it takes an _extremely_ long time for OTG to setup.
Here's the relevant logs from the Minecraft console:

> [16:47:40] [Server thread/INFO] [FML]: Holder lookups applied
**[16:47:41] [Server thread/INFO] [OTG]: Creating world "Biome Bundle"
[16:47:41] [Server thread/INFO] [OTG]: Loading configs for world "Biome Bundle"..
[16:50:30] [Server thread/INFO] [OTG]: 2138 world custom objects loaded.
[16:51:02] [Server thread/INFO] [OTG]: 452 biomes Loaded**
[16:51:02] [Server thread/INFO] [FML]: Loading dimension 0 (Biome Bundle)

Over three minutes! And this happens every time I launch the game and load the world!
I don't know if this sort of thing could be cached, or maybe if it could be moved to the Minecraft initialization instead, but if this could somehow be sped up I would greatly appreciate it.

**Comment by PG85** [comment]
Heya, this is a known issue with complex worlds like Biome Bundle that use lots of custom objects. I'll pass on your feedback to the Biome Bundle creators. You can also open an issue on their github if you like, it's at https://github.com/BiomeBundle.

Once I get done with 1.11.2 I'll see if I can take a look at optimising BO2/BO3 loading and making it faster, for the time being though it's up to worldpack creators to make sure their worlds don't take too long to load.
