### ISSUE TITLE
1.13 support

### ISSUE THREAD

**Issue by mibby** [PG85/OpenTerrainGenerator#190]
MC 1.13 seems to be right around the corner and Spigot has begun releasing pre-release builds for it.
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-pre7-development-builds.328883/

Do you have plans on updating OTG with any 1.13 biomes and vanilla generator changes?

**Comment by MCPitman** [comment]
This is not the place to nag about 1.13 updates, it's an issue tracker.
