### ISSUE TITLE
Zoo Animals: WaterCreature only spawn on land

### ISSUE THREAD

**Issue by Elias79** [PG85/OpenTerrainGenerator#191]
Tried adding a fish from the [Zoo Animals mod](
![2018-07-17_05 21 45](https://user-images.githubusercontent.com/13618389/42795091-9f88eb3c-8982-11e8-9d08-b040dfd1470f.png)
https://minecraft.curseforge.com/projects/zoo-wild-animals-rebuild) to the "Deep Ocean" biome but they only spawn on land but never in the water.
`SpawnWaterCreatures: [{"mob": "bluefish", "weight": 1000, "min": 4, "max": 4}]`

**Comment by PG85** [comment]
Hey @Elias79, thanks for reporting this. Unfortunately many modded mobs don't follow the vanilla spawning rules and need to be spawned by their own mod. When you add a mob via the mob spawning list in a biomeconfig, all OTG does is add it to the spawning list that the vanilla mob spawning mechanics use. So it looks like when the vanilla mob spawning mechanics try to spawn these creatures, it doesn't work. I've tried to fix this in the past, but I found I'd have to make an adapter for each mob mod. Unfortunately, I don't think I'll have time for something like that before the 1.13 update. See also: #301.
