### ISSUE TITLE
[1.12.2] crash with bedrock ores

### ISSUE THREAD

**Issue by TheSnowyChickens** [PG85/OpenTerrainGenerator#195]
Hello,
1.12.2
Forge 2739
OTG v6
BRO 1.2.6.41

![grafik](https://user-images.githubusercontent.com/29357962/43281734-b40adb9e-9114-11e8-8a8b-62504ee61e8d.png)

[crash-2018-07-26_20.34.58-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/2233195/crash-2018-07-26_20.34.58-server.txt)

**Comment by PG85** [comment]
Hey there, thanks for reporting. Looks like an issue with Bedrock Ores causing cascading chunk population, which causes a problem with OTG BO3's. Will need to test with Bedrock Ores.

**Comment by PG85** [comment]
Have made a number of changes and fixes for v7 and v8 that should also affect this. Problem may also have been fixed on the Bedrock Ores side by now. I'm hoping this is fixed already. v8 will be released asap, dev versions are available on the OTG Discord at #openterraingen. If the problem remains, feel free to reopen this issue or create a new one.

**Comment by TheSnowyChickens** [comment]
Okay, ty
