### ISSUE TITLE
Importing OTG into workspace / HarderFarming debugging

### ISSUE THREAD

**Issue by Draco18s** [PG85/OpenTerrainGenerator#196]
https://github.com/Draco18s/ReasonableRealism/issues/23

Pulling you in on this, as I can't see what the problem is, and in trying to import OTG into my workspace I've found that it's both:
 - Based against a different version of Forge (minor problem; easy to work around, but time consuming)
 - Likely using Access Transformers (unconfirmed, but large usage of fields and methods Eclipse tells me are private, moderate problem; headache to install and set up properly)
 - A coremod (major problem; headache to set up properly, may be the root cause of the issue)

As such I am unable to run your code in my development environment and locate the issue.
[This](https://github.com/Draco18s/ReasonableRealism/blob/master/src/main/java/com/draco18s/farming/FarmingEventHandler.java#L487-L488) is my best-guess as to the crashing line.

**Comment by PG85** [comment]
Hey, thanks for reporting this and sorry for the late response. I've reworked the coremod and done a lot fixes for mod compatibility for v7, so hopefully this problem should be fixed. Still need to look at making importing the mod into the workspace easy, will keep this ticket open for that.

**Comment by PG85** [comment]
Fixed on the Harder Farming side, OTG also made changes for v7 and v8 that may affect this. Assuming this is fixed, feel free to reopen if this is still an issue. I've also been doing a *lot* of refactoring and am updating the docs to make OTG easier to work with for other devs. It'll probably still be a bit of a pain in the butt, but it should at least be workable. Thanks for the feedback!
