### ISSUE TITLE
game crashes after uninstalling

### ISSUE THREAD

**Issue by LoneW0lf347** [PG85/OpenTerrainGenerator#197]
I've recently uninstalled the mod and whenever I try to create a new flat world the game crashes.
I thought that someone here could help me, so... here's the crash report. 
[crash-2018-08-02_01.48.58-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/2251528/crash-2018-08-02_01.48.58-server.txt)

is it because I haven't uninstalled it properly?
thanks for the help.

**Comment by Oxykronnos** [comment]
Hello dude,
uninstall OTG-Core, it is in the mods folder inside of another folder called 1.12.2 (or whatever version you're using).

Cheers!

**Comment by MCPitman** [comment]
Caused by OTGCore still being present in the mods folder.
