### ISSUE TITLE
[Question] 1.13 bukkit/spigot/forge compatibility mode

### ISSUE THREAD

**Issue by DmitryRendov** [PG85/OpenTerrainGenerator#201]
I do understand that upgrading this plugin is not a priority for you @PG85 and you still awaiting forge release, but our guys are kindly asking to upgrade spigot/bukkit part. With this in mind, could you please draft a new release (at least bukkit) just to enable compatibility 1.12.2/1.13 (without all those new aquatic features)?
Looking for any news from you  and thank you in advance!)

**Comment by MCPitman** [comment]
This is not the place to ask about 1.13 updates this is a bug report tracker. Closed.
