### ISSUE TITLE
DoublePlant Resource option to create tall plants (like Tallgrass) for mods

### ISSUE THREAD

**Issue by Guinaro** [PG85/OpenTerrainGenerator#202]
Currently I am unable to generate the double tall plants of the plants 2 mod. Like: Canary Island Flatpod, Chinese Honeysuckle, ...
Those plants have an upper and lower portion. I can generate the lower portion or top portion just fine with the Plant resource, but half the part is always missing.
Would it be possible to add a doubleplant resource like:
DoublePlant(PlantTypeBottomBlock, PlantTypeTopBlock,Frequency,Rarity,MinAltitude,MaxAltitude,BlockSource[,BlockSource2,BlockSource3.....])

Thank you,
Guinaro

**Comment by MCPitman** [comment]
Use a bo3

**Comment by PG85** [comment]
Will close this since it's so old.
