### ISSUE TITLE
Very high numbers in PregeneratorMaxChunksPerTick causes server crash (forge)

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#203]
Tested with 100 PregeneratorMaxChunksPerTick and the server stops with the error:

`[Server Watchdog/FATAL] [net.minecraft.server.dedicated.ServerHangWatchdog]: A single server tick took 60.00 seconds (should be max 0.05)`

Obviously that's an insane number, but OTG should probably set it to safe levels if it detects the number is set too high in the OTG.ini

**Comment by PG85** [comment]
For v8_r2, have set the maximum to 5. I've not seen any improvement past 3 myself.
