### ISSUE TITLE
OTG covers my Mod biome

### ISSUE THREAD

**Issue by MoeShimaKaze** [PG85/OpenTerrainGenerator#205]
I am running Vampire Mod and OTG on my server. When I use Biome_Bundle's preset, the terrain of the vampire forest in Vampire Mod can't be generated. Please tell me how to solve the compatibility of these mods for OTG.

**Comment by darchitectlp** [comment]
You have to recreate the biomes manually. You have to do this for every biome added by a mod. It sucks, but that's the price you have to pay to use OTG. I'm hoping that at some point we have a place to share our custom biomes for super popular mods (like Thaumcraft or Integrated Dynamics) so people can just drop them into their config folder, or download a BiomeBundle with the necessary biomes already added in.

Start here:
http://openterraingen.wikia.com/wiki/Biome_Configs

**Comment by MoeShimaKaze** [comment]
ok,thanks,i will try it

**Comment by PG85** [comment]
Will close this since it's so old, thanks for helping @darchitectlp!
