### ISSUE TITLE
Permanently dismiss warning about BOP? 

### ISSUE THREAD

**Issue by rhoark** [PG85/OpenTerrainGenerator#206]
I want to use blocks and mobs added by Biomes 'o Plenty in custom biomes defined for OTG. I would not be using BOP for any terrain generation at all. This seems to work just fine so far. Is there a way (for example in a config file) to permanently dismiss the warning saying BOP is likely to cause crashes? This warning would unnecessarily alarm/confuse end users of the modpack and if they followed the suggestion to remove BOP, it would just break the modpack. If there is not presently a way to disable the message, I would appreciate if such a way were to be added.

**Comment by PG85** [comment]
Hey, thanks for reporting. The message has been removed with v7, which should no longer cause problems with BoP.
