### ISSUE TITLE
WorldSettings nosuchmethod. Crash on Start

### ISSUE THREAD

**Issue by ghost** [PG85/OpenTerrainGenerator#208]
I transfered my singleplayer world to my server but now it crashes on start:

Crash Report:
[crash-2018-10-31_17.57.03-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/2535717/crash-2018-10-31_17.57.03-server.txt)

On my server.properties i've wrote:
level-type=OTG
level-name=Biome Bundle
but it still doesn't work.
What should I do?

**Comment by PG85** [comment]
Hey, thanks for reporting. Should be fixed with v7, you can grab a dev build from the OTG Discord at /openterraingen. Cheers.
