### ISSUE TITLE
Mod compat: Exception ticking world / ConcurrentModificationException

### ISSUE THREAD

**Issue by ghost** [PG85/OpenTerrainGenerator#209]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  ForgelinPlugin (Forgelin-1.8.0.jar)
  OTGCorePlugin (OTG-Core.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.17.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 11/5/18 9:44 PM
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1476)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1474)
	at com.pg85.otg.generator.biome.CachedBiomeGenerator.cleanupCache(CachedBiomeGenerator.java:103)
	at com.pg85.otg.forge.generator.OTGBiomeProvider.func_76938_b(OTGBiomeProvider.java:163)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:186)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1476)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1474)
	at com.pg85.otg.generator.biome.CachedBiomeGenerator.cleanupCache(CachedBiomeGenerator.java:103)
	at com.pg85.otg.forge.generator.OTGBiomeProvider.func_76938_b(OTGBiomeProvider.java:163)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:186)

-- Affected level --
Details:
	Level name: Biome Bundle
	All players: 1 total; [EntityPlayerMP['XXXXXXXXXX'/3246, l='Biome Bundle', x=144.57, y=86.12, z=53.33]]
	Chunk stats: ServerChunkCache: 1634 Drop: 0
	Level seed: 8120758378141785511
	Level generator: ID 09 - OTG, ver 0. Features enabled: true
	Level generator options: OpenTerrainGenerator
	Level spawn location: World: (113,64,1374), Chunk: (at 1,4,14 in 7,85; contains blocks 112,0,1360 to 127,255,1375), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Level time: 20784 game time, 20784 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 60410 (now: false), thunder time: 159001 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-38-generic
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1236289936 bytes (1179 MB) / 5699010560 bytes (5435 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 1 total; -Xmx8G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 97 mods loaded, 97 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                | Version                  | Source                                        | Signature                                |
	|:--------- |:--------------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                         | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                               | 9.42                     | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                             | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | otgcore                           | 1.12.2 - v7              | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | openmodscore                      | 0.12.1                   | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | bowinfinityfix                    | rv5                      | minecraft.jar                                 | e250ba31147feb059b86cfd74ee61a8aeb88fb9b |
	| UCHIJAAAA | opencomputers|core                | 1.7.2.67                 | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | appliedenergistics2               | rv6-stable-2             | appliedenergistics2-rv6-stable-2.jar          | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| UCHIJAAAA | bdlib                             | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                  | None                                     |
	| UCHIJAAAA | ae2stuff                          | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                 | None                                     |
	| UCHIJAAAA | applecore                         | 3.1.4                    | AppleCore-mc1.12.2-3.1.4.jar                  | None                                     |
	| UCHIJAAAA | jei                               | 4.12.1.217               | jei_1.12.2-4.12.1.217.jar                     | None                                     |
	| UCHIJAAAA | appleskin                         | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
	| UCHIJAAAA | forgelin                          | 1.8.0                    | Forgelin-1.8.0.jar                            | None                                     |
	| UCHIJAAAA | betterfoliage                     | 2.2.0                    | BetterFoliage-MC1.12-2.2.0.jar                | None                                     |
	| UCHIJAAAA | openterraingenerator              | v6                       | OpenTerrainGenerator-1.12.2+-+v6.jar          | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| UCHIJAAAA | biomebundle                       | 5.1                      | Biome_Bundle-1.12.2-v6.1.jar                  | None                                     |
	| UCHIJAAAA | biomesoplenty                     | 7.0.1.2402               | BiomesOPlenty-1.12.2-7.0.1.2402-universal.jar | None                                     |
	| UCHIJAAAA | buildcraftlib                     | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJAAAA | buildcraftcore                    | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJAAAA | buildcraftbuilders                | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJAAAA | buildcraftenergy                  | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJAAAA | buildcraftfactory                 | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJAAAA | buildcraftrobotics                | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJAAAA | buildcrafttransport               | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJAAAA | buildcraftsilicon                 | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJAAAA | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UCHIJAAAA | codechickenlib                    | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | chickenchunks                     | 2.4.1.73                 | ChickenChunks-1.12.2-2.4.1.73-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | ctm                               | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                     | None                                     |
	| UCHIJAAAA | chisel                            | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                  | None                                     |
	| UCHIJAAAA | chococraft                        | 0.9.7.0                  | chococraft_1.12.2-0.9.7.0.jar                 | None                                     |
	| UCHIJAAAA | clumps                            | 3.1.1                    | Clumps-3.1.1.jar                              | None                                     |
	| UCHIJAAAA | crafttweaker                      | 4.1.11                   | CraftTweaker2-1.12-4.1.11.jar                 | None                                     |
	| UCHIJAAAA | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.11.jar                 | None                                     |
	| UCHIJAAAA | crafttweakerjei                   | 2.0.2                    | CraftTweaker2-1.12-4.1.11.jar                 | None                                     |
	| UCHIJAAAA | customspawner                     | 3.11.4                   | CustomMobSpawner-3.11.4.jar                   | None                                     |
	| UCHIJAAAA | dimdoors                          | 3.0.9+287                | DimensionalDoors-3.0.9-287.jar                | None                                     |
	| UCHIJAAAA | ding                              | 1.0.1                    | Ding-1.12.1-1.0.1.jar                         | None                                     |
	| UCHIJAAAA | mocreatures                       | 12.0.5                   | DrZharks MoCreatures Mod-12.0.5.jar           | None                                     |
	| UCHIJAAAA | dsurround                         | 3.4.9.17                 | DynamicSurroundings-1.12.2-3.4.9.17.jar       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJAAAA | presets                           | 3.4.9.17                 | DynamicSurroundings-1.12.2-3.4.9.17.jar       | None                                     |
	| UCHIJAAAA | endercore                         | 1.12.2-0.5.43            | EnderCore-1.12.2-0.5.43.jar                   | None                                     |
	| UCHIJAAAA | enderio                           | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                     | None                                     |
	| UCHIJAAAA | enderiointegrationtic             | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                     | None                                     |
	| UCHIJAAAA | enderiobase                       | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                     | None                                     |
	| UCHIJAAAA | enderioconduits                   | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                     | None                                     |
	| UCHIJAAAA | enderioconduitsappliedenergistics | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                     | None                                     |
	| UCHIJAAAA | opencomputers                     | 1.7.2.67                 | OpenComputers-MC1.12.2-1.7.2.67.jar           | None                                     |
	| UCHIJAAAA | enderioconduitsopencomputers      | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                     | None                                     |
	| UCHIJAAAA | enderioconduitsrefinedstorage     | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                     | None                                     |
	| UCHIJAAAA | enderiointegrationforestry        | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                     | None                                     |
	| UCHIJAAAA | enderiointegrationticlate         | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                     | None                                     |
	| UCHIJAAAA | enderiomachines                   | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                     | None                                     |
	| UCHIJAAAA | enderiopowertools                 | 5.0.37                   | EnderIO-1.12.2-5.0.37.jar                     | None                                     |
	| UCHIJAAAA | enderstorage                      | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.4.jar                    | None                                     |
	| UCHIJAAAA | fastleafdecay                     | v14                      | FastLeafDecay-v14.jar                         | None                                     |
	| UCHIJAAAA | forgemultipartcbe                 | 2.6.0.79                 | ForgeMultipart-1.12.2-2.6.0.79-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | microblockcbe                     | 2.6.0.79                 | ForgeMultipart-1.12.2-2.6.0.79-universal.jar  | None                                     |
	| UCHIJAAAA | minecraftmultipartcbe             | 2.6.0.79                 | ForgeMultipart-1.12.2-2.6.0.79-universal.jar  | None                                     |
	| UCHIJAAAA | funkylocomotion                   | 1.0                      | funky-locomotion-1.12.2-1.1.2.jar             | None                                     |
	| UCHIJAAAA | gregtech                          | 1.0.124                  | gregtech-1.12.2-1.0.124.jar                   | None                                     |
	| UCHIJAAAA | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| UCHIJAAAA | ichunutil                         | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
	| UCHIJAAAA | teslacorelib                      | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | industrialforegoing               | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.11.5-215.jar     | None                                     |
	| UCHIJAAAA | infernalmobs                      | 1.7.5                    | InfernalMobs-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironchest                         | 1.12.2-7.0.51.836        | ironchest-1.12.2-7.0.51.836.jar               | None                                     |
	| UCHIJAAAA | journeymap                        | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHIJAAAA | jeresources                       | 0.8.10.50                | JustEnoughResources-1.12.2-0.8.10.50.jar      | None                                     |
	| UCHIJAAAA | lootbags                          | 2.5.7                    | LootBags-1.12.2-2.5.7.jar                     | None                                     |
	| UCHIJAAAA | mantle                            | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                      | None                                     |
	| UCHIJAAAA | mcjtylib_ng                       | 3.0.5                    | mcjtylib-1.12-3.0.5.jar                       | None                                     |
	| UCHIJAAAA | morph                             | 7.1.2                    | Morph-1.12.2-7.1.2.jar                        | None                                     |
	| UCHIJAAAA | morpheus                          | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                       | None                                     |
	| UCHIJAAAA | mrtjpcore                         | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar       | None                                     |
	| UCHIJAAAA | natura                            | 1.12.2-4.3.2.62          | natura-1.12.2-4.3.2.62.jar                    | None                                     |
	| UCHIJAAAA | openmods                          | 0.12.1                   | OpenModsLib-1.12.2-0.12.1.jar                 | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | openblocks                        | 1.8                      | OpenBlocks-1.12.2-1.8.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | harvestcraft                      | 1.12.2z                  | Pam's+HarvestCraft+1.12.2z.jar                | None                                     |
	| UCHIJAAAA | portalgun                         | 7.0.2                    | PortalGun-1.12.2-7.0.2.jar                    | None                                     |
	| UCHIJAAAA | projectred-core                   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar           | None                                     |
	| UCHIJAAAA | projectred-compat                 | 1.0                      | ProjectRed-1.12.2-4.9.1.92-compat.jar         | None                                     |
	| UCHIJAAAA | projectred-integration            | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar    | None                                     |
	| UCHIJAAAA | projectred-transmission           | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar    | None                                     |
	| UCHIJAAAA | projectred-fabrication            | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-fabrication.jar    | None                                     |
	| UCHIJAAAA | xreliquary                        | 1.12.2-1.3.4.780         | Reliquary-1.12.2-1.3.4.780.jar                | None                                     |
	| UCHIJAAAA | rftools                           | 7.56                     | rftools-1.12-7.56.jar                         | None                                     |
	| UCHIJAAAA | roguelike                         | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| UCHIJAAAA | soundfilters                      | 0.10_for_1.12            | SoundFilters-0.10_for_1.12.jar                | None                                     |
	| UCHIJAAAA | storagedrawers                    | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar               | None                                     |
	| UCHIJAAAA | worldedit                         | 6.1.8                    | worldedit-forge-mc1.12-6.1.8-dist.jar         | None                                     |
	| UCHIJAAAA | hungeroverhaul                    | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar    | None                                     |
	| UCHIJAAAA | teslacorelib_registries           | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar              | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ForgelinPlugin (Forgelin-1.8.0.jar)
  
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  squeek.applecore.asm.TransformerModuleHandler
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.17.jar)
  org.blockartistry.DynSurround.asm.Transformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  openmods.core.OpenModsClassTransformer
BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
  com.github.parker8283.bif.Transformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv6-stable-2 for Forge 14.23.5.2768
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	List of loaded APIs: 
		* AppleCoreAPI (3.1.0) from AppleCore-mc1.12.2-3.1.4.jar
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-2.jar
		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|core (2.2) from buildcraft-7.99.18.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.99.18.jar
		* BuildCraftAPI|enums (1.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.99.18.jar
		* BuildCraftAPI|filler (5.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.99.18.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.99.18.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.99.18.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.99.18.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.99.18.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|transport (5.0) from buildcraft-7.99.18.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* enderioapi (4.0.0) from EnderIO-1.12.2-5.0.37.jar
		* enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.0.37.jar
		* enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.0.37.jar
		* enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.0.37.jar
		* enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.0.37.jar
		* enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.0.37.jar
		* enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.0.37.jar
		* enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.0.37.jar
		* enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.0.37.jar
		* funkylocomotion_api (2.0) from funky-locomotion-1.12.2-1.1.2.jar
		* iChunUtil API (1.2.0) from iChunUtil-1.12.2-7.1.4.jar
		* industrialforegoingapi (5) from industrialforegoing-1.12.2-1.11.5-215.jar
		* jeresources|API (0.8.10.50) from JustEnoughResources-1.12.2-0.8.10.50.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.12.1.217.jar
		* openblocks|api (1.2) from OpenBlocks-1.12.2-1.8.jar
		* opencomputersapi|component (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|core (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|driver (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|driver|item (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|event (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|filesystem (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|internal (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|machine (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|manual (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|network (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|prefab (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* projectred|api (2.0) from ProjectRed-1.12.2-4.9.1.92-Base.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar
	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['XXXXXXXXXX'/3246, l='Biome Bundle', x=144.57, y=86.12, z=53.33]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by PG85** [comment]
Hey @ghost, sorry for the late response. Which modpack were you using? Feel free to reopen if the issue persists.
