### ISSUE TITLE
Crash on entering generated world

### ISSUE THREAD

**Issue by dr3ams** [PG85/OpenTerrainGenerator#21]
**1. Created world with OTG and Biome Bundle.
2. Pregenerated 125 chunks.
3. Deleted both mods, played some time on vanilla minecraft on generated chunks.
4. Decided I need more biomes generated with Biome Bundle.
5. Copied back both mods, tried to enter the world and got this crash.**

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 10.05.17 18:03
Description: Exception in server tick loop

java.lang.RuntimeException: Whatever it is you're trying to do, we didn't write any code for it (sorry). Please contact Team OTG about this crash.
	at com.khorn.terraincontrol.forge.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:218)
	at com.khorn.terraincontrol.forge.TCWorldType.getBiomeProvider(TCWorldType.java:67)
	at com.khorn.terraincontrol.forge.WorldProviderTC.func_76572_b(WorldProviderTC.java:80)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:39)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:113)
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:90)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:120)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 304678032 bytes (290 MB) / 927657984 bytes (884 MB) up to 4241293312 bytes (4044 MB)
	JVM Flags: 26 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xms512m -Xmn512m -XX:MaxMetaspaceSize=256m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=1024m -XX:+UseCodeCacheFlushing -XX:ParallelGCThreads=10
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2272 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2272.jar) 
	UCHIJAA	Forge{12.18.3.2272} [Minecraft Forge] (forge-1.10.2-12.18.3.2272.jar) 
	UCHIJAA	openterraingenerator{v14} [Open Terrain Generator] (OpenTerrainGenerator-1.10.2-v17.jar) 
	UCHIJAA	biomebundle{1.0} [Biome Bundle] (Biome_Bundle-v5.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by PG85** [comment]
Hey thanks for reporting this and sorry for the late reply. Unfortunately vanilla worlds (even partial ones) are not compatible with OTG. You can pre-generate a world using OTG and then use it without OTG but after that you can't use the world with OTG anymore.

You could generate a new OTG world using the same seed and then use something like worldedit to copy/paste your existing world into it.
