### ISSUE TITLE
Conflict with Tropicraft Crashes Server

### ISSUE THREAD

**Issue by korlandril** [PG85/OpenTerrainGenerator#212]
Hey there, I'm currently using OTG and Biome Bundle for my modpack and server. Clients crash the server when trying to enter the dimension added by Tropicraft and the error log seems to point to OTG being the cause. I reported it on their issue tracker https://github.com/Tropicraft/Tropicraft/issues/301, but was told to report it here instead.

Here's the initial error log:
https://pastebin.com/zEewcFwt

And here's the error log upon restarting the server and attempting to reconnect:
https://pastebin.com/zRgKEYg8

**Comment by PG85** [comment]
Hey, thanks for reporting, this should be solved with v7. Feel free to re-open if this is still an issue with v7.
