### ISSUE TITLE
Not a issue an addendum to compiling the code setting up the workspace

### ISSUE THREAD

**Issue by frakier** [PG85/OpenTerrainGenerator#213]
I had problems building the code and wrote up the process in case it helps others or the authors... Attaching the text file I wrote up for the process in 1.12/eclipse oxygen. 

[OpenTerrainGenerator -COMPILING addendum.txt](https://github.com/PG85/OpenTerrainGenerator/files/2587271/OpenTerrainGenerator.-COMPILING.addendum.txt)

**Comment by PG85** [comment]
Hey frakier, thanks for that! I'm currently cleaning up the repo, fixing the build scripts and adding some documentation. Will make sure everything is included and documented for v7.

**Comment by PG85** [comment]
If things are working correctly btw all you should need to do is /gradle setupdecompworkspace, /gradle eclipse and maybe a /gradle build. Then load up eclipse, add the projects, create a run configuration with --username and --password, and run. That's for Forge in any case.

**Comment by PG85** [comment]
Have added the META-INF.jar that was missing and reworked some gradle files and dependencies. Hopefully things should work out of the box now, still need to test on a clean system.

I'll see if I can add your eclipse instructions to the forge setup readme later, thanks!

**Comment by frakier** [comment]
/gradle setupdecompworkspace, /gradle eclipse work for me sometimes and then sometimes not, more to do with my inexperience than anything else. When I have problems I find writing it all up helps, especially if I can use the same information in other areas. Thanks, I'll Close Now.
