### ISSUE TITLE
Biome Bundle Preset crashed my game after i was logged in for like 20 minutes.

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [PG85/OpenTerrainGenerator#214]
[crash-2018-11-16_20.49.45-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/2591403/crash-2018-11-16_20.49.45-server.txt)

LAN World. No clue why its crashing. Something about TreeGen

**Comment by PG85** [comment]
Hey, thanks for reporting. Most likely a streams issue. Will close this since its so old, feel free to re-open if this still happens with the latest versions of OTG/Streams.
