### ISSUE TITLE
Crash when Loading Forest Biomes (Biome Bundle Preset)

### ISSUE THREAD

**Issue by plumprumps** [PG85/OpenTerrainGenerator#218]
Tried with and without mods. Problem persists through all 10+ test worlds. When specific forest biomes attempt to load the game crashes. **[Here is the latest crash log](https://pastebin.com/mkPNSNyn)**.

I cannot open the debug menu long enough to view which biomes cause the issue. Looks like an oak forest, large custom oak trees. Other forests are loading fine, including the sakura and spruce.

**Comment by PG85** [comment]
Hey thanks for reporting and sorry for the delay. Please visit our discord at /openterraingen for Biome Bundle support questions, thanks you! WIll close this since it's so old, if this turns out to be a bug, feel free to re-open.
