### ISSUE TITLE
Rogue scala import

### ISSUE THREAD

**Issue by Player3324** [PG85/OpenTerrainGenerator#219]
https://github.com/PG85/OpenTerrainGenerator/blob/bd09939a851456baa135e92d2329dc7b46205fbc/platforms/forge/src/main/java/com/pg85/otg/forge/asm/OTGClassTransformer.java#L22 should use org.objectweb.asm.Type instead

**Comment by PG85** [comment]
Thanks, fixed for v7. Finally cleaning up the project and refactoring things atm, if you want to take another look in a week or two that would be most welcome ;).
