### ISSUE TITLE
Is Logging working? Where are they? What's the trick?

### ISSUE THREAD

**Issue by totemo** [PG85/OpenTerrainGenerator#221]
I've configured logging of structure spawning but I don't see that information logged anywhere.

I've looked in:
 * The server log.
 * [The documentation](http://openterraingen.wikia.com/wiki/OpenTerrainGenerator.ini). 
 * OTG's plugin folder.
 * The server directory.
 * The world directories.
 * This issue list.

The only clue I can find is that there is apparently some other logging location, [separate from the server log](https://github.com/PG85/OpenTerrainGenerator/issues/13#issuecomment-298182005).

What I'm expecting to see, but don't, is the name and coordinates of every BO3 structure spawned.

Could someone please point me to the structure spawning logs?

Details:

`OpenTerrainGenerator version 1.12.2 v6`
```
$ grep -vE '^[ ]*$|^#' plugins/OpenTerrainGenerator/OTG.ini
SettingsMode: WriteAll
LogLevel: Debug
BiomeConfigExtension: .bc
SpawnLog: true
DeveloperMode: true
PregeneratorMaxChunksPerTick: 1
```

**Comment by PG85** [comment]
Hey totemo, looks like log levels TRACE and DEBUG may not be showing up in the normal logs, but only the debug logs. Did you check the debug log file? Should be fixed for v7.

**Comment by PG85** [comment]
Will fix logging for v8, see milestones.

**Comment by PG85** [comment]
Fixed for v7 anyway :). All logging will show up in normal logs now. SpawnLog:true should provide lots of information.

**Comment by totemo** [comment]
Thanks PG85.
