### ISSUE TITLE
Default worldgen (Vanilla Biome Only) generate only Ocean

### ISSUE THREAD

**Issue by EphisPaF** [PG85/OpenTerrainGenerator#225]
Hi,

First good job on the mod, the possibilities it offers are so good !
I tried to use it on a new modpack with pixelmon with Biom Bundle.
But Pixelmon seems to only spawn in Vanilla Biome, so I follow the wiki for creating a blank new world preset and it seems to only create world full with Ocean Biome.
Every time I use Terrain mode : Normal and Biome Mode : Normal, it failed.
If I use Terrain mode : Normal and Biome Mode : BeforeGroups, it works but pixelmon still not spawn other than in Ocean Biome.

Have you a preset world for Vanilla that actually work in Normal Biome Mode ?

**Comment by PG85** [comment]
Hey there, welcome to the community. Please join our Discord at /openterraingen and ask your support questions there, thanks!
