### ISSUE TITLE
Incorrect Crash Message

### ISSUE THREAD

**Issue by Snorps** [PG85/OpenTerrainGenerator#227]
If you accidentally define a biome twice under CustomBiomes in WorldConfig.ini, an incorrect crash message is produced. 

e.g if Ocean Island is designated id 75 and 614, the following crash report is generated
`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Open Terrain Generator (openterraingenerator)
Caused by: java.lang.RuntimeException: Could not allocate the requested id 614 for biome Ocean Island. All available id's under 256 have been allocated`
even though all id's under 256 have not been allocated. Which could be misleading for new pack makers n stuff.

Thanks,
snarp

**Comment by PG85** [comment]
Hey @Virtualistik, thanks for the feedback! This is fixed with v7 dynamic biome id's, which retires custombiomes (it only still exists to support legacy worlds).
