### ISSUE TITLE
Entity() resource cannot spawn modded mobs with custom nbt

### ISSUE THREAD

**Issue by Snorps** [PG85/OpenTerrainGenerator#228]
e.g: a text file, Pirate.txt, containing `{PersistenceRequired:1b}` exists in the root of WorldObjects. There is also a bo3 in this directory which contains 
`Entity(0,1,0,EntityPirate,1,Pirate.txt)
Entity(2,1,3,Skeleton,1,Pirate.txt)
Entity(1,1,4,EntityPirate,1)`
When this bo3 is placed, one EntityPirate without any nbt spawns, as does one Skeleton with nbt. Ideally a second EntityPirate with nbt should spawn. 

Thanks,
spork

**Comment by PG85** [comment]
Thanks for reporting! Will be fixed with v7_DEV_r24, which will be released on the Discord's OTG-dev channel soon.
