### ISSUE TITLE
OTG-Core: Crash when i launch a modpack - ClassNotFoundException: net.minecraft.entity.Entity

### ISSUE THREAD

**Issue by EchoBuster** [PG85/OpenTerrainGenerator#233]
[latest.log](https://github.com/PG85/OpenTerrainGenerator/files/2875523/latest.log)
can you plz help me

**Comment by PG85** [comment]
Related to https://github.com/PG85/OpenTerrainGenerator/issues/220

**Comment by PG85** [comment]
Hey @EchoBuster , thanks for teporting this and sorry for the late response. Should be fixed with v8_r2, to be released on the OTG Discord at #openterraingen asap. This should hopefully fix any coremod issues with Sponge.
