### ISSUE TITLE
OTG-Core not updated/deleted causes problems

### ISSUE THREAD

**Issue by xmasonx** [PG85/OpenTerrainGenerator#234]
when i try to start a new world its brings me to the lancher and it says
The game crashed whilst ticking entity
Error: java.lang.NoClassDefFoundError: com/pg85/otg/forge/dimensions/WorldProviderOTG 
and the crash report
---- Minecraft Crash Report ----

WARNING: coremods are present:
  OTGCorePlugin (OTG-Core.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 2/27/19 6:53 PM
Description: Ticking entity

java.lang.NoClassDefFoundError: com/pg85/otg/forge/dimensions/WorldProviderOTG
	at com.pg85.otg.forge.asm.OTGHooks.getGravityFactorFallingBlock(OTGHooks.java:72)
	at net.minecraft.entity.item.EntityFallingBlock.func_70071_h_(EntityFallingBlock.java:130)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.pg85.otg.forge.dimensions.WorldProviderOTG
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.pg85.otg.forge.asm.OTGHooks.getGravityFactorFallingBlock(OTGHooks.java:72)
	at net.minecraft.entity.item.EntityFallingBlock.func_70071_h_(EntityFallingBlock.java:130)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: minecraft:falling_block (net.minecraft.entity.item.EntityFallingBlock)
	Entity ID: 13
	Entity Name: Falling Block
	Entity's Exact location: -43.50, 7.01, -718.50
	Entity's Block location: World: (-44,7,-719), Chunk: (at 4,0,1 in -3,-45; contains blocks -48,0,-720 to -33,255,-705), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	Immitating block ID: 13
	Immitating block data: 0
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 5350062043047421108
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (112,64,-562), Chunk: (at 0,4,14 in 7,-36; contains blocks 112,0,-576 to 127,255,-561), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Level time: 4 game time, 4 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 112036 (now: false), thunder time: 94152 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 816193176 bytes (778 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID        | Version      | Source                               | Signature                                |
	|:--------- |:--------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft | 1.12.2       | minecraft.jar                        | None                                     |
	| UCHIJAAAA | mcp       | 9.42         | minecraft.jar                        | None                                     |
	| UCHIJAAAA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge     | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | otgcore   | 1.12.2 - v7  | minecraft.jar                        | None                                     |
	| UCHIJAAAA | cfm       | 6.2.0        | cfm-6.2.0-mc1.12.2 (2).jar           | None                                     |
	| UCHIJAAAA | radixcore | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar | None                                     |
	| UCHIJAAAA | mca       | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal (2).jar   | None                                     |

	Loaded coremods (and transformers): 
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

if some1 can help me then please help

**Comment by WilliamBlaze** [comment]
I'm experience the same exact error after uninstalling/deleting all OTG dependent mods. upon closer inspection of my mod folder i found in its contents a folder called 1.12 which contained a OTG core mod separate from the main OTG Jar itself.

Upon deleting this 1.12 folder from within my mods folder in my profile manually that issue was solved.
Since not many folks manually install their mods anymore this sort of thing was bound to happen, but this is why i like using the manual method, i can get down and see what i'm dealing with within my folders directly instead of letting a twitch launcher handle it all. lol

You should see if this folder is within your installed mods still, and if so, delete that item, it should fix the issue entirely' if your not using any actual OTG dependent mods

**Comment by PG85** [comment]
Hey, thanks for reporting and thanks for helping @WilliamBlaze. Will see if we can improve this.

**Comment by PG85** [comment]
For v8_r3, I've added OTG-Core as a dependency with a specific version, so if an incorrect version of OTG-Core is used, OTG will not load on app start and the logs will contain a warning about OTG-Core version xxx missing. Unfortunately I can't rename OTG-Core.jar to include a version number, since having multiple OTG-Core.jars after updating would cause even worse problems. Users will have to understand that they should delete OTG-Core and restart MC to re-generate it, hopefully that won't cause (as many) problems... All I can do for now though. Thanks for the feedback!
