### ISSUE TITLE
Crash when importing BOP world NoSuchMethodError WorldSettings

### ISSUE THREAD

**Issue by Sythe-Wolfius** [PG85/OpenTerrainGenerator#237]
When launching the server it hangs itself.
when reading along in the terminal I can see it's complaining about missing a few ID's
"[10:37:41] [Server thread/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:frozen_forest"
<details>
  <summary>Before suddenly spewing a large Error and stopping the server:
</summary>

**[10:37:42] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net/minecraft/world/WorldSettings.func_77166_b()Lnet/minecraft/world/WorldSettings; (loaded from jar:file:/Home/yoran/Downloads/Server/minecraft_server.1.12.2.jar!/amx.class by net.minecraft.launchwrapper.LaunchClassLoader@9457a747) called from class com.pg85.otg.forge.OTGWorldType (loaded from jar:file:/Home/yoran/Downloads/Server/./mods/OpenTerrainGenerator-1.12.2+-+v6.jar!/com/pg85/otg/forge/OTGWorldType.class by net.minecraft.launchwrapper.LaunchClassLoader@9457a747).
	at com.pg85.otg.forge.OTGWorldType.getBiomeProvider(OTGWorldType.java:70) ~[OTGWorldType.class:?]
	at com.pg85.otg.forge.dimensions.WorldProviderOTG.func_76572_b(WorldProviderOTG.java:87) ~[WorldProviderOTG.class:?]
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:40) ~[aym.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:116) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:812) [?:2.9 (10-29-2018)]
[10:37:42] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /Home/yoran/Downloads/Server/./crash-reports/crash-2019-03-20_10.37.42-server.txt**

</details>

<details>
  <summary>Crash log in case needed</summary>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  OTGCorePlugin (OTG-Core.jar)
  IvToolkit (IvToolkit-1.12.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.10-core.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 20/03/19 12:12
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net/minecraft/world/WorldSettings.func_77166_b()Lnet/minecraft/world/WorldSettings; (loaded from jar:file:/Home/yoran/Downloads/Server/minecraft_server.1.12.2.jar!/amx.class by net.minecraft.launchwrapper.LaunchClassLoader@8938b046) called from class com.pg85.otg.forge.OTGWorldType (loaded from jar:file:/Home/yoran/Downloads/Server/./mods/OpenTerrainGenerator-1.12.2+-+v6.jar!/com/pg85/otg/forge/OTGWorldType.class by net.minecraft.launchwrapper.LaunchClassLoader@8938b046).
	at com.pg85.otg.forge.OTGWorldType.getBiomeProvider(OTGWorldType.java:70)
	at com.pg85.otg.forge.dimensions.WorldProviderOTG.func_76572_b(WorldProviderOTG.java:87)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:40)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:116)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:812)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-46-generic
	Java Version: 1.8.0_191, IBM Corporation
	Java VM Version: IBM J9 VM (JRE 1.8.0 Linux amd64-64-Bit Compressed References 20181029_400846 (JIT enabled, AOT enabled)
OpenJ9   - c5c78da
OMR      - 3d5ac33
IBM      - 8c1bdc2), IBM Corporation
	Memory: 559088760 bytes (533 MB) / 1642004480 bytes (1565 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 5 total; -Xoptionsfile=/usr/lib/jvm/java-ibm-x86_64-80/jre/lib/amd64/compressedrefs/options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse7b_29 -Xmx2048M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 89 mods loaded, 89 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                        | Version                  | Source                                             | Signature                                |
	|:------- |:------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| UCHIJAA | minecraft                 | 1.12.2                   | minecraft.jar                                      | None                                     |
	| UCHIJAA | mcp                       | 9.42                     | minecraft.jar                                      | None                                     |
	| UCHIJAA | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2768-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | forge                     | 14.23.5.2768             | forge-1.12.2-14.23.5.2768-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | ivtoolkit                 | 1.3.3-1.12               | minecraft.jar                                      | None                                     |
	| UCHIJAA | otgcore                   | 1.12.2 - v7              | minecraft.jar                                      | None                                     |
	| UCHIJAA | opencomputers|core        | 1.7.4.153                | minecraft.jar                                      | None                                     |
	| UCHIJAA | ic2                       | 2.8.109-ex112            | industrialcraft-2-2.8.109-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAA | advanced_machines         | 61.0.1                   | Advanced+Machines-61.0.1.jar                       | None                                     |
	| UCHIJAA | advanced_solar_panels     | 4.3.0                    | Advanced+Solar+Panels-4.3.0.jar                    | None                                     |
	| UCHIJAA | orbis_api                 | 0.1.0                    | orbis_api-0.1.0.jar                                | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| UCHIJAA | aether                    | 0.1.1                    | Aether-2-Mod-1.12.2.jar                            | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| UCHIJAA | jei                       | 4.15.0.269               | jei_1.12.2-4.15.0.269.jar                          | None                                     |
	| UCHIJAA | baubles                   | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| UCHIJAA | projecte                  | 1.12.2-PE1.4.0           | ProjectE-1.12.2-PE1.4.0.jar                        | None                                     |
	| UCHIJAA | auxiliumequivalence       | 1.12.2-1.3.2             | auxiliumequivalence-1.12.2-1.3.2.jar               | None                                     |
	| UCHIJAA | battletowers              | 1.6.4                    | BattleTowers-Mod-1.12.2.jar                        | None                                     |
	| UCHIJAA | guideapi                  | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
	| UCHIJAA | bloodmagic                | 1.12.2-2.3.1-99          | BloodMagic-1.12.2-2.3.1-99.jar                     | None                                     |
	| UCHIJAA | zawa                      | 1.12.2-1.5.5             | zawa+-+1.5.5+(1.12.2).jar                          | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| UCHIJAA | bookworm                  | 1.12.2-2.1.0             | bookworm+-+2.1.0+(1.12.2).jar                      | None                                     |
	| UCHIJAA | thaumcraft                | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
	| UCHIJAA | botania                   | r1.10-360                | Botania+r1.10-360.jar                              | None                                     |
	| UCHIJAA | codechickenlib            | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAA | redstoneflux              | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAA | brandonscore              | 2.4.9                    | BrandonsCore-1.12.2-2.4.9.195-universal.jar        | None                                     |
	| UCHIJAA | buildcraftlib             | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| UCHIJAA | buildcraftcore            | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| UCHIJAA | buildcraftbuilders        | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| UCHIJAA | buildcrafttransport       | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| UCHIJAA | buildcraftsilicon         | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| UCHIJAA | buildcraftcompat          | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| UCHIJAA | buildcraftenergy          | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| UCHIJAA | buildcraftfactory         | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| UCHIJAA | buildcraftrobotics        | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| UCHIJAA | classiccombat             | 1.0.0                    | ClassicCombat-1.12-1.0.0.jar                       | None                                     |
	| UCHIJAA | sanlib                    | 1.3.0                    | SanLib-1.12.1.jar                                  | None                                     |
	| UCHIJAA | claysoldiers              | 3.0.0-alpha.4.1          | Clay-Soldiers-Mod-1.12.1.jar                       | None                                     |
	| UCHIJAA | cofhcore                  | 4.6.2                    | CoFHCore-1.12.2-4.6.2.25-universal.jar             | None                                     |
	| UCHIJAA | cofhworld                 | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAA | craftstudioapi            | 1.0.0                    | CraftStudio-API-1.12.1.jar                         | None                                     |
	| UCHIJAA | deadlyworld               | 1.0.0_for_mc1.12.2       | Deadly-World-Mod-1.12.2.jar                        | None                                     |
	| UCHIJAA | dimdoors                  | 3.0.9+287                | DimensionalDoors-3.0.9-287.jar                     | None                                     |
	| UCHIJAA | doggytalents              | 1.14.2.308               | Doggy-Talents-Mod-1.12.1.jar                       | None                                     |
	| UCHIJAA | thermalfoundation         | 2.6.2                    | ThermalFoundation-1.12.2-2.6.2.26-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAA | draconicevolution         | 2.3.20                   | Draconic-Evolution-1.12.2-2.3.20.333-universal.jar | None                                     |
	| UCHIJAA | gottschcore               | 1.7.0                    | GottschCore-mc1.12.2-f14.23.5.2768-v1.7.0.jar      | None                                     |
	| UCHIJAA | dungeons2                 | 1.7.0                    | Dungeons2-mc1.12.2-f14.23.5.2768-v1.7.0.jar        | None                                     |
	| UCHIJAA | energyconverters          | 1.0.1.2                  | energyconverters_1.12.1-1.0.1.2.jar                | None                                     |
	| UCHIJAA | exoticbirds               | 1.0                      | Exotic-Birds-Mod-1.12.2.jar                        | None                                     |
	| UCHIJAA | fastleafdecay             | v14                      | FastLeafDecay-v14.jar                              | None                                     |
	| UCHIJAA | forgemultipartcbe         | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAA | microblockcbe             | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar       | None                                     |
	| UCHIJAA | minecraftmultipartcbe     | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar       | None                                     |
	| UCHIJAA | hammercore                | 2.0.4.2                  | HammerCore-1.12.2-2.0.4.2.jar                      | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAA | waila                     | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| UCHIJAA | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAA | ironchest                 | 1.12.2-7.0.59.842        | ironchest-1.12.2-7.0.59.842.jar                    | None                                     |
	| UCHIJAA | journeymap                | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                        | None                                     |
	| UCHIJAA | mantle                    | 1.12-1.3.3.42            | Mantle-1.12-1.3.3.42.jar                           | None                                     |
	| UCHIJAA | millenaire                | Millénaire 7.1.3         | millenaire-7.1.3.jar                               | None                                     |
	| UCHIJAA | mrtjpcore                 | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar            | None                                     |
	| UCHIJAA | opencomputers             | 1.7.4.153                | OpenComputers-MC1.12.2-1.7.4.153.jar               | None                                     |
	| UCHIJAA | openterraingenerator      | v6                       | OpenTerrainGenerator-1.12.2+-+v6.jar               | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| UCHIJAA | harvestcraft              | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zb.jar                    | None                                     |
	| UCHIJAA | projectred-core           | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar                | None                                     |
	| UCHIJAA | projectred-compat         | 1.0                      | ProjectRed-1.12.2-4.9.1.92-compat.jar              | None                                     |
	| UCHIJAA | projectred-integration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar         | None                                     |
	| UCHIJAA | projectred-transmission   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar         | None                                     |
	| UCHIJAA | projectred-fabrication    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-fabrication.jar         | None                                     |
	| UCHIJAA | projectred-illumination   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-lighting.jar            | None                                     |
	| UCHIJAA | projectred-expansion      | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar          | None                                     |
	| UCHIJAA | projectred-relocation     | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar          | None                                     |
	| UCHIJAA | projectred-transportation | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar          | None                                     |
	| UCHIJAA | projectred-exploration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-world.jar               | None                                     |
	| UCHIJAA | reccomplex                | 1.4.7                    | RecurrentComplex-1.4.7.jar                         | None                                     |
	| UCHIJAA | refinedstorage            | 1.6.12                   | refinedstorage-1.6.12.jar                          | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCHIJAA | sanplayermodel            | 1.0.2                    | SanLib-1.12.1.jar                                  | None                                     |
	| UCHIJAA | twilightforest            | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar        | None                                     |
	| UCHIJAA | tconstruct                | 1.12.2-2.12.0.115        | TConstruct-1.12.2-2.12.0.115.jar                   | None                                     |
	| UCHIJAA | thaumadditions            | 12r                      | ThaumicAdditions-1.12.2-12r.jar                    | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAA | tcinventoryscan           | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar         | None                                     |
	| UCHIJAA | thebetweenlands           | 3.3.10                   | TheBetweenlands-3.3.10-universal.jar               | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCHIJAA | thermalexpansion          | 5.5.3                    | ThermalExpansion-1.12.2-5.5.3.41-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAA | thermalcultivation        | 0.3.2                    | ThermalCultivation-1.12.2-0.3.2.11-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAA | thermaldynamics           | 2.5.4                    | ThermalDynamics-1.12.2-2.5.4.18-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAA | thermalinnovation         | 0.3.2                    | ThermalInnovation-1.12.2-0.3.2.11-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAA | visuals                   | 3r                       | Visuals-1.12.2-3r.jar                              | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAA | worldedit                 | 6.1.10-SNAPSHOT          | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar  | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
IvToolkit (IvToolkit-1.12.jar)
  
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.10-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 2175 names; 3068 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUKCmNsaWVudCB7CiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdCiAgICBCOiJDdXN0b20gRW5jaGFudG1lbnQgQ29sb3JzIGZvciBWYW5pbGxhIEl0ZW1zIj10cnVlCgogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8KICAgICMgVGhpcyBmZWF0dXJlIGRvZXNuJ3Qgd29yayBvbiBhbGwgY2xpZW50cywgeW91IGFyZSBnb2luZyB0byBnZXQgYSBtZXNzYWdlIGluIGNoYXQgaWYgaXQgd2FzIHN1Y2Nlc3NmdWwvdW5zdWNjZXNzZnVsIFtkZWZhdWx0OiB0cnVlXQogICAgQjoiTEFOIFVQblAiPXRydWUKCiAgICAjIFJlcGxhY2UgdmFuaWxsYSBmdXJuYWNlIGFuZCBicmV3aW5nIHN0YW5kIHByb2dyZXNzIGJhcnMgdG8gdXNlIHNtb290aCByZW5kZXJpbmc/IFtkZWZhdWx0OiB0cnVlXQogICAgQjoiU21vb3RoIFZhbmlsbGEgR3VpcyI9dHJ1ZQp9CgoKaXdyZW5jaCB7CiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpCiAgICBTOkdyZWVuPTIyRkYyMgoKICAgICMgV2hhdCBpcyB0aGUgY29sb3Igd2hlbiB0aGUgaG92ZXJlZCBibG9jayBpcyBOT1Qgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpCiAgICBTOlJlZD1GRjIyMjIKfQoKCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgewogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgZm9yY2Utc3Bhd24gRW5kZXIgRHJhZ29uIEVnZyBvbiBFbmRlciBEcmFnb24gZGVhdGg/IFtkZWZhdWx0OiB0cnVlXQogICAgQjoiQWx3YXlzIFNwYXduIERyYWdvbiBFZ2ciPXRydWUKfQoKCg==
Pastebin Connection: Okay.
Dependent Mods:
    -Thaumic Additions: Reconstructed (thaumadditions) @12r
    -Visuals (visuals) @3r

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
</details>

This only happens when I try to import a previously single player world into my server.
The reason I am so persistent on importing a world is that when I let the server generate a world on it's own I keep getting vast ocean worlds.

<h3>Edit:</h3>
As a result of my impatience I have decided to keep trying to let the server generate a world on it's own, this did work but only after several attempts due to a known issue: PG85/OpenTerrainGenerator#136

**Comment by PG85** [comment]
Hey, thanks for reporting. This is a known issue, will try to fix this for v7.

**Comment by PG85** [comment]
Hey, thanks for reporting. Should be fixed with v7, you can grab a dev build from the OTG Discord at /openterraingen. Cheers.
