### ISSUE TITLE
"JLine terminal non blocking reader thread" high cpu usage

### ISSUE THREAD

**Issue by Sythe-Wolfius** [PG85/OpenTerrainGenerator#239]
Minecraft version: 1.12.2
Forge version: 1.12.2-14.23.5.2768
mods: OTG and Biome bundle
java version: "1.8.0_201"
![Screenshot from 2019-03-25 09-00-16](https://user-images.githubusercontent.com/16468476/54903730-e13aa780-4edc-11e9-8eb4-70d5c25300f0.png)
I can find anything unusual in the logs, if needed I can still add them.
My server is struggling even when there are no players on and visualVM gives me this, googling gives me abandoned github threads, hurray.

**Comment by Sythe-Wolfius** [comment]
Problem might not be caused by OTG, I'll try my lock on the forge forums instead.

**Comment by PG85** [comment]
Hey, thanks for reporting. Will assume this is fixed, feel free to re-open if not.
