### ISSUE TITLE
[19:55:00 ERROR]: Could not load 'plugins/OpenTerrainGenerator-1.10.2-v17 (1).jar' in folder 'plugins'

### ISSUE THREAD

**Issue by hydradestruction** [PG85/OpenTerrainGenerator#24]
It keeps giving me this error in 1.11 idk if it will work in 1.11 all I know is it won't work

**Comment by PG85** [comment]
Heya, you're trying to use the 1.10.2 release with MC 1.11 that won't work. The 1.11 release is not ready yet, I'll make a post on https://www.reddit.com/r/openterraingen/ as soon as it is done.
