### ISSUE TITLE
Chunk loading crash on startup with OTG / Biome Bundle, Sponge, and Farseek / Streams

### ISSUE THREAD

**Issue by egshels** [PG85/OpenTerrainGenerator#240]
[Crosspost from spongeforge #2660](https://github.com/SpongePowered/SpongeForge/issues/2660)

**Comment by PG85** [comment]
Hey, thanks for reporting. Need to confirm that this has been fixed with the latest versions of Streams/Farseek.

**Comment by PG85** [comment]
Fixed on Farseek's end :).
