### ISSUE TITLE
Game crashing while generating terrain

### ISSUE THREAD

**Issue by ekkomaru** [PG85/OpenTerrainGenerator#241]
Running the latest forge,

The crash happens when generating new terrain  close to spawn (with Biome Bundle)
and it also happens with a default preset after a while (let's say 50 chunks from the spawn).
The game has allocated 12GB RAM and never runs out, I already tried it without optifine to no success.
EDIT: Reverting forge from 2835 to 2827 fixed  the issue.

**Comment by PG85** [comment]
Hey, thanks for reporting. This bug should be fixed with V7_r24.
