### ISSUE TITLE
Farseek + OTG: Server Crashing on exploration

### ISSUE THREAD

**Issue by ghost** [PG85/OpenTerrainGenerator#242]
Server crashing while in-game on new gen being created. Worked fine for about 10 mins. then crash.  - Using with Biome Bundle

Crash Log:  https://pastebin.com/NYTSfAKj
- We had many issues with worldgen of other mods such as ThaumCraft, MagneticCraft ores. They are fine in most chunks but randomly crashing as well.

**Comment by PG85** [comment]
Looks like a thread got stuck / was lagged, timed out and caused a crash. No clear culprit, so I can't do much more with this unfortunately. If you find a way to reproduce this reliably, and can work out which mod combination is causing this crash, feel free to re-open this issue or create a new one, thanks!
