### ISSUE TITLE
Nether fortresses enabled by default in "vanilla" preset.

### ISSUE THREAD

**Issue by aswheaton** [PG85/OpenTerrainGenerator#243]
All biomes in the vanilla preset have the lines:

`# Whether a Nether Fortress can start in this biome. Might extend to neighbor biomes.
NetherFortressesEnabled: true`

Which results in occasional nether fortresses throughout the overworld. Surely this should only be the case for the Hell biome? Modifying this for every biome may be cumbersome for the uninitiated. Steps to reproduce:
1) Generate a fresh world using OTG without an existing preset installed (i.e. set worlds: world: generator: OpenTerrainGenerator in the bukkit.yml). 
2) The resulting biome configs generated by OTG all have the line above.

**Comment by PG85** [comment]
Hey, thanks for reporting. The setting is false for the worldconfig, but true for all biomes, it is now only true for the hell biome by default. Will be included with v7 (v7_dev_r24 to be exact).
