### ISSUE TITLE
Cascading chunk gen during world-gen (forge, no sponge) StackOverflow

### ISSUE THREAD

**Issue by Water-Moon** [PG85/OpenTerrainGenerator#247]
The game crash randomly when walking around.
Seems that the generation method is calling check trunk method, and check trunk method is calling generation method, causing infinite recursive call.
Crash report:
[crash-2019-05-02_22.09.49-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3140480/crash-2019-05-02_22.09.49-server.txt)

**Comment by PG85** [comment]
Hey, thanks for reporting. Looks like a mod compatibility issue, please see if you can reproduce the issue after removing mods. Thanks!

**Comment by Water-Moon** [comment]
Oh I figured it out. It is a mod compatibility problem with a mod called "FuturePack". After removing that mod everything was fine.
