### ISSUE TITLE
Streams/Farseek: Server crash (com.pg85.otg.forge.ForgeMaterialData.isAir)

### ISSUE THREAD

**Issue by orblazer** [PG85/OpenTerrainGenerator#249]
Hello,
I am playing on **Life And Village** modepack and i have recently server crash with generation.

The version of mod : 1.12.2 - V6
The version of modpack: 1.10a
The crash report : https://pastebin.com/LAVvqKhi

Thanks

**Comment by PG85** [comment]
Hey, thanks for reporting. Streams and perhaps Farseek look like likely candidates, please try removing them and see if the crash continues, thanks!
