### ISSUE TITLE
Incompatibility with SpongeForge

### ISSUE THREAD

**Issue by viiivira** [PG85/OpenTerrainGenerator#25]
When using both OpenTerrainGenerator and [SpongeForge](https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2), the game [crashes with an exception in server tick loop](https://gist.github.com/Everett1999/859ac6dd017ad58fbc9787d453443a2a) when generating a world, or loading a previously generated world. 

While loading the world, the log reads 
`[FML]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.`

This issue has also been reported on the SpongeForge Github page SpongePowered/SpongeForge#1489

This has apparently been an [issue in the past with TerrainControl,  but was fixed at some point?](https://forums.spongepowered.org/t/sponge-server-crash/18780)

This issue is present on v18 of OpenTerrainGenerator.

**Comment by BakermanLP** [comment]
The same here, only sponge and OpenTerrainGeneration version 17 or 18 with latest spongeforge were installed.

**Comment by ghost** [comment]
Same here! Brand new server, all files newly generated. Latest version of sponge with the correct version of forge to go along with that. When I have just OpenTerrainGenerator installed, not sponge, it works fine. Even with Biome Bundle to go along with it it works just fine. As soon as I install Sponge though, I get the same error.
Please fix it, this bug could prevent a lot of people, including me, from using it on a public server

**Comment by PG85** [comment]
Hey thanks for reporting this, could you grab the latest dev version from the comment in this post and tell me if that fixes the problem?

https://www.reddit.com/r/openterraingen/comments/6g6zvq/new_otg_releases_for_1102_and_1112/

**Comment by ghost** [comment]
Loaded the server up with sponge, OTG and Biome Bundle, started up without errors and loaded the world. I was also able to join the world with a client with the same OTG and biomebundle versions installed. 

Thank you for the hotfix!

**Comment by PG85** [comment]
Great to hear! Thanks for the feedback :)

**Comment by viiivira** [comment]
This fix does not seem to work when playing a single player/local instance. When generating a world with the latest version of sponge installed along with any OTG preset or biome bundle, the game freezes and no crash log is created. However, in the [fml-client-latest.log, it appears the crash is due to an NPE: World Properties has a null UUID (Line 4353).](https://gist.github.com/Everett1999/8a494fe22e45acb8437162338fd77d83#file-fml-client-latest-log-L4353)

**Comment by PG85** [comment]
Looks like the problem might only occur when using dimensions, Could you try to confirm and if you can create a new issue for Sponge+dimensions specifically?

Biome Bundle has Skylands/Flatlands/Void configured as dimensions by default, so would have to remove the Skylands/Flatlands/Void jars and also delete their world directories in OpenTerrainGenerator/worlds/. If OTG works with only Biome Bundle then you can try adding only Skylands and see if that breaks things. If it breaks when adding skylands then it's likely an issue with dimensions.

Thanks!

**Comment by viiivira** [comment]
You are right, with only OTG and Biome Bundle, everything works as expected, once adding another pack the crash occurs. I will create another issue. Thank you.
