### ISSUE TITLE
OTG not fully deleted

### ISSUE THREAD

**Issue by thypastdilemma** [PG85/OpenTerrainGenerator#250]
I downloaded OTG, but upon experiencing problems with loading the Minecraft launcher, I was prompted to remove it.
When I thought I _fully_ removed the OTG file, the Minecraft launcher always crashed when I ever tried to make a new world, saying that OTG was still in use in files.
Any help with this? Literally cannot play 1.12 anymore rip,,

**Comment by blobfishhero** [comment]
In the mod folder of your usual version check in the version specific folder and delete OTGCore.jar if found. Heres some examples. It's in the same place if on windows.
![Screen Shot 2019-05-19 at 8 59 19 PM](https://user-images.githubusercontent.com/50812736/57990924-43490080-7a79-11e9-97bd-86e729d2a9bd.png)

**Comment by PG85** [comment]
Hey, thanks for reporting this, this is a know issue, will see if I can improve this for v8.
