### ISSUE TITLE
v7 Crash on pressing otg create world button.

### ISSUE THREAD

**Issue by SirSpence99** [PG85/OpenTerrainGenerator#253]
[crash-2019-05-25_16.39.07-client.txt](https://github.com/PG85/OpenTerrainGenerator/files/3219853/crash-2019-05-25_16.39.07-client.txt)

If you have a folder that is not a properly formatted biome folder in your worlds folder, you get this crash on pressing create OTG world. The crash occurs before getting the option to pick a preset.

**Comment by PG85** [comment]
Thanks for reporting! Will be fixed with V7_DEV_r24, release will be posted in the Discord in the OTG-dev channel soon.
