### ISSUE TITLE
v7 Having a seed that is not an integer on a dimension causes crash.

### ISSUE THREAD

**Issue by SirSpence99** [PG85/OpenTerrainGenerator#254]
[crash-2019-05-25_17.10.24-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3219874/crash-2019-05-25_17.10.24-server.txt)

I have a dimension that is loaded on world creation and the configs for that world have a world seed "PixelmonHollows". 

If I create a world using a different world that loads this one as a dimension, I get a crash. If I change the seed to "1" I no longer get a crash. This happens whether I have writeDisabled on or not.

This issue only seems to occur for dimensions. If I create a world that has a non integer seed it loads fine.

**Comment by PG85** [comment]
Thanks for reporting, fixed in v7_r25 :).
