### ISSUE TITLE
v7 (and v6) UnloadAllCustomDimensionData

### ISSUE THREAD

**Issue by SirSpence99** [PG85/OpenTerrainGenerator#255]
[crash-2019-05-25_17.24.20-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3219876/crash-2019-05-25_17.24.20-server.txt)

If I create a world with OTG dimensions and then leave it and attempt to create another world (OTG or otherwise) without restarting my client I get this crash.

**Comment by PG85** [comment]
Thanks for reporting, this should be fixed with v7-r24.
