### ISSUE TITLE
Game crashed after playing for hours and won't restart: CustomObjectStructureCache.LoadStructuresFile

### ISSUE THREAD

**Issue by Devious67** [PG85/OpenTerrainGenerator#256]
[crash-2019-05-27_17.28.56-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3224485/crash-2019-05-27_17.28.56-server.txt)

**Comment by PG85** [comment]
Looks like a BO3 issue, please use a text editor such as notepad++ to do a text search on all your world's files in the mods/OpenTerrainGenerator/worlds/<world> folder for the text: "-1129]".

Are you using a pre-made pack or are you editing BO2's/BO3's yourself?

**Comment by PG85** [comment]
On closer inspection, it may also be the result of an error in an earlier session, where a structure wasn't generated properly or the structure data could not be saved. You'll probably find the string "-1129]" in the StructureData.txt file in the world save folder.
