### ISSUE TITLE
ReplaceToBiomeName replaces to wrong biomes

### ISSUE THREAD

**Issue by Darsenia** [PG85/OpenTerrainGenerator#259]
I found another problem with ReplaceToBiomeName feature:it causes the game sometimes to use wrong biome name(and it's colors etc),not the mentioned one.Biome,that I use for replacement has id<256 and has no spaces in its name(however,spaces don't seem to make any sense),for example, biome BirchWaters(id:265) has line ReplaceToBiomeName: BirchLakes(id:76).However,it replaces BirchWaters name and colors with ConiferousForest biome(id:73).Similar things happen to some other replaced biomes.Deleting world,making new one,restarting game isn't helpful,nothing changes.

**Comment by SirSpence99** [comment]
Are you running any mods other than OTG? Do those mods add biomes?

**Comment by Darsenia** [comment]
Yes,but just a few,mostly decorative(better foliage,optifine,jei,treecapitator etc).As for biomes-only Thaumcraft ,because I've also added some features for better compatibility to my biome pack(Magical biome,custom greatwood and silverwood trees in other biomes,flowers etc).I will remove it,maybe it could be the reason...

**Comment by PG85** [comment]
Hey @Darsenia, we'll need more information to help you. Could you create an OTG world with as few biomes as possible (preferably 1-3) that demonstrates the problem, using as few mods as possible (preferably 0-1)? Thanks!

**Comment by SirSpence99** [comment]
Get the mod "tellme" and get a dump of your biomes on a vanilla world. Make sure that none of your biome IDs overlap with the ones that thaumcraft is using.

My best guess is that this will help you fix your problems.

**Comment by Darsenia** [comment]
As for now I'm removing Thaumcraft from biomes(it will take some time,it's features are everywhere...),as I see it helpes with some biomes already,but I need some time to check 200+biomes.I'll do a tellme dump also)

**Comment by Darsenia** [comment]
Wow,i checked those biomes i remember to be wrong and everything is ok!)You are awesome^^So it was a biome id conflict with Thaumcraft.However it's strange,because Thaumcraft uses only 3 ids(i did a dump some time ago with only vanilla biomes and Thaumcraft),and I had much more chaotic errors with biomes, and  they appeared only after  I had reached 256 limit and had to change half of the biomes to virtual.Everything was ok with just ordinary biomes 40-126,168-255

**Comment by Darsenia** [comment]
Well,without Thaumcraft tellme dump is ok,with it - part of the biomes from 40-126 were not dumped at all! 40-42 are Thaumcraft biomes,then 127 with vanilla minecarft "void".
I changed my ids 40-42 to not conflict with Thumcraft and it seems to work.Dump is now ok.
Thanks a lot!

**Comment by SirSpence99** [comment]
No problem, I ran into this issue as well and spent a good couple days troubleshooting it. Of course, I didn't know the tellme mod existed (I even searched for it) so I had to manually go through and check every biome for errors. I found out about the mod about half an hour after I had finished going through all possible IDs.

**Comment by Darsenia** [comment]
Yeah,I know,It's so frustrating to see how all your work is turning into a mess:/

**Comment by PG85** [comment]
Thanks for helping @SirSpence99! @Darsenia: OTG v7 generates biome id's dynamically for new worlds, so we shouldn't see this problem anymore :).
