### ISSUE TITLE
OTG + RC: Missing chunks in large structures and villages

### ISSUE THREAD

**Issue by chland** [PG85/OpenTerrainGenerator#26]
When I try to use the latest OTG+BiomeBundle in conjunction with RecurrentComplex (RecurrentComplex-1.3.1.1-1.10.jar) structures from RC only generate partially inside of villages. Its basically the same issue described in https://github.com/Ivorforce/RecurrentComplex/issues/197 

Ivorforce did actually find a bug in his code and after fixing it, villages were generated normally in all "alternative" World-Generators I tested (ATG, RTG+ClimateControl, BoP, Quark) but the problems in OTG-worlds stayed the same. Pretty much every village I found was totally messed up with missing parts in RC (and vanilla!) structures.

My guess is, that probably the generators run in an "unexpected" order - so I guess RC generates parts of the village and OTG then overwrites parts of it later... probably... maybe :) I don't know :)

Edit: I've posted a few screenshots (that are also showing chunk-borders) over at http://imgur.com/a/btVrS - the strange thing seems to be, that always half-chunks are missing - not full chunks. And that if the generation breaks it destroys vanilla-structures, too.

**Comment by PG85** [comment]
Hey @chland, thanks for reporting this. It's most likely related to RC spawning things across chunk borders in chunks that are not currently being populated. Only a 2x2 chunk area so 4 chunks should be being populated at once, if a mod tries to spawn something across chunk borders then that may force other (unloaded) chunks into being loaded and populated, OTG cancels spawning of some things in those chunks to prevent cascading/runaway chunk population (chunks basically trigger each other into populating and it just keeps going and causes lag spikes or even crashes/servers being stuck populating chunks forever).

Will have to do some tests with RC to confirm. You can also set the log level to Trace in OpenTerrainGenerator.ini, you should then see messages whenever chunks are being force-populated, as well as a stack trace for each such event in which you can see which mod caused it. In the latest OTG builds (where we've added multiple dimensions) OTG actually force-populates chunks itself sometimes, this should be rare though.

**Comment by Reidlos65** [comment]
Any further information on this? workarounds?

**Comment by PG85** [comment]
Nope, sorry still working on it. Did have a chat with the RC dev, he gave me some new things to try. Will take a look a.s.a.p.

**Comment by Ivorforce** [comment]
Also see BiomeBundle/BiomeBundle#56 as well as https://github.com/Ivorforce/RecurrentComplex/issues/260.

**Comment by xAlicatt** [comment]
I'm working on a modpack and really want to have the fuction of RC, but this isn't fixed yet. Would it be possible to get the same functionality out of OTG alone? I know it already generates some prefab structures? Couldn't the prefab structures from RC be moved into the OTG WorldObjects folder? Does OTG have the ability to add structures to villages?

**Comment by PG85** [comment]
Fixed with OTG 1.12.2 v3 / 1.11.2 v9, release asap.
