### ISSUE TITLE
Crash in OTG 1.12.2 - v6 "Unsupported modified version of game"

### ISSUE THREAD

**Issue by ErkisLurkis** [PG85/OpenTerrainGenerator#263]
Tried to load my single player server and not sure why it's like this. I have no knowledge of logs or mods so bare with me here. Here are the logs.
https://pastebin.com/bnPZ3zKu

**Comment by MCPitman** [comment]
Likely caused by the forge version, try downgrading to the recommended build (2768) and see if that solves the issue.

The next release of OTG (v7) will fix issues with later forge versions.

**Comment by ErkisLurkis** [comment]
I have to wait then. Some of my mods aren't compatible with 2768 forge
