### ISSUE TITLE
Bug: Armorstands in BO3s spawn in a Random Direction instead of the per NBT defined direction

### ISSUE THREAD

**Issue by LanToaster** [PG85/OpenTerrainGenerator#265]
Armorstands generate in Random Directions even if NBT data with proper direction is attached.

**Comment by PG85** [comment]
Thanks for reporting, does this affect Forge and/or Spigot?

**Comment by LanToaster** [comment]
Only tested on Spigot. Should I also test that on Forge?

**Comment by PG85** [comment]
With proper direction attached, do you mean the "Rotation" tag in the root, or the tags for each bodypart under "Pose" (see: https://minecraft.gamepedia.com/Armor_Stand)? Are there any other entities that are rotated this way?

**Comment by authvin** [comment]
Fixed as of https://github.com/PG85/OpenTerrainGenerator/pull/549

**Comment by PG85** [comment]
Thanks @LanToaster for reporting and @authvin for the fix, let us know if you have any problems.
