### ISSUE TITLE
Issue generating a chunk with RAD modpack, seems to be OTG mansion structure related

### ISSUE THREAD

**Issue by timturtle13** [PG85/OpenTerrainGenerator#267]
[crash.txt](https://github.com/PG85/OpenTerrainGenerator/files/3293627/crash.txt)

**Comment by PG85** [comment]
Hey @timturtle13, thanks for reporting this. Will have to test with RAD modpack. Can you provide reproduction steps?

**Comment by PG85** [comment]
Should be fixed with v8_r2, to be release on the OTG Discord at #openterraingen asap.
