### ISSUE TITLE
Bug: OTG Spawn doesnt work for WorldObjects 

### ISSUE THREAD

**Issue by LanToaster** [PG85/OpenTerrainGenerator#268]
"/otg spawn OBJECT" only works for Objects located in GlobalObjects, and only for Objects that dont contain a Space.

E.g.
OpenTerrainGenerator\GlobalObjects\FooBar.bo3 - Spawns
OpenTerrainGenerator\GlobalObjects\Foo Bar.bo3 - NotFound
OpenTerrainGenerator\worlds\world\WorldObjects\BarFoo.bo3 - NotFound
OpenTerrainGenerator\worlds\world\WorldObjects\Bar Foo.bo3 - NotFound

Tested on Spigot, but I assume it wont work on Forge the same, this is Broken since quite some time.

Edit: Okey, it turns out you can add the Preset to the command, but it should default to the world you are currently in if none Specified. But still cant spawn Objects with Spaces in the name.

Maybe one should also update the Usage Info on the command. Typing: 
"/otg spawn" just prints: "You must enter the name of the BO2" this sounds very outdated.

**Comment by PG85** [comment]
Thanks for reporting this. Josh from the Discord has reportedly already taken a look at this and fixed it, but hasn't submitted a pr yet. Since this can be made to work with a workaround, it's not critical, will put this in backlog for now.

**Comment by PG85** [comment]
Fixed for v9.0_r2. The worldname parameter has been removed, so its /otg spawn <objectname>. Spaces are allowed. The worldobjects folder for the current world is searched, if no bo3 is found, other dims' world folder are searched, if no bo3 is found, globalobjects is searched.
