### ISSUE TITLE
Crash: getChunk StackOverflow, seemingly random, updateTimeLightAndEntities

### ISSUE THREAD

**Issue by LudoKip** [PG85/OpenTerrainGenerator#269]
This crash appears to happen randomly during chunk generation while playing, as I have not been able to reproduce consistantly it.

I assume it is caused by one of the mods I have installed, as Pitman said he hasn't run into this issue.  Foamfix is not responsible, I encountered the crash even without it, same goes for Phosphor. The only other mods that might cause it, are Optifine and VanillaFix, I'll test without VanillaFix now. 

It does not happen all that often, but it is still a fairly annoying.
[crash-2019-06-23_22.09.15-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3318547/crash-2019-06-23_22.09.15-server.txt)

**Comment by LudoKip** [comment]
For this crash I was using forge 2768, and OTG v7 dev 26.

**Comment by PG85** [comment]
Hey, thanks for reporting. I'll need to see the beginning of the stack that caused the overflow. It should be in the debug log, the file may be large. I only need to see the beginning of the exception, so the bit that isn't repeated all the time. Thanks!

**Comment by LudoKip** [comment]
Not sure if this bit is what you mean.
https://pastebin.com/hSk9n5Q3
EDIT: This is from another crash I just had, this time without VanillaFix.

Another edit:
https://pastebin.com/WsNyE17T
This is from an earlier crash, I notice some similarities.

**Comment by PG85** [comment]
Hey thanks, have seen this crash myself as well, haven't been able to track it down yet. If you find a reliable way to reproduce it, please let me know.

**Comment by PG85** [comment]
Have also seen this in dev environment without any other mods installed, according to an old comment of mine this apparently happens on rare occasions when a chunk that has already been loaded is falsely reported as unloaded, and MC tries to generate the chunk again. Not sure if that's really the case, still have to find a way to reproduce this reliably. Will continue with this once I've got more information.

**Comment by Froosty11** [comment]
Been having this exact issue with crashing happening while I fly fast on an elytra. Mods installed are lots. crashLog here. 
https://pastebin.com/RSze0x2f

**Comment by solunareclipse1** [comment]
Having the same issue from what I can tell. Seems to happen when moving very fast into new chunks.
I have 350ish mods in this, but from what I can tell this report is at least related, so I thought I would just put it here, just in case it helps :)
https://paste.ee/p/ojaI5

**Comment by PG85** [comment]
Thanks for the feedback! Haven't seen this bug in a long time, still no idea what might be causing it. Please try v8.3 once its released or grab a dev version from the Discord and let me know if you see it again.

**Comment by PG85** [comment]
Needs testing/confirmation with v8.3_r4 or up.

**Comment by PG85** [comment]
Haven't seen this in weeks, testing with v9.0 (dev version). Feel free to reopen if the issue still occurs with v9.0 or above.
