### ISSUE TITLE
Crash after quitting a world and opening it again

### ISSUE THREAD

**Issue by mensreaMC** [PG85/OpenTerrainGenerator#272]
Minecraft version 1.12.2
Forge 14.23.5.2838
OpenTerrainGenerator-1.12.2+-+v6 (latest github build but it also happens with v6)

If you leave either a single player map it crashes and prevents you from going back into any map. You have to restart the game for it to work again. There's a special message in the crash log if you have optifine but it's also happening without it. 

Optifine crash log: https://pastebin.com/2kNUFWiZ
Without Optifine crash log: https://pastebin.com/wFE4BDjd

**Comment by mensreaMC** [comment]
This is also happening without optifine as well. Has anyone else seen this? It prevents you from going into a world more than once. I have to restart every time I leave a single player map. Here's another crash log minus optifine: https://pastebin.com/wFE4BDjd

**Comment by PG85** [comment]
Hey @mensreaMC, thanks for reporting this. Very odd that I've not noticed this and noone else has reported this. Can you confirm this has been fixed for you with v7 (available on OTG Discord otg-dev channel)?

**Comment by mensreaMC** [comment]
This was fixed with v7 and v8. Thanks again!

**Comment by PG85** [comment]
Sweet, thanks :)
