### ISSUE TITLE
MovementFactor not correctly implemented v7r26

### ISSUE THREAD

**Issue by SirSpence99** [PG85/OpenTerrainGenerator#273]
It appears that there is an issue with MovementFactor when moving between dimensions.

Let's say you have dimension A with a factor of 1 and dimension B with a factor of 10. If you move from A at the coords 100,0 you end up in B at 100,0 (Instead of 10,0) if you then move from B to A you end up at 1000,0 (As expected)

So when moving from one dimension to the other, it only mulitiplies the dimension by an integer. This means that the coordinate will never be smaller than the dimension you entered from.

This happens with portals and using DimensionAbove/Below and can allow you to travel millions of blocks within 10 minutes with a factor as small as 2.

I am running v7r26

**Comment by PG85** [comment]
Hey @SirSpence99, thanks for reporting this. Will be fixed for v8 release.

**Comment by PG85** [comment]
Should be fixed for v8_r2
