### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by IGieckI** [PG85/OpenTerrainGenerator#274]
Hi minecraft crashed and gave me this error by designating the OTG as a probable cause, I hope it can be useful to fix the problem:
[crash-2019-06-30_21.59.18-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3343286/crash-2019-06-30_21.59.18-server.txt)

**Comment by PG85** [comment]
Hey @IGieckI, thanks for reporting this. Same as #279 .
