### ISSUE TITLE
Mod compat: Pam's Harvestcraft, Forestry, and Advent of Ascension. Trees not spawning.

### ISSUE THREAD

**Issue by MechanosG** [PG85/OpenTerrainGenerator#275]
First, I'd like to suggest better compatibility with mods like Pam's Harvestcraft, Forestry, and Advent of Ascension.

With Pams, the fruit trees don't spawn at all, and with the gardens it seems like only 2 or 3 garden types will spawn.  Mostly shaded gardens everywhere regardless of biome.  Arid gardens seem to spawn properly around deserts, and I might have seen a windy garden once.  With Forestry, none of the trees will spawn, and [some of the beehives have been reported not spawning](https://github.com/ForestryMC/ForestryMC/issues/1911).  With AoE, I think biomes intended only for other dimensions might be spawning in the overworld, such as the Mysterium biome.  While far from a perfect search, the above observations have been main in roughly a 5000x5000 area, using Biome Bundle.

Secondly, unless it exists already, I recommend some kind of configurable global multiplier for biome sizes.  Currently to the best of my knowledge, if I want to change the size of biomes in Biome Bundle, I have to manually edit every single one individually, right?  That's 445 files I have to edit lmao.  I have a survival modpack currently in private multiplayer testing, and people are reporting having extreme difficulty looking for biomes because other biomes are so huge and some of them are seemingly rare (like jungles, which have a biome rarity of 99 out of 100 in Jungle.bc).  Specific biomes are important in this pack due to mods spawning blocks/enemies only in certain biomes.  It would be super handy to be able to just change a multiplier and reduce the size of all biomes.

**Comment by PG85** [comment]
Hey @MechanosG, thanks for reporting. @MCPitman could you take a look at this? Would be good to know what works, what doesn't, which features ppl should use to make these things appear in biomes etc.

OTG v7 has some new features, so some of these things may already work, provided you have the correct settings for the biomes. As for the biome sizes, that's a bit more complicated. I hope you and Pitman can drill down on this a bit and define some more concrete tasks for me. Thanks!

**Comment by PG85** [comment]
For v8, have made some minor improvements that may allow more modded content to spawn (added some missing events, fixed some minor registry issues). For some things, like HarvestCraft's trees, there is a bigger problem though, see #300. For questions and support about biome sizes etc, please visit our Discord at #openterraingen, thanks!
