### ISSUE TITLE
Bug: Strongholds spawn in ocean even when disabled in biome config

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#276]
Strongholds still spawn in the Ocean biome (even with the default configs) if they are disabled in the biome config. Usually this results in a single room containing only the end portal:

![2019-07-07_23 56 00](https://user-images.githubusercontent.com/9453952/60774909-2a70d900-a113-11e9-8909-be6e3d0e30fd.png)

**Comment by PG85** [comment]
Version? Forge and/or Spigot?

**Comment by PG85** [comment]
Needs testing / more info.

**Comment by PG85** [comment]
Won't fix this for 1.12.2, will have to see if the issue occurs for 1.16.
