### ISSUE TITLE
[1.12.2] crash using map configs from v.6 in v.7

### ISSUE THREAD

**Issue by mensreaMC** [PG85/OpenTerrainGenerator#277]
forge version: 14.23.5.2838
OTG version: v7 dev r26

I'm trying to load a custom map along with its dimensions that I set up and successfully ran in v6. I keep running into this error when I try to make a new map: https://pastebin.com/uCfZbuNM

EDIT: I removed a dimension that had biomes that were named the same things as biomes in another dimension and now I'm getting a brand new error involving gravity. I saw the note about 1.11 but I'm definitely running 1.12.2. Error: https://pastebin.com/NseCwMJv

**Comment by PG85** [comment]
Hey @mensreaMC, thanks for reporting this. Did you delete OTG-Core.jar from the 1.12.2 directory when updating from v6 to v7?

**Comment by mensreaMC** [comment]
Yes, this was the issue. Thanks!

**Comment by PG85** [comment]
Awesome, thanks for the feedback :)
