### ISSUE TITLE
[1.12.2][Request] Flag on "SaveToDisk waiting... an endless loop" to ensure the log isn't filled with message until crash

### ISSUE THREAD

**Issue by NichFons** [PG85/OpenTerrainGenerator#278]
If the loop is hit, the game's log can quickly fill up pretty quickly. In my case it was producing 2 GB logs, around 1.9 of which were this log message. In the off case that this comes up, could a flag be added to make sure the log file isn't flooded?

For reference:
[01:15:51] [Server thread/INFO]: SaveToDisk waiting on Populate. Although other mods could be causing this and there may not be any problem, this can potentially cause an endless loop!

**Comment by PG85** [comment]
Hey @NichFons, thanks for reporting this. Have fixed this for v8_r1, to be released on the otg discord otg-dev channel a.s.a.p.
