### ISSUE TITLE
Random Crash - StackOverflow 'Exception generating new chunk'

### ISSUE THREAD

**Issue by ghost** [PG85/OpenTerrainGenerator#279]
In my current pack setup, once in a while there is a random crash that seems to be on the integrated servers end in a single player world (I imagine this could/would happen on a server as well), the crash doesn't corrupt the world, doesn't cause chunk boarders and doesn't render it as unplayable in any other way, but it still can be somewhat of an inconvenience.

Crash report (As of July 18th):
https://paste.dimdev.org/lijaqubecu.mccrash

Crash report (as of July 27th):
https://paste.dimdev.org/ijulupacus.mccrash

Forge Version:
forge-14.23.5.2838

Terrain Generator Mod(s) Versions:
OpenTerrainGenerator-1.12.2 - v6.jar
Biome_Bundle-1.12.2-v6.1.jar

**Comment by PG85** [comment]
Hey @SextupleTap, thanks for reporting this. I've seen this crash as well, unfortunately I haven't been able to figure out what's causing it. If you find a way to reproduce this, let me know.

**Comment by ghost** [comment]
I'll keep in touch for this report since I'm still working on this personal modpack-

**Comment by PG85** [comment]
Same as #269.
