### ISSUE TITLE
Feature: Re-implement UseTemperatureForSnowHeight

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#285]
UseTemperatureForSnowHeight in the worldconfig.ini doesn't do anything. From the comments description it should place deeper snow layers at higher terrain Y values but enabling it doesn't do anything. Here's an example of what could be achieved if it worked:

http://i.imgur.com/cJLSS4I.jpg

**Comment by PG85** [comment]
Like the idea, need more info. How exactly should temperature / terrain height relate to snow height? Why would higher terrain Y get "deeper" snow layers, is it always colder there? Deeper as in, the higher the y of the surfaceblock, the more stacks of snow put on it? Not sure I understand.

**Comment by PG85** [comment]
Have disabled this setting for now, it is not read from or written to the configs. Will need to re-implement later.

**Comment by PG85** [comment]
Fixed for v9.0, enable BetterSnow in the worldconfig for layered snow.
