### ISSUE TITLE
Feature: Biome Rarity Scaling/Minimum Distance to Spawn

### ISSUE THREAD

**Issue by TerdyTheTerd** [PG85/OpenTerrainGenerator#287]
I spent several days messing around and configuring BiomeBundle for OTG to my liking, and one thing that I really wanted was the ability to specify for biomes to scale their rarity with distance, so you could specify a biome to be super rare near spawn. or [0,0], and as the distance increases so does its chance of spawning, using some type of ratio calculation, like a DistanceStep: 500 and DistanceStepMultiplier: 2, so that every 500 blocks the current rarity gets double, so a biome with low rarity like .005, would eventually become ~5 at 20000 blocks out. Additionally there should be an option to limit this, MaxDistanceRarirty: 5, or some other way to prevent that biome from completely taking over world gen at extreme distances. Another possible option is to add in SpawnMinimumDistance: or SpawnMaximumDistance: to set lower/upper bounds on where biomes can spawn, but not really important. If this is already added or planned that would be great, when I did all my testing it was on v6.
If this isn't planned or already implemented, if you had any pointers on to how this might be possible I'd love to hear, I can dabble around a bit in the code and run some test implementations

**Comment by PG85** [comment]
Hey @TerdyTheTerd, thanks for the feedback :). @MCPitman, could you take a look at this?

**Comment by PG85** [comment]
Be sure to join us on the OTG Discord at #openterraingen btw and ask around there. MCPitman, the creator of BB is also lurking around there.

**Comment by PG85** [comment]
Have made a new issue for new biomegen modes, see: #720
