### ISSUE TITLE
Sapling queue error

### ISSUE THREAD

**Issue by LudoKip** [PG85/OpenTerrainGenerator#288]
I tried out sapling queue in v8, here is what I found.

Here is a crash report generated by VanillaFix. The game doesn't shut down, you can still play. 
https://pastebin.com/z3ZdAM88
I planted a sapling (oak) on grass, and used bonemeal to grow the tree. 
Here is the line I used:
Sapling(Oak,ForestOakLarge1,20.0,ForestOakLarge2,25.0,ForestOakLarge3,33.0,ForestOakLarge4,50.0,ForestOakLarge5,100.0)
All these trees are objects present in the WorldObject folder, with tree: true. When the tree is grown, either the sapling simply disappears, or a tree broken tree is placed.

I then tried the same with spruce trees. It seems like the tree spawns fine, unless it is near/crossing a chunk boundary. 

Next to that, the object completely replaces any blocks in it's way. A block of bedrock directly above the sapling, is removed. 

All of this occurs even when OTG is the only mod present.

**Comment by PG85** [comment]
Hey @LudoKip, thanks for reporting this. Will take a look at this for v8.

**Comment by PG85** [comment]
For v8_r2 exception is fixed and saplings spawn fine now even on chunk borders. Blocks being replaced can be configured via SourceBlocks/OutsideSourceBlock
