### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by Henryman23** [PG85/OpenTerrainGenerator#289]
https://paste.dimdev.org/akuvileqow.mccrash

**Comment by PG85** [comment]
Hey @Henryman23, could you try grabbing v7/v8 from the OTG discord and see if that fixes your problem? Also, could you provide a description as to what you're trying to do?

**Comment by PG85** [comment]
If you're still having problems, visit our Discord at #openterraingen, thanks!
