### ISSUE TITLE
Client crash on going into portal

### ISSUE THREAD

**Issue by a-frenzy** [PG85/OpenTerrainGenerator#29]
Going through a portal from flatlands to biome bundle https://gist.github.com/frenzye/14b1eb376ef56807795c933881c875e6

**Comment by PG85** [comment]
Thanks for reporting this, did this happen once or does it keep happening even after server/client reboot?

**Comment by a-frenzy** [comment]
Keeps happening https://gist.github.com/frenzye/5ccd1d3e9a41f6610a126385a4cffcf8 Going between a modified flatlands and a stock biome bundle. Have dimensions turned on for both and have specified different portal types

**Comment by PG85** [comment]
I've seen this before with other mods. It appears that some mod is replacing or removing the default teleporter registered to the world. I thought it was AbyssalCraft but I don't see that in your mod list. Could you try removing/disabling any mods that affect dimensions/portals, see if that fixes it and if so try to narrow down the problem to as few mods as possible?

**Comment by a-frenzy** [comment]
https://minecraft.curseforge.com/projects/netherportalfix was the culprit

**Comment by PG85** [comment]
Cool, thanks for confirming!
