### ISSUE TITLE
[Linux] World not saved to OpenTerrainGenerator/worlds/ if name does not match preset

### ISSUE THREAD

**Issue by 7thfleet** [PG85/OpenTerrainGenerator#294]
This issue only occurs on Linux. It occurs with both OpenJDK and Oracle's JDK. I have reproduced it on two separate computers, both running Arch. The same computer running Windows does not exhibit this issue.

This is forge, client.

This issue occurs on v7 and v8, but not v6.

If a world is not saved with the same name as the preset name, it is not written to OpenTerrainGenerator/worlds/.
It is written to saves/, and still appears in the world selection menu. See screenshot.

![Screenshot](https://i.imgur.com/tL2zg1P.png)

As a result, [This returns null.](https://github.com/PG85/OpenTerrainGenerator/blob/1.12-OTG+-V8/platforms/forge/src/main/java/com/pg85/otg/forge/gui/mainmenu/OTGGuiListWorldSelectionEntry.java#L329) 

Compare the directory information in the above screenshot to the values below.
![Locals](https://i.imgur.com/J7pO1Vl.png)

Let me know if there is anything you'd like me to do to help.

**Comment by 7thfleet** [comment]
I found that part of the problem is the use of the Windows-style slashes instead of / or File.separator [here.](https://github.com/PG85/OpenTerrainGenerator/blob/1.12-OTG%2B/platforms/forge/src/main/java/com/pg85/otg/forge/gui/dimensions/OTGGuiDimensionList.java#L627)

Fixing this allows OTG to successfully load vanilla worlds generated through the OTG menu. However, BiomeBundle fails to load, as seen below.
![Screenshot](https://i.imgur.com/0CgLjPE.png)

An inspection of the OpenTerrainGenerator/worlds/ directory shows that some of the relevant folders exist, but are empty. Examine the tree [here](http://termbin.com/11vm) to see the difference.

**Comment by PG85** [comment]
Hey @7thfleet, thanks for reporting this and sorry, I've neglected the Linux users a bit. I've changed all filepaths (I could find) to use platform-independent file separators. Will be included in v8_r2 (dev build), to be posted on the OTG Discord at #openterraingen asap. When you have the chance, please let me know if it fixes the problems for Linux.
