### ISSUE TITLE
Crash: Map made in WorldPainter populated with OTG doesn't generate any vanilla structures on a server

### ISSUE THREAD

**Issue by RRyyas** [PG85/OpenTerrainGenerator#296]
So i made a custom map in WorldPainter, and i'm using OTG to populate the map, since you could control where things generate. It works on Forge singleplayer, but not on a Bukkit or Spigot server. The other stuff works, such as ores, trees and custom structures. I couldn't try it out on a Forge server, because it keeps crashing with this message: https://pastebin.com/bWUWvrRB (not relevant to this problem)

**Comment by PG85** [comment]
Hey @RRyyas, thanks for reporting this. Have you already tried asking for support on the OTG Discord at #openterraingen? Unfortunately I rarely use FromImageMode, would be good to confirm with the people on the Discord that this is not somehow a configuration issue and that this feature really isn't working. Thanks!

**Comment by PG85** [comment]
Needs testing/confirmation. NLBlackEagle could help?

**Comment by PG85** [comment]
Please ask NLBlackEagle on the OTG discord if you're still having problems with this. He's been using FromImageMode / WorldPainter for ages and has never reported problems with this.
