### ISSUE TITLE
Non virtual biomes not spawning in v7/v8

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#297]
Both attached example worlds are supposed to spawn only one custom biome, the only difference between the two is that the custom biome is virtual in #2 and not in #1

You'll see that with the non-virtual example (#1) the custom biome isn't even registered by OTG (i checked using the tellme mod) and as a result never generates. This is happening when using dynamic IDs btw (nothing in CustomBiomes:)

[Example Worlds.zip](https://github.com/PG85/OpenTerrainGenerator/files/3512114/Example.Worlds.zip)

**Comment by PG85** [comment]
Should be fixed for v8_r2.
