### ISSUE TITLE
Bug: Weird grass colour lines in v8

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#298]
https://cdn.discordapp.com/attachments/285816707040280586/607213577350152203/unknown.png

They seem to disappear if i reload chunks but then appear elsewhere:

https://cdn.discordapp.com/attachments/285816707040280586/607213909136637952/unknown.png

**Comment by PG85** [comment]
I've seen the same thing, appears to be very rare though, looks like more lighting issues. Will need more info and/or a way to reproduce this reliably before I can fix this.

**Comment by PG85** [comment]
Merging with #376 (Flickering grass colours)
