### ISSUE TITLE
pre-generating chunks

### ISSUE THREAD

**Issue by ghost** [PG85/OpenTerrainGenerator#299]
I created a survival world with OTG and I got an hour into it before realizing that I had set the pre-generating chunks to be a very high number. This has caused my world to lag while it is loaded and the estimated time until its done generating chunks is 6500 hours. I don't want to wait that long, so is there a way that I can stop these chunks from generating without deleting my world?

**Comment by PG85** [comment]
Hey @Reedscraft, you can use the /otg pregen command (OTG v6) or the "O" menu (OTG v7 and up) to set the pregeneration radius to 0, this will cause the pregenerator to stop as soon as it finished its current cycle. It will then save and set the pregeneration radius to the amount it had already generated. For more questions or support, please visit our Discord at #openterraingen, we like to keep the git for technical issues, thanks!
