### ISSUE TITLE
[1.10.2] Client crash with WTF Ore

### ISSUE THREAD

**Issue by ruyanve** [PG85/OpenTerrainGenerator#3]
Re-post from reddit
WTF Mod: https://minecraft.curseforge.com/projects/wtfs-expedition-cavebiomes-ores-trees-and-tweaks?gameCategorySlug=mc-mods&projectID=227931
Here's the log: https://gist.github.com/ruyanve/da7bc2879606fdf24d5f625be9935bc5

**Comment by ruyanve** [comment]
I'm stupid! Has nothing to do with OTG... Sorry!!

**Comment by PG85** [comment]
No problem, thanks for reporting bugs anyways ;).
