### ISSUE TITLE
Feature: Re-implement TerrainMode: Default

### ISSUE THREAD

**Issue by moxydotorg** [PG85/OpenTerrainGenerator#30]
I've got a world config that works when used in the spigot environment but the identical config causes a crash in the forge environment.

The problem seems to stem from setting TerrainMode to Default.

After you choose create new world the program hangs and the console says

> SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.

I tried increasing the logging level in the OpenTerrainGenerator.ini to Debug and Trace but was unable to get any additional output from either of these settings.

The crash report references a NullPointerException in WorldServer.java. I know that's not part of OTG but maybe OTG is passing it a null value somewhere that shouldn't be null in the forge version and passing a valid value in the spigot version?

Attached are my sample world config files with the absolute minimal settings required to exhibit this issue, the log files, and crash reports for both the forge run and the spigot runs.

Spigot version:
CraftBukkit version git-Spigot-a9631d2-67b2424 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

Forge version: 1.10.2-12.18.3.2297

OTG version: OpenTerrainGenerator v1.10.2 v18

I know this may seem a bit silly to fix but with the dimension support now we can hopefully move our server from spigot to forge. Fixing this issue will allow us to bring over all of our vanilla worlds and keep the vanilla generator keeping the biome information accurate. It'll also keep the spigot and forge version features the same.

This same config file works in TC for forge version 1.8 as a point of reference when it was last known to work in forge.

[Error Files.zip](https://github.com/PG85/OpenTerrainGenerator/files/1034721/Error.Files.zip)

**Comment by PG85** [comment]
Hey, I'm sorry it's currently not possible to use the vanilla world generator in the overworld together with OTG.

**Comment by PG85** [comment]
Ok I think I misunderstood, looks like the problem is that TerrainMode: Default isn't working properly. To be honest I hadn't taken that feature into account when working on dimensions and re-doing a lot of the Forge code. I'm not sure that it can be made to work properly, will have to investigate. I see how handy it could be for using OTG with existing worlds though. Will look at this later when there are less critical things on the to-do list.

**Comment by PG85** [comment]
@MCPitman, please let me know how this should work and if this should have prio.

**Comment by PG85** [comment]
I've disabled TerrainMode: Default and OldGenerator for v8_r3. The settings are no longer read from or written to the configs. Will have to re-implement this in the future, will keep this ticket open for that.

**Comment by PG85** [comment]
Since OTG v8, non-OTG overworlds (vanilla or modded) can be used with OTG dimensions for Forge.
