### ISSUE TITLE
Missing world-config result in crash at server startup

### ISSUE THREAD

**Issue by ErikSteiner** [PG85/OpenTerrainGenerator#304]
Two cases that end in a crash.

Details:
- Forge 1.12.2-14.23.5.2768
- Biome_Bundle-1.12.2-v6.1.jar
- OpenTerrainGenerator-1.12.2_-_v8_r3

### **1. Case one:**

**Conditions:**
- mods folder contains two files: OpenTerrainGenerator-1.12.2_-_v8_r3.jar, Biome_Bundle-1.12.2-v6.1
- any leftover of other versions in mods folder were deleted. Like the "1.12.2"- and/or the "OpenTerrainGenerator"-folder
- folder with world name does not yet exist (so map is not yet generated)
- level-name in server.properties is not Biome Bundle, e.g. Midgard

**Expected:**
OTG loads at startup and creates folder called Midgard in `\mods\OpenTerrainGenerator\worlds`

**Actual Result:**
Server crash at startup. See [crash_case_one.txt](https://github.com/PG85/OpenTerrainGenerator/files/3538216/crash_case_one.txt)

### **2. Case one:**

**Conditions:**
- mods folder contains one file: OpenTerrainGenerator-1.12.2_-_v8_r3.jar
- any leftover of other versions in mods folder were deleted. Like the "1.12.2"- and/or the "OpenTerrainGenerator"-folder
- folder with world name does not yet exist (so map is not yet generated)
- level-name in server.properties is not Biome Bundle, e.g. Midgard

**Expected:**
OTG loads at startup and creates folder called Midgard in `\mods\OpenTerrainGenerator\worlds`

**Actual Result:**
Server crash at startup. See [crash_case_two.txt](https://github.com/PG85/OpenTerrainGenerator/files/3538228/crash_case_two.txt)

### **Conclusion:**
Both cases worked on OpenTerrainGenerator-1.12.2+-+v6.jar.
Typical procedure of case one: I choose any level-name for my server and launched the server. Then I stopped it and copied the content of the "Biome Bundle" folder in `\mods\OpenTerrainGenerator\worlds` to my worlds folder called Midgard. So next time launching my level-name Midgard it loaded the Biome Bundle config for Midgard..

The typical procedure for case two would be the lack of a config, because you want to create one. So you can not provide any config in `\mods\OpenTerrainGenerator\worlds`. What to do then?

**Comment by PG85** [comment]
Hey @ErikSteiner , thanks for reporting this. With v6, if no OTG world directory existed for the specified world, it creates a new world directory and fills it with a worldconfig and biomeconfigs for a default world, right? 

You can currently do that in Forge SP via the world creation menu (create a new preset via the presets menu. I suppose this would be nice for MP, although I don't recommend designing configs on a Forge server (SP is much easier). For Spigot I suppose this does have to work, or users won't have a way of creating a new default world (they can ofc also use Forge SP and copy the world to Spigot).

**Comment by ErikSteiner** [comment]
With v6, if no OTG world directory existed for the specified world, it creates a new world directory and fills it with a worldconfig and biomeconfigs for a default world, right?
Yes, in my opinion this is the best to handle the case where the user forgot to add a world directory or if he used the wrong level-name (if on MP).

**Comment by PG85** [comment]
Should be fixed for v8_r6, to be released on the otg-dev channel on the Discord at #openterraingen. v8 official release should be within a week or two. Actually, this should be one of the last issues :). Thanks for reporting!
