### ISSUE TITLE
Biomes from other mods being spawned in overworld.

### ISSUE THREAD

**Issue by MechanosG** [PG85/OpenTerrainGenerator#307]
I already mentioned this in another [issue](https://github.com/PG85/OpenTerrainGenerator/issues/275) that reported other problems too, but the issue was closed without mention of whether this biome problem was addressed/known.

Simply put, using OTG:Biome Bundle with Advent of Ascension will cause the Mysterium biome to be used in the overworld sometimes, which is a biome that's only supposed to spawn in the Mysterium dimension.  I haven't personally noticed any other biomes doing this, but I really have no idea if only the Mysterium biome is affected or not, or if other mods share this problem.  It's not a huge huge deal, but the mobs that spawn in the Mysterium biome are quite deadly to a new player.  And the starting area in our test server just happened to be a Mysterium biome.

There were many deaths lol.

**Comment by BiomeBundle** [comment]
This is a biome ID conflict which is fixed by either configuring AoA or Biome Bundle to not have overlapping IDs.

**Comment by MechanosG** [comment]
Alright.  AoA does allow id changing in the configs.  Is there a way for me to see which ids are taken up by Biome Bundle?

Edit:  Or rather, since I'll probably be removing AoA in my modpack, is there a way for me to see which ids are taken up by Biome Bundle so I can avoid id conflicts in the future?

**Comment by MCPitman** [comment]
Yeah they are all listed in the worldconfig.ini in /mods/openterraingenerator/worlds/Biome Bundle

**Comment by MechanosG** [comment]
Hmm.  Well this is interesting.  There isn't actually any conflicts.

Here's the Biome Bundle IDs:
CustomBiomes: Frozen Forest:44, ForestSakura:45, ForestSakuraHills:46, Autumnal Woods Hills:47, Autumnal Woods M:48, Autumnal Woods:49, Tropical Savanna:50, ForestConifer:57, Uplands:58, ForestEnchanted:65, ForestEnder:66, TemperatePlainsAutumnal:67, Steppe:71, Webbed Forest:72, SavannaEdge:73, Tundra:110, SwamplandSpooky:111, Canyon:270, CanyonHigh:271, CanyonMid:272, HighCliffsEdge:273, DesertMountain:274, DesertSmall:275, Birch Meadow:276, Forest M:277, ForestBaldCypress:278, ForestPlateau:279, ForestMountainRange:280, ForestMountain:281, TemperatePlainsOakgroveBorder:282, ForestWoodland:284, PlainsCliffM:285, PlainsCliff:286, JungleLowlands:287, JunglePlateau:288, JunglePlateauLow:289, JungleCliffsCanyon:290, JungleCliffsEdge:291, JungleCliffsCanyonMid:292, JungleCliffsCanyonHigh:293, Highlands:294, SavannaHills:295, DrySavanna:296, Mesa Verde Edge:297, MesaVerdeCanyonHigh:298, MesaVerdeCanyonMid:299, MesaVerdeCanyon:300, TundraEdge:301, TundraForest:302, ForestGrandFir:303, TemperatePlainsMeadowM:304, ForestConiferMountain:305, ForestConiferSnow:306, ForestConiferEdge:307, BirchForestRocky:308, TemperatePlainsMeadowBorder:309, SwamplandBorder:310, AlpsEdge:311, AlpsForest:312, AlpsMountain1:313, AlpsMountain2:314, AlpsMountain3:315, AlpsMountainEdge:316, AlpsMountainEdge2:317, AlpsMountainHighlands:318, AlpsMountainPeak:319, AlpsMountainPeak2:320, OceanDesertIsland:323, OceanForestIsland:324, RiverEnchantedForest:325, RockyMountainPeak1:326, RockyMountainPeak2:327, RiverHaunted:328, ArchipelagoHigh:329, ArchipelagoMid:330, ArcticEdge:331, OceanRockyIslandPeak:332, TaigaHighlands:333, RockyPlainsM:334, Webbed Forest Grove:335, DesertFlats:336, SavannaSmall:337, ForestFirThicket:338, HighCliffsSummit:339, ForestFirThicketEdge:340, ColdForestFirThicket:341, ColdForestFirThicketEdge:342, RockyMountainsPeakEdge:346, SwamplandSmall:347, DesertLowlandsEdge:348, DesertLowlands:349, MountainSteps:350, MountainStepsEdge1:351, MountainStepsEdge2:352, DesertLowlandsOasis:353, DesertLowlandsOasisEdge:354, TemperateHillsBorder:355, AlpineM:356, AlpineForest:357, DryPlainsM:358, BirchForestHighlands:359, ForestWetlandM:360, ColdTaigaBorder:361, Tropical Savanna Canyon:362, Tropical Savanna Canyon High:363, Tropical Savanna Canyon Mid:364, Tropical Savanna Edge:365, Tropical Savanna Summit:366, JungleHighlands:367, Rainforest Plateau:368, Rainforest M:369, Rainforest Plateau M:370, Rainforest Plateau Low:371, OceanPlateauLow:373, RiverAutumnal:374, TemperatePlains:375, HighlandsPeaks:376, SwamplandLarge:377, Extreme Hills Jungle:378, Extreme Hills Jungle Edge:379, MountainStepsGlacier:380, MountainStepsGlacierEdge1:381, MountainStepsGlacierEdge2:382, BirchForestMountain:383, BirchForestMountainRange:384, Pumpkin Plains:385, Desert Cliffs Edge:386, DesertCanyon:387, DesertCanyonHigh:388, DesertCanyonMid:389, GlacierM:391, TemperatePlainsDarkMeadow:393, GiantMushroomIsland:394, RainforestTropical:395, Caverns Edge:396, Caverns M:397, Caverns+ M:398, Caverns+:399, Mesa Small:400, Mesa Small M:401, Mesa Small Edge:402, OceanRockyIsland:403, SteppeHill:404, IcyMountainPeak1:405, IcyMountainPeak2:406, DesertOasisBorder:407, JungleLonePeak:408, ForestEnchantedGrove:409, ForestEnchantedBorder:410, ForestEnderMountain:411, ForestEnderValley:412, FloatingEdge:413, FloatingHole:414, WoodlandBorder:415, Mesa (Bryce) Rocks:416, Mesa (Bryce) Forest:417, SteppeHeathland:418, SteppeRocks:419, Webbed Hills:420, Webbed Hills Edge:421, ForestPlateauRoofed:422, RedMountain:423, TemperateLonePeak:424, Mesa (Bryce) Edge:425, MesaPeak:426, MesaCanyon:427, Mesa Rock:428, Mesa Desert:429, OceanIslandDesert:430, Monument:431, MonumentM:432, TropicalPillarSmall:433, TropicalPillarLarge:434, MonumentSmall:435, MonumentValleyFir:436, TemperatePlainsM:437, TemperatePlainsCypresshill:438, TemperatePlainsMeadow:439, TemperatePlainsHeathland:440, TemperatePlainsOakgrove:441, OceanRocksM:442, OceanPlateauM:443, SnowyPlainsM:444, SwamplandRuins:446, TundraCliffs:447, TemperateLowlandsEdge:448, OceanIslandForest:449, OceanIslandRoofedForest:450, Mesa Verde Forest:451, Drylands:452, DrylandsEdge1:453, DrylandsEdge2:454, DrylandsIsle:455, Swampland Bushes:456, DesertCliffsOasis:457, DesertCliffsOasisEdge:458, TemperateHillsForest:460, Mesa Sandstone:462, Mesa Sandstone Edge:463, Mesa Sandstone M:464, ForestMountainRangeEdge:465, DesertSmallRed:466, DesertSmallRedEdge:467, Mesa Sandstone Peak:468, AlpineConiferSnow:469, AlpineConiferMountain:470, HighCliffsThicket:471, HighCliffsThicketMountain:472, ForestBaldCypressSmall:473, TaigaSmall:474, RedwoodSmall:475, ForestGrandFirSmall:476, ForestDry:477, ForestDryEdge:478, UplandsBlackSpruce:479, JungleAncient:480, MesaPaintedCanyon:482, JungleAncientMushrooms:483, JungleAncientMountain:484, MonumentValleyEdge:485, UplandsEdge:486, DesertTropicalPlateau:496, DesertTropicalM:497, JungleAncientMountainTall:498, JungleAncientRocks:499, ForestConiferSnow2:500, BirchGrove:503, BirchGroveBorder:504, ForestFir:505, ForestFirMountain:506, ForestFirMountainEdge1:507, ForestFirMountainEdge2:508, RockyHills:509, RockyHillsEdge:510, RockyHillsCliff:511, RainforestBog:513, JungleCliffsVolcano:514, JungleSwampy:515, BirchForestTropical:516, BirchForestTropicalIsle:517, BirchForestTropicalIsle2:518, BirchForestTropicalIsle3:519, ForestHighlands:520, ForestLarch:521, CliffsSmall:522, CliffsSmallEdge:523, CliffsSmallPlateau:524, CliffsSmallPlateau2:525, CliffsSmallPlateau3:526, CliffsSmallMountain:527, CliffsSmallMountainEdge:528, CliffsSmallForest:529, CliffsSmallForest2:530, TropicalPillars:531, Mountain Peak:532, Mountain Peak2:533, Mountain Peak3:534, ForestOakSmall:535, ForestPoplar:536, ForestPinyon:537, FloatingIslands:539, RockyPlainsSmall:540, ForestEnchantedCaves:541, DesertRedConifer:542, ForestCliffs:543, ForestCliffsMountain:544, ForestCliffsMountainEdge:545, ForestCliffsLowlands:546, RainforestTropicalMountain:547, RainforestTropicalEdge:548, RainforestTropicalMountainPeak:549, TaigaHighlandsPeak:550, Mega Taiga Mountains:551, Cold Plains:552, SnowyMesa:553, SnowyMesaRocks:554, SnowyMesaEdge:555, SnowyMesaForest:556, IcyMountains:559, Alps:560, Mesa Verde Mountain:561, RiverTundra:562, DesertTropical:563, RiverEnder:564, Arctic:565, Caverns:566, High Cliffs:567, Desert Cliffs:568, Glacier:569, JungleMountainPeak:570, Roofed Fungi Forest:571, Rainforest:572, FlyingForest:573, FloatingPlains:574, RiverRoofedForest:575, JungleMountainRange:576, Mesa River:577, Archipelago:578, Dry Plains:579, TemperateHills:580, TropicalMountain:581, SnowyLonePeak:582, ForestPeak:583, RiverSavanna:584, RiverDesert:585, Mesa Verde:586, RiverSandy:587, RiverForest:588, RiverRocky:589, RiverBirchForest:590, RiverSwampland:591, IceWall:592, MonumentValley:593, Redwood Forest:594, JungleCliffs:595, Forest Wetland:596, RiverWetland:597, RiverTaiga:598, RiverForestConifer:599, RockyMountains:600, Mountain Range:601, RockyPlains:602, DesertRed:603, IsleRiver:604, RiverClay:605, RiverTropical:606, Rocks:607, OceanRocks:608, OceanPlateau:609, SnowyPlains:610, Marsh:611, TemperateLowlands:612, SnowyMountains:613, Ocean Island:614, Alpine:615, RiverAlpine:616, DesertOasis:617, Mangrove Forest:618, DesertBaobabs:619, TaigaPlateau:620, MarshBorder:621, OceanRocksDiorite:622, OceanForestHighlands:623, TaigaPlateauEdge:624, OceanForestHighlandsBorder:625, ForestCliffsBorder:626, DioriteCliffs:627, DioriteCliffsM:628, RiverDiorite:629, DioriteCliffsPeak:630, RiverVerde:631, ForestLarchPeak:632, DesertTropicalEdge:633, RiverSteppe:634, Beach Desert:635, SnowyPlainsEdge:636, OceanCoral:637, DrySavannaBorder:638, MonumentMountains:639, MonumentMountainsPeak1:640, MonumentMountainsPeak2:641, MesaWhite:642, MesaWhitePeak:643, MesaWhiteEdge1:644, MesaWhiteEdge2:645, MesaWhiteLow:646, SpookyGrove:647, SpookyGroveEdge:648, ForestPlateauThicket:649, FloatingJungleEdge:650, FloatingJungleHole:651, FloatingJungle:652, Frozen Forest Edge:653, RiverUplands:654, RiverSpooky:655, Birch Forest Peak:656, RoofedForestEnchanted:657, ForestPlateauEdge:658, ForestGiantSpruceSmall:659, RoofedForestFlat:660, JungleFlat:661, JungleMonument:662

And here's the AoA IDs:
dimensionids {
        I:abyss=800
        I:ancientCavern=801
        I:barathos=802
        I:candyland=803
        I:celeve=804
        I:creeponia=805
        I:crystevia=806
        I:deeplands=807
        I:dustopia=808
        I:gardencia=809
        I:greckon=810
        I:haven=811
        I:immortallis=812
        I:iromine=813
        I:lborean=814
        I:lelyetia=815
        I:lunalus=816
        I:mysterium=817
        I:precasia=818
        I:runandor=819
        I:shyrelands=820
        I:voxPonds=821
}

Being Mysterium is the one that showed up, I would assume ID 817 should be showing up in the Biome Bundle IDs, but they stop at 662?

**Comment by PG85** [comment]
Hey @MechanosG, which version of OTG are you using? If it's v6 or an existing world ported from v6 to v7/v8, then yes the custombiome id's from the worldconfig are used. If it's a new world created with v7 or v8, then it should have its biome id's generated dynamically on world creation, based on which id's are free (not taken by other mods). So if AoA registers its biomes at app start (as pretty much every mod except OTG does) and you're using v7/v8, OTG should not be using the same id's and you shouldn't be getting a conflict.

**Comment by MechanosG** [comment]
Ahh ok.  Yeah this config was made with v6.  Do I need to delete the WorldConfig.ini in order for it to dynamically create the new ID's with v7/v8?  Or will it change automatically the next time I create a world?

**Comment by PG85** [comment]
It will change when you create a world with v7/v8, I recommend using v8_r4 from the OTG discord's dev channel at #openterraingen. This is a dev version so I can't guarantee that it won't have any bugs, but it is very close to a release and testing looks good so far. Alternatively, you could keep using v6, which at least has been proven to be stable. Would have to figure out which id is conflicting though. Could you generate a world with the AoA biome, then stand in it and do /otg biome -s? That'll tell you the actual saved id it's using.

**Comment by BiomeBundle** [comment]
Those AoA IDs are dimension IDs not Biome IDs

**Comment by MechanosG** [comment]
@BiomeBundle - Errr...  yeah, you're right.  Sorry I must be tired.  I guess AoA ID's don't have a config option from what I can see.

@PG85 - Alright cool, I'll check that out.  As far as doing "/otg biome -s", yeah I should be able to manage that.  I'll see what it says next time I have a bit of time.

Thanks both of you for your help.

**Comment by PG85** [comment]
Hope it works out, join us on the OTG Discord at #openterraingen if you have any more questions. Cheers :)
