### ISSUE TITLE
Apparently random occasional crashes while flying around in creative

### ISSUE THREAD

**Issue by inkdear** [PG85/OpenTerrainGenerator#310]
#### OTG Plugin or Mod
OTG Mod for Forge

#### OTG Version
 1.12.2_v8_r4

#### Forge or Spigot Versions
forge 1.12.2-14.23.5.2838

#### Server/Client Log
i hope this is the right file, it's the most recent date/time 
 from my logs folder. i included the crash report too
[2019-08-31-7.log.gz](https://github.com/PG85/OpenTerrainGenerator/files/3562333/2019-08-31-7.log.gz)
[crash-2019-08-31_22.20.09-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3562335/crash-2019-08-31_22.20.09-server.txt)
edit: finally spotted the actual 'latest', my bad
[latest.log](https://github.com/PG85/OpenTerrainGenerator/files/3562340/latest.log)

#### What other plugins are you running?
walljump-1.12.2-1.2.3
VerticalDimensionStack-1.12.2-0.1.5
superflatcaves-1.3.1
justenoughdimensions-1.12.2-1.6.0-dev.20190711.220109
CD4017BE_lib-1.12.2-6.4.8
BiomesOPlenty-1.12.2-7.0.1.2441-universal
AppleCore-mc1.12.2-3.2.0

#### Description
Random crashes when flying through a default OTG world in creative. Game freezes and I have to close it, then Minecraft gives a crash message afterwards. Both times happened while flying towards deserts. I believe I had the same mod combination both times, but only included the most recent crash, as the actual crash reports were identical.

**Comment by PG85** [comment]
Hey @inkdear, thanks for reporting this. Should be fixed for v8_r6, to be released on the dev channel of the OTG Discord at #openterraingen asap. V8 official release is expected within a week or two.
