### ISSUE TITLE
Crash: Crash with Superflat Caves World Provider Override

### ISSUE THREAD

**Issue by inkdear** [PG85/OpenTerrainGenerator#311]
#### OTG Plugin or Mod
OTG Mod for Forge

#### OTG Version
 1.12.2_v8_r4

#### Forge or Spigot Versions
forge 1.12.2-14.23.5.2838

#### Server/Client Log
[latest.log](https://github.com/PG85/OpenTerrainGenerator/files/3563008/latest.log)
[crash-2019-09-01_13.49.31-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3563009/crash-2019-09-01_13.49.31-server.txt)

#### What other plugins are you running?
superflatcaves-1.3.1

#### Description
OTG crashes when creating or loading a world with the "disable world provider override" option set to false in Superflat Caves. Whilst this isn't that big of a deal since it works with it turned on, I spoke to the creator of Superflat Caves before he re-added the ability to disable the world provider override (ie, it crashed every time, but we knew why) and he said you'd probably want to know about this.

**Comment by PG85** [comment]
Hey @inkdear, thanks for reporting this. I'm not entirely sure what Superflat Caves does and how it works, there's not much I can see in this crash log except that it appears to fail very early on. Will have to check out Superflat Caves and do some testing with it. Don't think it'll have prio any time soon, but good to have in the backlog to pad an upcoming release.

**Comment by inkdear** [comment]
This is what the developer of Superflat Caves said when I talked to him about it (a while ago, I forgot to report it here after he suggested it.) 

"Hm
No, I understand, they're trying to fetch a specific world provider even though I'm overriding it
I am curious as to why this would be the case though
That they would look for the specific name rather than the world itself
I'll try to do an update shortly"

Superflat Caves lets you generate caves in superflat worlds (with specific compatibility for a couple of cave-generating mods), in particular I was using it with Just Enough Dimensions to create a mining dimension that would be compatible with Cave Generator caves (since OTG isn't, although its dev said he intended for it to be compatible eventually - I have no idea if that's just something he's doing on his own or what.) It's very unlikely anyone would install Superflat Caves and OTG concurrently unless they were trying to do the same trick I did.

**Comment by PG85** [comment]
Won't look at this anymore for 1.12.2 as we're focusing on 1.16. Thanks for reporting
