### ISSUE TITLE
Client crash on bonemeal OTG/NetherEx

### ISSUE THREAD

**Issue by KingRizla** [PG85/OpenTerrainGenerator#313]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [ x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [x ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
forge-1.12.2-14.23.5.2831-universal

#### What other plugins are you running?
modlist:
AppleCore (by squeek502)
Just Enough Resources (JER) (by way2muchnoise)
Better Builder's Wands (by Portablejim)
Better With Mods (by primetoxinz)
Hwyla (by TehNut)
InGame Info XML (by Lunatrius)
Potion Core (by Tmtravlr)
LunatriusCore (by Lunatrius)
Living Enchantment (by Clownvin)
Cosmetic Armor Reworked (by ZLainSama)
Super Factory Manager ( SFM ) (by TeamDman)
Shadowfacts' Forgelin (by shadowfactsmc)
Missing Pieces (by sboy205)
Open Glider (by gr8pefish)
Repurpose (by WuestMan)
Colossal Chests (by kroeser)
Magic Bees (by MysteriousAges)
ViesCraft - Airships! (by Viesis_Gaming)
Signpost (by Gollorum)
Extra Alchemy (by zabi94)
CplPibald's Tweaks (by CplPibald)
Project: Vibrant Journeys (by solis_nova123)
No Mob Spawning on Trees (by oldjunyi)
Ender Storage 1.8.+ (by covers1624)
TombManyGraves 2 API (by M4thG33k)
Waystones (by BlayTheNinth)
TombManyPlugins - Cosmetic Armor Reworked (by M4thG33k)
Terracart Reloaded (by Kreezxil)
Comforts (by TheIllusiveC4)
Super Sound Muffler (by EdgarAllen)
Moar Boats (by jglrxavpok)
Placebo (by Shadows_of_Fire)
RealBench (by Prototik)
Better Advancements (by way2muchnoise)
Forestry (by SirSengir)
Ping (by Girafi)
Pam's HarvestCraft (by MatrexsVigil)
NetherEx (by LogicTechCorp)
Quality Tools (by Tmtravlr)
MegaLoot (by Winter_Grave)
Building Gadgets (by direwolf20)
Waila Harvestability (by squeek502)
AI Improvements (by DarkGuardsman)
Spartan Weaponry (by ObliviousSpartan)
FTB Utilities: Backups (by LatvianModder)
Open Terrain Generator (OTG) (by team_otg)
Dungeon Tactics (by PegBeard)
V-Tweaks (by oitsjustjose)
BiblioCraft (by JDSinclair)
Carry On (by Tschipp)
Chisel (by tterrag1098)
Spice of Life: Carrot Edition (by LordCazsius)
Better With Lib (BWM - Core) (by primetoxinz)
Immersive Engineering (by BluSunrize)
Chest Transporter (by CubeX2)
Wawla - What Are We Looking At (by DarkhaxDev)
ConnectedTexturesMod (by tterrag1098)
CraftTweaker (by Jaredlll08)
Ore Excavation (by Funwayguy)
Mob Grinding Utils (by vadis365)
Totemic (by ljfa)
Familiar Fauna (by Forstride)
Custom Main Menu (by lumien231)
VanillaTweaks (by StrikerRocker)
Charm (by svenhjol)
Quark (by Vazkii_)
AutoRegLib (by Vazkii_)
Thaumcraft (by Azanor13)
No Recipe Book (by Seneschal_Luwin)
Paintings ++ (by senpaisubaraki)
StepUp (by NotTooManyItems)
stimmedcow : NoMoreRecipeConflict (by Oliv1er)
Mantle (by mDiyo)
Chance Cubes (by turkey2349)
Inventory Tweaks (by Kobata)
MrCrayfish's Furniture Mod (by Mr_Crayfish)
ItemPhysic Lite (by CreativeMD)
Obfuscate (by Mr_Crayfish)
Controlling (by Jaredlll08)
Resource Loader (by lumien231)
Garden Stuff (by jaquadro)
FTB Quests (by LatvianModder)
Cooking for Blockheads (by BlayTheNinth)
VanillaFoodPantry Mod [FORGE] (by The_Wabbit0101)
MTLib (by Jaredlll08)
OreLib (by OreCruncher)
Doggy Talents (by percivalalb)
Iron Backpacks (by gr8pefish)
Prefab (by WuestMan)
FastWorkbench (by Shadows_of_Fire)
VanillaFix (by Runemoro)
Biome Bundle (by mc_pitman)
Pickle Tweaks (by BlakeBr0)
AppleSkin (by squeek502)
Future MC (by thedarkcolour)
OpenCubicChunks (by barteks2x)
FTB Utilities (by FTB)
Fast Leaf Decay (by olafskiii)
Bountiful (by ejektaflex)
ModTweaker (by Jaredlll08)
Just Enough Items (JEI) (by mezz)
Baubles (by Azanor13)
Iron Chests (by progwml6)
BetterFps (by Guichaguri)
MrCrayfish's Gun Mod (by Mr_Crayfish)
Landlust - Furniture (by streifentier)
LibraryEx (by LogicTechCorp)
PinklySheep Mod (by The_Wabbit0101)
ReAuth (by TechnicianLP)
Minecolonies (by H3lay)
RandomPatches (by TheRandomLabs)
Aquaculture (by Shadowclaimer)
Login Shield (by Glasspelican)
FastFurnace (by Shadows_of_Fire)
Bailey's Dailies (by ToroCraft)
FTB Library (by FTB)
OpenModsLib (by OpenMods)
LLibrary (by iLexiconn)
OpenBlocks (by OpenMods)
Unique Crops (by bafomdad)
Plants (by Shadows_of_Fire)
Roguelike Dungeons (by Greymerk)
Chameleon (by jaquadro)
Better Questing (by Funwayguy)
Better Questing - Standard Expansion (by Funwayguy)
World Primer (by masa_)
Tomb Many Graves 2 (by M4thG33k)
Rustic (by mangoose3039)
Compressed Items (by cesar_zorak)
Akashic Tome (by Vazkii_)
Level Up! Reloaded (by BeetoGuy)
Cyclops Core (by kroeser)
Mo' Money (by Kwebber321)
Mouse Tweaks (by YaLTeR97)
FTB Money (by LatvianModder)
Inspirations (by KnightMiner)
Improved Hoes (by Furgl)
Storage Drawers (by jaquadro)
JEI Bees (by bdew)
Heroic Armory (by skeddles)
Soartex Fanver - Modded (by Soartex)
Fairy Lights (by pau101)
Cucumber Library (by BlakeBr0)
CodeChicken Lib 1.8.+ (by covers1624)
JourneyMap (by techbrew)
Bigger Packets Please (by ElNounch)
MalisisDoors (by Ordinastie)
MalisisCore (by Ordinastie)
Item Filters (by LatvianModder)
Buildcraft (by CovertJaguar)
Sound Filters (by Tmtravlr)
Tinkers Construct (by mDiyo)
FoamFix for Minecraft (by asiekierka)

#### Description
when a player bonemeals a tree their client will crash, server is unaffected, we can bonemeal fruits on tree's & crops, even grass without issues. nut as soon as we bonemeal a tree the client crashes,   here is the log it give on a normal tree, and the second link is for a pams harvestcraft tree

https://paste.dimdev.org/ujometawov.mccrash   ---  normal tree

https://paste.dimdev.org/evikajacor.mccrash   --- pam's tree

is this because of user error or is this an actual bug? incase its a user error, would you be so kind to maybe guide me in the right direction to how to fix it :)

**Comment by PG85** [comment]
Hey @KingRizla , thanks for reporting this. This should be fixed with v8, which should be released in the next week or two. A dev is also build is available on the OTG Discord at #openterraingen. Always backup your files before updating. Please try the new build and let me know if the issue persists, thanks!
