### ISSUE TITLE
Crash while "sapling growing" (???)

### ISSUE THREAD

**Issue by inkdear** [PG85/OpenTerrainGenerator#314]
#### OTG Plugin or Mod
OTG Mod for Forge

#### OTG Version
1.12.2_v8_r6

#### Forge or Spigot Versions
14.23.5.2838

#### Server/Client Log
[latest.log](https://github.com/PG85/OpenTerrainGenerator/files/3572760/latest.log)
[crash-2019-09-04_16.42.29-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3572761/crash-2019-09-04_16.42.29-server.txt)

#### What other plugins are you running?
Welcome+To+The+Jungle-1.2005.1222
walljump-1.12.2-1.2.3
VerticalDimensionStack-1.12.2-0.1.5
The+Backrooms+1.2.0
Tabula-1.12.2-7.0.1
superflatcaves-1.3.1
PrimalCore-1.12.2-0.6.105
OptiFine_1.12.2_HD_U_E3
llibrary-1.7.19-1.12.2
justenoughdimensions-1.12.2-1.6.0-dev.20190711.220109
jei_1.12.2-4.15.0.268
iChunUtil-1.12.2-7.2.1
iceandfire-1.8.1
HorseTweaks_1.12.2-1.0.5
dwmh-1.12.2-3.1.2 (Dude Where's My Horse)
CD4017BE_lib-1.12.2-6.4.8
BiomesOPlenty-1.12.2-7.0.1.2441-universal
betternether-0.1.8.3
astikorcarts-1.12.2-0.1.2.7
AppleCore-mc1.12.2-3.2.0
a_fistful_of_hay-1.0.1

#### Description
I was alt-tabbed and went back to the game to find it had crashed. Was just standing still in a jungle in creative. I got the "sapling" thing from the crash report.

**Comment by PG85** [comment]
Hey @inkdear, thanks for reporting this. This should be fixed with v8, you can grab the newest dev version on the OTG Discord at #openterraingen or wait for the official release which should be within a week or two. If the problem persists, feel free to reopen this issue or create a new one, thanks!
