### ISSUE TITLE
Should rivers be spawning on the boundary between land biomes and ocean?

### ISSUE THREAD

**Issue by inkdear** [PG85/OpenTerrainGenerator#315]
#### Is your feature request related to a problem? Please describe.
It feels like rivers generate between normal biomes and oceans much more frequently on this version (all the v8 dev versions I've tried) of OTG than the current release (effectively eliminating the sandy part of the beach biome when it happens.) I'm using a default preset with nothing changed except some block replacements in beach biomes (just to get rid of high elevation sand.)

#### Describe the solution you'd like
I'm not sure if the bevaviour is actually different from previous versions or not, I may have just not noticed it before - but the ability to prevent rivers from generating on the border between ocean and land would be great - would give much more reliable generation of beach type biomes, less messy-feeling.

#### Describe alternatives you've considered
Shrug.

#### Description aka Additional context
Here's a screenshot of what I mean. The beachless coast is all river, or a strange combination of river-beach-plains (with the 'beach'
 being between the river and the ocean.) The little sandless inlet on the right is a river biome, seems to be the start of a river.
![2019-09-04_17 01 57](https://user-images.githubusercontent.com/41709276/64227073-235d2000-cf36-11e9-9ad5-dc2c507925c6.png)

**Comment by BiomeBundle** [comment]
Are rivers disabled in beaches and oceans?

**Comment by PG85** [comment]
Hey @inkdear, I don't think anything significant should have changed for rivers. Please confirm whether this really is different between v6 and v8, if it is, I can take a look.

**Comment by inkdear** [comment]
I had the default preset settings that OTG generates, which turned out to be rivers in beaches and not in oceans. I set beaches the same as oceans, ie no river biome specified (unless that's not the right way to do it?) and am still getting weird river-beach-ocean mess on coastlines.

I'll get v6 to check tomorrow morning, for now here's some better screenshots of what I mean (found while I was checking if the problem could be solved by disabling rivers in beach biomes.) Apologies if I've just disabled beach rivers wrong/nothing's actually different/I screwed up in some other way, etc.

![2019-09-04_23 05 57](https://user-images.githubusercontent.com/41709276/64250215-aa77bb80-cf69-11e9-836f-071cac5eaea0.png)
![2019-09-04_23 04 36](https://user-images.githubusercontent.com/41709276/64250225-b2376000-cf69-11e9-8c0f-1950561b4eee.png)
![2019-09-04_22 39 28](https://user-images.githubusercontent.com/41709276/64250243-bd8a8b80-cf69-11e9-9576-d85a02f6e882.png)

**Comment by inkdear** [comment]
Ok, I checked the current release, and it does have rivers between beach and land. I also found an Extreme Hills Edge -> River -> Ocean sequence. (Default-generated preset.) Is there currently a way to prevent rivers from spawning adjacent to oceans/beaches like this? (other than changing the river mode. like what's the correct way to disable them?)

**Comment by MCPitman** [comment]
This is intended behaviour if `RandomRivers: false`, as with this option disabled rivers will generate at the borders of biomes (which includes when biomes meet the ocean).

To randomise river placement set `RandomRivers: true`.
