### ISSUE TITLE
crash with AppliedEnergistics2-rv6-stable-1

### ISSUE THREAD

**Issue by zhourui123** [PG85/OpenTerrainGenerator#317]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [x] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
[The full Spigot Server or Forge versions that you are running]
forge-1.12.2-14.23.5.2838-universal.jar
#### Server/Client Log
[The full latest.log file from your server or game client, especially important if you have a stack trace]
https://gist.github.com/zhourui123/9879a83c5f36c42bf07157261ed579fa

#### What other plugins are you running?
[List of your Mods or Plugins installed, ideally with versions]
spongeforge-1.12.2-2838-7.1.7-RC3843.jar
appliedenergistics2-rv6-stable-1.jar

#### Description
[What is happening? - Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures;)]
When going into the `storage cell` dimension of the AppliedEnergistics2.
![image](https://user-images.githubusercontent.com/17756918/64402602-211ad300-d0a8-11e9-9ced-674a433edf57.png)

[What did you expect to happen? - Explain what you expected to happen after performing the previously described steps]
no crash when going into the dimension.
[And Delete the lines in square brackets!]

**Comment by SXRWahrheit** [comment]
Please test this with v8, available on the OTG Discord as a pinned message in the `#otg-dev` channel.

**Comment by PG85** [comment]
Thanks for reporting @zhourui123 this and thanks for responding @SXRWahrheit . Please try testing this with a newer version of OTG. Development version v8_r7 will be available soon and should hopefully fix the last problems for v8. You can try either 1.12.2-v6, a dev release from the OTG discord's dev channel or wait for a stable v8 release. If the problem persists, feel free to reopen this issue.

**Comment by zhourui123** [comment]
I solve the problem by cancelling the Teleport Dimension event. Later, I will update to v8_r7 to test the problem. If the problem reappears, I will reopen the thread, thank you for your help.
