### ISSUE TITLE
Bug: Water sources don't automatically flow when world is generated

### ISSUE THREAD

**Issue by inkdear** [PG85/OpenTerrainGenerator#318]
#### OTG Plugin or Mod
Forge mod

#### OTG Version
v8_r6

#### Forge or Spigot Versions
14.23.5.2838

#### What other plugins are you running?
![modlist](https://user-images.githubusercontent.com/41709276/64499221-47d94380-d30c-11e9-862f-25d88ae71b1b.png)

#### Description
IIRC, this happens in the released version as well, especially in places where the edge of a body of water is interrupted by a ravine, cave, etc.

Here's an example:
![2019-09-09_13 57 42](https://user-images.githubusercontent.com/41709276/64499191-1fe9e000-d30c-11e9-973d-cd9d82a49e6b.png)

EDIT: I found some that flow on their own, and some that eventually flow after an abnormally long delay. It seems inconsistent?

**Comment by inkdear** [comment]
I found some better examples (caves generated in a swamp biome) and was able to look at it in more detail.
- Loading the game in and out or leaving and coming back to the area doesn't cause the source blocks to flow.
- I made sure the game had 110% fully loaded the surrounding chunks and wasn't 'caught on' anything (mobs all moving around fine, I take damage without weird delays, etc)
- Breaking a block near to a source, obviously, causes it to flow
- If it's just a delay, it's SUPER delayed - I messed around in this swamp for ~10 minutes and it still didn't update on its own.
- I installed Better Foliage, Dynamic Surroundings and Quark in between the original issue submission and this, but there's no apparent change in behaviour.

![2019-09-11_15 03 38](https://user-images.githubusercontent.com/41709276/64668732-d25ba780-d4b2-11e9-8327-04b35c97c25f.png)

**Comment by PG85** [comment]
Hey @inkdear , we've had this behaviour for a while. There are a number of different mechanics at work related to placing and updating the water blocks and their neighbours, so unfortunately I can't easily point to a culprit. If this behaviour doesn't happen for vanilla, then OTG is doing something wrong when placing / updating (or neglecting to update) blocks. This may also explain some of the lighting bugs we're seeing. Will need to look at this for a future release.

**Comment by PG85** [comment]
*if localworld.setblock is used to place these blocks, that explains the missing block updates. Could make all resources except bo4's do setblock with updates. For BO4's this shouldn't be a problem, since all their blocks should be spawned in their proper updated state and shouldn't care about neighbouring blocks (or lack thereof).

*this shouldn't happen when placing water blocks in the base terrain though, need to confirm.

**Comment by jaskarth** [comment]
Fixed with 1.16.5 0.0.8!
