### ISSUE TITLE
Modded cave gen still doesn't seem to work

### ISSUE THREAD

**Issue by yungnickyoung** [PG85/OpenTerrainGenerator#319]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - specify here: 1.12.2_v8_r6

#### Forge or Spigot Versions
1.12.2 - 14.23.5.2838

#### What other plugins are you running?
YUNG's Better Caves or Worley's Caves (only one at a time)

#### Description
Modded cave gen is supposed to work with this version, but does not. I put the v8_r6 jar and the modded cave gen jar in the mods directory and make sure OTG Core and whatever else generated from previous use is deleted. Create a world using Create OTG World. The resulting caves are regular caves, not modded.

**Comment by PG85** [comment]
Hey @yungnickyoung, thanks for reporting this. I tested this with Worleys earlier and saw different caves with and without the mod. Will have to check again. Are you using any other mods at all? Are you testing with a default world or using a preset?

**Comment by yungnickyoung** [comment]
No, no other mods. I tried on both a default world and with the Biome Bundle preset. I don't believe either were working for me. I'll double check in a bit.

EDIT: Yeah, in either case the caves that generate aren't Worley's. I cross-referenced with a vanilla world (+ Worley's only) just to be sure.

EDIT 2: I've had people tell me that they've tried it with Worley's and the caves do appear to be different, however they don't look like typical Worley's? I'll investigate a little more later today.

EDIT 3: Using default configs for OTG + Worley's and OTG + Better Caves, I am unable to find any difference in cave structures for both OTG default worlds and Biome Bundle worlds. 
For default OTG worlds, the caves looked quite similar to vanilla caves, consisting of what appears to be solely Perlin worms, perhaps occasionally with small cavern-esqe rooms placed at the intersection of worms.
For Biome Bundle worlds, the caves also appear to use Perlin worms, but with more variation in tunnel width, as well as with more frequent placement of larger cavernous rooms. (These cavernous rooms have notably more steepness/verticality than any such default OTG world counterparts).

In either case, default or Biome Bundle, the cave structures and frequency appear to be fundamentally the same.

**Comment by MCPitman** [comment]
Can confirm Worley's does not appear to be working properly. I tested comparing to a vanilla world and it seems that the cave noise pattern remains OTG's default, the only difference is with Worleys installed the caves close to bedrock are flooded with lava (which is one of its other features).

**Comment by superfluke** [comment]
I think you're missing an else statment here: https://github.com/PG85/OpenTerrainGenerator/blob/7f91dfa77d152730f02d623cb4eb9c0b236df3c5/platforms/forge/src/main/java/com/pg85/otg/forge/world/ForgeWorld.java#L160

`else {
this.cavesGen = moddedCaveGen;
}`

Since currently you check for modded caves but you never set cavesGen equal to them. So when you get down to generateModdedCaveGen, the caveGen is still equal to the vanilla caves

**Comment by PG85** [comment]
Hey @yungnickyoung  , @MCPitman and @superfluke . Thanks for reporting this and looking into this. I tested by disabling OTG cavegen and adding worley's, which spawned caves, so I thought things were working. Hadn't realised that the caves were vanilla and not worley's tho XD. Will be fixed for v8_r7.
