### ISSUE TITLE
Ravines generation doesn't turn off

### ISSUE THREAD

**Issue by Darsenia** [PG85/OpenTerrainGenerator#320]
#### OTG Plugin or Mod

- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version

- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [x] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
Forge 14.23.5.2814

#### What other plugins are you running?
Only decorative/technical mods:Optifine,BetterFoliage,JourneyMap,TellMe,TreeCapitator,NEI+JEI

#### Description
There were a lot of ravines everywhere, so I started changing values in WorldConfig.ini,however,it doesn't help.I had to set option RavineRarity: 0.0 in WorldConfig.ini, but it also doesn't work,ravines are still found in every biome,even very small,like beach,sometimes up to 3 in the same place,crossshaped.I want ravines to happen in the world,but not so often,and not in every biome.I didn't change cave settings,they are still default.
Is there any way to change ravines frequency?
If you need to look at WorldConfig.ini,I attached it(in txt format),but it is still work-in-progress and a big mess:)

[WorldConfig.txt](https://github.com/PG85/OpenTerrainGenerator/files/3601177/WorldConfig.txt)

**Comment by Jishuna** [comment]
Ravine rarity shouldn't have a decimal in it, try setting it to 0 instead.

**Comment by Darsenia** [comment]
Thank you very much! It helped ^_^ It was really stupid mistake,I hadn't even thought about decimal!
