### ISSUE TITLE
Crash during World Generation

### ISSUE THREAD

**Issue by PiordaNautor** [PG85/OpenTerrainGenerator#326]
- [X] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

- [ ] 1.12.2_v8_r1
- [x] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

Forge Versions
forge-14.23.5.2847

Server/Client Log/Other Mods
https://paste.dimdev.org/qobenilumi.mccrash (I assume the link explains both)

Description
When attempting to use a Far From Home world generation, the game was unable to begin the world/complete generation for more than 10 minutes. The only way to close Minecraft at that point was using Task Manager or wait for the following message.
"The following mods have been identified as potential causes: Open Terrain Generator, Wesley's RogueLike Dungeons"

Expected Result
The world fully loading, before being put into said world.

Edit:
It appears to be a problem with either this mod, or Far From Home, or both since I have crashed and received a similar crash message attempting to use Far From Home. Biome Bundle seems to have no or little issue, however, Far From Home causes every crash when attempting to generate.
https://paste.dimdev.org/gariqahete.mccrash

**Comment by MCPitman** [comment]
You should take this up with the preset author as it doesn't appear to be an OTG issue.
