### ISSUE TITLE
OTG crash and bugs teleporting to a swamp biome

### ISSUE THREAD

**Issue by mensreaMC** [PG85/OpenTerrainGenerator#328]
- [x] OTG Mod for Forge
- [X] 1.12.2_v8_r6
- Forge: 14.23.5.2846

Here is a full crash log with the same error from a different occasion that also features my full mod list.
https://pastebin.com/JZAcDthq

What happens: I teleport to a Swamp biome, get a error in the server log, and no resources generate from there on out.

What I expected: I expected resources to spawn.

Error log: https://pastebin.com/22jjMKcg

EDIT: Turning off vine generation completely fixes this issue. The code in question: Vines(10,10.0,63,256)

**Comment by PG85** [comment]
Hey @mensreaMC , thanks for reporting this and looking into it. Have you tested with any other Vines() syntax, does it only fail in certain cases with certain parameters?

**Comment by PG85** [comment]
This needs to be tested and confirmed for v8.3 or higher.

**Comment by Ezoteric** [comment]
Tped to a lot of swamps(spooky, large and swamp and swamp M) on 50+ worlds and havent happend for me once on 1.12.2_-_v8.3_r4

**Comment by PG85** [comment]
Thanks for testing @Ezoteric ! Closing this, feel free to reopen if the problem still occurs.
