### ISSUE TITLE
Feature: Custom Fog color and density for every biome

### ISSUE THREAD

**Issue by Darsenia** [PG85/OpenTerrainGenerator#330]
As for now, fog properties can be changed for the whole world only,and it limits possibilities(or makes this option sometimes useless).For example, we want to make atmospheric swampland etc,water/sky/foliage/grass colors can be changed to something swampy,but dense and murky fog will make everything much more realistic!The same with some other places,like desert "sand in the air" effect,like it was done in Biomes O'Plenty mod.
OTG is such a powerful nature simulator,and it really deserves this option)

**Comment by PG85** [comment]
We've got our wizard Josh working on this as we speak, moving this to his milestone.

**Comment by Darsenia** [comment]
Awesome!

**Comment by PG85** [comment]
Implemented for v9.0_r1
