### ISSUE TITLE
One chunk causes repeatable crashes during terrain generation

### ISSUE THREAD

**Issue by Flarkinater** [PG85/OpenTerrainGenerator#331]
#### OTG Plugin or Mod
- [X] OTG Mod for Forge

#### OTG Version
- [x] 1.12.2_v8_r6

#### Forge or Spigot Versions
forge-1.12.2-14.23.5.2838

#### Server/Client Log
[latest.log](https://pastebin.com/RkP4SvBK)
[Crash #1](https://pastebin.com/GyS7sCu6)
[Crash #2](https://pastebin.com/U61a3cv9)

#### What other plugins are you running?
badmobs 1.1.28
pixelmon 7.0.7
fastleafdecay v14
Dynmap-3.0-beta-4-forge-1.12.2

#### Description
**What is happening?**
The world crashes when I try to generate a specific chunk for the first time. When crashing, the server kicks any logged-in player and displays "server closed", but does not _actually_ close according to the console until about 60 seconds later, when it crashes again due to a tick taking too long. Both crash reports are above.

**What did you expect to happen?**
For me to go along on my merry way playing Minecraft with no issues.

**What have you already tried?**
I approached the "problem chunk" from multiple angles - it does in fact seem to be a specific chunk causing the problem. I can't figure out what biome the chunk is supposed to be, since I can't even get close enough to run /otg biome on a neighboring chunk before crashing.

I also tried changing the Resource Seed, but the server still crashed (so it's likely not a specific-bo3 issue?).

**Comment by BiomeBundle** [comment]
Can this be reproduced with normal forge (not spongeforge)? As spongeforge is not a supported platform.

**Comment by Flarkinater** [comment]
Unfortunately I can't tell. I transferred the world to a forge-only singleplayer world, but the terrain generates differently even with the same seed. I could try running a large pre-gen in forge, but if the error never appears it could just be that I got lucky with no errored chunks.

**Comment by Flarkinater** [comment]
Resolved: After narrowing the problem down using older backups, I found the issue - basically it was my fault. An NBT file used by one of the structures was causing an error, probably because at some point I messed it up with Notepad++.
