### ISSUE TITLE
CustomStructure bo3s offset issue

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#332]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x] 1.12.2_v8_r6

Testing Biome Bundle with the latest dev release I see customstructure bo3s are commonly offset by one block or are missing branches:

https://cdn.discordapp.com/attachments/285816707040280586/620712300680052784/2019-09-09_21.08.37.png

https://cdn.discordapp.com/attachments/285816707040280586/620708452855185455/2019-09-09_20.53.03.png

https://cdn.discordapp.com/attachments/285816707040280586/620710317017661451/2019-09-09_21.00.58.png

Tested with the latest forge version for 1.12.2, have not yet tested if this occurs with Spigot.

**Comment by PG85** [comment]
Thanks for reporting, should be fixed with v8_r7.
