### ISSUE TITLE
Custom saplings overwrite any blocks in their path when grown

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#333]
#### OTG Version
- [x] 1.12.2_v8_r6

In vanilla, a sapling will not grow if there is not enough available space directly above it (i.e. if there is a block above the sapling). Also, if the tree grows and collides with other blocks it will not replace them.

Saplings grown with OTG's sapling queue do not obey either of these rules, the second is quite important as it prevents sapling growth from destroying player made structures.

**Comment by PG85** [comment]
I think Josh fixed this?

**Comment by PG85** [comment]
Fixed by Josh, saplings don't spawn unless all their blocks can spawn.
