### ISSUE TITLE
Unable to spawn entities at XYZ coord containing 0

### ISSUE THREAD

**Issue by Wh1t3W3nd1g0** [PG85/OpenTerrainGenerator#336]
#### OTG Plugin or Mod
- [X] OTG Mod for Forge
#### OTG Version
- [X] Other - OpenTerrainGenerator-1.12.2_-_v8_r6_Josh1
#### Forge or Spigot Versions
[Minecraft Version: 1.12.2
(modded) forge-14.23.5.2847]
#### Description
Unable to spawn entities at XYZ coordinates containing"0" using Spawners function of CustomObjects. Example attached.

[TreeDarkOakParrot0.zip](https://github.com/PG85/OpenTerrainGenerator/files/3654215/TreeDarkOakParrot0.zip)

Failing example(no block at location 1,7,0):
     Spawner(1,7,0,Parrot,1,30,100,1,30,0.0,0.0,0.0,0.0,0.0)

Working example(no block at location 1,7,0):
     Spawner(1,7,1,Parrot,1,30,100,1,30,0.0,0.0,0.0,0.0,0.0)

**Comment by PG85** [comment]
This may be due to the behaviour of Spawner(), need to be tested and confirmed.

**Comment by PG85** [comment]
Spawner(0,1,0,Blaze,1,30,100,1,30,0.0,0.0,0.0,0.0,0.0)

This works fine for me, please try OTG v8.3 or higher, thanks for reporting!
