### ISSUE TITLE
server-side crash when entering deep dark

### ISSUE THREAD

**Issue by bobodoustaud** [PG85/OpenTerrainGenerator#338]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ x] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
[forge-1.12.2-14.23.5.2838-universal.jar]

#### Server/Client Log
[https://pastebin.com/tsZ6kaZS]

#### What other plugins are you running?
[List of your Mods or Plugins installed, ideally with versions
![Capvture](https://user-images.githubusercontent.com/49878442/66230026-8384e480-e6e3-11e9-8178-ce92a2e43110.JPG)
![Caphreure](https://user-images.githubusercontent.com/49878442/66230027-8384e480-e6e3-11e9-9e9d-d0b99a333f7c.JPG)
![Capture](https://user-images.githubusercontent.com/49878442/66230028-8384e480-e6e3-11e9-8569-02e89f50af97.JPG)

]

#### Description
[when i travel to the deep dark, the server is closed and crash. ]

[i think that OTG tries to create a biome bundle biome in the deep dark but it can't and it crashes.]

**Comment by bobodoustaud** [comment]
crash report : https://pastebin.com/sSG7q5Qy

**Comment by PG85** [comment]
Hey @bobodoustaud , thanks for reporting this. This should be fixed with v8, to be released asap. You can grab a dev release from the OTG Discord's dev channel (OpenTerrainGenerator-1.12.2_-_v8_r6.jar), or wait for a stable release.

**Comment by bobodoustaud** [comment]
Thanks !

**Comment by bobodoustaud** [comment]
Thanks !
