### ISSUE TITLE
[1.11.2] Mod compat: Animania - Crash on world load

### ISSUE THREAD

**Issue by scaredtodeaf** [PG85/OpenTerrainGenerator#34]
[crash-2017-06-10_20.00.18-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/1065746/crash-2017-06-10_20.00.18-server.txt)

Not sure why this is occuring. Thought i might post here to see if i could get some help. And i can't downgrade either for forge version since i have other mods that requires the latest versions.

**Comment by PG85** [comment]
Hey thanks for reporting this, could you grab the latest dev version from the comment in this post and tell me if that fixes the problem? 

https://www.reddit.com/r/openterraingen/comments/6g6zvq/new_otg_releases_for_1102_and_1112/

**Comment by scaredtodeaf** [comment]
Testing now and will update.

**Comment by scaredtodeaf** [comment]
[crash-2017-06-10_21.08.03-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/1065795/crash-2017-06-10_21.08.03-server.txt)
It has crashed once again.

**Comment by PG85** [comment]
That's odd, looks like some problem with a mob spawning mod (mob registered to biome without a proper mob name). Did you create a new world or try to load an existing world? You may have to create a new world to make sure the biomes are spawned correctly. If that doesn't help, could you try to figure out if one of your mods add mobs and if removing it solves the problem.

**Comment by scaredtodeaf** [comment]
It doesn't seem to be compatible with Animania mod. (Which replaces most of the vanilla farm animals.)

**Comment by scaredtodeaf** [comment]
Disabling that made it work fine.

**Comment by scaredtodeaf** [comment]
I've also noticed that with the biome bundle the biomes aren't very accurate in their size. Like if im on an extreme hills area parts that seems to belong to it register as another biome. Might be just me. But will probably do more testing with this in single player to see how it goes. Thanks for the help.

**Comment by PG85** [comment]
Thanks for the report, I'll do some testing with Animania and custom mobs in general a.s.a.p.

As for the biome names, you can use /otg biome and /otg biome -s to see the internal names of biomes, in Biome Bundle there are a lot of different biomes that have the same name in F3 but are actually different biomes.

**Comment by scaredtodeaf** [comment]
Yeh, I have ActualMusic in my pack so having the biomes would be good. Will try that out.

**Comment by PG85** [comment]
This build should fix the problem: https://cdn.discordapp.com/attachments/307111022257373185/323263341709623326/OpenTerrainGenerator-1.11.2-v6-DEV2.jar

Please give it a try and tell me if it works for you, thanks!

**Comment by scaredtodeaf** [comment]
Works! Thanks.

**Comment by scaredtodeaf** [comment]
Hmm, Does this generate the biomes added from Abyssalcraft or not? Just wondering.

**Comment by PG85** [comment]
Great to hear, I'll close this issue. 

As for Abyssalcraft, I don't think it will generate the biomes but I'm not sure, you could ask on the reddit (https://www.reddit.com/r/openterraingen/) or the discord channel (/openterraingen). The discord channel would probably be the quickest.
