### ISSUE TITLE
Bug: Random "torn" out chunks appear while using Nature Compass with OTG

### ISSUE THREAD

**Issue by Darsenia** [PG85/OpenTerrainGenerator#341]
#### OTG Plugin or Mod

- [x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version

- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [x ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
Forge 14.23.5.2847 (I used different Forge versions,it doesn't matter)

#### What other plugins are you running?
(latest) Nature Compass 1.5.1

#### Description
Firstly I tried to get help in Nature Compass thread,but authors don't think this issue is related to them.However this bug happenes ONLY while using Nature Compass.I met this thing only 
while working with OTG and using Nature Compass to find needed biomes.It's very-very hard to search for random biomes without compass(/otg tp ... searches in a very small radius,I need sometimes more then 10000 of blocks,and I don't know is it even possible to change otg search radius).
I can't understand,how nature compass can ruin chunk generation,but it does.
Without using compass(for example using /otg tp) everything is fine.
Original issue:
https://github.com/MattCzyr/NaturesCompass/issues/32

So,I search for biomes with the compass(if the biome is far away,bug happens more often),or simply open Nature Compass gui(not so often ).
Screenshots:
![2019-06-06_22 16 12](https://user-images.githubusercontent.com/36276289/66578788-65583200-eb84-11e9-81b1-9e4bbb9b34aa.png)
![2019-07-03_22 17 54](https://user-images.githubusercontent.com/36276289/66578790-65583200-eb84-11e9-8f3b-3a758082bc54.png)
![2019-08-05_22 50 47](https://user-images.githubusercontent.com/36276289/66578791-65583200-eb84-11e9-8823-397cdeae7684.png)

I have no id conflicts in the OTG world biomes or something else(I doublechecked!;))

**Comment by Darsenia** [comment]
Today I get this,trying to find and take a photo of one dumb river:
![2019-10-12_17 18 42](https://user-images.githubusercontent.com/36276289/66702818-6a4beb80-ed14-11e9-8a11-35f29bac9911.png)
Chaotically amazing:-D

**Comment by PG85** [comment]
Hey @Darsenia , thanks for reporting this. Will have to look into this for a future release, but no prio atm unless more people start reporting it. Moving to backlog for now, to be put in a future release milestone.

**Comment by Darsenia** [comment]
PG85,
I've discovered why this issue started happening only when I was finishing my work! I had set render distance to 23-31 chunks to make cinematic screenshots...After the reset back to 9 chunks I'm experiencing this issues much less often, just sometimes.I always thought it is somehow connected to the world gen, render process and game ticks out of sync.Something like that :)
Anyway, Nature Compass is much more usable again)

**Comment by PG85** [comment]
Thanks for figuring this out! Will still need to take a look at this, looks like something pretty fundamental going wrong.

**Comment by PG85** [comment]
Will need logs for this, it may have logged some warnings/errors while generating the chunks. No prio for v9, so will move this into support.

**Comment by Darsenia** [comment]
Hello there,
I got a fresh log=)
It's very easy to reproduce, fortunately.
[latest.log](https://github.com/PG85/OpenTerrainGenerator/files/4116405/latest.log)

**Comment by Darsenia** [comment]
Just spawned in the world, set chunk radius to 35(extreme), used nature compass to find something, looked at chunky things appearing,tried to teleport, freezed and kill java process.I hope this can be helpful.

**Comment by PG85** [comment]
Please try this again with 1.12.2 v9 (available on curse asap, or grab a dev build from the disc), feel free to reopen this issue if the problem persists, thanks!
