### ISSUE TITLE
Crash when teleporting out of a dimension if no portal block set. 

### ISSUE THREAD

**Issue by Bahnschrift** [PG85/OpenTerrainGenerator#344]
OTG v8
Forge

When using a portal to leave a dimension, the game will crash if a portal block is not set for the dimension you are in. 
A solution could be to make it impossible to leave the dimensions menu if the portal block option is not set. 

Crash report:
[crash-2019-10-18_23.32.14-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3743864/crash-2019-10-18_23.32.14-server.txt)

Sorry for not using the regular issue layout. It didn't come up when I started the issue and I only realised a few hours later.

**Comment by PG85** [comment]
Hey @TheNoseOfSauron , thanks for reporting this. Will move this into a release milestone asap, expect to fix this for the next release.

**Comment by PG85** [comment]
Just tested this in-dev with v8.4_r1, appears to be fixed already. I suspect this already works for 8.3 too. If you're still seeing the problem, feel free to reopen this issue.
