### ISSUE TITLE
RTG and BoP overworlds created before OTG is installed cause issues with the 'o' menu

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#345]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge

#### OTG Version
- [x] 1.11.2-v8

If you create a world with either BoP or RTG before installing OTG and then install OTG and try to use the 'o' menu it will not work. 

With BoP the menu simply does not appear after pressing o, with RTG you get the following crash:
https://paste.bombsite.be/zoxuyiyuke

**Comment by MCPitman** [comment]
Why is this marked as backlog? Shouldn't it be something that should be fixed as it's a bug with a v8 feature?

**Comment by PG85** [comment]
@MCPitman Backlog means unassigned, labeled/sorted but still needs a milestone.

**Comment by MCPitman** [comment]
Ok makes sense, didn't realise

**Comment by PG85** [comment]
Should be fixed for v8.2_r1.
