### ISSUE TITLE
Config.yaml file is written outside instance directory on Mac OS

### ISSUE THREAD

**Issue by Angela** [PG85/OpenTerrainGenerator#346]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [X] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [X] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
forge-14.23-5.2847

#### What other plugins are you running?
Biome Bundle

#### Description
On Mac OS, After creating a new single player OTG world, the `Config.yaml` file is written outside the instance directory,  at `<instance>\saves/<worldname>/OpenTerrainGenerator/Config.yaml`

Note that `\` is not a path separator on Mac OS (or linux) as it is on Windows.

<img width="469" alt="Screen Shot 2019-10-18 at 10 41 47 PM" src="https://user-images.githubusercontent.com/554489/67138533-91fdf080-f1f9-11e9-8dae-047f1e39e47d.png">

Expected behavior: file is neatly contained within `<instance>/saves/<worldname>/OpenTerrainGenerator/Config.yaml`

**Comment by Angela** [comment]
Possibly related to this issue: https://github.com/PG85/OpenTerrainGenerator/issues/294

Attempting to reopen a world with name not matching a preset (in this example `NotMatchingPresetName`) fails to do anything and logs the following error:

`[23:22:49] [Client thread/ERROR] [OTG]: Could not load world. Preset not found: /Users/angela/Documents/Curse/Minecraft/Instances/Test OTG/mods/OpenTerrainGenerator/worlds/NotMatchingPresetName`

**Comment by PG85** [comment]
Hey @Angela , thanks for reporting this. Will see if I can fix this for the next release, will move into a release milestone asap.

**Comment by PG85** [comment]
Should be fixed for v8.1_r1, dev version will be on the OTG discord asap.
