### ISSUE TITLE
can't load into world

### ISSUE THREAD

**Issue by lagreflex** [PG85/OpenTerrainGenerator#347]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

[crash-2019-10-19_09.57.02-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3746759/crash-2019-10-19_09.57.02-server.txt)

i used the previous version of OTG to generate the world and play in it

**Comment by LunerticDev** [comment]
I've encountered the same issue

**Comment by ColterD** [comment]
I had this same issue and was debugging it for a while.  Something I found that completely helped was to delete the /OpenTerrainGenerator/ folder in /mods/.  Just wipe it out and let the mod rebuild the folder and configs.  See if that helps any.

**Comment by lagreflex** [comment]
> I had this same issue and was debugging it for a while. Something I found that completely helped was to delete the /OpenTerrainGenerator/ folder in /mods/. Just wipe it out and let the mod rebuild the folder and configs. See if that helps any.

i did try that and no luck, same with the OTG folder in the save file
Edit: i lied downgrading and doing this did fix the issue, not sure if i can use version 8 though

**Comment by PG85** [comment]
Hey @lagreflex , thanks for reporting this. Did you use v8_r1 from the dev channel of the discord, or did you get the v8 official version from curse? Updating a v6 world to v8 by copying the world save + the /mods/OpenTerrainGenerator/worlds/<worldname> folder should work. Is that what you were doing?

**Comment by AdaraChristine** [comment]
I just tested v8 with my v6 server world and got he same error. Is there more to updating than deleting v6 and core and dropping in v8?
