### ISSUE TITLE
BO3AtSpawn not working properly with highestBlock

### ISSUE THREAD

**Issue by AdaraChristine** [PG85/OpenTerrainGenerator#349]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [X ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [X ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
forge-1.12.2-14.23.5.2838-universal
#### What other plugins are you running?
modified Biome Bundle

#### Description
[What is happening? - Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures;)]
When there is a bo3 set at spawn player spawns at y33.
![2019-10-19_16 35 51](https://user-images.githubusercontent.com/30163566/67152624-31b98e00-f28f-11e9-8706-7b5957e11bc6.png)
[What did you expect to happen? - Explain what you expected to happen after performing the previously described steps]
I expected to spawn in correctly. My modified BB preset worked fine in the previous version of OTG.

**Comment by AdaraChristine** [comment]
OTG 1.12.2_v8_r1
Ive loaded a default BiomBundle and have done some tests. The first thing i changed was i removed all floating biomes which was done in the modified BB i used. This is the result of loading a new world WITH a BO3AtSpawn. I spawned in the tree next to the building.
![2019-10-19_19 49 52](https://user-images.githubusercontent.com/30163566/67154100-b1a12180-f2aa-11e9-9a39-eb24b6fd3f06.png)
Spawing is normal without the a BO3AtSpawn

**Comment by AdaraChristine** [comment]
So is this a bug or something on my end?

**Comment by PG85** [comment]
Hey @AdaraChristine , thanks for reporting this. If I understand it correctly, is the structure always spawning correctly, but the player isn't?

**Comment by AdaraChristine** [comment]
Neither bo3 or player spawn in correctly when i removed the floating biomes from BB. It seem like when a bo3 is involved they are spawning too high at the y

**Comment by PG85** [comment]
Could you check if the bo3 uses randomY and has minheight/maxheight set?

**Comment by AdaraChristine** [comment]
BeachHutWest8x11.bo3    -----      SpawnHeight: highestBlock

**Comment by PG85** [comment]
Thanks for reporting, will need to make a simple test world with just terrain and bo3 to do some debugging.

**Comment by AdaraChristine** [comment]
Not sure if its related but it appears if you /otg tp biome and there is a structure there, you end up underground in a block under it.

**Comment by AdaraChristine** [comment]
I see this is marked as backlog does this mean it has a very low priority? I was waiting for this fix to release a pack update because ive included a bo3 at spawn for players. All my beta testers report falling through the world. Thanks

**Comment by AdaraChristine** [comment]
After a bit of testing ive discoved that setting SpawnRadius: 10 spawns me in correctly around 0,0 with a bo3 set at spawn. Setting the SpawnRadius: 0 seems to be causing the issue?

**Comment by PG85** [comment]
Hey @AdaraChristine , thanks for figuring this out! Will take a look at this for v9.

**Comment by PG85** [comment]
Spawn point detection has been fixed (for as far as is possible) for v8.4_r1. MC by default only allows grass blocks as spawn location, and only allows a small number of default biomes. If it can't find a spot, it just uses the default location around 0,0. I've changed it to now allow any collidable block in any land biome, it also disallows logs and leaves. You may ofc still spawn on other collidable blocks that you wouldn't expect to be able to spawn on, I'd have to exclude all of them explicitly, I can't do that for modded blocks ofc. I hope leaves and logs will do for now, let me know if you see any more problems, thanks!
