### ISSUE TITLE
Crashes when portal is created when Teleporter is not the vanilla Teleporter

### ISSUE THREAD

**Issue by TheRandomLabs** [PG85/OpenTerrainGenerator#350]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
Forge 1.12.2-14.23.5.2847

#### Server/Client Log
https://paste.dimdev.org/linakezesi.mccrash

#### What other plugins are you running?
RandomPortals 1.12.2-1.8.1.1

#### Description
[Here](https://github.com/PG85/OpenTerrainGenerator/blob/472973c931796ac3fa7eae59783136290f0565ca/platforms/forge/src/main/java/com/pg85/otg/forge/dimensions/OTGBlockPortal.java#L68), `Teleporter.class` should be used instead of `_this.getClass()`. `Class#getDeclaredFields` does not return inherited fields, so modded Teleporters such as `RPOTeleporter` cause a `NullPointerException`.

**Comment by PG85** [comment]
Hey @TheRandomLabs , thanks for reporting this, will include this for 8.1_r1, to be released on the OTG discord's dev-channel, will be in the 8.1 release.
