### ISSUE TITLE
Big problems in moving from v6 to v8 and back with "ReplaceToBiomeName:" option

### ISSUE THREAD

**Issue by Darsenia** [PG85/OpenTerrainGenerator#354]
#### OTG Plugin or Mod

- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version

- [x] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
forge-1.12.2-14.23.5.2847

#### Description
I wanted  to test my finished with v6 preset with v8 before posting (god bless the backups!...), and noticed some strange issues with grass and leaves colors.So those colors became vanilla ones(I guess) in virtual biomes and remade vanilla biomes.I checked those virtual biomes,checked remade vanilla ones,compared them with backups.All was absolutely identical.But colors were from OTG vanilla, not from my remade vanilla biomes!
Screenshots:

Roofed Forest Border (virtual, replaced to Roofed Forest remade)in v6:
![2019-10-12_19 54 36](https://user-images.githubusercontent.com/36276289/67210437-c3590500-f421-11e9-8095-1733802d1170.png)
Roofed Forest Border (virtual, replaced to Roofed Forest remade) in v8:
![2019-10-21_16 19 37](https://user-images.githubusercontent.com/36276289/67210474-d5d33e80-f421-11e9-854e-e21ee4f6340e.png)

Plains (vanilla remade) v6:
![2019-10-09_00 57 42](https://user-images.githubusercontent.com/36276289/67210682-306c9a80-f422-11e9-9b9c-0f0095b1f3e3.png)
Plains (vanilla remade)v8 (trees are a bit different, first screenshot was old, but colors were not touched):
![2019-10-21_16 19 12](https://user-images.githubusercontent.com/36276289/67210695-35314e80-f422-11e9-9c22-b1ef8843f3b2.png)

Then I changed OTG version back to v6, and after restart I got plenty of errors about biomes with ids>255.It was strange.Checking .bc files shows: 
All vanilla biomes names from "ReplaceToBiomeName:"  were removed! My custom biomes with ids<255 names in this line were not touched.

**Comment by Darsenia** [comment]
I made new folder,reinstalled mods and my preset, and everything changed.ReplaceToBiomeName now contains something like "minecraft:mesa_clear_rock" for example, for **not virtual** Mesa Plateau biome. Colors of course changed to vanilla.I removed that line, removed "region", reloaded-this line appears again and colors are still vanilla.I'll try to make .bc files "WriteDisable" again and check.

**Comment by Darsenia** [comment]
Well, it stopped rewriting my configs,but nothing changed,colors are still vanilla.

**Comment by Darsenia** [comment]
And I also found, that everything works fine with an empty line in ReplaceToBiomeName in a virtual biome.It doesn't crash or say something about it the log...

**Comment by MCPitman** [comment]
I'm not really clear as to what the issue is, all of my presets seem to be ok when tested with v8

**Comment by AdaraChristine** [comment]
I had the same problem. I loaded up my preset in v8 to test, then when i changed back to v6 with the same preset ALL the ReplaceToBiomeName entries in each biome file was blank.

**Comment by Darsenia** [comment]
MCPitman,
Did you have any changed colors(leaves and grass with multiplier:false) in vanilla biomes in your presets?If not, you may simply not run into this problem...
So, I see a few problems now:
1.Vanilla biomes don't accept any color changes(with temp/humidity multiplier:false);all colors remain default;
2.Virtual biomes, replacedtobiomename with vanilla ones,also stay with default colors;
3.Blank fields instead of vanilla names in the ReplaceToBiomeName field after going back to OTG v6.Custom biomes names were not affected(in my case).
I guess it may be somehow connected to the v8 added ability of using modded biomes in the  ReplaceToBiomeName field.OTG changes "biome name"(like Plains) to "biome registry name"(minecraft: plains)after restart.If these registry names adress to Minecraft biomes colors etc. instead of user-changed OTG ones, it may be the reason...It is just my guess-work,I don't know what happens inside OTG code))

**Comment by Darsenia** [comment]
AdaraChristine,
Were your blank entries vanilla biomes names or your custom biomes names?For me custom names were not affected...

**Comment by MCPitman** [comment]
Why would you use vanilla biomes if you're going to change their biome colours instead of a custom one? Can't you just copy the biomes and make them custom to fix this?

Worlds with v8 replacetobiomename syntax are not compatible with v6 that is normal.

**Comment by PG85** [comment]
Hey guys, thanks for responding to this.

- Updating v6 configs to v8 should work fine, but v6 may not be able to handle updated configs. You can prevent configs being updated using SettingsMode:WriteDisable.
- For mod compatibility, OTG no longer replaces any vanilla biomes in the registry for v8. If you want to use custom colors, you'll have to turn your biomes into custom biomes.

**Comment by Darsenia** [comment]
MCPitman,
v8 sintax is not compatible with v6-yes,it is logical,ok)
I thought about this "elegant" solution of the issue with colors already.It's not good at all.Well,I use vanilla biomes mostly to save free ids.Why not?Colors can be changed,nothing forbids it ( in v6).Simple calculations:there are at about 60 vanilla biomes.I have to make 60 more custom copies: free ids= (255-60)-60.And...I already have only 49 ids free now, when I'm using vanilla to save at least some ids free! I'm a bit worried even now about compatibility with other mods in modpacks in that case,to few free ids...Why would i use so many non-virtual biomes?Mostly because of different colors,sometimes to make some significant biomes to have their own biome tags,climate and to use them for teleportation with NatureCompass.
Well,I see.It is the way OTG v8 functions now...It is a bit sad.

**Comment by PG85** [comment]
Hey @Darsenia , sorry we had to sacrifice colors for vanilla biomes, OTG works a lot better with other mods now though :).
