### ISSUE TITLE
Issues with BO4 files

### ISSUE THREAD

**Issue by mensreaMC** [PG85/OpenTerrainGenerator#357]
- [X] OTG Mod for Forge
- [X] 1.12.2_v8
-forge-14.23.5.2846
-log: https://pastebin.com/45yUn5mE (for the second crash)
-other mods listed in crash reports

Two things seem to be happening. 
-First, if I set a file to IsOTGPlus: true and writeall it will populate a BO3 file with BO4 info, but it also removes the IsOTGPlus: true setting. If I add that back it gives me this crash to desktop when attempting to spawn the structure: https://pastebin.com/A1pEkvSg

Here's a copy of the BO4 causing the crash: https://pastebin.com/xiWd7if9

-Second, if I just leave IsOTGPlus: true on and don't use writeall it actually does spawn the structure but it won't let me add branches without this crash: https://pastebin.com/7y2GdzNg

**Comment by MCPitman** [comment]
Do you have OTG plus mode enabled in the worldconfig?

**Comment by mensreaMC** [comment]
Yes.

**Comment by PG85** [comment]
Need to confirm if this is still an issue (v8.3_r4 or up), BO4's work fine for me.

**Comment by PG85** [comment]
WriteAll and WriteWithoutComments weren't working properly for BO4's. Fixed with v9.0_r2.
