### ISSUE TITLE
Structures don't obey HeightOffset

### ISSUE THREAD

**Issue by mensreaMC** [PG85/OpenTerrainGenerator#358]
- [X] OTG Mod for Forge
- [x] 1.12.2_v8
- forge: forge-14.23.5.2846

The HeightOffset setting does nothing. Structures still spawn without taking it into account. This occurs with both BO3 and BO4 structures.

**Comment by MCPitman** [comment]
Pretty sure this is intended behaviour rather than a bug so I'm going to tag this as a feature request.

**Comment by PG85** [comment]
HeightOffset should work just fine for BO4's. Be sure to have IsOTGPlus:true set in the worldconfig.
