### ISSUE TITLE
Feature: Config to disable all ore generation

### ISSUE THREAD

**Issue by SynfulChaot** [PG85/OpenTerrainGenerator#36]
Would it be possible to add a setting to the base WorldConfig.ini file to override all biome ore settings to play nicer with other mods that handle ore generation?

**Comment by PG85** [comment]
Hey, thanks for the feedback. That's a good idea, will see if I can put it in the next major release.

**Comment by PG85** [comment]
Added DisableOreGen to worldconfig for 1.12.2 v9_r11, disables any Ore(), UnderWaterOre() or Vein() resource that uses any type of ore block.
