### ISSUE TITLE
Floating snow layers on top of other mods ground cover

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#362]
In biomes with a low enough temperature for snow to generate upon initial generation, snow layers appear to place above any modded ground cover. This is easily reproduced by using any preset with OTG v8 and Biomes o Plenty installed. 

![2019-10-27_19 13 55](https://user-images.githubusercontent.com/9453952/67639960-72984f00-f8ee-11e9-8799-48995a0c76d9.png)

**Comment by PG85** [comment]
If other mods' blocks are correctly identified as solid/non-solid, then this should be fixed for v8.2_r1.
