### ISSUE TITLE
Pregenerator is still broken on PregeneratorMaxChunksPerTick: 1

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#363]
Here is what I got after doing a 300 radius pregen with PregeneratorMaxChunksPerTick: 1 in the v8 release:
![image](https://user-images.githubusercontent.com/9453952/67705348-c36f7c80-f9ae-11e9-9d55-956f681dff6b.png)

**Comment by PG85** [comment]
Does PregeneratorMaxChunksPerTick: 2 show any problems?

**Comment by PG85** [comment]
Thanks, should be fixed for v8.3_r4.
