### ISSUE TITLE
Block fallbacks crash Spigot in v8_r6_Josh7

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#364]
Adding block fallback data in OTG dev version v8_r6_Josh7 crashes Spigot, ideally Spigot would still be compatible with the syntax but not bother looking for the modded blocks, that way a preset could still support Spigot and Forge.

The error (Reported by NLBlackEagle):
https://pastebin.com/ET1cgjPs

**Comment by PG85** [comment]
This method isn't called anymore on the client for fog colors, biome is fetched by saved id like biome colors, should be fixed.

**Comment by PG85** [comment]
*wrong issue, reopened ><.

**Comment by PG85** [comment]
Should be fixed for v9.0_r2.
