### ISSUE TITLE
Biomes fail to Generate.

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#366]
#### OTG Plugin or Mod
- [x] OTG Plugin for Spigot

#### OTG Version ( Issue does not happen to V6 or any forge builds. )
- [x] 1.12.2_v8.1
- [x] 1.12.2_v8

#### Forge or Spigot Versions
CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

#### What other plugins are you running?
Dregora v1.62 [Closed Development]
DiscordSRV-Build 1.16.4
EssentialsX 2.0.1
Multiverse-Core 2.6.0
PermissionsEx 1.23.4
VoxelSniper 5.171.0 Snapshot
Worldedit bukkit 6.1.7.3

#### Description
A fromimage biome at -2547 146 -7491 in Dregora get reverted back to Ocean. At first it looks like a mistake in the hexcolors but using OTG v6 it works and the hexcolors match perfectly. This may also be happening to other presets but due to waterheight being the same as vanilla it would be harder to spot.

I do not want to put any pressure on this issue but due as i want everyone to have the full experience playing once v1.62 comes out I will recommend OTG v6 as OTG v8 contains missing biomes due to an OTG bug.

**Comment by NLBlackEagle** [comment]
Here's a simplified version of the world with the bug: https://dregora.com/wp-content/uploads/2019/11/world_dregora_issue366.zip

**Comment by MCPitman** [comment]
Couldn't reproduce this when I tried, using Spigot and the test world and everything looks fine.
![2019-11-03_14 36 38](https://user-images.githubusercontent.com/9453952/68088533-15ede480-fe58-11e9-92f0-ae025f57f5cc.png)

**Comment by NLBlackEagle** [comment]
I will try to figure out what is going on here in the upcoming few days and close or update the isssue.

**Comment by PG85** [comment]
Thanks for reporting and responding :)

**Comment by NLBlackEagle** [comment]
Couldn't reproduce the issue myself either. This may have been some result of switching workstations often and not renewing the otg biome id's.
