### ISSUE TITLE
Setting a spawn with SpawnPointSet: does not effect spawning

### ISSUE THREAD

**Issue by AdaraChristine** [PG85/OpenTerrainGenerator#368]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [X ] OTG Mod for Forge

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ X] 1.12.2_v8_r1

#### Forge or Spigot Versions
forge-14.23.5.2847

#### What other plugins are you running?
https://www.curseforge.com/minecraft/modpacks/mystical-village-2/files/2819266

#### Description
Setting a spawn with SpawnPointSet: does not effect spawning

This is what was attempted:
SpawnPointSet: true
SpawnPointX: -10
SpawnPointY: 64
SpawnPointZ: -15
SpawnRadius: 0

Result:
Player spawn in at x-231,z-49,y64

**Comment by PG85** [comment]
SpawnPointSet has been fixed for v8.4_r1 (to be released on the otg discord dev channel asp), also takes into account SpawnRadius. Looks like MC automatically selects the Y coord, still seeing if I can fix that as well. Please test this with v8.4_r1 when it's available and let me know if you still see any issues, thanks!
