### ISSUE TITLE
VinesGen crash when above worldheight

### ISSUE THREAD

**Issue by Darsenia** [PG85/OpenTerrainGenerator#369]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [x] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
latest 1.12.2 Forge

#### Server/Client Log
[latest.log](https://github.com/PG85/OpenTerrainGenerator/files/3820150/latest.log)

#### What other plugins are you running?
Optifine (latest for 1.12.2)

#### Description
The game freezes near Jungle generating chunks because of vines.

(some other issues with not found tags etc - I'm working on it right now:)It's my fault, it doesn't cause crash)

**Comment by Darsenia** [comment]
Fixed)
It was line Vines(30,100.0,65,256) 
I've set 255 instead of 256 and all seems to be ok.

**Comment by PG85** [comment]
Hey @Darsenia , thanks for reporting this. Should improve this to make it log a warning instead of throwing an exception.

**Comment by PG85** [comment]
For v8.4_r1, values for resources are automatically corrected to 255 if they are higher. Thanks for reporting!
