### ISSUE TITLE
Server crash when applying v8.2

### ISSUE THREAD

**Issue by AdaraChristine** [PG85/OpenTerrainGenerator#370]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [X ] OTG Mod for Forge

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ X] 1.12.2_v8_2
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
forge-1.12.2-14.23.5.2847-universal

#### Server/Client Log

https://pastebin.com/iTASMMPv

[latest.log](https://github.com/PG85/OpenTerrainGenerator/files/3820402/latest.log)

#### What other plugins are you running?
https://www.curseforge.com/minecraft/modpacks/mystical-village-2/files/2823432

#### Description
Server wont start when applying v8r2 to existing world

**Comment by PG85** [comment]
Hey @AdaraChristine , thanks for reporting this. What kind of world was it, created with which version of OTG? Does the world still work with the previous version?

**Comment by AdaraChristine** [comment]
It was a BB world with edited biomes created with v8.0. Could not restore with v8.1 or v8.2.  But I was able to load a old save from version v8.0 and use v8.2 to get it to work. Perhaps something got corrupted with 8.1

**Comment by AdaraChristine** [comment]
Thanks for your quick attention and great work , Hopefully this just a isolated indecent and just glitch.

**Comment by PG85** [comment]
Thanks for reporting and figuring this out!
