### ISSUE TITLE
ReplaceToBiomeName in v8.2 and Biomes O'Plenty

### ISSUE THREAD

**Issue by Darsenia** [PG85/OpenTerrainGenerator#372]
#### OTG Plugin or Mod

- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version

- [x] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
latest Forge

#### What other plugins are you running?
latest Biomes O'Plenty

#### Description
I'm not sure if it is normal or not,but:
when using BOP biome in ReplaceToBiomeName, custom OTG biome is populated with BOP trees and other decorations 99%.I hardly met a few my trees there.Is there any way of removing BOP trees etc from there?I tried to make all BOP biomes ids "-1" in its config, but now my custom biome is simply "plains" without any BOP decorations.
I thought, that ReplaceToBiomeName will change only colors and climate (and a name)...

**Comment by MCPitman** [comment]
Why replace to a BoP biome if you don't want it to populate it with it's stuff? Turning off BoP's population would be down to BoP to implement if anything.

**Comment by Darsenia** [comment]
I found how turn off trees in configs.But it would work only with mods that are so configurable.
Never mind;) 
So that kind of ReplaceToBiomeName is for full integration of any biome.Ok)

**Comment by MCPitman** [comment]
OTG doesn't fully integrate anything when you use replacetobiomename, it just uses the ID and whatever happens next is up to the other mod(s).

**Comment by Darsenia** [comment]
Ah,that's it...Thanks for explanation)
I have another question about virtual biomes in v8: if there is no need now to mention them with ids in "custom biomes: " line in worldconfig and they are read directly from worldbiomes folder, how can ids>256 be assigned to the virtual biomes? The old way, via that line? If I don't want them to take ids <256 for better mods compatibility.Will biomes with ids>256 be affected by dynamic ids allocation?

**Comment by MCPitman** [comment]
If a biome uses replacetobiomename it gets assigned an ID > 256
