### ISSUE TITLE
CustomStructure bo4s behaving weirdly in OTG v8/8.1/8.2

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#373]
Have spent the last couple of hours figuring this out (yayy) so let me know if you need a test world or something - but it should be clear enough from the description.

I noticed that I was getting different structures spawning under the same conditions depending on which CustomStructure() line was first in the resource queue, and since bo4s used to allow multiple lines this is causing issues when using v8.

I tried to narrow it down and I saw that when using multiple CustomStructure() lines in the resource queue (using OTGPlus mode) the 'CalculateBranches (minimumSize)' process is only happening for things in the initial CustomStructure() entry and as such only a limited number of bo4s are spawning.

Putting all structures into a single CustomStructure() entry seems to fix it, but that gets difficult to read fairly quickly.

Unfortunately this is likely the source of some the perceived performance improvements in v8 as when testing Wildlands it's spawning way fewer structures in v8 than in v6 due to this issue.

**Comment by PG85** [comment]
Thanks for figuring this out! Fixed for v8.3_r1.

**Comment by BiomeBundle** [comment]
Awesome!

**Comment by MCPitman** [comment]
Re-opened this because I still get different results depending on what structures are first in the resource queue.

**Comment by MCPitman** [comment]
Actually what I'm seeing is caused by a different issue, closing again and will open a fresh issue.
