### ISSUE TITLE
Time not advancing when sleeping in non-overworld OTG dimension

### ISSUE THREAD

**Issue by raqu73** [PG85/OpenTerrainGenerator#375]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - 1.12.2_v8.2

#### Forge or Spigot Versions

forge-14.23.5.2847

#### What other plugins are you running?

Biome_Bundle-1.12.2-v6.1

#### Description

In an OTG dimension traveled to from the overworld, I tried sleeping during night to pass time until day, and this did not happen. To be clear, time does advance as normal when sleeping in the overworld.

After sleeping in the bed, I expected time to advance until morning.

**Comment by PG85** [comment]
Thanks for reporting this, it's happening for me as well. Moving to backlog for now, to be moved to a release milestone asap.

**Comment by PG85** [comment]
This should be fixed for v8.4_r1 (to be released on the OTG discord asap), feel free to reopen if the issue remains.
