### ISSUE TITLE
CalculateBranches (minimumsize) is making bo4 enabled worlds really slow

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#378]
Two issues with CalculateBranches (minimumsize):

CalculateBranches (minimumsize) checks are happening when re-entering a world where it was already done before (for the same bo4s).

The check process seems unnecessary (given it is so slow) for non-random bo3s since it could just count the number of files to know how large it is.

**Comment by PG85** [comment]
Thanks, should be solved for v8.3_r4
