### ISSUE TITLE
Crash when exploring pregenerated chunks in v8.3_r1

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#379]
To reproduce the below crash pregenerate a radius of 100 chunks or so and then fly around the pregenerated area, I have reproduced this issue 3 times this way:

https://gist.githubusercontent.com/MCPitman/f3171980f4740af3f5f8714e1f2907ce/raw/eab5870d0e0616b409f008d1fde5d624dfb4d663/OTG%2520v8.3%2520bo4%2520crash

**Comment by PG85** [comment]
Thanks, should be solved for v8.3_r4
