### ISSUE TITLE
OTG + ID: Menril trees don't spawn with biome bundle.

### ISSUE THREAD

**Issue by Claycorp** [PG85/OpenTerrainGenerator#38]
I can't find Integrated Dynamics menril trees anywhere. Got any advice on this?

**Comment by PG85** [comment]
Hey Claycorp, 

Thanks for reporting this. Will need to investigate, right now I have no idea how ID decides when/where to place these trees.

**Comment by kragnoth** [comment]
Maybe a conflict from somewhere else?  I get them spawning, just not the biomes.  They spawn kind of randomly in the more open areas.  I don't have alot, because I seem to get Mesa world.

**Comment by PG85** [comment]
The Forge biome dictionary may be being used to figure out where to place the trees. You can use the console command "/otg biome -d" to find out which biome dictionary id's a biome has assigned to it. Likely the trees only spawn for specific id's.

As for biomes, not sure I understand, is ID also supposed to add its own biomes to the world? That may be a bit tricky with OTG, I wouldn't expect that to work.

**Comment by 12foo** [comment]
I'm having this issue as well, but I'm unfortunately not familiar with the OTG code. It seems like ID hooks into Forge's DecorateBiomeEvent and occasionally intercepts the decoration to replace it with a menril tree. My guess is that OTG does not fire this event so decoration hooks by other mods don't work at all?

**Comment by PG85** [comment]
Event should be fired with v8_r2, dev build will be on the Discord at #openterraingen.
