### ISSUE TITLE
bo4 structures are not cancelling when they extend into biomes where they are not listed as customstructures (even with 0.0 rarity)

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#380]
Title says it all really, seems to be only checking the starting location is valid - which was not the case in v6 OTG.

(Using v8.3_r1)

**Comment by PG85** [comment]
Thanks! Cannot reproduce this with v8.3_r4, feel free to reopen if you can still reproduce it.
