### ISSUE TITLE
/otg tp command failing to find biomes that it should find

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#381]
Something not quite right with /otg tp as it's not finding biomes that are sometimes less than 100 blocks away.

The below is a biome with no spaces in the name and the biome is >500 blocks across, the command failed to find the biome even though it was within view distance and I found it manually shortly afterwards.

![image](https://user-images.githubusercontent.com/9453952/69015655-ec6fa580-098d-11ea-8211-6fc59b0a68d8.png)

**Comment by PG85** [comment]
Needs to be checked if it's an issue with biome config names, biomes too small to find, or an actual bug.

**Comment by MCPitman** [comment]
I already stated in the bug report above that it isn't a biome name issue and that biome is >500 blocks across.

I tried to narrow this down recently and it may only be something that impacts developers (need to verify), as the last time I noticed it the world had the biome layout changed from initial generation (generated world, changed a biome rarity so changed biome layout and /otg tp failed to find a biome that was 100 blocks away).

**Comment by PG85** [comment]
WIll need a seed, coords and biome name to repro this plz.

**Comment by MCPitman** [comment]
Will do next time it happens.

**Comment by PG85** [comment]
should be fixed for v9.0_3
