### ISSUE TITLE
Feature: enforce specific generation via config

### ISSUE THREAD

**Issue by twothe** [PG85/OpenTerrainGenerator#382]
For mod-pack creators it would be great if you could add a feature that allows to set the default world a player is spawned in.

I.E.: I have Vanilla Vista installed and if the player or server creates a new default world, then with no further options given a Vanilla Vista world is created.

A plus would be to have a selection of various worlds that have been generated similar to the way Skyblocks 4 does it.

**Comment by PG85** [comment]
Hey @twothe , thanks for the feedback! OTG v8 added a modpack config file for modpack creators. Modpack creators can specify an overworld and OTG dimensions via the config, the config can target either any new vanilla world being created (to automatically add OTG dimensions), or any OTG preset being used to create a new world (the settings from the modpack config will be used as default settings in the OTG world creation menu).

A modpack config is easy to create, just create an OTG world with dimensions you like, then look in the saves/world/openterraingenerator/ folder to find the Config.yaml file. It's a yaml file, so you can edit it with a text editor if you like. Modpack creators can generate a Config.yaml file with OTG, rename it (fe YourConfig.yaml) and include it in their modpack so it's copied to config/OpenTerrainGenerator/YourConfig.yaml when installing the modpack.

**Comment by MCPitman** [comment]
Someone could just not click the 'Create OTG World' button at all though, there are other mods out there that 'lock in' what happens when any new world is created which is a good solution for some modpacks that isn't solved by an OTG modpack config.

**Comment by twothe** [comment]
@PG85: Thanks for the quick reply, I will try that. I also found a "#TODO: Provide instructions for modpack devs." at the first line of that file. That would indeed be helpful because one of the most common problems is players not selecting the correct world. ;)

What do I need to do to make this the default world even when the player does not click on the "New OTG World" button?
