### ISSUE TITLE
FillEmpty: ContinueNormal

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#385]
#### Is your feature request related to a problem? Please describe.
After testing I found out that any undefined FromImage mode color within the dimensions of the map are replaced with the value of the Fillempty setting and that anything outside the boundaries of the image becomes random mode if the continuenormal feature is used .

#### Describe the solution you'd like
I was hoping that random generation could be applied to any undefined colors in the map as well. Enabling could be "FillEmpty: RandomMode" or applying the continuenormal setting over the undefined biomecolors as well.

**Comment by PG85** [comment]
Love this idea, hope to have some time to give fromimagemode some love in the future. 1.13/1.14/1.15 have prio atm tho.

**Comment by PG85** [comment]
See https://github.com/PG85/OpenTerrainGenerator/pull/396, when @authvin uploads a build, please test it and let me know if everything works OK.

**Comment by PG85** [comment]
Tested OK, thanks!
