### ISSUE TITLE
"Select a Preset" screen does not (correctly) load mcmod.info information.

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#386]
#### OTG Plugin or Mod
- [X] OTG Mod for Forge

#### OTG Version
- [x] 1.12.2_v8.2

#### Forge or Spigot Versions
1.12.2 forge 14.23.5.2847

#### What other plugins are you running?
Dregora V1.62
OTG 8.2

#### Description
Dregora mcmod.info is not being used for "Select a Preset" It seems as if it pulls the Vincent | NLBlackeagle from https://dregora.com meta text and the other text from another location? Or from cache?

The strange thing is that the mod information page displays the information correctly.

Contents jar:
![afbeelding](https://user-images.githubusercontent.com/4073584/69555911-3109cb00-0fa4-11ea-9bf7-791b6d6fa108.png)

OTGLogo.png:
![afbeelding](https://user-images.githubusercontent.com/4073584/69555944-3cf58d00-0fa4-11ea-93da-b3b614fd477a.png)

mcmod.info:
![afbeelding](https://user-images.githubusercontent.com/4073584/69555978-4848b880-0fa4-11ea-8b70-48384b7120de.png)

Select a Preset screen:
![afbeelding](https://user-images.githubusercontent.com/4073584/69556009-572f6b00-0fa4-11ea-91ec-d3e800209f2d.png)

Mod Information page:

![afbeelding](https://user-images.githubusercontent.com/4073584/69556078-729a7600-0fa4-11ea-99c7-bc58d8d66a10.png)

**Comment by PG85** [comment]
Hey @NLBlackEagle , if the png is showing up in the mods list, you've done it right so far. All you should need to do now is add to the worldconfig:
WorldPackerModName: -modid from mcmod.info-

That tells OTG that the worldconfig came from a specific worldpacker jar. Will try to automate this in the future so the WorldPackerModName setting isn't needed anymore.

**Comment by PG85** [comment]
*updated comment, WorldPackerModName: -modid from mcmod.info-

**Comment by NLBlackEagle** [comment]
I noticed a typo in the WorldPackerModName: ( Within worldconfig.ini ) Where the "Dregora" modid had a capital D. I tried changing the all files to match everything but despite doing so the correct info still did not showed up. Here's some screenshots:

**Modinfo contents:**
![afbeelding](https://user-images.githubusercontent.com/4073584/70148404-67330300-16a6-11ea-9bf0-a634da583a2c.png)

**worldpacker contents:**
![afbeelding](https://user-images.githubusercontent.com/4073584/70148472-8b8edf80-16a6-11ea-85ce-398cf7a8cf19.png)

**WorldConfig.ini**
![afbeelding](https://user-images.githubusercontent.com/4073584/70148553-b0835280-16a6-11ea-943f-84b5ab45dbb2.png)

**Result:**
![afbeelding](https://user-images.githubusercontent.com/4073584/70148597-c133c880-16a6-11ea-8a01-a36ce96360bd.png)

**Comment by Bahnschrift** [comment]
Regarding that last comment, ModIDs cannot usually contain capitals...

**Comment by PG85** [comment]
Thanks for responding guys, and rgr that, try with lower-case mod id.

**Comment by NLBlackEagle** [comment]
Lower case solved the issue

**Comment by RikAzerion** [comment]
Awesome, thanks for reporting! Note to team OTG: Need to document this on the wiki!
