### ISSUE TITLE
Bug/Crash: OTG + Better With Mods: Hardcore Stump option causes world to "Build" forever

### ISSUE THREAD

**Issue by Hosed** [PG85/OpenTerrainGenerator#39]
The Better With Mods mod has several configs that modify world generation, though I can only find one that outright crashes when interacting with OTG.

The Hardcore Stump feature, when turned on, causes OTG worlds to just hang forever at "building terrain" during loading/creation.  This feature replaces the bottom log of trees with a "stump" log in vanilla worlds.

All other world gen features (abandoned structures and villages) seem to load fine, though I didn't test to see if they were actually devoid of loot and crops.

**Comment by PG85** [comment]
Hey, thanks for reporting this. Will look into this when I have the time but since it does not appear to be a critical bug it's not going to have priority for a while.

**Comment by PG85** [comment]
Needs to be tested with v8.3_r4 or higher.

**Comment by PG85** [comment]
Closing this since it's so old. Feel free to reopen this if the issue persists with newer versions of otg (8.3+)
