### ISSUE TITLE
Bug: Passive mobs spawning inside blocks and dying

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#390]
Seems to only happen with bo3s and bo4s but since passive mobs have a very low chance to respawn in already generated chunks (based on the info on the wiki) it's likely to impact the number of passive mobs a player sees as well as causing small amounts of unnecessary lag:

![2019-11-29_22 43 59](https://user-images.githubusercontent.com/9453952/69892155-7d357200-12fa-11ea-8c21-5bc7f1b81ed2.png)

**Comment by PG85** [comment]
Thanks for reporting this, will have to look at spawn order, mobs should be spawned after BO3's/BO4's so they should be able to see their blocks.

**Comment by PG85** [comment]
Need to create a test setup for this and figure out what's going on. Moving to backlog for now.

**Comment by PG85** [comment]
Need to confirm if this happens for 1.16, otherwise move back to 1.12 backlog.

**Comment by PG85** [comment]
Have not yet seen this for 1.16.5, mob spawning seems ok, closing this for now. If we find issues with mobs choking for 1.16.5, feel free to reopen this issue. For 1.12.2, don't think we'll fix this, unless someone would like to make a PR.
