### ISSUE TITLE
Bug: Some vanilla world-managing functionality is removed, which breaks some other mods

### ISSUE THREAD

**Issue by floral-qua-floral** [PG85/OpenTerrainGenerator#394]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [ X ] OTG Mod for Forge

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ X ] Other - 1.12.2_v8.3

#### Forge or Spigot Versions
Forge 1.12.2 version 14.23.5.2847 (probably not relevant)

#### What other plugins are you running?
None (however, as an example of broken mod functionality, [Backups](https://www.curseforge.com/minecraft/mc-mods/backups/files/2827701) v1.4.8 is used)

#### Description
Vanilla functionality regarding world management is removed entirely by OTG. Specifically, the Rename World and Recreate World buttons are not present. Changing a world's display name is remarkably difficult without the Rename World button, and the Recreate World button is highly useful in testing things such as structure generation, particularly in modpack environments.

Furthermore, the removal of these buttons can affect other mods. Silly511's [Backups](https://www.curseforge.com/minecraft/mc-mods/backups) mod typically modifies the Recreate World button to allow viewing the backups of the selected world in the World Select screen, however since this button is removed by OTG, the backups screen is completely inaccessible when the two mods are loaded together. This seems to effectively remove some key functionality from the Backups mod, such as the ability to enter world backups.

Ideally, I think OTG should not remove these buttons. Even if world renaming and recreating will never be possible for OTG worlds, the buttons should probably remain so that they can at least be used with non-OTG worlds, and to retain compatibility with mods that depend on or modify these buttons.

Update: The Backups mod has updated to fix its specific button incompatibility, but OTG still does remove some vanilla functionality. The missing buttons are the main focus of this report, not just the incompatibilities the missing buttons can cause.

**Comment by PG85** [comment]
Hey @floral-qua-floral , OTG removes these buttons because they could cause problems when used with certain existing OTG preset/world configurations. World name used to be tied to preset name, which is no longer the case in OTG v8, so we could make some improvements here and re-enable the rename world button. Regarding backup mods, OTG saves some of its own state in the world save folder, so will have to see if backup mods pick that up as well, will need some testing. Moving this to backlog for now, as we have some other issues that have prio. Will move into a release milestone asap.

**Comment by PG85** [comment]
This will be fixed for 1.16, we won't be fixing this for 1.12.2.
