### ISSUE TITLE
Bug: No population with cubic chunks

### ISSUE THREAD

**Issue by Metalit** [PG85/OpenTerrainGenerator#397]
With only OTG v8.3 (using Biome Bundle) and cubic chunks v0.0.970.0, the terrain lacks any grass or non-vanilla trees, as in the screenshots, abd underground is plain stone with no caves. When a village generated, the villagers spawned, but with no buildings.

It would be really cool if cubic chunks could be supported, including terrain generation above (and below) the height limit.

![2019-12-10_18 30 54](https://user-images.githubusercontent.com/48568911/70629894-4ad81e80-1bf0-11ea-83e1-722f3832d3f4.png)
![2019-12-10_18 30 38](https://user-images.githubusercontent.com/48568911/70629919-5297c300-1bf0-11ea-8eb2-5c85f547e6ef.png)

**Comment by PG85** [comment]
Hey @Metalit , thanks for reporting this. Would be nice to fix this, but won't have prio atm since these features appear to work fine with other mods, so would have to change things for CC only, 1.13/1.14 update has more prio atm, moving to backlog.

**Comment by PG85** [comment]
For 1.12.2, we won't be adding support for cubic chunks. We're moving on to 1.16 asap, will continue with new features after that.
