### ISSUE TITLE
Structure String for in BiomeConfigs

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#399]
#### Is your feature request related to a problem? Please describe.
Currently we need to convert structures into bo3's which can be tedious if one needs to start from scratch which is why I believe IceSpikes where added alongside other mechanics to add in reed ( now sugarcane ) Hence my request to add in a more universal method e.g.:

structure(frequency,rarity,maxheight,minheight,type)

#### Describe the solution you'd like
I would love to see a structure() string added in the biomeconfig to add minecraft default structures.

#### Describe alternatives you've considered
Converting structures into Bo3's

**Comment by PG85** [comment]
Hey @NLBlackEagle , thanks for reporting this. Default structures and resources are different from BO2's/BO3's, use their own mechanics and have their own settings, not sure it would really make sense to replace them or add this to the already existing settings. 

Ofc it would be good to think about rewriting/reorganising the configs in a way that makes it easier to work with default structures and BO's. Rewriting the configs is a different issue though, will create a new ticket for that and close this one for now.

**Comment by NLBlackEagle** [comment]
All right, that was a thing I was worried about, such as ships and treasure maps in 1.13 as those would need to be connected somehow I would assume
