### ISSUE TITLE
Request (Personally Major) - Archipelago Generator for Island Adventures MC-1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [PG85/OpenTerrainGenerator#4]
I love your Skylands mod. I got to thinking such a skilled developer should have no problem making a mod that would allow map makers to make a Archipelago or Many small Islands mod. Basically I have been on a kick about island adventures. I wanted a server that had Skyblock - Lava Block - And Aqua Block Style maps. The problem with this is default minecraft customized seed tends to break some generation with sea level ... so basically whilst I try to generate a map using sea level 78 and all ores spawn from 0-255 I get many breaks. At any rate can you make a mod that forces all ore types (Including modded) to spawn from level 0-255 and add the bonus of raising sea level to 78 so I can play windwaker minecraft :3 ?

**Comment by PG85** [comment]
Actually, OTG already allows you to customise the world and biomes and do all these things. Unfortunately the documentation is incomplete at the moment so you'll have to look at existing worlds' worldconfig and biomeconfig files (in the mods/OpenTerrainGenerator/worlds/worldname/ folder). You can also ask questions on /r/openterraingen or /r/biomebundle to get answers from experienced OTG content creators.
