### ISSUE TITLE
Bo4s will sometimes fail to ever generate at all in a world

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#400]
When a bo4 has height restrictions, if the initial spot that the bo4 checks for viability is outside the height range the log will report the following:

`Branching BO4 icecrystal2 could not be spawned in minimum configuration (isRequiredBranch branches only).`

In this case the bo4 is only 3x3 chunks in this case and has no 'checks' other than height range and has no random/optional branches.

Once this happens the bo4 will never place even in viable spots anywhere in the world - but if another (new) world is generated and the height check is passed (because biome height is variable) then the bo4 will generate fine within its height constraints.

**Comment by MCPitman** [comment]
Here is the biome with height restrictions on the ice crystals:

![2019-12-16_00 41 14](https://user-images.githubusercontent.com/9453952/70872145-d6113580-1f9d-11ea-92c0-dfe04b740417.png)

Here is the biome (same spot, same seed) without height restrictions on the crystals:

![2019-12-16_00 48 10](https://user-images.githubusercontent.com/9453952/70872158-e6c1ab80-1f9d-11ea-8e83-f5de516759d8.png)

The key point here is that the trees have the same max height limit as the crystals in the first image, so both should be spawning.

**Comment by PG85** [comment]
Thanks for reporting, looks like height checks for the structure's start chunk were being done when calculating minimumsize, which ofc they shouldn't have been. So when calculating the minimumsize when a customstructure was first being plotted, if the height checks failed, the structure wouldn't be allowed to spawn anywhere in the biome.

Should be fixed for v8.4_r1, minimumsize is calculated without performing starting chunk height checks.
