### ISSUE TITLE
issues using Biome Bundle in multiplayer mode

### ISSUE THREAD

**Issue by TRLWeiss** [PG85/OpenTerrainGenerator#403]
when i press the"o"key and set up a Biome Bundle dimension like single player mode,i find that there is no new dimension created in the server document.
And also,when i use the teleport button to tp to Biome Bundle dimension, i find that i only remain the previous dimension,but generator changed.
I just want to create a new Biome Bundle dimension,so i do not want to delete "world"document.
How can i fix it up?
version:1.12.2 v8.3
servercore:catserver(forge&spigot)

**Comment by TRLWeiss** [comment]
Moerover,i use the "o"menu to create a Biome Bundle dimension in the multiplayer,and i press the teleport button,but there is no result,i still remain the overworld dimension.

**Comment by PG85** [comment]
Hey @3094300238 , thanks for reporting this. Sounds like what you're doing should just work. I'm guessing it may have something to do with catserver, haven't tested with that at all tbh. Sponge also has problems with OTG dimensions, so it wouldn't be surprising. Won't have prio to add compatibility for minor platforms for a while unfortunately (1.13/1.14 update first). For now, please try this with a normal Forge server and let me know if you have the same problem.
