### ISSUE TITLE
Armorstand Rotation Bug

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#404]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [X] OTG Mod for Forge
- [X] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [X] 1.12.2_v8_r2

#### Forge or Spigot Versions
Spigot v1.12.2 R0.1 SnapShot

#### What other plugins are you running?
Essentials v2.0.1-b483

#### Description
While the armor stand should always spawn facing south it has a random rotation when spawned. Here is an example that can be spawned in using **/otg spawn ArmorStandBug presetname**

https://dregora.com/wp-content/uploads/2019/12/AmorStand.zip

**Comment by PG85** [comment]
Hey @NLBlackEagle , thanks for reporting. Same as https://github.com/PG85/OpenTerrainGenerator/issues/265.
