### ISSUE TITLE
1.16.x 1.0.0: 5.1 - Rewrite/reorganise configs

### ISSUE THREAD

**Issue by PG85** [PG85/OpenTerrainGenerator#407]
See updated description in the comments below.

**Comment by MCPitman** [comment]
I started this a little while ago will dig out what I have so far.

**Comment by Sakata-MC** [comment]
I would also request that configs go into the proper folder while that is being looked at.

**Comment by PG85** [comment]
For 1.16.x, configs will go in the /config/ folder.

**Comment by PG85** [comment]
1.16 WorldConfig: https://codeshare.io/5DDMYp
1.16 BiomeConfig: https://codeshare.io/5z8M3r
1.16 OTG.ini: https://codeshare.io/G63KY0

*I've just taken configs from BB with write enabled, needs to be edited down, some settings may be missing (?)

Things we can do:
- change sections like the big headers to make them smaller.
#######################################################################
# +-----------------------------------------------------------------+ #
# |                           WorldConfig                           | #
# +-----------------------------------------------------------------+ #
#######################################################################

*We do still need headers like these to be able to parse read some settings, so they need to be unique.
- Rename settings
- Remove legacy or unimplemented settings
- Add new (1.0.0) settings
- Re-write comments (also add min/max values where relevant, and make sure they're sane)
- Re-order / categorise settings
- Add links to wiki / git pages articles

Things we can't do:
- Change the way existing settings function (unless they're broken)
- Change the syntax of existing settings (unless they're broken)

**Comment by PG85** [comment]
OTG.ini/WorldConfig/BiomeConfig have been re-written. Will still need some tweaking for new resources and settings ofc.
