### ISSUE TITLE
Periodic crash of a game while exploring the world

### ISSUE THREAD

**Issue by FLAPIXCODE** [PG85/OpenTerrainGenerator#408]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [x] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
Forge 14.23.5.2768

#### Server/Client Log
[latest.log](https://github.com/PG85/OpenTerrainGenerator/files/3995607/latest.log)
[crash-2019-12-23_18.12.47-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/3995617/crash-2019-12-23_18.12.47-server.txt)

#### What other plugins are you running?
Biome_Bundle-1.12.2-v6.1.jar

#### Description
Random crash during normal exploration of the world. Sometimes every few minutes, sometimes you need to play for about 30 minutes. I noticed that this happens during the generation of new chunks.

**Comment by PG85** [comment]
Hey @Tolans , thanks for reporting this. This is a known bug that we've not been able to reproduce in a development environment. See #269 ,
