### ISSUE TITLE
Incompatibility with Pam's Portal Poof

### ISSUE THREAD

**Issue by Profilename1** [PG85/OpenTerrainGenerator#409]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [X ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ X] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
Forge 14.23.5.2838

#### What other plugins are you running?
Pam's Portal Poof, 1.12.Xa

#### Description
When you create a nether portal like normal, you can light it and go through to the nether. With PPP installed but OTG removed, the portal is disabled (intended behaviour) but when OTG is installed alongside OTG the portal is enabled again.

**Comment by PG85** [comment]
Hey @Profilename1 , thanks for reporting this. Will need to take a look at this for a future release, atm other things have prio though, so moving to backlog for now.

**Comment by PG85** [comment]
Should hopefully be fixed for v9_r10, portal mechanics have been changed, otg has its own portal block(s) now.
