### ISSUE TITLE
Request - OpenTerrainGenerator for Spigot 1.12.x

### ISSUE THREAD

**Issue by andris155** [PG85/OpenTerrainGenerator#41]

**Comment by Naxdy** [comment]
I second that. A bleeding update/branch that only fixes the imports would be appreciated, in case that's possible.

**Comment by PG85** [comment]
I could do that just like TC did but it would be full of bugs and I'd have to fix those too. Unfortunately I've got my hands full at the moment with 1.10.2 and 1.11.2. Will get to 1.12 as soon as I can.

**Comment by Naxdy** [comment]
Alright. In the meantime I'd like to suggest to everyone who wants a custom world in 1.12, to just pre-generate the necessary chunks in an 1.11 or 1.10 server and then load the world in 1.12 :)

**Comment by Naxdy** [comment]
@andris155 I have created a fork of OTG and made a 1.12 version. I haven't checked forge, but bukkit seems to work fine from what I've seen so far.

**Comment by andris155** [comment]
@xNaXDy Please update 1.12.1. :)

**Comment by Naxdy** [comment]
@andris155 I've updated my OTG fork to 1.12.1 Bukkit (Forge is still 1.12). I haven't gotten round to testing it yet, so proceed with caution!

**Comment by PG85** [comment]
OTG is up to date again and supports Forge and Bukkit 1.12.2 :).
