### ISSUE TITLE
Bug: snow_layer (still) spawning on top of modded non-solid blocks

### ISSUE THREAD

**Issue by dominik-ro** [PG85/OpenTerrainGenerator#411]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge

#### OTG Version
- [x] 1.12.2_v8_r1

#### Forge or Spigot Versions
Forge 14.23.5.2847

#### What ~other~ plugins are you running?
- jei_1.12.2-4.15.0.291.jar
- 'OpenTerrainGenerator-1.12.2 - v8.3.jar'
- 'Vanilla_Vistas 1.1.jar'

and either
- TheCampingMod_2.4.3.jar
  - RikMuldsCore_1.3.3.jar

or
 - pyrotech-1.12.2-1.4.16.jar
   - athenaeum-1.12.2-1.17.4.jar
   - dropt-1.12.2-1.16.1.jar

#### Description
`minecraft:snow_layer` gets generated on top of modded blocks that do not seem solid to me. In my full pack I've observed this behaviour with various blocks when generating custom structures via recurrent complex. For testing purposes I've only used the aforementioned mods, but the issue persists nonetheless. I have tried both Biome Bundle as well as Vanilla Vistas.

##### Pyrotech
![pyrotech](https://user-images.githubusercontent.com/47299286/71737899-4e5c6f80-2e55-11ea-9d5a-dd8d04371b97.png)

##### The Camping Mod
![the_camping_mod](https://user-images.githubusercontent.com/47299286/71738017-9e3b3680-2e55-11ea-8050-c9ebb927d507.png)

The expected outcome is -- of course -- that snow is not generated on top of blocks that are not 'full blocks'. I don't know why only I seem to have this problem. With a mod like pyrotech installed, it is very easy to reproduce on my end by tping to a 'Cold Taiga' biome.

[Here is one of the logs](https://pastebin.com/raw/V9xbyVTR) in case it helps.

**Comment by PG85** [comment]
Hey @dominik-ro , thanks for reporting this. I believe this should already be fixed with the latest version of OTG, are you using 8.3?

**Comment by authvin** [comment]
From the log, it looks like he is using v8.3

**Comment by PG85** [comment]
Right, thanks, looks like the same problem as #362 , this is known to still happen for blocks that are identified as solid blocks by MC. May have to change that to full blocks, though I think it may equate to the same thing. Moving to backlog for now, as we have issues that have more prio. To be moved into a release milestone asap.

**Comment by PG85** [comment]
Will be picking this up for 1.16, not for 1.12.2 (tho if the fix is easy/small, we may backport it). Mod compatibility will be looked at after 1.16.x 1.0.0, moving this to 1.16 backlog for now.

**Comment by PG85** [comment]
We'll be reimplementing snow/freezing for 1.16. If this is still an issue for 1.16, feel free to reopen.
