### ISSUE TITLE
Life in the village | crashing - (Open terrain loader)

### ISSUE THREAD

**Issue by DuckZ69** [PG85/OpenTerrainGenerator#412]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
[The full Spigot Server or Forge versions that you are running]
OptiFine_1.12.2_HD_U_C5
#### Server/Client Log
[The full latest.log file from your server or game client, especially important if you have a stack trace]
  Loaded coremods (and transformers): Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.8-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
                                        pw.prok.realbench.asm.RBTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      LoadingPlugin (BetterWithLib-1.12-1.5.jar)
                                        betterwithmods.library.core.ClassTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      FutureMC (future-mc-0.1.13.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      CharmLoadingPlugin (Charm-1.12.2-1.3.6.jar)
                                        svenhjol.charm.base.CharmClassTransformer
                                      ItemPatchingLoader (ItemPhysic Lite 1.3.7 mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      RandomPatches (randompatches-1.12.2-1.19.1.1.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
                                     - WailaPlugin (Enabled/Not Forced)
  Suspected Mods: Open Terrain Generator (openterraingenerator)
  Profiler Position: N/A (disabled)
  Player Count: 0 / 8; []
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Client Crashes Since Restart: 0
  Integrated Server Crashes Since Restart: 1

#### What other plugins are you running?
[List of your Mods or Plugins installed, ideally with versions]
Modpack : Life in the village
#### Description
[What is happening? - Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures;)] When loaded into my server i will crash within 5 sec to 3 minutes happens faster when i try to load new chunks

[What did you expect to happen? - Explain what you expected to happen after performing the previously described steps] The game freezes for a second and quickly closes

[And Delete the lines in square brackets!]

**Comment by PG85** [comment]
Hey @DuckZ69 , thanks for reporting this. I'll need to see a log file attached before I can say anything about this though :o.

**Comment by PG85** [comment]
Closing this, feel free to reopen or make a new issue if you're still seeing this problem. Please attach the full log, thanks!
