### ISSUE TITLE
Console command "blocks" not working.

### ISSUE THREAD

**Issue by Sakata-MC** [PG85/OpenTerrainGenerator#414]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [ x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [v8.3] Other - specify here

#### Forge or Spigot Versions
[14.23.5.2847]

#### What other plugins are you running?
[Quite a few, irrelevant for issue]

#### Description
[/OTG blocks command doesn't work.  it is listed in help.]

[And Delete the lines in square brackets!] If I do that there won't be a post

**Comment by PG85** [comment]
Hey @Sakata-MC , thanks for reporting this. Will fix for v9.0_r2, moving this into the v9 milestone.

**Comment by PG85** [comment]
Looks like this has been fixed for v9.0_r1 already actually, available on the discord.
