### ISSUE TITLE
OTG crash wouldn't let me enter my world

### ISSUE THREAD

**Issue by Nootcher** [PG85/OpenTerrainGenerator#419]
The OTG mod 1.12.2-v8.3.jar returned me to the Minecraft home screen when trying to enter a world, saying it had crashed. How do I fix this? I was using forge-14.23.5.2847 for 1.12.2. And the other mods I was using with it are in the crash report. Here's the link to the [crash report](https://paste.dimdev.org/xobikawejo.mccrash).

**Comment by PG85** [comment]
Hey @Nootcher , It looks like you're loading the world with different mods than it was created with, the biome registry doesn't point to the correct biomes anymore. If you've added/removed mods that add biomes, that's probably the cause. Please join us on the OTG discord for questions like this, as people can help you faster there, cheers.
