### ISSUE TITLE
Request: Update to Forge 1.12.x

### ISSUE THREAD

**Issue by Dockter** [PG85/OpenTerrainGenerator#42]
Hello,

I've updated a repo of TerrainControl to Forge 1.12:

https://github.com/AlmuraDev/TerrainControl/commits/master

However it lacks the additional optimizations that you've added to OpenTerrainGenerator.  Could you be so kind to grab blood_mc's update to 1.11 and continue on from there?

**Comment by PG85** [comment]
Hey, link isn't working. I'm not sure what you're asking, you'd like me to re-do about 35k edits in your repo?

**Comment by ryantheleach** [comment]
I'm guessing that the link was supposed to link to https://github.com/AlmuraDev/OpenTerrainGenerator/tree/1.11

However, building it at current using ./gradlew build resulted in 

Edit: stay off github at midnight, the fork is incomplete.

```
Z:\OpenTerrainGenerator-1.11\OpenTerrainGenerator-1.11>gradlew build
Found AccessTransformer: openterraingenerator_at.cfg
:common:compileJava UP-TO-DATE
:common:processResources UP-TO-DATE
:common:classes UP-TO-DATE
:common:jar UP-TO-DATE
:common:assemble UP-TO-DATE
:common:compileTestJava UP-TO-DATE
:common:processTestResources UP-TO-DATE
:common:testClasses UP-TO-DATE
:common:test UP-TO-DATE
:common:check UP-TO-DATE
:common:build UP-TO-DATE
:platforms:assemble UP-TO-DATE
:platforms:check UP-TO-DATE
:platforms:build UP-TO-DATE
:releases:assemble UP-TO-DATE
:releases:check UP-TO-DATE
:releases:build UP-TO-DATE
:platforms:bukkit:compileJava UP-TO-DATE
:platforms:bukkit:processResources UP-TO-DATE
:platforms:bukkit:classes UP-TO-DATE
:platforms:bukkit:jar UP-TO-DATE
:platforms:bukkit:assemble UP-TO-DATE
:platforms:bukkit:compileTestJava UP-TO-DATE
:platforms:bukkit:processTestResources UP-TO-DATE
:platforms:bukkit:testClasses UP-TO-DATE
:platforms:bukkit:test UP-TO-DATE
:platforms:bukkit:check UP-TO-DATE
:platforms:bukkit:build UP-TO-DATE
:platforms:forge:deobfCompileDummyTask
:platforms:forge:getVersionJson
:platforms:forge:extractUserdev UP-TO-DATE
:platforms:forge:downloadClient SKIPPED
:platforms:forge:downloadServer SKIPPED
:platforms:forge:splitServerJar SKIPPED
:platforms:forge:mergeJars SKIPPED
:platforms:forge:applyBinaryPatches SKIPPED
:platforms:forge:deobfProvidedDummyTask
:platforms:forge:extractDependencyATs SKIPPED
:platforms:forge:extractMcpData SKIPPED
:platforms:forge:extractMcpMappings SKIPPED
:platforms:forge:genSrgs SKIPPED
:platforms:forge:deobfMcMCP
Applying SpecialSource...
:platforms:forge:deobfMcMCP FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':platforms:forge:deobfMcMCP'.
> java.util.zip.ZipException: duplicate entry: net/minecraft/command/AdvancementCommand$Mode.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by PG85** [comment]
Sorry, no clue what exactly you're trying to do there, have you tried gradlew setupdecompworkspace? and gradlew --refresh-dependencies?

**Comment by ryantheleach** [comment]
turns out I was in error, and I didn't understand this issue, and the fork wasn't as updated as I thought.

**Comment by Dockter** [comment]
This will be getting my attention soon I hope.

**Comment by BakermanLP** [comment]
All 1.12er ports having nearly the same problem. On creating a new world I got the following error / crash:

java.lang.NullPointerException: Exception in server tick loop
        at com.khorn.terraincontrol.forge.ForgeEngine.unRegisterForgeBiome

**Comment by BrainStone** [comment]
What's the status on updating this mod?

**Comment by Dockter** [comment]
@PG85 where does OTG stand with 1.12.x?

**Comment by BrainStone** [comment]
@PG85 ? Any new on an update? I mean 1.13 is comming near.

**Comment by Dockter** [comment]
We have made a TerrainControl branch that is functional with 1.12.  
https://github.com/AlmuraDev/TerrainControl

Bloodmc has also made one that is a slight variation to ours.
https://github.com/bloodmc/TerrainControl

**Comment by PG85** [comment]
OTG is up to date with 1.12.2 now, v3 release with some more bugfixes incoming asap :).
