### ISSUE TITLE
Minecraft says I don't have v8.3 despite having it

### ISSUE THREAD

**Issue by coolkidjpg** [PG85/OpenTerrainGenerator#420]
#### OTG Plugin or Mod
- [x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [x ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
forge-14.23.5.2847

#### Server/Client Log
[latest.log](https://github.com/PG85/OpenTerrainGenerator/files/4101297/latest.log)

#### What other plugins are you running?
Screenshots bc it's a lot and I'm lazy I hope this is okay?
![image](https://user-images.githubusercontent.com/60208809/72957911-52ecb780-3d73-11ea-8890-cba131e644ba.png)
![image](https://user-images.githubusercontent.com/60208809/72957951-7adc1b00-3d73-11ea-8a29-7714627a5109.png)
![image](https://user-images.githubusercontent.com/60208809/72957984-96dfbc80-3d73-11ea-8b03-8135fc8c5713.png)
![image](https://user-images.githubusercontent.com/60208809/72958030-bbd42f80-3d73-11ea-9464-c66bcd48f097.png)
![image](https://user-images.githubusercontent.com/60208809/72958048-d1495980-3d73-11ea-8443-d9a0c1774694.png)

#### Description
When I boot up Minecraft and the mods begin to load, it gives me an error stating 
"You must include the right dependencies for **Open Terrain Generator:**
Requires **OTG Core** 1.12.2 - v8.3 (you have 1.12.2 - v7)".
Despite this error, I do indeed have OTG Core v8.3 installed, I don't even _have_ v7 anywhere as far as I know.
![asddsa](https://user-images.githubusercontent.com/60208809/72958124-25ecd480-3d74-11ea-9473-424940179e5b.PNG)

**Comment by PG85** [comment]
Hey @coolkidjpg , delete OTG-Core.jar from the 1.12.2 folder and it should work fine, cheers.
