### ISSUE TITLE
1.16.x 1.0.0: 6.1 - Java 9+ compatibility

### ISSUE THREAD

**Issue by authvin** [PG85/OpenTerrainGenerator#423]
If possible, should make the mod/plugin compatible with newer versions of Java in the 1.13+ release. Should theoretically be possible to compile with a newer version while keeping 8 as the target version. Gradle needs to be updated to do this.

**Comment by PG85** [comment]
Thanks for the feedback, will definitely take a look at this for 1.13+.

**Comment by jaskarth** [comment]
Should be fixed with 0.0.5 :)
