### ISSUE TITLE
World crashes  for whatever reason

### ISSUE THREAD

**Issue by Silk-Hood** [PG85/OpenTerrainGenerator#426]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x ] Other - 1.12.2_v8.3

#### Forge or Spigot Versions
[1.12.2 ### (modded) forge-14.23.5.2847]
#### Server/Client Log
[https://paste.dimdev.org/yijohulace.mccrash]

#### What other plugins are you running?
![image](https://user-images.githubusercontent.com/60352889/73185151-920c6700-40eb-11ea-9531-9e06c61cfdd9.png)
![image](https://user-images.githubusercontent.com/60352889/73185327-dbf54d00-40eb-11ea-8bf5-20b303bcde77.png)
![image](https://user-images.githubusercontent.com/60352889/73185393-fd563900-40eb-11ea-929d-bf245fb9410d.png)

#### Description
Game crashes when loading a world.
![image](https://user-images.githubusercontent.com/60352889/73185746-9edd8a80-40ec-11ea-919a-e8347fec6924.png)
I had disabled this mod earlier.
![image](https://user-images.githubusercontent.com/60352889/73185998-101d3d80-40ed-11ea-8f09-949ea9c725de.png)
AFter clicking yes, this screen pops up.

**Comment by PG85** [comment]
Hey @Silk-Hood , thanks for reporting this. Will look at this for the next dev version (v9.0_r4), available on the Discord asap.

**Comment by PG85** [comment]
@Silk-Hood Will need more info, what were you trying to do, create a new world or join an existing one?

**Comment by Silk-Hood** [comment]
> @Silk-Hood Will need more info, what were you trying to do, create a new world or join an existing one?

I’ve tried creating and joining an existing world using a world generation mod requiring OTG. It would crash.

**Comment by PG85** [comment]
What's the name of the modpack, can I get it via twitch launcher or do you have a download link?

**Comment by Silk-Hood** [comment]
It’s a custom modpack so I’m not sure how to export it.

**Comment by PG85** [comment]
It should not be possible for this to happen when creating new worlds with v8 and up, so I'm not sure why that doesn't work. For existing worlds this can happen if you added/removed mods that add their own biomes, after creating the world. It looks like a mod you added afterwards is now claiming an id that belonged to OTG when the world was first created.

Can you confirm that this really does happen when creating a new world and if so, could you try removing mods until you have only the mods that cause the problem? Thanks!

**Comment by Silk-Hood** [comment]
> It should not be possible for this to happen when creating new worlds with v8 and up, so I'm not sure why that doesn't work. For existing worlds this can happen if you added/removed mods that add their own biomes, after creating the world. It looks like a mod you added afterwards is now claiming an id that belonged to OTG when the world was first created.
> 
> Can you confirm that this really does happen when creating a new world and if so, could you try removing mods until you have only the mods that cause the problem? Thanks!

I can confirm that v9.0_r4 is working perfectly fine.

**Comment by PG85** [comment]
Great, thanks for reporting :)
