### ISSUE TITLE
Crash on spigot v9 r01

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#427]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [] OTG Mod for Forge
- [X] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]

- [X] 1.12.2 V9.0 R1

#### Forge or Spigot Versions
git-spigot-642f6d2-57ab4cf (MC: 1.12.2) 1.12.2-R0.1-SNAPSHOT

#### Server/Client Log
https://pastebin.com/LHne1upE

#### What other plugins are you running?
FastAsyncWorldEdit, Essentials, Worldedit

#### Description
I tried to startup dregora v1.64 ( https://www.curseforge.com/minecraft/mc-mods/dregora/files/2850247 ) which resulted in this crash.

**Comment by PG85** [comment]
Fixed for 9.0_r4
