### ISSUE TITLE
Bug: Crash when creating new worlds.

### ISSUE THREAD

**Issue by Claycorp** [PG85/OpenTerrainGenerator#43]
https://pastebin.com/Szt0h46M

I had just updated OTG and was trying to find out why menril trees still were not spawning so I disabled Biome Bundle and OTG made two worlds switched them back on and now every world I make crashes with this error.

Any help is appreciated.

**Comment by RikAzerion** [comment]
Thanks for reporting this, looks like you're probably trying to use existing (non-OTG) world data with OTG. You can only use worlds created with OTG. Also, if you load up an OTG-created world without OTG and any new world data is saved there is a chance that the world will be bugged when you re-enable OTG.

**Comment by Claycorp** [comment]
That isn't what I said.
I made two vanilla worlds, turned the mods back on and now every world I create crashes. I know the worlds aren't backwards or forwards compatible. I can't even load new worlds, They never generate.

I deleted the biome bundle folder thinking something happened to it and it still crashes when creating new worlds.

**Comment by Claycorp** [comment]
I found part of the issue.
Disabling the "Prefab" mod fixes this issue. Going to report it over there too.

**Comment by Claycorp** [comment]
Ok, I'm getting quite annoyed at this issue. I have deleted every world, BB file and OTG file I can find. Yet the issue priests. I have attempted to find out more from the other devs and I'm no farther than I was over two weeks ago.

Am I missing something right under my nose? Is there a fix you can do? I've done everything I can think of....

**Comment by PG85** [comment]
So you've deleted the OTG and Biome Bundle jars and cannot create new worlds? Are Biome Bundle and/or OTG listed in the mods menu in the main menu? If they're not there and you still can't make new worlds then it looks like some other mod must be causing it?

**Comment by Claycorp** [comment]
Let me start over, you don't seem to be on the same page.

I had an existing pack I was working on with BB and OTG. Everything was working fine until I went to test why Menril trees weren't spawning. Someone said they spawn for them so I wasn't sure if it was OTG or an Integrated Dynamics issue.
To test this issue I disabled OTG and BB so the pack would start, Made a New world and looked for the trees. I saw them spawning thus I knew it was an issue with OTG or BB. I then re-enabled both mods and attempted to make a new world. That's when it crashed. Now if I try to make new worlds at all it always will crash.

You said it looked like it was trying to use existing data, Thus I deleted every file I could find that had anything to do with OTG or BB so it could be made fresh. This did not solve the problem. Thus I started to disable mods and see if some other mod was causing issues as I just updated them. I found that if I remove Prefab, OTG/BB, or Botania the problem is gone. The Prefab dev said it should have nothing to do with him. I tried with just Prefab, OTG/BB and Botania and they work fine. Just not in the pack I have.

I then waited a while to see if any updates came out to fix it and nothing has, Thus I started an issue on Botania looking for more information about the issue. The info I got wasn't helpful as I already knew what the crashlog said. I then came back here looking for any information that you perhaps never mentioned or I wouldn't know about to fix this. This has nothing to do with vanilla worldgen or reusing worlds. I'm getting close to just giving up as nobody seems to understand what is going on.

**Comment by PG85** [comment]
Hey, sorry for the delay and thanks for the detailed description. If the mod pack + OTG and BB works on a clean install, but then you disable them, generate a world, then reenable them and generate a new world and suddenly things stop working that's very odd. It would suggest that the mods do actually work (since they worked the first time) but that something is somehow different after you've disabled and re-enabled them. That's going to be tricky to track down, can only start by excluding as many possibilities and checking as many assumptions as possible. In this case there don't seem to be a lot of obvious potential causes. Could you check if on a clean install you can create multiple worlds in a row, even with some reboots etc in between? That would at least confirm that the modpack itself works and that the problem really is with disabling/reenabling mods.

**Comment by PG85** [comment]
Update: By the way, for Forge it was not possible to create an OTG,world, delete OTG and load the world, then re-install OTG and enter the world (OTG would crash). This is fixed in the next release (1.10.2 v22 / 1.11.2 v7, should be this week).

**Comment by Claycorp** [comment]
Sorry I haven't gotten back to you yet, Was feeling sick the last two days. 

Anyway, Currently I'm just working on it without prefab as I have a deadline of the 8th to have this server up. The pack will not work with a fresh install unless I let the mods generate new configs but then it seems to work fine. At this point nobody is going to want to revert everything I've done and start trying mod by mod as its ~6 months worth of dev time. I don't even remember everything I changed anymore. 

I think at this point its best to just ignore it and continue on without prefab as the error is such an obscure issue. I don't think we will ever find it.

**Comment by PG85** [comment]
Okay then, thanks for reporting this :).
