### ISSUE TITLE
Relinquary Lily Pads and Vanilla Lily pads

### ISSUE THREAD

**Issue by blacksythe** [PG85/OpenTerrainGenerator#431]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [ ] OTG Mod for Forge

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] OpenTerrainGenerator-1.12.2+-+v8.3.jar

#### Forge or Spigot Versions
forge-1.12.2-14.23.5.2847-universal.jar

#### Server/Client Log
[crash-2020-02-05_16.45.56-client.txt](https://github.com/PG85/OpenTerrainGenerator/files/4161548/crash-2020-02-05_16.45.56-client.txt)
[crash-2020-02-05_16.45.09-client.txt](https://github.com/PG85/OpenTerrainGenerator/files/4161552/crash-2020-02-05_16.45.09-client.txt)
[crash-2020-02-05_16.44.16-client.txt](https://github.com/PG85/OpenTerrainGenerator/files/4161553/crash-2020-02-05_16.44.16-client.txt)
[crash-2020-02-05_16.41.00-client.txt](https://github.com/PG85/OpenTerrainGenerator/files/4161554/crash-2020-02-05_16.41.00-client.txt)

#### What other plugins are you running?
Beyond the skies mod pack. https://www.curseforge.com/minecraft/modpacks/beyond-the-skies 
Random Tweaks
Random Patch's
Worldedit forge
Fast Asyncronous World edit

#### Description
Issue occurs when placing lily pads 
Issue occurs when playing reliquenary lily pads
OTG is running on client side only

[What did you expect to happen? - Explain what you expected to happen after performing the previously described steps]

[Can you provide a Minimal, Reproducible Example? See here for details: https://stackoverflow.com/help/minimal-reproducible-example]

[And Delete the lines in square brackets!]

**Comment by PG85** [comment]
Hey @blacksythe , thanks for reporting this. Could you try removing mods to see which minimal combination of mods exactly causes the issue? Also, could you try using OTG v9.0_r6, available on the Discord (otg-dev-releases channel). Be sure to delete OTG-Core.jar from the 1.12.2 folder when updating. Thanks!

**Comment by blacksythe** [comment]
Will do my suspects are reliquery

Ok so you can probably close this as it works fine on single player and the server in question no longer has otg installed. So it is likely related to having otg installed on a client and a server not having it.

**Comment by PG85** [comment]
Allright, thanks for reporting back, glad you could figure it out :).
