### ISSUE TITLE
OpenTerrainGenerator Skylands Bug

### ISSUE THREAD

**Issue by OutOffSkill** [PG85/OpenTerrainGenerator#434]
I created a world with the Skylands OpenTerrainGenerator. But instead of void at height 0 there is Bedrock and I dont know how to change it into Air or Void.

**Comment by authvin** [comment]
You want to go to the Skylands worldconfig (found in mods/Openterraingenerator/worlds/Skylands) and make sure DisableBedrock is set to true

**Comment by OutOffSkill** [comment]
it is set to true. Thats why I dont know whats wrong.
