### ISSUE TITLE
Feature: NotBorderNear whitelist/blacklist

### ISSUE THREAD

**Issue by inkdear** [PG85/OpenTerrainGenerator#435]
#### Is your feature request related to a problem? Please describe.
Sometimes you want a border biome for a specific situation, but to prevent it from spawning in tons of undesired locations you have to write out huge numbers of biome names in the NotBorderNear section, excluding just 3-4 biomes you DO want it to spawn next to, and requiring you to continually add subsequently-created biomes to these 'special case' border biome configs.

#### Describe the solution you'd like
It would be nice if there were a setting to make NotBorderNear a whitelist instead of a blacklist for a specific biome.

#### Description aka Additional context
Apologies if there's already some way to do this that I haven't uncovered.

**Comment by PG85** [comment]
Hey @inkdear , sounds like a good idea, will have to put this in the backlog for now though. Feature development will be minimal until development for 1.15.2 is done.

**Comment by PG85** [comment]
For 1.16.5-0.0.15 (to be released on the discord a.s.a.p.), OnlyBorderNear: (whitelist) was added, when used NotBorderNear is ignored. It is now also possible to assign multiple biome borders of the same size to the same biome. OnlyBordernear/NotBorderNear can be used to force a specific border to spawn.
