### ISSUE TITLE
massive pits to bedrock under water

### ISSUE THREAD

**Issue by Genovvaa** [PG85/OpenTerrainGenerator#437]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [ x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x ] Other - 1.12.2_V8.3

#### Forge or Spigot Versions
Forge 14.23.5.2824
#### What other plugins are you running?
Biome Bundle V6.1

#### Description
created a new random world for other mod bug testing purposes, got 100+ block tall mountains with sheer cliffs to bedrock that consume chunks and floating islands

create new world with biome bundle with seed -7978087414004472511, look underwater.

![2020-02-12_19 21 48](https://user-images.githubusercontent.com/60989445/74389940-ccedea80-4dcd-11ea-8528-44a0393fc56d.png)
![2020-02-12_19 21 29](https://user-images.githubusercontent.com/60989445/74389948-cfe8db00-4dcd-11ea-9130-656857ebee0f.png)
![2020-02-12_19 21 24](https://user-images.githubusercontent.com/60989445/74389954-d24b3500-4dcd-11ea-8f6f-8fd7c9d1027a.png)

**Comment by PG85** [comment]
Hey @Genovvaa , thanks for reporting this, but I suspect it has something to do with your configs, could you ask for help on the OTG discord first? @MCPitman, the creator of Biome Bundle is there too. Putting this to support for now, if you can confirm that this is a bug, let me know, otherwise I'll close this issue if it remains inactive. Thanks!

**Comment by Genovvaa** [comment]
MCPitman says this is normal so ill be closing this issue.
