### ISSUE TITLE
Error when creating an map or exploring the map 

### ISSUE THREAD

**Issue by AlexNova1555** [PG85/OpenTerrainGenerator#439]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [ ] OTG Mod for Forge
- [X ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ X] 1.12.2_-_v9.0_r6

#### Forge or Spigot Versions
[This server is running CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT]

#### What other plugins are you running?
[https://prnt.sc/r2qc1i]

#### Description
[After upgrading to version v9.0_r6 i got error when loading my chunk or creating a new map version v9.0_r5 works fine to me! here is error https://pastebin.com/UjcxCHiE and full server startup log https://pastebin.com/f1rNKDPu]

**Comment by PG85** [comment]
Hey @AlexNova1555 , which preset are you using? It looks like customstructures are not configured correctly, so they spawn in unloaded chunks, which loads the chunks and spawns more customstructures. You can prevent this by setting PopulationBoundsCheck:true in the WorldConfig.ini, but you'll get cut off structures.

**Comment by PG85** [comment]
Feel free to reopen this if the problem continues.
