### ISSUE TITLE
how to make otg reads the biomes on the existed map files 

### ISSUE THREAD

**Issue by TRLWeiss** [PG85/OpenTerrainGenerator#440]
#### Is your feature request related to a problem? Please describe.
 I'm always frustrated when i want to use a map created by worldpainter,which means there are sevreal biomes waiting otg to generate trees,ores,and etc.But in fact,when otg opens a map(I copied the regions to a current OTG files),it just generate trees and ores using its seeds.

#### Describe the solution you'd like
hope there are a config files which can manage options whether read a existed worldpainter map or not.If this option is set to true,the OTG will follow the biomes contained in the map file to generate trees and buildings.

**Comment by PG85** [comment]
Hey @3094300238 , please join us on the OTG Discord for questions like this. as there are more people who can help you there. I don't personally use WorldPainter, but users like NLBlackEagle do. Thanks!
