### ISSUE TITLE
Error (after a long time on the world)

### ISSUE THREAD

**Issue by uiytt** [PG85/OpenTerrainGenerator#444]
#### OTG Plugin or Mod
- [X] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [X] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading 
Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_231, running on Linux:amd64:5.4.14-mtxserv, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre 

#### Server/Client Log
https://pastebin.com/S9XupK4C

#### What other plugins are you running?
https://pastebin.com/h5kFzDSX

#### Description
So everything worked fine for more than 3 month but at some time while exploring at more than 20 000 blocks, the server crashed and I have the same error every time I reload the server.
(P.S : I was in v6 but when I got this error I tried to update in v8, the problem is still the same)

**Comment by PG85** [comment]
Hey @uiytt , it appears that the StructureData.txt file in saves/world save folder/OpenTerrainGenerator/ has been corrupted. I'm not sure how this could have happened, perhaps the server crashed while the file was being saved. If you're not using BO4's (you most likely aren't, most presets like BB don't), you may be able to just delete the file, or create a new world and copy its StructureData.txt to your broken world.

*Each dimension has its own StructureData.txt, make sure you delete/replace the right one.

If you need help with more things like this, please join us on the OTG Discord. If you've found a technical error you're sure is a bug, feel free to open a new git issue and provide logs+repro steps, thanks!
