### ISSUE TITLE
Putting < in the world name causes a crash

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#447]
Looks like OTG allows characters for the world name which cannot be used in windows folder names which causes CTD on world creation.

**Comment by pezzy28** [comment]
Normally, Minecraft will substitute invalid symbols with an underscore in the file name to prevent this crash. OTG does not do this, causing the crash.

**Comment by PG85** [comment]
For v9.0_r8, only "^[\(\)a-zA-Z0-9 _-]+$" are allowed, continue button is unavailable until name complies.
