### ISSUE TITLE
Mobs wont spawn on Spigot versions ( V9 R7 )

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#451]
#### OTG Plugin or Mod
- [ ] OTG Mod for Forge
- [X] OTG Plugin for Spigot

#### OTG Version
- [X] 1.12.2_v9_r7

#### Forge or Spigot Versions
git-paper-1618 (MC 1.12.2)

#### What other plugins are you running?
Essentials 2.0.1-b483
Dregora V1.65 Biome+ [Part1]

#### Description
Neither hostile or passive mobs are spawning.

This issue can be reproduced with at least Dregora V1.65 Biome+ [Part1] but is likely to happen to any preset with OTG v9 R7 installed.

The characteristics of the issues are that neither of the following settings & commands work:
( This is the same for every biome )

- ReplaceToBiomeName: minecraft:jungle
- InheritMobsBiomeName: minecraft:plains

Commands:

/otg biome -m
/otg biome -d
/otg entities

From my own findings I think that everything works as it is supposed to work but some forge implementation for OTG caused a blockade making it so the spigot spawn mechs do not work.

Here's a link to the dregora download: https://www.curseforge.com/minecraft/mc-mods/dregora/files/2910777

**Comment by MCPitman** [comment]
Here's a quick test world with one biome that is not virtual and has InheritMobsBiomeName: minecraft:forest and I can confirm no mobs spawn on Spigot.


[MobsTest.zip](https://github.com/PG85/OpenTerrainGenerator/files/4389570/MobsTest.zip)

**Comment by PG85** [comment]
Hey @NLBlackEagle , thanks for reporting this. Will fix this for v9_r10.

**Comment by authvin** [comment]
Should be fixed with https://github.com/PG85/OpenTerrainGenerator/pull/496

**Comment by PG85** [comment]
Will be included for v9_r10, thanks @authvin !
