### ISSUE TITLE
OTG portals get created deeper than those quotes that 14 year olds think they make

### ISSUE THREAD

**Issue by Fnige** [PG85/OpenTerrainGenerator#453]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - 1.12.2 v8.3

#### Forge or Spigot Versions
14.23.5.2847

#### What other plugins are you running?
FTB Builders Paradise 1.6.0
Decocraft 2.6.3 (PTRLib 1.0.4)
Extra Utilities 2 1.9.9
Born in a barn v1.8-1.1
AI improvements 0.0.1b3
Vanilla fix 1.0.10-SNAPSHOT
FPS reducer 1.14.1

#### Description
Getting into an OTG portal creates and teleports you into a portal close to y=0. (Note: don’t know the exact specifics but it is possible to also spawn deep below the surface when coming back too, maybe via teleporting directly to that dimension) 

Make a portal (maybe having a y of 92 will help), go through it

Well I expected to have the portal on the surface, not one deeper than Kola Superdeep Borehole (40,230ft deep)

**Comment by PG85** [comment]
Hey @SlimyPython , this should hopefully be fixed for v9. Please try the latest dev version from the OTG Discord at https://discord.gg/UXzdVTH. If the problem still occurs, feel free to reopen this issue, thanks!
