### ISSUE TITLE
Spawn structure error when trying to create exported chest

### ISSUE THREAD

**Issue by Telun1** [PG85/OpenTerrainGenerator#455]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - OpenTerrainGenerator-1.12.2_-_v9.0_r7

#### Forge or Spigot Versions
Forge 1.12.2-forge 1.12.2-14.23.5.2847

#### What other plugins are you running?
Biome_Bundle-1.12.2-v6.1
jei_1.12.2-4.15.0.268
Traveler'sDream-Compact-1.12.2-v1.1
worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist

#### Description
Exporting a chest with contents using the "/otg export <name> -t" command, then trying to place the chest again results in an "Unexpected error" from OTG and cancels the generation from that point on. Using the exported NBT data for other working structures like those in Biome Bundle will yield the same result. I believe the exported NBT data is somehow wrong.

Normal generation of the chest with loot.

**Comment by Jishuna** [comment]
Can you provide the NBT file and possibly the object for testing?

**Comment by Telun1** [comment]
Here you go, hope it helps.

[Testor.zip](https://github.com/PG85/OpenTerrainGenerator/files/4400021/Testor.zip)

**Comment by Telun1** [comment]
Also ConsoleLog for the export function.

[ConsoleLog.txt](https://github.com/PG85/OpenTerrainGenerator/files/4400075/ConsoleLog.txt)

**Comment by PG85** [comment]
Thanks for the feedback! Should be fixed by @Coll1234567  for v9.0_r10 :). To be released on the OTG discord at https://discord.gg/UXzdVTH asap.
