### ISSUE TITLE
Crash Report in Engineers Life

### ISSUE THREAD

**Issue by ghost** [PG85/OpenTerrainGenerator#457]
#### OTG Plugin or Mod
- [x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [x ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
forge-14.23.5.2847
#### Server/Client Log
VanillaFix: https://paste.dimdev.org/ojiwosigig.mccrash

#### What other plugins are you running?
EngineersLife EL 1.8

#### Description
Minecraft Crashes Upon first generating, VanillaFix catches it

**Comment by MCPitman** [comment]
My guess is you have some non-standard characters in your world name

**Comment by PG85** [comment]
Hey guys, thanks for the feedback and sorry for the late reply. Unfortunately I can't open the link, feel free to reopen this issue if you find it's a technical problem/bug, thanks!
