### ISSUE TITLE
Crash on Roguelike Adventures and Dungeons, i can't load the world

### ISSUE THREAD

**Issue by leRanger7** [PG85/OpenTerrainGenerator#459]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- 1.12.2 (can't say more sorry)

#### Forge or Spigot Versions
[Forge : 14.23.2838]

#### Server/Client Log
[https://paste.dimdev.org/avacayonaj.mccrash
i retried : https://paste.dimdev.org/uzifobuxun.mccrash]

#### What other plugins are you running?
[playing on roguelike adventures and dungeons, no change from the original]

#### Description
[I can't load my world (already created), the last time the issue happened, i just created another world]

[i expected to be able to play xD]

 I hope this time you'll have enough information because i don't have more :)

**Comment by PG85** [comment]
Hey @leRanger7 , thanks for the feedback. I'm sorry for the late reply, the links to your logs don't work anymore. I hope you've been able to find an answer by now on the OTG Discord at https://discord.gg/UXzdVTH. Be sure to try the latest dev version of OTG if you're having a technical issue. Feel free to reopen this ticket if you've found a bug.
