### ISSUE TITLE
Request: Worldpacker for own worlds

### ISSUE THREAD

**Issue by BakermanLP** [PG85/OpenTerrainGenerator#46]
Hello there,

I wanted to ask, if it is possible to get the Worldpacker as source or anything like that. I saw the OTG-Flatlands and the other packages as a single jar file. That would be nice, that the download of modpacks will be dramatically increased by only downloading one file instead of 1000+ files. Also a version system will be possible with that

Thanks for reading

Michael (aka BakermanLP)

**Comment by RikAzerion** [comment]
Hey BakermanLP, yeah, good one. This has been on the to-do list for a while, will upload the worldpacker project to git soon, if you know how to download and import a project then making your own worldpacker jar takes only a few steps.

**Comment by BakermanLP** [comment]
I have extracted all the files of the existing ones. But in one jar file there is the name of the Pack and therefore the "Source" would be nice.
Thanks in advance.

**Comment by PG85** [comment]
Hey, sorry for the wait, WorldPacker is up at: https://github.com/PG85/WorldPacker
