### ISSUE TITLE
Villages + Bo4s

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#462]
![2020-04-08_01 24 23](https://user-images.githubusercontent.com/9453952/78731475-c300e780-7937-11ea-9de0-039a621519cd.png)

**Comment by PG85** [comment]
"A picture says more than a thousand turds". Hmkay will take a quick look at village placement/detection for r10.

**Comment by PG85** [comment]
BO4's are no longer allowed to spawn within a 4 chunk radius of villages/rare buildings/mansions/oceanmonuments etc for v9_r11. Underground structures like mineshafts and strongholds are excluded. If other mods add structures that are larger than vanilla's, may have to configure a different radius per mod.
