### ISSUE TITLE
Error: OTG tried to load a world that is missing OTG information.

### ISSUE THREAD

**Issue by mistythecat** [PG85/OpenTerrainGenerator#463]
[crash-2020-04-13_01.02.53-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/4467423/crash-2020-04-13_01.02.53-server.txt)
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [x] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
[The full Spigot Server or Forge versions that you are running]

#### Server/Client Log
[The full latest.log file from your server or game client, especially important if you have a stack trace]

#### What other plugins are you running?
[List of your Mods or Plugins installed, ideally with versions]

#### Description
[What is happening? - Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures;)]

[What did you expect to happen? - Explain what you expected to happen after performing the previously described steps]

[Can you provide a Minimal, Reproducible Example? See here for details: https://stackoverflow.com/help/minimal-reproducible-example]

[And Delete the lines in square brackets!]

**Comment by mistythecat** [comment]
plezz help

**Comment by PG85** [comment]
Hey @mistythecat , have you asked on Discord for support? It looks like you're trying to use an incompatible world save as an otg world, so I'm not sure what you're trying to do. Sorry for the late reply, I hope you've found an answer on the OTG Discord by now (https://discord.gg/UXzdVTH). Please try solving your problem with the help of the people there, they can respond to you quickly. If you find that this is a technical problem or bug, feel free to reopen this issue.
