### ISSUE TITLE
Changing to Creative mode on new world should automatically enable cheats

### ISSUE THREAD

**Issue by aaronhowser1** [PG85/OpenTerrainGenerator#464]
#### Is your feature request related to a problem? Please describe.
In vanilla, cheats are automatically enabled when you make a new world in Creative. It should be the same with OTG

#### Describe the solution you'd like
New creative worlds should have cheats enabled by default

**Comment by PG85** [comment]
Hey @aaronhowser1 , thanks for the feedback. Will see if I can include this for 1.12.2 v9.0_r10.

**Comment by PG85** [comment]
Will be in 1.12.2 v9.0_r10, available on the disc asap.
