### ISSUE TITLE
OTG with BOP causes a crash.

### ISSUE THREAD

**Issue by MagmaSlime123** [PG85/OpenTerrainGenerator#467]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [X] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [X] Other - specify here
Latest Dev release within #otg-dev-releases on Discord.

#### Forge or Spigot Versions
[crash-2020-04-30_22.50.49-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/4562665/crash-2020-04-30_22.50.49-server.txt)

#### What other plugins are you running?
Listed within the crash report.

#### Description
Entering any world causes a crash.

[What did you expect to happen? - Explain what you expected to happen after performing the previously described steps]
Entering fine.

**Comment by MCPitman** [comment]
I just tested OTG, Biome Bundle and BoP and started a world with no issues.

**Comment by MagmaSlime123** [comment]
You had this same issue, lol.

**Comment by PG85** [comment]
Have not been able to reproduce this issue with only OTG/BB/Bop. I see many other mods listed in the logs, please try to remove mods to see which exact combination is causing the issue, thanks!
