### ISSUE TITLE
Bug: SpawnHeightOffset not working with Tree()

### ISSUE THREAD

**Issue by Culvanen** [PG85/OpenTerrainGenerator#47]
Hi,

SpawnHeightOffset in .bo3 file not working.

I using 1.11.2 of OTG

![sans titre 1](https://user-images.githubusercontent.com/12481447/28517599-2e4d5dcc-7065-11e7-998a-5a7f859c1d34.png)

Thanks for your working

**Comment by Culvanen** [comment]
i pray for resolve in next version

**Comment by PG85** [comment]
This will be fixed for the next release (should be this week).

**Comment by Culvanen** [comment]
Thanks guys !
