### ISSUE TITLE
Crash: Client crashes while attempting to use the minecolonies mod on servers.

### ISSUE THREAD

**Issue by BlueYoshi68** [PG85/OpenTerrainGenerator#472]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge

#### OTG Version
- [x] Other -1.12.2+-+v8.3

#### Forge or Spigot Versions
forge-1.12.2-14.23.5.2847-installer

#### Server/Client Log
https://paste.dimdev.org/suyakezayi.mccrash

#### What other plugins are you running?
See mod list in paste bin.

#### Description
When trying to use the mine colonies mod and attempting to build a building using the structurize tool, the client crashes but this only happens on servers for some reason, not in singleplayer.

**Comment by PG85** [comment]
Hey @BlueYoshi68 , link won't work for me unfortunately. Will need to test with minecolonies, putting this in the backlog for now.

**Comment by PG85** [comment]
Won't be picking this up as we're focusing on 1.16, thanks for resporting.
