### ISSUE TITLE
Game crash with core when OTG is disabled

### ISSUE THREAD

**Issue by tyler489** [PG85/OpenTerrainGenerator#473]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [X] Other - specify here
Unknown
#### Forge or Spigot Versions
Unknown
#### Server/Client Log
Unknown
#### What other plugins are you running?
Unknown

#### Description
Received an issue on enderio's git tracker. After discussing with the devs we decided that i should probably forward it to you. Im not sure about the above info but it should be irrelevent.

OTG has an embeded core jar that extracts on run correct?
It seems that if OTG is disabled the core will remain and run however the game will crash because this line https://github.com/PG85/OpenTerrainGenerator/blob/174ed59b36bff94765a9853d36a91e5f356456ea/platforms/forge/src/main/java/com/pg85/otg/forge/events/dimensions/BlockTracker.java#L16
refers to OTG config. This could be most like solved by making OTG core have a hard dependency on OTG itself. 

Crash report can be found 
https://pastebin.com/LMHByhJH

and original issue can be found on enderio's issue tracker 
https://github.com/SleepyTrousers/EnderIO/issues/5377

**Comment by PG85** [comment]
Hey @tyler489 , this has been fixed for newer versions of OTG, please try v8 from curse or v9 from the OTG Discord at https://discord.gg/UXzdVTH. Thanks!
