### ISSUE TITLE
Crash - OTG World Generator

### ISSUE THREAD

**Issue by RodrigoTaipe93** [PG85/OpenTerrainGenerator#475]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
[14.23.5.2854]

#### Server/Client Log

Latest Log: https://mega.nz/file/JhEgDIaS#LGhufvnyAYwromvsXraeRn5m9jELvj1Ddv0kAqYSPrw

Crash #1: https://paste.ee/p/JkVFE

Crash#2: https://paste.ee/p/D3MHh

#### What other plugins are you running?

- See latest log

#### Description

Game crashes when you reach a certain biomes.

The name is in the picture (Extreme Hills +)

- https://imgur.com/5LXDyOR

Just go there and the game crashes. The coordinates are in the picture.

**Comment by RodrigoTaipe93** [comment]
Ok! So I tried to narrow down as much as I can how to replicate the issue. Just install the following mods:

- Biome Colorizer

- Journey Map (just so you can teleport quickly there)

- Traveler's Dream

- OTG

Basically, try to travel around the biome, at a certain point, the game will shut down and it will give you this crash log:

- https://paste.ee/p/liQP4

- https://paste.ee/p/uwvBo

The coordinates are in the link with the picture in IMGUR

**Comment by Darsenia** [comment]
Issue confirmed.The answer found,that's a preset issue,will  be fixed.

**Comment by PG85** [comment]
Awesone, thanks for reporting @RodrigoTaipe93  and thanks for helping @Darsenia  :).
