### ISSUE TITLE
OTG GUI button doesn't work

### ISSUE THREAD

**Issue by aaronhowser1** [PG85/OpenTerrainGenerator#477]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [X] Other - 1.12.2 - v8.3

#### Forge or Spigot Versions
14.23.5.2847

#### What other plugins are you running?
https://pastebin.com/ZNEivhzs

#### Description
The OTG Hud key was unbound, so I set it to O (which is not taken by another control). When I press O, nothing happens. Nothing pops up, nothing goes into chat, nothing is in the log, nothing. Changing the key to something else also does nothing.

**Comment by Jishuna** [comment]
You need to be OP/have cheats enabled. We should probably add a message if you aren’t able to open the menu.

**Comment by aaronhowser1** [comment]
Ah, I assumed making a world in creative mode also enabled cheats, like it does in vanilla. I already logged that in #464, but I completely forgot about it.

**Comment by PG85** [comment]
Thanks for reporting will close as duplicate.
