### ISSUE TITLE
OTG doesnt work server side (Roguelike Adventures & Dragons 1.12.2) 

### ISSUE THREAD

**Issue by Dsaha1420** [PG85/OpenTerrainGenerator#478]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [x] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
[The full Spigot Server or Forge versions that you are running]
releast forge-14.23.5.2838
#### Server/Client Log
[The full latest.log file from your server or game client, especially important if you have a stack trace] 
https://drive.google.com/file/d/1YNGIOdPhnMXC13LcR_77Z3XFTThwm5VY/view?usp=sharing (crash report)
#### What other plugins are you running?
[List of your Mods or Plugins installed, ideally with versions]
 Roguelike adventures and dungeons 1.38 modpack

#### Description
[What is happening? - Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures;)]
I cannot use my single player worlds for my server because it seems like OTG crashes server side.  
at com.pg85.otg.forge.OTGWorldType.getBiomeProvider(OTGWorldType.java:70)
    at com.pg85.otg.forge.dimensions.WorldProviderOTG.init(WorldProviderOTG.java:87)

[What did you expect to happen? - Explain what you expected to happen after performing the previously described steps]
I expected to just be able to use single-player worlds as server worlds. That was not the case
[Can you provide a Minimal, Reproducible Example? See here for details: https://stackoverflow.com/help/minimal-reproducible-example]

[And Delete the lines in square brackets!]

**Comment by PG85** [comment]
Hey @Dsaha1420 , this has been fixed for newer versions of OTG. Please try v8 from curse or v9 from the OTG Discord at https://discord.gg/UXzdVTH. Thanks!
