### ISSUE TITLE
Yung's caverns in ocean biomes have walls on chunk borders

### ISSUE THREAD

**Issue by mxnmnm** [PG85/OpenTerrainGenerator#479]
#### OTG Mod
Forge

#### OTG Version
1.12.2_v8.3

#### Forge Version
14.23.5.2847

#### What other mods are you running?
I will only post them if it's directly related to the issue so for reference this happens with yung's better caves version 2.0.3

#### Description
Everything you need is here https://github.com/yungnickyoung/YUNGs-Better-Caves/issues/53

tl;dr- flooded caves are broken when used with otg

**Comment by PG85** [comment]
Hey @mxnmnm , thanks for reporting this, have responded on Yung's git issue.

**Comment by mxnmnm** [comment]
It's all fixed now :D

**Comment by PG85** [comment]
Sweet, thanks for the feedback! :)
