### ISSUE TITLE
OTG Crashes at or around world startup with custom mob spawner, need help with compatibility

### ISSUE THREAD

**Issue by SpencerMeow** [PG85/OpenTerrainGenerator#481]
I'm trying to use OTG (Biome Bundle) with Mo' Creatures as well as a few dungeon mods I already tried disabling, and at random when moving after making the world, it just crashes and says "Shutting down internal server" and in the VanillaFix report, the cause is unknown and you're unable to get a link, so I'll just put the file here.
[crash-2020-06-07_16.50.51-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/4743078/crash-2020-06-07_16.50.51-server.txt)

Please help me find a way to use Mo Creatures with this I've been trying for hours...

**Comment by BiomeBundle** [comment]
I don't see OTG mentioned in the log, not sure this is an OTG problem.

**Comment by mxnmnm** [comment]
Pretty sure mo creatures doesn't even need custom mob spawner, plus it's known for being super buggy. If you have trouble with mob spawns after removing custom mob spawner, just use incontrol to adjust mob spawns.

**Comment by PG85** [comment]
Hey @SpencerMeow , unfortunately CustomMobSpawner is known to cause problems with OTG. You should be able to use mo creatures without it, although I'm not sure all features will work. Thanks for reporting!
