### ISSUE TITLE
Snow layers spawn on ice/packed ice when temperature is low

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#482]
OTG places snow layers on ice and packed ice when the temperature is low.

Snow layers shouldn't be able to spawn on ice or packed ice, breaking a single one currently causes a chain reaction of them disappearing across all adjacent surfaces.

**Comment by PG85** [comment]
Should be fixed for 1.12.2 v9.0_r9, available on the OTG discord.
