### ISSUE TITLE
Instant crash when I try to open Singleplayer menu (the menu that has a list of worlds)

### ISSUE THREAD

**Issue by aaronhowser1** [PG85/OpenTerrainGenerator#485]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - OpenTerrainGenerator-1.12.2 - v8.3

#### Forge or Spigot Versions
14.23.5.2847

#### Server/Client Log
[latest.log](https://github.com/PG85/OpenTerrainGenerator/files/4809959/latest.log)

#### What other plugins are you running?
AdvancedRocketry-1.12.2-1.7.0-225-universal.jar                       
AkashicTome-1.2-12.jar                                                
AppleSkin-mc1.12-1.0.9.jar                                            
appliedenergistics2-rv6-stable-7.jar                                  
AutoRegLib-1.3-32.jar                                                 
Avaritia-1.12.2-3.3.0.33-universal.jar                                
base-1.12.2-3.13.0.jar                                                
Baubles-1.12-1.5.2.jar                                                
bdlib-1.14.3.12-mc1.12.2.jar                                          
BetterAdvancements-1.12.2-0.1.0.77.jar                                
BetterFps-1.4.8.jar                                                   
BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar                         
Biome_Bundle-1.12.2-v6.1.jar                                          
Biome_Bundle_O_Plenty-1.12.2_v1.0.jar                                 
BloodMagic-1.12.2-2.4.3-105.jar                                       
Bookshelf-1.12.2-2.3.590.jar                                          
Botania r1.10-363.jar                                                 
BuildingGadgets-2.8.3.jar                                             
Chameleon-1.12-4.1.3.jar                                              
Charm-1.12.2-1.3.7.jar                                                
Chisel-MC1.12.2-1.0.2.45.jar                                          
chiselsandbits-14.33.jar                                              
CodeChickenLib-1.12.2-3.2.3.358-universal.jar                         
CoFHCore-1.12.2-4.6.6.1-universal.jar                                 
CoFHWorld-1.12.2-1.4.0.1-universal.jar                                
CommonCapabilities-1.12.2-2.4.6.jar                                   
CompactDrawers-1.12.2-1.0.5.125.jar                                   
ContentTweaker-1.12.2-4.9.1.jar                                       
Controlling-3.0.9.jar                                                 
CraftPresence-1.12.2-1.6.1.jar                                        
CraftTweaker2-1.12-4.1.20.574.jar                                     
CTM-MC1.12.2-1.0.2.31.jar                                             
Cucumber-1.12.2-1.1.3.jar                                             
CyclopsCore-1.12.2-1.6.4.jar                                          
DefaultOptions_1.12.2-9.2.8.jar                                       
diethopper-1.1.jar                                                    
DynamicSurroundings-1.12.2-3.6.1.0.jar                                
EnderCore-1.12.2-0.5.76.jar                                           
EnderIO-1.12.2-5.1.55.jar                                             
EnderIO-endergy-1.12.2-5.1.55.jar                                     
EnderStorage-1.12.2-2.4.6.137-universal.jar                           
environmentaltech-1.12.2-2.0.20.1.jar                                 
extrautils2-1.12-1.9.9.jar                                            
FancyBlockParticles-1.12.x-2.4.1.jar                                  
FastFurnace-1.12.2-1.3.1.jar                                          
FastWorkbench-1.12.2-1.7.3.jar                                        
foamfix-0.10.10-1.12.2.jar                                            
forestry_1.12.2-5.8.2.387.jar                                         
Forgelin-1.8.4.jar                                                    
ForgeMultipart-1.12.2-2.6.2.83-universal.jar                          
framedcompactdrawers-1.2.6.jar                                        
FTBBackups-1.1.0.1.jar                                                
FTBLib-5.4.7.0.jar                                                    
FTBQuests-1.8.1.239.jar                                               
FTBUltimine-1.12-1.3.2.jar                                            
FTBUtilities-5.4.0.124.jar                                            
GameStages-1.12.2-2.0.123.jar                                         
gendustry-1.6.5.8-mc1.12.2.jar                                        
gendustryjei-1.0.2.jar                                                
Guide-API-1.12-2.1.8-63.jar                                           
ImmersiveEngineering-0.12-98.jar                                      
immersivepetroleum-1.12.2-1.1.9.jar                                   
industrialcraft-2-2.8.220-ex112.jar                                   
IntegratedCrafting-1.12.2-1.0.9.jar                                   
IntegratedDynamics-1.12.2-1.1.6.jar                                   
IntegratedTerminals-1.12.2-1.0.13.jar                                 
IntegratedTunnels-1.12.2-1.6.11.jar                                   
InventoryTweaks-1.63.jar                                              
ItemFilters-1.0.3.12.jar                                              
jeibees-0.9.0.5-mc1.12.2.jar                                          
jei_1.12.2-4.15.0.291.jar                                             
jetif-1.12.2-1.5.1.jar                                                
journeymap-1.12.2-5.7.1.jar                                           
JustEnoughResources-1.12.2-0.9.2.60.jar                               
KubeJS-forge-1.12.2-1.1.0.63.jar                                      
letsencryptcraft-1.10.2-1.2.0.jar                                     
LibVulpes-1.12.2-0.4.2-75-universal.jar                               
llibrary-1.7.19-1.12.2.jar                                            
logisticspipes-0.10.3.39.jar                                          
MagicBees-1.12.2-3.1.10.jar                                           
mcjtylib-1.12-3.5.4.jar                                               
Mekanism-1.12.2-9.8.3.390.jar                                         
MekanismGenerators-1.12.2-9.8.3.390.jar                               
MekanismTools-1.12.2-9.8.3.390.jar                                    
minetogether-1.10.2-2.2.5.jar                                         
modnametooltip_1.12.2-1.10.1.jar                                      
moreoverlays-1.15.1-mc1.12.2.jar                                      
MouseTweaks-2.10-mc1.12.2.jar                                         
MrTJPCore-1.12.2-2.1.4.43-universal.jar                               
mysticallib-1.12.2-1.7.0.jar                                          
mysticalworld-1.12.2-1.8.4.jar                                        
NaturesCompass-1.12.2-1.8.5.jar                                       
NetherPortalFix_1.12.1-5.3.17.jar                                     
NuclearCraft-2o.2.7-1.12.2.jar                                        
OpenTerrainGenerator-1.12.2 - v8.3.jar                                
OreLib-1.12.2-3.6.0.1.jar                                             
Patchouli-1.0-20.jar                                                  
phosphor-1.12.2-0.2.6+build50-universal.jar                           
Placebo-1.12.2-1.6.0.jar                                              
pneumaticcraft-repressurized-1.12.2-0.11.15-398.jar                   
prefab-1.3.0.26.jar                                                   
ProjectRed-1.12.2-4.9.4.120-Base.jar                                  
ProjectRed-1.12.2-4.9.4.120-integration.jar                           
ProjectRed-1.12.2-4.9.4.120-lighting.jar                              
Quark-r1.6-179.jar                                                    
QuarkOddities-1.12.2.jar                                              
QuickLeafDecay-MC1.12.1-1.2.4.jar                                     
rats-3.2.12-1.12.2.jar                                                
RebornCore-1.12.2-3.19.4.529-universal.jar                            
RecipeStages-1.1.3.jar                                                
RedstoneFlux-1.12-2.1.1.1-universal.jar                               
ResourceLoader-MC1.12.1-1.5.3.jar                                     
ResourceReloader-1.0.2.5.jar                                          
rftools-1.12-7.73.jar                                                 
rftoolsdim-1.12-5.71.jar                                              
Simple-Void-World-1.12-1.2.0.9-universal.jar                          
simpletrophies-1.2.2.1.jar                                            
SmoothFont-mc1.12.2-2.1.2.jar                                         
StorageDrawers-1.12.2-5.4.2.jar                                       
Thaumcraft-1.12.2-6.1.BETA26.jar                                      
ThaumicInventoryScanning_1.12.2-2.0.10.jar                            
ThaumicJEI-1.12.2-1.6.0-27.jar                                        
theoneprobe-1.12-1.4.28.jar                                           
ThermalFoundation-1.12.2-2.6.7.1-universal.jar                        
TipTheScales-1.12.2-1.0.4.jar                                         
TombManyGraves-1.12-4.2.0.jar                                         
topaddons-1.12.2-1.13.0.jar                                           
UniDict-1.12.2-2.9.6.jar                                              
unloader-1.2.0.jar                                                    
valkyrielib-1.12.2-2.0.20.1.jar                                       
VanillaFix-1.0.10-150.jar                                             
Vanilla_Vistas 1.1.jar                                                
WanionLib-1.12.2-2.4.jar                                              
xnet-1.12-1.8.2.jar                                                   
zerocore-1.12.2-0.1.2.8.jar                                           

#### Description
![](https://cdn.discordapp.com/attachments/307111022257373185/724319068924018779/unknown.png)
When I click "Singleplayer" here, it crashes.
![](https://cdn.discordapp.com/attachments/307111022257373185/724320254808817734/unknown.png)
Weird first line in crash report

Renaming `saves` to `saves-` fixes it. Looks like its a specific world causing the crash, and renaming its `OpenTerrainGenerator` folder fixes it.
Here is the folder from the world, in case you need it.
[OpenTerrainGenerator.zip](https://github.com/PG85/OpenTerrainGenerator/files/4809974/OpenTerrainGenerator.zip)

**Comment by authvin** [comment]
Related to this issue: https://github.com/PG85/OpenTerrainGenerator/issues/445

**Comment by PG85** [comment]
Hey @aaronhowser1 , looks like some of the .txt files were corrupted, presumably because of a crash or abnormal exit during saving. 

For OTG 1.12.2 v0.0_r10 I've made OTG rename existing txt/yaml files to xxx-backup before writing new files. If during loading a file is corrupted, it'll try to load the backup file. When reading/writing fails, OTG logs an error telling the user how to manually fix the problem (where possible). r10 will be available on the OTG discord a.s.a.p.

For help fixing your existing world, please ask on the OTG Discord. You should be able to create a new world with the same setup and copy the files to your old world (BiomeId's.txt, Config.yaml, DImensions.txt, WorldSave.txt).
