### ISSUE TITLE
Crash from OTG.

### ISSUE THREAD

**Issue by MagmaSlime123** [PG85/OpenTerrainGenerator#491]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [ X] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ X] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
Forge 14.23.5.2854.

#### What other plugins are you running?
Crash report has what you need.

#### Description
Create a world and join it.

[What did you expect to happen? - Explain what you expected to happen after performing the previously described steps]
My game not crashing.

[Can you provide a Minimal, Reproducible Example? See here for details: https://stackoverflow.com/help/minimal-reproducible-example]
Read what's above.
[crash-2020-07-05_14.28.52-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/4875701/crash-2020-07-05_14.28.52-server.txt)
I'm only seeing stuff related to OTG in this, so I'm not sure if this is being caused by other mods.

**Comment by authvin** [comment]
This error means OTG failed to load a biome from one of the biome groups. Have you been editing presets? If not, deleting the preset and letting it re-extract from the worldpacker should fix it

**Comment by MagmaSlime123** [comment]
I'll try removing the OTG folder.
I have never touched anything related to OTG's biomes.

**Comment by authvin** [comment]
I'm guessing you're using a preconfigured modpack?

**Comment by MagmaSlime123** [comment]
A pack of my own. Regenerating the folder somehow fixed it. Not sure if something currupted or not... Might've did.
