### ISSUE TITLE
OTG crash , excepction generating new chunks

### ISSUE THREAD

**Issue by ecr99** [PG85/OpenTerrainGenerator#497]
I need help , whenever i try to play on a OTG world , after a few minutes of walking around new chunks the game crashes.

Heres the crash log: 

[crash-2020-07-20_11.40.06-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/4949002/crash-2020-07-20_11.40.06-server.txt)

Thank you , have a nice day

**Comment by PG85** [comment]
Hey @ecr99 , this looks like a mod compatibility problem. Please try and remove mods to find the specific mods that are causing the problem, then I can take a look. Feel free to reopen this issue if you find which mods are causing the problem. Also try the latest dev builds on the OTG discord, you can also ask any modpack related questions there. Thanks!
