### ISSUE TITLE
Request: Config goes to config folder MC-1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [PG85/OpenTerrainGenerator#5]
So why is the config folder generating in the mods folder? 
![6](https://cloud.githubusercontent.com/assets/10351221/25315872/1d807b5e-2822-11e7-9411-479b0ed9a552.PNG)
![7](https://cloud.githubusercontent.com/assets/10351221/25315873/1d825b7c-2822-11e7-8111-a54ef78d23ac.PNG)

**Comment by P3rf3ctXZer0** [comment]
Config files almost exclusively go to configs ... its not supposed to be with jars its a bad practice. The other option is the root directory located here 
![8](https://cloud.githubusercontent.com/assets/10351221/25315905/aefc8b40-2822-11e7-8c77-031be8e01e5b.PNG)

**Comment by BakermanLP** [comment]
In the old days of TerrainControl as a bukkit plugin this was the folder. Thats only the history of that. In my opinion the folder also should go to the config folder.

**Comment by PG85** [comment]
Hey, thanks for the feedback. For terraincontrol this was necessary to make things work with certain launchers, also users had been used to placing their stuff in the mods folder for years. Now that we've re-branded to OTG this doesn't make sense anymore though and we can now move it into configs. Will do this for the next major release (working on bugs atm).

**Comment by BakermanLP** [comment]
Thank you.

PG85 <notifications@github.com> schrieb am Do., 27. Apr. 2017, 14:28:

**Comment by PG85** [comment]
Hey BakermanLP, 

Sorry! This decision has been vetoed, so we won't be moving the files after all and keeping it as it is atm to avoid confusion.
