### ISSUE TITLE
Biome could not be registered, no free biome id's!

### ISSUE THREAD

**Issue by chouuul** [PG85/OpenTerrainGenerator#500]
[crash-2020-07-24_12.09.23-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/4971456/crash-2020-07-24_12.09.23-server.txt)
Hello ! 
I just have on my server this error with the last version of OTG / Biome Bundle and Biome Bundle O Plenty...

I tried Just enough Id and Not enough Id but it doesn't works, you're my last hope

**Comment by PG85** [comment]
Hey @chouuul , unfortunately there's a limited amount of biome id's available, so you cannot create an infinite amount of dimensions using an infinite amount of biomes. Just enough id's / not enough id's unfortunately won't fix this. Please join us on the OTG Discord at https://discord.gg/UXzdVTH for questions about worlds/dimensions setup and combining presets/mods.

*Some older versions of OTG would allow you to create dimensions even when not enough biome id's are available, this causes a crash when restarting the server with this log message. Newer versions of OTG warn if there aren't enough biome id's and won't let you add the dimension(s). I'm not exactly sure what happened in your case, but you may have to remove one of your OTG dimensions. Like i said, please join us on the discord for these kinds of questions, if you find a technical error, feel free to open an issue on the git, closing this for now.
