### ISSUE TITLE
The biome Cold Plains tried to inherit mobs from itself.

### ISSUE THREAD

**Issue by jbjornberg** [PG85/OpenTerrainGenerator#501]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - OpenTerrainGenerator-1.12.2+-+v8.3

#### Forge or Spigot Versions
OpenTerrainGenerator-1.12.2+-+v8.3

#### Server/Client Log
https://pastebin.com/HSGUbxyJ

#### What other plugins are you running?
Thaumcraft
Chunk Pregenerator

#### Description
- Used Pregenerator Mod to generate a Biomes Bundle OTG World.
- Uninstalled OTG & Pregenerator after I was done using them. (It's a world with a world-border, so I didn't need OTG anymore. 
- Decided I wanted to create a new Dregora Dimension, re-added OTG & Chunk-Pregenerator 
- Thaumcraft Conflicted with OTG

Simple
- Had OTG, removed it.
- Added Thaumcraft
- Re-added OTG.

Things I have tried:
Removing Thaumcraft and re-adding OTG. (Doesn't break, but breaks as soon as Thaumcraft is re-added)
Adding the older version of OTG I had used at the time. (Breaks again.)

**Comment by BiomeBundle** [comment]
The title isnt related to the problem?

You have an ID conflict because it's not possible to add mods that add biome IDs to an existing OTG world. Your options are to remove thaumcraft or start a new world.
