### ISSUE TITLE
All worlds are saved as WorldSave version 6

### ISSUE THREAD

**Issue by authvin** [PG85/OpenTerrainGenerator#504]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge
- [x] OTG Plugin for Spigot

#### OTG Version
- [x] v9 dev builds

#### What other plugins are you running?
None necessary

#### Description
When a world is created in v9, its world save version is set to 6 instead of 8, meaning it gets treated as a legacy world and has its CustomBiomes section parsed and loaded

I expected the world to be saved as world save version 8

Every preset I've tested has done this. That's dregora, biome bundle, planets, far from home, traveler's dream, and my own. This also happens in both Forge SP, Forge MP, and Spigot.

**Comment by PG85** [comment]
should be fixed for 1.12.2 v9_r10
