### ISSUE TITLE
Please help!! OTG Plugin crashing my Forge server.

### ISSUE THREAD

**Issue by xinkalta** [PG85/OpenTerrainGenerator#506]
#### OTG Plugin or Mod
- [x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ x] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
1.12.2-forge-14.23.5.2854

#### Server/Client Log
https://pastebin.com/Eh1aXChg

#### What other plugins are you running?
[List of your Mods or Plugins installed, ideally with versions]

#### Description
When I start up the server using a run.bat file it will run and stop with this crash.

**Comment by Jishuna** [comment]
Have you tried replicating the issue on OTG v8

**Comment by xinkalta** [comment]
> Have you tried replicating the issue on OTG v8

yes i did. it still caused the same issue :(

**Comment by PG85** [comment]
Hey xinkalta, one of the .txt files in your world save's /OpenTerrainGenerator/ folder has been corrupted, likely the server crashed while writing to it. You can try deleting StructureData.txt and NullChunks.txt, this may lead to some structures being cut off in your world. If you have backups, you can try using an old StructureData.txt or NullChunks.txt.

For v9 i've recently added an auto-backup and restore feature to prevent this problem, a dev version is available on the OTG Discord, v9 will be released asap.
