### ISSUE TITLE
Bug: OTG dedicated server no zawa spawns

### ISSUE THREAD

**Issue by Ezoteric** [PG85/OpenTerrainGenerator#507]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x] Other - v9 - latest from discord

#### Forge or Spigot Versions
[The full Spigot Server or Forge versions that you are running]
forge-1.12.2-14.23.5.2847-universal.jar

#### What other plugins are you running?
[List of your Mods or Plugins installed, ideally with versions]
![otgpack](https://user-images.githubusercontent.com/14137626/90312478-134f0e00-df05-11ea-9123-a61eac7be5df.png)

#### Description
[What is happening? - Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures;)]
Zawa doesnt spawn animals in server, it works on SP without any problems its pure server related

**Comment by authvin** [comment]
Did some testing. Zawa mobs are indeed added to spawn lists in singleplayer but not multiplayer. Tested in Biome Bundle, the Mesa Plateau biome. The SP world had a long list of creatures, the server only had vanilla.

**Comment by authvin** [comment]
Did the same test rundown with Mo' Creatures, which did not have this issue. I also looked at the code and couldn't find any places where OTG should treat this differently for SP and MP. This is likely an issue with ZAWA adding mobs to spawn lists for non-vanilla overworlds. Could be a configuration issue possibly, will poke around

**Comment by authvin** [comment]
Can confirm it only happens with OTG overworlds. With BB as a dimension, the mobs spawn as normal.

**Comment by Ezoteric** [comment]
Hmmz when i add BB as dimension i still have no spawns.
Checked with /otg biome -m also :(

Tho i used BBOP as overworld

**Comment by authvin** [comment]
make sure you set "ZAWA overworld only spawns" to false in the config

**Comment by Ezoteric** [comment]
Tried both to be even sure :)

**Comment by Ezoteric** [comment]
Ok ZAWA works the first time you enter a other dimension and when you restart the server its back to no spawns again.

**Comment by willbattel** [comment]
I'm experiencing this as well, it seems that we're getting no ZAWA spawns in a Biome Bundle overworld- but are getting them in other dimensions as well as the BB overworld on singleplayer. Any ideas?

**Comment by BiomeBundle** [comment]
@willbattel as mentioned earlier in the thread, this is not an issue with OTG. 

OTG uses biome dictionary tags as normal and other mob mods work completely fine, the ZAWA devs did not even properly read the issue before closing and marking as 'offtopic - wontfix'.

**Comment by PG85** [comment]
Just to be sure, can you guys test some things for me?

- For MP OTG Overworld, apart from zawa, do the biome mob spawn settings work properly, does /otg biome -m report the correct values for all creature types in the lists? And with other mods' (mocreatures) mobs?
- Does /otg biome -d report the correct biome dictionary tags?
- Do /otg biome and /otg biome -s report the correct biome id's?
- If as @Ezoteric says the spawns stop working on server restart for dims, do /otg biome -d/-m/-s still report the correct values?

**Comment by Ezoteric** [comment]
If you make a new dim with O go to it zawa works and shows up in the -m after reset no spawns and also the -m shows no more zawa mobs. 
Any other mod that adds mobs have no problems whatsoever at least the ones i checked all work expect zawa

havent checked the -d -s yet tho

**Comment by PG85** [comment]
Allright, that sort of makes sense, it sounds like any biomes registered during a session work (creating a dim via the O menu registers biomes), but any biomes registered at world creation / world load on server start don't work. So it's not so much an overworld/dim thing, i suspect it's the same problem for overworld and dims on server restart.

Need to know then if /otg biome -m/-s/-d reports any other differences on server reboot. If everything reports the same except only zawa mobs missing, then would expect that to be a zawa issue. Would be curious to know if this also affects other mob mods.

**Comment by Ezoteric** [comment]
Zawa for sure :P shame they think its not but meh :)

**Comment by PG85** [comment]
If the above assumptions are correct, then a likely explanation is that when OTG inherits the mob spawn settings for its biomes at world creation / world load on server start, the zawa mobs aren't in the vanilla biomes' mob spawn lists. When a user creates an OTG dimension during a session, OTG registers biomes, the zawa mobs are in the vanilla biomes' mob spawn lists and are inherited.

So the problem would be the exact moment when zawa adds its mobs to the vanilla biomes' mob spawn lists. It does it too late for OTG to pick up at server start, apparently (either that or OTG indexes biomes too early, which would be odd).

**Comment by PG85** [comment]
Won't be picking this up for 1.12.2 as we're focusing on 1.16, thanks for reporting.
