### ISSUE TITLE
Feature: 128 height worlds for Forge dimensions

### ISSUE THREAD

**Issue by PG85** [PG85/OpenTerrainGenerator#54]
For Forge dimensions add an option to create a 128 height worlds for nether/end/underground dimensions.

**Comment by SamGunGraven** [comment]
It would be cool if you could create a 255 Nether - there is a Spigot plugin that does that called TallNether (https://www.spigotmc.org/resources/tallnether.22561/) and the The Beneath also used 256 high generation. However, MC said it was going to create performance problems with OTG.

**Comment by PG85** [comment]
Yeah there's a a good reason that Mojang made the Nether only 128 tall. Unfortunately MC gets really laggy the taller the world is, so you can have a few mountains in an overworld but MC just cannot handle an entire world with height 256 filled with blocks (like an underground world).

**Comment by SamGunGraven** [comment]
Yeah, but TallNether and The Beneath have no performance problems

**Comment by PG85** [comment]
TallNether is for Spigot, lag should be less of a problem there. The Beneath I'll have to try, if it's spawning 256 height worlds filled with blocks though then it's likely using some kind of shortcut or workaround.

We've done tests with all kinds of dimensions and worlds, for cave dimensions we found that even if the dimension is fully generated, so no worldgen is going on, and all you do is enter the world then it's very laggy. It even happens when OTG isn't installed and you enter the world.

**Comment by SamGunGraven** [comment]
OK, I chatted with the creator of NetherEx and he also abandoned the tall nether after doing experiments with it. Of course, my 4.2 ghz watercooled rig that can easily go to 5ghz won't have too much trouble :-)

**Comment by PG85** [comment]
Lol haha yeah, that'll do it!

**Comment by PG85** [comment]
For 1.17(?), we're expecting changes to world height anyway, will see if we can make it fully configurable.
