### ISSUE TITLE
otg biome -m/-d neither working.

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#541]
#### OTG Plugin or Mod
- [X] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x] 1.12.2_v9 R10

#### Forge or Spigot Versions
![afbeelding](https://user-images.githubusercontent.com/4073584/92805307-4926cb80-f3b9-11ea-9101-add9d7a3eb27.png)

#### What other plugins are you running?
![afbeelding](https://user-images.githubusercontent.com/4073584/92805357-5643ba80-f3b9-11ea-970b-f6aa0ed21dc2.png)

#### Description
/otg biome -m & /otg biome -d do not show in help menu or work the way they should work. Instead they display the biome ID & name.

**Comment by authvin** [comment]
-m should already be fixed in r11, should check with that version

**Comment by NLBlackEagle** [comment]
Thanks for the info! i totally missed R11, I will be able to confirm this tomorrow 👍 ( If it's already confirmed feel free to close this one up :) )

**Comment by PG85** [comment]
biome -m should work now, biome -d won't be implemented for spigot as biome dictionary tags are a Forge feature. Feel free to reopen this if biome -m doesnt work (it really should tho :o).
