### ISSUE TITLE
Bug: 1.12.2 Flickering fog 

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#542]
#### OTG Plugin or Mod
- [X] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [X] 1.12.2_v9_r11

#### Forge or Spigot Versions
forge-14.23.5.2854

#### Description
Whenever the ViewDistance is set beyond 16 the fog starts flickering on player movement. The higher you set the viewdistance the more it can be noticed as seen in the following gif:

https://gyazo.com/dea962663e8fe21ade9c10be7bae3f78

Here's a testworld:

[DregoraTestMod.zip](https://github.com/PG85/OpenTerrainGenerator/files/5213401/DregoraTestMod.zip)

**Comment by PG85** [comment]
Thanks for reporting this, will definitely keep an eye out for this for 1.16.5, for 1.12.2 we won't be fixing this, unless someone does a PR.
