### ISSUE TITLE
Passenger tag for Entity() with .txt extension does not work among other issues encountered.

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#543]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [X] OTG Plugin for Spigot

#### OTG Version
- [X] 1.12.2_v9_r11

#### Forge or Spigot Versions
![afbeelding](https://user-images.githubusercontent.com/4073584/93024052-9aba9a80-f5f3-11ea-8c9b-de11eb2d8667.png)

#### Description
The passenger tag does not get passed to OTG through the .txt attached to the mob resulting in the mount to spawn but not it's rider. Other then that the entity spawns just fine. Also if the same command is used as /summon in a command block it works. This issue goes for all mounted mobs such as spider jockeys, skeleton traps and so on.

Within this .zip you'll find a white_howl bo3 and a NBT folder in which the .txt for the wolf can be found.
[EntityBo3.zip](https://github.com/PG85/OpenTerrainGenerator/files/5214693/EntityBo3.zip)

Thanks for talking a look! I tried determining in what version this broke but was not successful in finding this. I'd love to see this fixed before the final release!

**Comment by NLBlackEagle** [comment]
Here is a pack containing 47 EntityTags for debugging use, took me a while to grab em all together.
[EntityTagswithBo3s.zip](https://github.com/PG85/OpenTerrainGenerator/files/5235445/EntityTagswithBo3s.zip)

And here is the spawnlist for each tag:

`/otg spawn CatType
/otg spawn creeperboom
/otg spawn creeperFuseTime
/otg spawn creeperignited
/otg spawn DogAngry
/otg spawn DogColarColor
/otg spawn DogOwner
/otg spawn DogSittting
/otg spawn DonkeyChested
/otg spawn DonkeyTamed
/otg spawn DonkeyTemper
/otg spawn GhastBoomPower
/otg spawn LLamaChestStrength
/otg spawn LLamaSaddleDecor
/otg spawn LLamaType
/otg spawn PiggySaddle
/otg spawn PigmanAngry
/otg spawn RabbitType
/otg spawn randomprof
/otg spawn randomprofBaby
/otg spawn randomprofBreakDoor
/otg spawn randomprofConversionTime
/otg spawn randomprofDamage
/otg spawn randomprofDisAI
/otg spawn randomprofFireProof
/otg spawn randomprofFly
/otg spawn randomprofFollowRange
/otg spawn randomprofglow
/otg spawn randomprofGravy
/otg spawn randomprofInvulnerable
/otg spawn randomprofKnockback
/otg spawn randomprofLefty
/otg spawn randomprofLooty
/otg spawn randomprofPersistent
/otg spawn randomprofReinforcement
/otg spawn randomprofRiding
/otg spawn randomprofSilent
/otg spawn randomprofSpeedy
/otg spawn randomprofTag
/otg spawn randomprofTeam
/otg spawn SheepyColor
/otg spawn ShulkerColor
/otg spawn SkeletonRidden
/otg spawn skeletonTrap
/otg spawn SlimeSize
/otg spawn VillagerProfession
/otg spawn VindicatorJohnny
`

**Comment by NLBlackEagle** [comment]
I've also found that OTG still uses the old Entity format for the mushroom cows which is "MushroomCow"

This should be: "mooshroom"

**Comment by authvin** [comment]
Fixed as of https://github.com/PG85/OpenTerrainGenerator/pull/549

Also, it now accepts both "mooshroom" and "mushroomcow" for both platforms

**Comment by NLBlackEagle** [comment]
Thanks for the awesome last minute work on this!!!! Issue Fixed & Closed
