### ISSUE TITLE
Ghost immages

### ISSUE THREAD

**Issue by KingCajun** [PG85/OpenTerrainGenerator#545]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x] 1.12.2_v8_r1

#### Forge or Spigot Versions
[The full Spigot Server or Forge versions that you are running]

#### What other plugins are you running?
[List of your Mods or Plugins installed, ideally with versions]
Traveler's Dream
#### Description
[What is happening? - Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures;)]
Getting ghost images as I look around. Like shadows, but only edges and faint.
[What did you expect to happen? - Explain what you expected to happen after performing the previously described steps]

[Can you provide a Minimal, Reproducible Example? See here for details: https://stackoverflow.com/help/minimal-reproducible-example]

[And Delete the lines in square brackets!]

**Comment by authvin** [comment]
Is your installation haunted? Sorry, but I'm having trouble understanding what you mean by ghost images. Some pictures would be nice

**Comment by KingCajun** [comment]
It's like seeing shadows, but you only see the edges. They float around as you look around, they don't stay still. I've not had this with BOP. I even tried it without Traveler's, and still does the same.Sent via the Samsung Galaxy S8, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: authvin <notifications@github.com> Date: 9/14/20  12:02 PM  (GMT-05:00) To: PG85/OpenTerrainGenerator <OpenTerrainGenerator@noreply.github.com> Cc: KingCajun <twhite.fbc@gmail.com>, Author <author@noreply.github.com> Subject: Re: [PG85/OpenTerrainGenerator] Ghost immages (#545) 
Is your installation haunted? Sorry, but I'm having trouble understanding what you mean by ghost images. Some pictures would be nice

**Comment by PG85** [comment]
Unfortunately cannot reproduce this, feel free to reopen if this issue still occurs for the latest version of OTG for 1.12.2.
