### ISSUE TITLE
OTG mob spawning conflict 

### ISSUE THREAD

**Issue by disastercube** [PG85/OpenTerrainGenerator#555]
OTG 1.12.2 v8.3 MOD

1.12.2-forge1.12.2-14.23.5.2847

https://github.com/BobMowzie/MowziesMobs/issues/269#issuecomment-706636893

**Comment by authvin** [comment]
As mentioned in the linked issue, this was fixed for v9 already, in https://github.com/PG85/OpenTerrainGenerator/commit/044e3e49f56a9fc91fb60cc3089594337249969c

**Comment by disastercube** [comment]
Is v9 still in development?

**Comment by authvin** [comment]
Yes. You can get development builds in the OTG discord

**Comment by PG85** [comment]
Thanks for responding! If the you're still seeing this problem with v9, feel free to reopen this issue.
