### ISSUE TITLE
OTG Pregen

### ISSUE THREAD

**Issue by Noahleon000** [PG85/OpenTerrainGenerator#556]
Hi i started a world and decided to pregen but accidently made the pregen area way to large how do i stop pregenning? (this is singleplayer)

**Comment by authvin** [comment]
Set it to a lower number in the O menu

**Comment by Noahleon000** [comment]
Sorry for the inconvenience but how do i ask the menu?

**Comment by authvin** [comment]
If you have cheats enabled, you should be able to open the OTG GUI by pressing "o". You'll find the field to set pregen radius there

**Comment by Noahleon000** [comment]
This doesn't seem to work when i press o my OTG version is v7 nothing happens sorry for the further inconvenience btw I'm in a modpack but doubt that would change anything.

**Comment by Jishuna** [comment]
If you don't have cheats enabled you will have to open the world to LAN and enable cheats that way.

**Comment by authvin** [comment]
Ah, you need v8 for the GUI. For older versions, use "/otg pregen" to set the radius lower

**Comment by Noahleon000** [comment]
Tysm this had been bothering me for ages.

**Comment by PG85** [comment]
Thanks for helping @authvin, closing this issue.
