### ISSUE TITLE
1.16.x 1.0.0: 5.1 - Advanced console commands

### ISSUE THREAD

**Issue by PG85** [PG85/OpenTerrainGenerator#566]
Implement missing console commands (if they're still needed):

- /otg biome (-s, -d, -f)
- /otg biome -m
- /otg biomes
- /otg lookup
- /otg exportbo4data
- /otg blocks
- /otg entities
- /otg particles
- /otg structure
- /otg export
- /otg spawn

Make a separate ticket when working on individual commands.

**Comment by authvin** [comment]
/otg data should replace the need for biomes, blocks, entities, particles

Still to-do:
- [ ] /otg biome
- [ ]  /otg lookup
- [ ] /otg exportbo4data
- [ ] /otg structure
- [x] /otg export
- [x] /otg spawn

The wiki has a list of commands for 1.12.2: https://github.com/PG85/OpenTerrainGenerator/wiki/GUI-and-Commands

**Comment by PG85** [comment]
/otg spawn works for bo4's as well now, should be done. Otg export has  a separate issue.
