### ISSUE TITLE
Request - OpenTerrainGenerator for Spigot 1.12.1

### ISSUE THREAD

**Issue by andris155** [PG85/OpenTerrainGenerator#57]

**Comment by PG85** [comment]
Same as https://github.com/PG85/OpenTerrainGenerator/issues/41. 1.12 support is high on the to-do list atm, will get to it soon but can't give an ETA yet. Thanks for your interest.

**Comment by Naxdy** [comment]
@andris155 I've updated my OTG fork to 1.12.1 (Bukkit only). I haven't gotten round to testing it yet though, so proceed with caution.

**Comment by andris155** [comment]
Thanks @xNaXDy
