### ISSUE TITLE
1.16.x 1.0.0: 5.1 - New Datapack Biome Settings

### ISSUE THREAD

**Issue by authvin** [PG85/OpenTerrainGenerator#570]
Implement settings found in datapack biomes which don't exist in old OTG configs
Reference: [https://minecraft.gamepedia.com/Custom_world_generation/biome](url)
This doesn't cover features in the datapack biomes which OTG already have from before in some form

- [x] **category**, _string_ : The type of biome, unknown usage. Assumed similar to forge biome dict tags, except only allows one value.
- [x] **grass_color_modifier**, _string_ : allows "none", "dark_forest", or "swamp"
- [x] **particle** : particles in the air of a biome
- [x] **ambient_sound**, _string_ : ambient sound to use in a biome
- [x] **mood_sound** : think cave sounds
- [x] **additions_sound** : smound that has a certain chance to play in the biome, used in basalt deltas
- [x] **music** : specify music that's played in the biome, as seen in the new nether biomes
- [ ] **player_spawn_friendly**, _boolean_ : if true, this biome is more likely to be picked for a spawn location
- [ ] **creature_spawn_probability**, _float_ : Between 0 and 1, higher value means more passive mobs can spawn
- [ ] **spawn_costs**, _list_ : New mob spawn setting?

**Comment by PG85** [comment]
Awesome tx!

category is an enum with the following options:
      NONE("none"),
      TAIGA("taiga"),
      EXTREME_HILLS("extreme_hills"),
      JUNGLE("jungle"),
      MESA("mesa"),
      PLAINS("plains"),
      SAVANNA("savanna"),
      ICY("icy"),
      THEEND("the_end"),
      BEACH("beach"),
      FOREST("forest"),
      OCEAN("ocean"),
      DESERT("desert"),
      RIVER("river"),
      SWAMP("swamp"),
      MUSHROOM("mushroom"),
      NETHER("nether");
Not sure what they're used for atm or if we can add our own somehow.

For music and sounds, how would you add your own custom files?

**Comment by PG85** [comment]
There's also some new "features", do we need to add anything new to our biome configs to achieve the same results (also taking into account all the customisation options for these new features)?

- RAW_GENERATION. Used by miniature end island features by default.
- LAKES. Used by water and lava lakes by default.
- LOCAL_MODIFICATIONS. Used for rocks in taigas and icebergs by default.
- UNDERGROUND_STRUCTURES. Used for dungeons and overworld fossils by default.
- SURFACE_STRUCTURES. Used for desert wells and blue ice patches by default.
- STRONGHOLDS. Not used for any features by default.
- UNDERGROUND_ORES. Used for overworld ore veins, overworld dirt/gravel/stone variant patches, and sand/gravel/clay disks by default.
- UNDERGROUND_DECORATION. Used for infested block veins, nether gravel and blackstone veins, and all nether ore veins by default.
- VEGETAL_DECORATION. Used for trees, bamboo, cacti, kelp, and other ground and ocean vegetation, as well as lava and water springs by default.
- TOP_LAYER_MODIFICATION. Used for surface freezing by default.

**Comment by authvin** [comment]
Music and sounds can be added through resource packs, at least. Can also specify vanilla sounds, of course.

**Comment by jaskarth** [comment]
A quick list of all the new resource generators we're going to need:
* Coral
* Kelp
* Seagrass
* Icebergs (*shudders*)
* Bamboo

Nether generators (lower priority, but nice-to-haves):
* Huge fungus
* Weeping vines
* Twisting vines
* Deltas
* Basalt Columns
* Replace blobs
* Basalt pillars
* No surface ore (netherite ore)

1.17 stuff, lowest priority:
* Geodes

**Comment by PG85** [comment]
For Coral/Kelp/Seagrass, can we use the existing UnderWaterPlant resource?
For Bamboo, fungus etc, can we use Plant?

**Comment by PG85** [comment]
For biome resources, see #575 
For default structures, see #576

**Comment by PG85** [comment]
Comparing biomeconfigs to  datapacks, I think we've implemented most of the useful features now. WIll look again at datapack integration later (OTG+Datapacks), wil use a separate issue.
