### ISSUE TITLE
Sky land - sand fall

### ISSUE THREAD

**Issue by Neoowiz** [PG85/OpenTerrainGenerator#572]
- [x] OTG Mod for Forge
- [x] 1.12.2_v9

Hello I am having problems creating {skylands}. The fact is that there is no sand beneath the sandstones, which leads to the fact that entire islands fall into the void. The server cannot sustain every such event; in the case of / pre-generation /, the load will grow to a critical point. Do you know how to add / replace bottom block or disable sand physics?

**Comment by PG85** [comment]
Fixed for 1.12.2 v9.2, a dev version will be available on the OTG discord asap.
