### ISSUE TITLE
The game crashed whilst exception in server tick loop Error: java.lang.ClassCastException: com.pg85.otg.forge.generator.structure.OTGVillageGen

### ISSUE THREAD

**Issue by Alvariun** [PG85/OpenTerrainGenerator#573]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]

- OTG Mod for Forge

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]

- 1.12.2-v9.0

#### Forge or Spigot Versions
forge-14.23.5.2854

#### Server/Client Log
[The full latest.log file from your server or game client, especially important if you have a stack trace]
https://pastebin.com/uauaCKp6

#### What other plugins are you running?
[List of your Mods or Plugins installed, ideally with versions]

#### Description
[What is happening? - Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures;)]

When I tried to create a world I stopped responding to the game and then it crashed. I also tried to enter a server that I have with my same mods and everything. before putting the otg I entered as if nothing but now I disconnected and did not enter

**Comment by Alvariun** [comment]
Sorry my bad english

**Comment by PG85** [comment]
It looks like one of your mods that affects villages doesn't work with OTG's villages. Due to a limitation, OTG's villages do not inherit from MapGenVillage, but rather MapGenStructure. We can't change this atm, so the other mod would have to do a check before trying to cast to MapGenVillage. Please join us on the discord at https://discord.gg/UXzdVTH for any questions about mod compatibility.

**Comment by Alvariun** [comment]
> Parece que una de tus modificaciones que afecta a las aldeas no funciona con las aldeas de OTG. Debido a una limitación, las aldeas de OTG no heredan de MapGenVillage, sino de MapGenStructure. No podemos cambiar este cajero automático, por lo que el otro mod tendría que hacer una verificación antes de intentar lanzar a MapGenVillage. Únase a nosotros en la discordia en https://discord.gg/UXzdVTH si tiene alguna pregunta sobre la compatibilidad de mod.

ok thanks a lot for the help <3

**Comment by PG85** [comment]
You can also disable OTG villages via the WorldConfig.ini file (in mods/OpenTerrainGenerator/worlds/<preset name>/WorldConfig.ini

VillagesEnabled: false

And then let other mods do all the spawning of villages. Cheers :)

**Comment by Alvariun** [comment]
> You can also disable OTG villages via the WorldConfig.ini file (in mods/OpenTerrainGenerator/worlds//WorldConfig.ini
> 
> VillagesEnabled: false
> 
> And then let other mods do all the spawning of villages. Cheers :)

I tried to do that but it keeps throwing the same error until I finish removing the mo village which was what gave that incompatibility and that is how it worked for me :c
