### ISSUE TITLE
Odd error with OTG on client and not server.

### ISSUE THREAD

**Issue by crossfirearena** [PG85/OpenTerrainGenerator#578]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [ X] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ X] Other - 1.12.2 V9 (newest)

#### Forge or Spigot Versions
1.12.2 - Forge 2847 (Newest)

#### Description
Removing OTG from the server any still having it client side does not allow people to connect to a server. Working on a modpack that ships with OTG from a vendor, but trying to make a server without it due to compatibility issues. Any connection results in the following error, or some permutation of this: https://pastebin.com/DRQJstgQ

The server does not crash and is responsive the entire time, it just doesnt let the user connect.

I cannot alter the modpack as I am not the vendor of it, nor will the vendor change it. Please do not suggest this as a fix, even though that would clearly fix it.

Is there a setting to fix this error, or is there another thing I can do here?

-Thank you in advance!

**Comment by PG85** [comment]
Unfortunately the error doesn't show any information that could help find the problem, it also doesn't list anything related to otg as far as I can tell. Can't help you with this one, sorry.

**Comment by crossfirearena** [comment]
Removing OTG from the server generates this error, if OTG is on the server, a player can join without this error. Although the server then crashes exactly 5 mins after startup

**Comment by authvin** [comment]
Noticing that this is a modpack, but also involves Bukkit? Would this happen to be a hybrid server? OTG generally does not work as a plugin on hybrid servers, only as a mod

**Comment by BiomeBundle** [comment]
We're not getting reports of servers crashing 5 mins after startup from anywhere else.

Could you provide a log of the crash you're getting when OTG is on both server and client?

**Comment by crossfirearena** [comment]
> Noticing that this is a modpack, but also involves Bukkit? Would this happen to be a hybrid server? OTG generally does not work as a plugin on hybrid servers, only as a mod

It is a hybrid server. Using it as a mod or plugin doesn't work. I tried both. Mod causes the crash, plugin isnt recognized.



> We're not getting reports of servers crashing 5 mins after startup from anywhere else.
> 
> Could you provide a log of the crash you're getting when OTG is on both server and client?

Here is the crash when its on both: https://pastebin.com/vMbH1jim
Server crashes, but not the client.

**Comment by BiomeBundle** [comment]
That last crash log isn't caused by OTG either.

**Comment by crossfirearena** [comment]
> That last crash log isn't caused by OTG either.

Removing otg causes the server to not crash

**Comment by Jishuna** [comment]
> 
> 
> > Noticing that this is a modpack, but also involves Bukkit? Would this happen to be a hybrid server? OTG generally does not work as a plugin on hybrid servers, only as a mod
> 
> It is a hybrid server. Using it as a mod or plugin doesn't work. I tried both. Mod causes the crash, plugin isnt recognized.
> 
> > We're not getting reports of servers crashing 5 mins after startup from anywhere else.
> > Could you provide a log of the crash you're getting when OTG is on both server and client?
> 
> Here is the crash when its on both: https://pastebin.com/vMbH1jim
> Server crashes, but not the client.

We don't support hybrid servers, users have reported it usually works as a mod, but there is no guarantee.

**Comment by crossfirearena** [comment]
I had unloader on there, removed it, crash went from happening 30 seconds after start to 5 mins.

**Comment by crossfirearena** [comment]
> > > Noticing that this is a modpack, but also involves Bukkit? Would this happen to be a hybrid server? OTG generally does not work as a plugin on hybrid servers, only as a mod
> > 
> > 
> > It is a hybrid server. Using it as a mod or plugin doesn't work. I tried both. Mod causes the crash, plugin isnt recognized.
> > > We're not getting reports of servers crashing 5 mins after startup from anywhere else.
> > > Could you provide a log of the crash you're getting when OTG is on both server and client?
> > 
> > 
> > Here is the crash when its on both: https://pastebin.com/vMbH1jim
> > Server crashes, but not the client.
> 
> We don't support hybrid servers, users have reported it usually works as a mod, but there is no guarantee.

That may be the case, but im more trying to find some direction as what can be causing this. Server run, boots and then crashes after it finishes loading with other. Remove it and it doesn't crash anymore but doesn't let players connect. So thats why I started here.

**Comment by BiomeBundle** [comment]
> 
> 
> > That last crash log isn't caused by OTG either.
> 
> Removing otg causes the server to not crash

Doesn't mean the crash is caused by OTG directly.

**Comment by crossfirearena** [comment]
> > > That last crash log isn't caused by OTG either.
> > 
> > 
> > Removing otg causes the server to not crash
> 
> Doesn't mean the crash is caused by OTG directly.

Can you give me any direction at all here to go on? No one seems to be able to decipher this crash. All I know is that removing OTG results in it not crashing so its something _related_ to OTG. Now whether that is another mod not playing nice or what is anyone's guess at this point. All I know is that I need to get this server working, and I do not have the time frame to adequately learn slacktrace to get this working. I am just looking for help to try to get past these crashes.

**Comment by SXRWahrheit** [comment]
As stated above, we don't provide support for hybrid servers. You'll have to determine the conflict.

**Comment by BiomeBundle** [comment]
> 
> 
> > > > That last crash log isn't caused by OTG either.
> > > 
> > > 
> > > Removing otg causes the server to not crash
> > 
> > 
> > Doesn't mean the crash is caused by OTG directly.
> 
> Can you give me any direction at all here to go on? No one seems to be able to decipher this crash. All I know is that removing OTG results in it not crashing so its something _related_ to OTG. Now whether that is another mod not playing nice or what is anyone's guess at this point. All I know is that I need to get this server working, and I do not have the time frame to adequately learn slacktrace to get this working. I am just looking for help to try to get past these crashes.

You already got an answer to the question in the first reply. The error doesn't show any information that could help find the problem, so nobody can help.

**Comment by crossfirearena** [comment]
Alright then.
