### ISSUE TITLE
Bug: Spigot 1.11.2 v6 / v7 Crash in snowy biomes, FrozenSurfaceHelper

### ISSUE THREAD

**Issue by Jishuna** [PG85/OpenTerrainGenerator#58]
Randomly while generating snowy biomes the server will crash with the following: 

java.lang.StackOverflowError: Exception ticking world

This happens infrequently and usually continues to occur whenever the server attempts to load that same area. It also occurs using both 1.11.2 v6 and v7 spigot versions. 

Crash report: https://pastebin.com/Cyb42zAC

Edit: Seems this has also been noted on the original Terrain Control: https://github.com/MCTCP/TerrainControl/issues/495

**Comment by PG85** [comment]
Thanks for reporting this, will look at it asap.

**Comment by RealmportalMC** [comment]
https://pastebin.com/7idQvdBy Getting the same(?) error

**Comment by SanityCh3ck** [comment]
Also happens in 1.12.2 v4 with normal Forge (14.23.1.2590)

[Crash report](https://pastebin.com/miMRDiKu)

**Comment by Jishuna** [comment]
Should be fixed as of 1.12.2 v6
