### ISSUE TITLE
Bug: Snow layers inside structures on snowy biomes

### ISSUE THREAD

**Issue by Cyliann** [PG85/OpenTerrainGenerator#581]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge

#### OTG Version
- [x] Other - 1.16.4-0.0.1

#### Forge or Spigot Versions
Forge 35.1.0

#### What other plugins are you running?
Xaero's Minimap, Optifine

#### Description
The title is self explanatory. There are snow layers inside structures (like houses) on snowy biomes.
![2020-12-04_12 39 19](https://user-images.githubusercontent.com/33868960/101159582-eba7c100-362d-11eb-83dd-8ee08e6c8afa.png)

**Comment by authvin** [comment]
What kind of structure is this, BO3 or vanilla?

**Comment by Cyliann** [comment]
That is a village house, but I also seen it in other structures generated automatically with BiomeBundle (I just couldn't find them for screenshot)

**Comment by PG85** [comment]
Thanks for reporting this. Only way I can make sense of it would be that the snow is placed before the structure, and the structure ignores the snow when looking for the highest block. Will take a look, thanks!

**Comment by PG85** [comment]
Should hopefully be fixed by recent versions, 0.0.13 will solve some more snow problems. If you're still having problems with 0.0.13 (to be released on the OTG disc asap), feel free to reopen this issue or create a new one.
