### ISSUE TITLE
1.16.x 1.0.0: 5.1 - Mob spawning: merge vanilla mob settings

### ISSUE THREAD

**Issue by PG85** [PG85/OpenTerrainGenerator#585]
Mob spawning can be configured in the biomeconfigs, but inheriting mob spawn settings from default/vanilla biomes isn't working atm. Fix that.

**Comment by SXRWahrheit** [comment]
@authvin will implement this for Spigot

**Comment by PG85** [comment]
Included with 1.16.5-0.0.6
