### ISSUE TITLE
Feature: 1.16.x - PresetPacker Jar 1.16.

### ISSUE THREAD

**Issue by PG85** [PG85/OpenTerrainGenerator#586]
Update the worldpacker project for 1.16.

**Comment by authvin** [comment]
PresetPacker is basically complete, but should be tested for usability. The preset versioning in particular might need some tweaking, but that requires some preset dev feedback first.

**Comment by PG85** [comment]
Forge allows modders to package json files in the mod's resources folder, which are automatically packaged as the mod's datapack and included when worlds are created. Should make users aware that this is a feature of presetpacker.

**Comment by FrankTCA** [comment]
Finished this off yesterday just forgot to close it.
