### ISSUE TITLE
[1.12.2 v9] game crash

### ISSUE THREAD

**Issue by vaniron** [PG85/OpenTerrainGenerator#589]
OTG Mod for Forge
1.12.2 v9 from curseforge.com with latest biome bundle
forge 14.23.5.2847

Crash log with all mods:
https://pastebin.com/raw/J91regqb

Game crashes sometimes upon connecting to the server, starting the modpack and joining again helps.
Friend experiencing same problem with same error. So its propably not PC related.

**Comment by BiomeBundle** [comment]
Suggest updating your forge and optifine to the most recent versions and seeing if that helps, your optifine build is from 2018.

**Comment by vaniron** [comment]
Tried, still same issue even with latest forge and optifine.
https://pastebin.com/raw/RxxChgi6

**Comment by vaniron** [comment]
Tested without optifine, still crashes on newest forge.
https://pastebin.com/raw/tLr3gBGK

**Comment by PG85** [comment]
Appears to be an issue with packets and timings, the client seems to be requesting data in the world before the connection was properly resolved and data processed. Will add a null check for 9.3, which should solve the immediate problem, hope this is not an indication of a more fundamental issue though. Will post a new dev version on the discord asap an post a link.

**Comment by vaniron** [comment]
Maybe caused by bungeecord, fixed with dev build provided by Authvin.

**Comment by authvin** [comment]
Fix will be included with v9.3 release when it goes up on curseforge
