### ISSUE TITLE
Mesa (Bryce) Stone surface generation Bug

### ISSUE THREAD

**Issue by GamingMunk100** [PG85/OpenTerrainGenerator#591]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - OTG Version 1.12.2 v9.0

#### Forge or Spigot Versions
[Forge Version: forge-1.12.2-14.23.5.2854-universal]

#### What other plugins are you running?
[Mod List: All versions of these Mods are 1.12.2 compatible and are all .jar format]
- [1.12.2]+SecurityCraft+v1.8.20.2
- [1.12]bspkrsCore-universal-7.6.0.1
- [1.12]TreeCapitator-client-1.43.0
- AdditionalEnchantedMiner-1.12.2-12.4.5-universal
- appliedenergistics2-rv6-stable-7
- backpack-3.0.2-1.12.2
- BiblioCraft[v2.4.5][MC1.12.2]
- Biome_Bundle-1.12.2-v6.1
- buildcraft-all-7.99.24.7
- CodeChickenLib-1.12.2-3.2.3.358-universal
- coroutil-1.12.1-1.2.37
- EnderStorage-1.12.2-2.4.6.137-universal
- Galacticraft-Planets-1.12.2-4.0.2.281
- GalacticraftCore-1.12.2-4.0.2.281
- Golden_Airport_Pack_Immersive_Vehicles_2.2.2
- hbm-1.3.4a-1.12.2
- Hwyla-1.8.26-B41_1.12.2
- Immersive+Vehicles-1.12.2-18.5.0
- ImmersiveEngineering-0.12-98
- ImmersiveRailroading-1.7.3_1.12.2
- industrialcraft-2-2.8.221-ex112
- ItemBlacklist-1.4.3
- IvToolkit-1.3.3-1.12
- jei_1.12.2-4.16.1.301
- journeymap-1.12.2-5.7.1
- MicdoodleCore-1.12.2-4.0.2.281
- MJRLegendsLib-1.12.2-1.2.0
- MTS_Official_Pack_V16
- mw_2.0-0.4.4.6_mc1.12.2
- NotEnoughItems-1.12.2-2.4.3.245-universal
- obfuscate-0.4.2-1.12.2
- OpenTerrainGenerator-1.12.2-v9.0
- OptiFine_1.12.2_HD_U_F5
- Pam's+HarvestCraft+1.12.2zg
- RecurrentComplex-1.4.8.2
- TrackAPI-1.2
- twilightforest-1.12.2-3.11.1021-universal
- UNU+Parts+Pack+[MTS]+1.12.2-18.0.0-3.5.0
- vehicle-mod-0.44.1-1.12.2
- weather2-1.12.1-2.6.12
- worldedit-forge-mc1.12.2-6.1.10-dist

#### Description
- When flying through the World to see if everything is working properly I stumbled upon the Mesa (Bryce) and its other inherited Biomes (Forest, Rocks, Edge). I noticed random Stone Pillars almost looking like chunk errors. How they looked when sitting above the water, as shown below.
![2020-12-10_21 20 02](https://user-images.githubusercontent.com/75859806/101953086-f2e34780-3bb6-11eb-924a-d3d9b402eecf.png)
![2020-12-10_21 19 20](https://user-images.githubusercontent.com/75859806/101953395-8288f600-3bb7-11eb-99f1-493a47eab46f.png)

- I expected the Biome to spawn without those stone structures. Why I expected it not to happen was because I had thorough look throughs of the Biomes and the objects spawning as well as the Spawning Surface and Ground control setting.

- To try this for yourself just load in a OTG World and do "/otg tp Mesa (Bryce)"

**Comment by PG85** [comment]
Hey @GamingMunk100 , thanks for reporting this. Should be fixed with v9.3, available on curse.
