### ISSUE TITLE
crash when second world is created

### ISSUE THREAD

**Issue by vaniron** [PG85/OpenTerrainGenerator#592]
OTG Mod for Forge
1.12.2 v9.3 from discord
forge 14.23.5.2854 +sponge

Crash log with all mods:
https://pastebin.com/raw/1n8BM6g6

Game crashes when server is trying to load the world, happens only on second world created on the server. 
First world (default but with OTG installed is okay).
I tried to create this problematic world both with and without OTG generator - still the same issue.

**Comment by authvin** [comment]
OTG and sponge don't work well together, and multi-world is one of the things that just don't work. I'm assuming this is what's going wrong here

**Comment by vaniron** [comment]
so no workaround for this?

**Comment by authvin** [comment]
None known, not without removing Sponge
