### ISSUE TITLE
I need OTG Core 1.12.2 (v9.3)? I have v9.3 but it says I have v9.0?

### ISSUE THREAD

**Issue by SmileyWasTaken** [PG85/OpenTerrainGenerator#594]
#### OTG Plugin or Mod

- [ x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version

- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x ] Other - 1.12.2 - v9.3

#### Forge or Spigot Versions

I'm using Forge 14.23.5.2854

#### What other plugins are you running?

(All mods are at the latest versions)
[OTG] Cave Update

AutoRegLib

BetterFps

Biome Bundle

Biomes O' Plenty

Cave Addon

Cavern II

Caves and Cliffs Mod, 1.17 concept

Davincis Vessels

Decocraft

Dynamic Lights

Dynamic Surroundings

Fossils and Archeology Revival

GraveStone Mod

Hwyla

IBE Editor

iChunUtil

JourneyMap

JurassiCraft

Just Enough Items (JEI)

LLibrary

Mantle

Mo' Bends

Morph

MovingWorld

Neat

Oh The Biomes You'll Go

Open Terrain Generator (OpenTerrainGenerator / OTG)

OreLib

OTG: Dungeons

OTG: Flatlands

OTG: Skylands

OTG: The Void

Pam's HarvestCraft

Prehistoric Spawns- A Fossils and Archeology Revival add-on [1.12.2 RELEASED!]

PTRLib

Quark

Reforged

Roguelike Dungeons

Security Craft

So Many Enchantments

Subterranean Waters

Tinkers Construct

Twitch Craft

Waystones

Waystones2Waypoints

Worley's Caves

Xaero's Minimap

YUNG's Better Caves (Forge)

YUNG's Better Mineshafts (Forge)

#### Description

Its not really steps. I just boot up minecraft and it says I need dependencies of OTG Core v9.3 it says I have v9.0 but I have v9.3.
![sadsadasd](https://user-images.githubusercontent.com/76948543/103532853-fb4b3d00-4e59-11eb-99ab-47d37501bd48.PNG)

My game to say what it said.

You just boot up the game

**Comment by authvin** [comment]
You need to delete the otg-core.jar file from your /mods/1.12.2/ directory. Then OTG will unpack the v9.3 core automatically

**Comment by SmileyWasTaken** [comment]
> You need to delete the otg-core.jar file from your /mods/1.12.2/ directory. Then OTG will unpack the v9.3 core automatically

Still wont work for me

**Comment by SmileyWasTaken** [comment]
> > You need to delete the otg-core.jar file from your /mods/1.12.2/ directory. Then OTG will unpack the v9.3 core automatically
> 
> Still wont work for me

nevermind found it

**Comment by mitko8009** [comment]
> You need to delete the otg-core.jar file from your /mods/1.12.2/ directory. Then OTG will unpack the v9.3 core automatically

**Tnx ♥**
