### ISSUE TITLE
Special characters in world name cause crash on world load

### ISSUE THREAD

**Issue by MechaFinch** [PG85/OpenTerrainGenerator#595]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - 1.12.2-v9.3 (and a v8 version, issue is the same before and after updating)

#### What other plugins are you running?
A slightly modified version of the modpack UfoCraft 4 (found on curseforge) with a couple extra mods. According to the error and its solution, they are unrelated.

#### Description
When certain (non UTF-8?) special characters (specifically these characters in my case: じゃない) are in the world name, the game crashes on world load. This is caused by a YAML exception when reading [world name]/OpenTerrainGenerator/Config.yaml due to the world name doing something like producing invalid UTF-8. My guess is that these characters aren't in UTF-8 and when creating the YAML file, it tries to use it anyways.
Editing the YAML file so that it no longer contains these characters resolves the issue as far as I can tell, although an unrelated issue caused by a different mod is still preventing world loading in a later step.

What did you expect?  
I expected the world to load

MRE:  
Create a world with a name containing the example characters (or other similar characters) generated via OTG. Save and exit the world, then attempt to reload it. It may be the case that you have to restart minecraft for the crash, but this is unlikely.

**Comment by PG85** [comment]
Hey @MechaFinch , thanks for reporting this. It's a know issue, via the OTG world creation screen we prevent invalid input when creating worlds, and only allow simple characters/names. Preset creators make sure to name their presets appropriately. It's a legacy code thing, the world/preset names are used for some lookups. For 1.12.2 we've decided not to fix it and focus on 1.16 instead. For the other, unrelated issue with mods+OTG you're having, join us on the Discord as there are more users who can help. Thanks and cheers.
