### ISSUE TITLE
1.16 - bo4 enabled worlds and saving

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#598]
Saving/loading causes seams in worlds with bo4s

Might have to move the save logic to chunk/region save, which may cause some concurrency issues

**Comment by PG85** [comment]
Appears to be a problem with chunks being regenerated (generated+populated twice) by mc on exit/rejoin. We can make it so BO4's can be regenerated, that would require some more work though. See https://github.com/PG85/OpenTerrainGenerator/issues/604
