### ISSUE TITLE
Feature: 1.16.4 - 0.1.0: Ocean Update

### ISSUE THREAD

**Issue by jaskarth** [PG85/OpenTerrainGenerator#599]
To get parity with 1.13 oceans, we need:
- [x] Icebergs (SAGC)
- [x] Icebergs (Resource)
- [x] Kelp resource
- [x] Seagrass resource
- [x] Coral resource
- [x] Sea pickles
- [x] Shipwrecks and Ocean Ruins
- [x] Ocean temperature distribution via perlin noise
To allow for greater configurability by preset developers, the following config format is proposed:
`WarmOceanBiomes: ocean_1, 10, ocean_2, 5, ocean_3, 20, ...`
Where it would be possible to specify multiple biome configs that generate within the temperature "band". If no weights are given, it would also be possible to specify just a single biome config. We would need `WarmOceanBiomes` , `LukewarmOceanBiomes`, `OceanBiomes`, `ColdOceanBiomes`, and `FrozenOceanBiomes` to fill all temperature bands provided by vanilla.

**Comment by PG85** [comment]
TODO:
- Icebergs resource
- Spigot SAGC issue #658 
- Unable to assign borders to new ocean biomes #615 
- Ocean biomes don't use variable temperatures internally, like vanilla swamps and oceans, used to make ice spawn in patches.

*Have closed above issues so we can handle them in this issue.

**Comment by PG85** [comment]
Added UseFrozenOceanTemperature: true/false to biomeconfig, to enable frozen ocean variable temperature, used to create patches of ice. 

Fixed some Iceberg sagc bugs, Iceberg sagc now also allows normal SAGC commands after "Iceberg", for example: SurfaceAndGroundControl: Iceberg -normal SAGC command-. Added biomeconfig PackedIceBlock and SnowBlock to control iceberg sagc materials.

**Comment by PG85** [comment]
Only TODO left should be #615, will reopen that.
