### ISSUE TITLE
1.16.4: Multithreading

### ISSUE THREAD

**Issue by authvin** [PG85/OpenTerrainGenerator#600]
When trying to enable isParallelCapable in SpigotChunkGenerator, OreGen started throwing nullpointers in the cache. Would need to make resource caches local to the population method instead of the resource object to fix this. Multithreading is likely to have other issues beyond this, like BO4 plotting and potentially some vanilla population we hook in. Has potential to break mods as well on forge.

**Comment by PG85** [comment]
Should be fixed for 0.0.14/0.0.15.
