### ISSUE TITLE
OTG crashing server at start

### ISSUE THREAD

**Issue by Mithandill** [PG85/OpenTerrainGenerator#602]
#### OTG Plugin or Mod
[/]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - 1.12.2-v8.3

#### Forge or Spigot Versions
[forge-1.12.2-14.23.5.2854]

#### Server/Client Log
[
crash-2021-01-31_11.47.55-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/5899622/crash-2021-01-31_11.47.55-server.txt)
]

#### What other plugins are you running?
[BiomeBundle-1.12.2-V6.1]

#### Description
[crash at server start]

[server launch]

[/]

[/]

**Comment by authvin** [comment]
Try to update to v9.3

**Comment by Mithandill** [comment]
it still doesn't start after i updated to 9.3
[crash-2021-01-31_13.35.46-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/5899695/crash-2021-01-31_13.35.46-server.txt)

**Comment by authvin** [comment]
Delete your otgcore.jar file under mods/1.12.2

**Comment by PG85** [comment]
Update OTG, delete OTG-core. If it still doesn't work, your preset files may be corrupted, for BB delete (mods/openterraingenerator/worlds/Biome Bundle. The files should be recreated on next app start if you have the BB jar. If you have more question or problems like this, join us on the Discord as there are more users there who can help. Cheers.
