### ISSUE TITLE
Bug:[1.12.2]OTG world cannot normal load and read

### ISSUE THREAD

**Issue by HaktyGaona** [PG85/OpenTerrainGenerator#603]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - 1.12.2-v9.3

#### Forge or Spigot Versions
[1.12.2-forge1.12.2-14.23.5.2847]

#### Server/Client Log
[
[2021-02-04-3.log.gz](https://github.com/PG85/OpenTerrainGenerator/files/5925526/2021-02-04-3.log.gz)

[2021-02-04-3.log.gz](https://github.com/PG85/OpenTerrainGenerator/files/5925512/2021-02-04-3.log.gz)
]

#### What other plugins are you running?
[Multiverse-Core-2.5.0](This server plugin and OTG have similar function, I guess it will happen. Because I will upload the map to my server.)

#### Description
[When I created the OTG world, it crashed while loading the world, and the game exited; If I add OTG world to the loaded world, I will not be able to enter it. And the world didn't respond. This only happens in single player games.]

[I guess there is a compatibility problem between RFTools mod and OTG. If I delete them, it may solve the problem.]

**Comment by PG85** [comment]
Hey HaktyGaona, there may be some incompatibilities with dimension management mods like RFTools. Generally speaking, if you use OTG to manage OTG dimensions, and other mods to manage other dimensions, it should be okay. OTG won't touch other mods' dimensions, so if they don't touch OTG dimensions, in theory it should work fine. Join us on the Discord if you have more problems/questions, we've got more users there who can help you. Cheers.

*Hybrid servers have their own problems btw, refering to Forge here. Spigot MV should work fine btw.
