### ISSUE TITLE
More 1.16 bugs

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#608]
**Bamboo resource (and registry) pokes holes in stuff:**
https://cdn.discordapp.com/attachments/630666815533613057/828963139394469898/2021-04-06_13.03.23.png

**Vines resource attaches to bamboo:**
https://cdn.discordapp.com/attachments/630666815533613057/828962910952489021/2021-04-06_13.02.21.png

**Leaves are decaying:**
In 1.12.2 (and every minecraft version before that) you could set all your leaves to just the basic leaves:0 and if they didnt collide with anything upon generation, it didnt matter that they weren't 7 blocks away from a log, they would only begin to decay if the player touched them. In the current build any leaves more than 7 blocks away are decaying even if they do not collide with anything.

**Material stuff:**
- Stone brick stairs wrongly mapped to stone stairs
- Log block with bark on all sides wrongly mapped to standard log blocks
- Some mushroom block issues (pores showing on wrong sides, red mushroom blocks being used instead of blocks with pores on all sides)
- Stairs directions are all kinds of messed up
- Banner directions broken and have no patterns
- Ladder directions wrong
- Doors spawn with top and bottom half on different rotations

**Comment by authvin** [comment]
Fixed stone brick stairs and bark blocks

Banner patterns are NBT, which I've fixed but not pushed. Direction looks good to me, at a glance. A bigger problem with banners is that their colour, which in 1.12 is stored in the tile entity, and in 1.16 is separated into different items. I don't see a way to solve this, personally; LegacyMaterials doesn't have access to NBT. Would need to be part of the update process for old NBT files.

Need some examples of mushroom, I looked over the code and I can't find any issues. It looks correctly mapped to me. Same with stairs. 

For the rest of the materials, I'll need some example files. The mapping looks correct, so the issue likely lies somewhere else. It's possible this is stuff that OTG used to fix when spawning or similar, which it no longer is. It's also possible that these issues will be fixed through /otg fixbo3, I think that's worth a shot.

**Comment by BiomeBundle** [comment]
Banner directions dont look ok to me:
![2021-04-07_01 48 25](https://user-images.githubusercontent.com/23154920/114172538-b12c9880-992d-11eb-9941-a608081e7f15.png)

**Comment by authvin** [comment]
![2021-04-09_13 43 18](https://user-images.githubusercontent.com/37563355/114174845-82b4ba80-9939-11eb-9c9b-32574981f0cf.png)
It seems to be an issue of rotation; turning off RotateRandomly, it looks normal. Gonna have to look more at this

**Comment by BiomeBundle** [comment]
Example mushroom block issue:

1.12.2:
![2021-04-10_16 42 08](https://user-images.githubusercontent.com/23154920/114275855-0cd54f80-9a1c-11eb-88bd-9d2dc6b275d8.png)

1.16.5:
![2021-04-10_16 46 52](https://user-images.githubusercontent.com/23154920/114275984-95ec8680-9a1c-11eb-9139-86cb2239ec98.png)

Plenty of other issues too on other objects

**Comment by jaskarth** [comment]
Fixed bamboo!

**Comment by BiomeBundle** [comment]
More bugs:

- Blue ice blocks spawn as air, even in vanilla resources
- Having multiple border biomes of the same size makes only one of them ever spawn regardless of NotBorderNear settings. This makes having multiple beach biomes almost impossible. (This needs checking to see if it is a problem also in 1.12.2 or is something new in 1.16)
- Dungeon resource is causing console errors (Failed to fetch mob spawner entity at X,Y,Z) and they are spawning cut in half or not at all
- Caves are really messed up outside of spawn chunks (spigot only)
- Bo4 generation is very odd, with structures generating in straight lines across the map (spigot only)
- Trees and other objects generating cut in half (even vanilla trees)

**Comment by BiomeBundle** [comment]
Closing this as I've recreated them as individual issues to make it easier to track/prioritise
