### ISSUE TITLE
Feature: Allow us to define our own portal ignition sources in 1.12 version.

### ISSUE THREAD

**Issue by Dread131313** [PG85/OpenTerrainGenerator#614]
#### Is your feature request related to a problem? Please describe.
It's not a problem per se' - as i'm building a modpack based off of stages. I have flint and steel gated behind a later stage 
where steel/iron isn't available early game. However I want players to be able to enter OTG worlds via portal only in earlier stages. 

This creates a problem where they don't have access to a flint and steel. I have other mods that have tools for early game for creating fire (Pyrotech - specifically) and they cannot use a flint and tinder, nor a bow drill, nor any other type of fire producing device. It seems the only thing that works is a right click on a portal frame with a flint and steel in the hand. 

My apologies in advance if portals already DO act like nether portals, whereas they activate if a fire is nearby - just taking longer instead of being instant. (I will be testing this and if this is so, I will close this post!)

#### Describe the solution you'd like
Just be able to specify what portal activation device id like to use, or at the very least portals to behave like nether portals do where a fire is nearby they will eventually activate.

#### Describe alternatives you've considered
Since this is somewhat of an easy fix (im assuming) I dont know any better alternatives.

#### Description aka Additional context
n/a

Thanks in advance!

**Comment by Dread131313** [comment]
Update: After several tries with minecraft leaves, planks, and logwood - with different ignition sources, I cannot get the portal to activate outside of literally using the flint and steel on the portal frame. So it would seem even unconventional methods of lighting the portal wont work. :(

**Comment by PG85** [comment]
Hey @Dread131313 we're busy developing 1.16 so don't have any 1.12.2 releases scheduled. It'd be easy to hardcode a different ignition source, if you can check out the project and know a bit of java. Making the ignition source configurable is a bit more work, but also doable. Join us on the OTG Discord if you need any pointers. Will leave this issue open in case anyone finds time for it.

**Comment by PG85** [comment]
https://github.com/PG85/OpenTerrainGenerator/blob/1.12-OTG%2B/platforms/forge/src/main/java/com/pg85/otg/forge/events/dimensions/RightClickListener.java#L26

**Comment by PG85** [comment]
Will definitely keep this in mind for 1.16.5 if/when we look at OTG portals, won't be fixing this for 1.12.2 though, unless someone would like to PR it. Thanks for reporting ofc!
