### ISSUE TITLE
1.16 - Rose bushes generating with no top half

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#616]
Seems to be the only double plant affected for some reason.

![2021-05-08_18 20 31](https://user-images.githubusercontent.com/23154920/117547937-20c79d80-b02a-11eb-9fd6-96a14e824fa2.png)

**Comment by authvin** [comment]
![2021-05-08_21 05 38](https://user-images.githubusercontent.com/37563355/117550534-31374280-b041-11eb-8109-6ac518c9e1bf.png)
Could you give a specific example? I loaded up a test preset with the only resource being `Plant(RoseBush,3,50.0,0,139,minecraft:grass_block[snowy=false],minecraft:dirt)` and I got normal rose bushes

**Comment by BiomeBundle** [comment]
[NewDefaults.zip](https://github.com/PG85/OpenTerrainGenerator/files/6446408/NewDefaults.zip)

Plains biome:

![2021-05-08_20 09 52](https://user-images.githubusercontent.com/23154920/117550698-8b340a00-b039-11eb-971f-3cdb89694903.jpg)

**Comment by authvin** [comment]
Turns out, these are not rose bushes, this is every non-tall flower spawning as the bottom half of a rose bush. Should be a simple fix

**Comment by BiomeBundle** [comment]
Thought there were a few too many, thanks for figuring it out Auth.

**Comment by authvin** [comment]
![2021-05-08_21 55 48](https://user-images.githubusercontent.com/37563355/117551785-351a9300-b048-11eb-94e2-81ee513af004.png)
World is back to normal ^^
