### ISSUE TITLE
1.16 - Some vanilla tree resources are generating incorrect trees

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#617]
Here are the vanilla tree types and what they correspond to when used in the Tree() resource:

![image](https://user-images.githubusercontent.com/23154920/117548796-ced54680-b02e-11eb-9fde-ebd22974a72e.png)

1. Here's a biome with JungleTree, which should be the huge jungle type:

![2021-05-08_18 55 35](https://user-images.githubusercontent.com/23154920/117548848-017f3f00-b02f-11eb-952a-f312cb195ff6.png)

2. Taiga1 generates the trees shown as Taiga2 in the initial image and vice versa

3. HugeTaiga1 generates the trees shown as HugeTaiga2 in the initial image and vice versa

4. Tree, BigTree, Birch, TallBirch, SwampTree, Acacia, HugeMushroom, HugeRedMushroom, HugeBrownMushroom, CocoaTree and GroundBush all look ok

**Comment by jaskarth** [comment]
Should be fixed!
