### ISSUE TITLE
Bug: 1.16 - Leaf decay

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#618]
In 1.12.2 (and every minecraft version before that) you could set all your leaves to just the basic leaves:0 and if they didnt collide with anything upon generation, it didnt matter that they weren't 7 blocks away from a log, they would only begin to decay if the player touched them. 

in 1.16.5, any adjacent block update can cause a chain reaction of leaf block updates - meaning that preset developers may have to review all of their trees and prevent this somehow.

A few things have been done already to minimise the impact but it's still a problem, a band-aid solution could be make 'illegal' leaves persistent (meaning they wont decay when the tree is chopped).

**Comment by SXRWahrheit** [comment]
If we can determine which leaves are illegal for the purpose of marking them as persistent, we could also remove the persistent state when nearby legal leaves decay / are broken / etc.

I can't decide whether I think this should be in an addon or in the main plugin, but it's one possible approach for the future.

**Comment by FrankTCA** [comment]
This is a block tag in 1.13+. It's called "persistent".

Check the screenshot here. Debug stick is an extremely useful tool: [Screenshot](https://infotoast.org/ToastCDN/uploads/Frank/1627168276/persistent-block-tag.png)

**Comment by FrankTCA** [comment]
This is fixed in /otg update and /otg edit.
