### ISSUE TITLE
Bug: 1.16 - Blue ice blocks spawn as air, even in vanilla resources

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#619]
![image](https://user-images.githubusercontent.com/23154920/117550183-d567bc00-b036-11eb-8007-dccaf7368bec.png)

![image](https://user-images.githubusercontent.com/23154920/117550195-e0bae780-b036-11eb-91c3-efd9fb67084b.png)

![image](https://user-images.githubusercontent.com/23154920/117550212-f92b0200-b036-11eb-9b19-72f25d417c6b.png)

**Comment by authvin** [comment]
Is this with the Iceberg SAGC, or a Registry() resource? Or both?

**Comment by BiomeBundle** [comment]
Both, first screenshot above is a Registry() resource, second and third are SAGC.

**Comment by authvin** [comment]
For SAGC, the vanilla version uses a surface structure to place the blue ice, namely "blue_ice". We could likely use the same, or we could implement something similar ourselves that's more configurable. 

What I did find, was that vanilla frozen oceans spawn two different features for the icebergs, both "iceberg_packed" and "iceberg_blue". So I would guess you only have "iceberg_packed", and that adding "iceberg_blue" as well could solve it. If you already have both, then I'm a bit stumped.

**Comment by BiomeBundle** [comment]
Registry(minecraft:iceberg_blue) is already in the frozen ocean config.

**Comment by Jishuna** [comment]
Blue ice appears to spawn properly in the latest builds. The large amount of missing blocks inside the icebergs appears to be vanilla behaviour. I've attached an image from a fully vanilla world for comparison.

![2021-07-10_12 32 52](https://user-images.githubusercontent.com/24664776/125170063-1ab18280-e17b-11eb-9256-92063fb34960.png)

And here is an image of some blue ice in the default preset.
![2021-07-10_12 35 58](https://user-images.githubusercontent.com/24664776/125170150-7da31980-e17b-11eb-9156-9f5ba2886e91.png)

**Comment by PG85** [comment]
Since this seems to be vanilla behaviour, and there's not really any other sensical explanation (blue ice blocks themselves work fine). closing this for now. If there's more information, feel free to reopen.
