### ISSUE TITLE
(BiomeMode: Normal) BiomeGroups not generating

### ISSUE THREAD

**Issue by Graagh** [PG85/OpenTerrainGenerator#62]
With BiomeMode = Normal, and the default BiomeGroups generated in a world with no pre-existing WorldConfig.ini, OTG will Keep the BiomeGroups from generating next to each other.  In fact, it pursues this duty with such single-minded determination that it will not spawn any biomes except those listed in the first BiomeGroup in the list.  Not sure if this is also true for pregenerated world types, but I would guess so.  You can easily test this by re-ordering the lines.  

Also, it doesn't seem to allow any arbitrary BiomeGroup names.  I assume it requires any/all of the names generated by default, but none of this is explained or mentioned in any of the very brief documentation for this feature (among others).  But that maybe warrants a separate issue just for docs.  Several of the comments are demonstrably inaccurate or just downright false.

**Comment by MCPitman** [comment]
I just tested the default generated world and teleported to a Mesa biome which is 5th in the group list. Most of what you are saying is incorrect, it does allow any BiomeGroup name, and does not require anything vanilla by default.

The comments are not inaccurate, I have no idea what you are talking about.

**Comment by Graagh** [comment]
That's actually very good news.  I was hoping it worked this way, but for some reason I haven't been able to make it work.  But I haven't been methodical enough to offer specific details.  I'll continue testing.
