### ISSUE TITLE
1.16 - Multiple border biomes of the same size

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#620]
Having multiple border biomes of the same size makes only one of them ever spawn regardless of NotBorderNear settings. 

This makes having multiple beach biomes almost impossible. (Will update here when I've checked to see if it is a problem also in 1.12.2 or is something new in 1.16).

**Comment by PG85** [comment]
Need to update https://github.com/PG85/OpenTerrainGenerator/blob/1.16.4/common/common-generator/src/main/java/com/pg85/otg/gen/biome/layers/BiomeBorderLayer.java, currently it's only storing one possible border biome for each parent biome per gen depth.

**Comment by PG85** [comment]
Implemented for 0.0.15, also added OnlyBorderNear: whitelist, when used NotBorderNear is ignored.
