### ISSUE TITLE
1.16 - Bo4 generation is very odd, with structures generating in straight lines across the map (spigot only)

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#623]
![image](https://user-images.githubusercontent.com/23154920/117550380-eebd3800-b037-11eb-9213-03118e8d0639.png)

**Comment by PG85** [comment]
Hm, interesting to note is the sand that's not being replaced to red sand. Looking only at that, I can see 2 bands in the picture, one on the left edge, and one you've marked as the left in the picture. The second band you've marked doesn't have that problem. 

If the problem with the second band is that there's bo4's spawning in biomes they shouldn't (red circles/dots in green biomes), I think I also see that happening outside the bands?

So is this 2 separate problems? 1: bands where sand isn't replaced. 2: bo4's spawning in the wrong biome?

**Comment by PG85** [comment]
Should be fixed for OTG 1.16.5 0.0.12.
