### ISSUE TITLE
1.16 - Trees and other objects generating cut in half on chunk borders (even vanilla trees)

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#624]
![image](https://user-images.githubusercontent.com/23154920/117550422-35ab2d80-b038-11eb-8438-bd53f94e6f53.png)

![image](https://user-images.githubusercontent.com/23154920/117550429-3fcd2c00-b038-11eb-9df9-616f20af9a4c.png)

**Comment by SXRWahrheit** [comment]
FWIW, I think this used to happen on my server in 1.12.2 when using worldedit's regen command. We're on 1.16 (without OTG) now, and it's certainly a good bug to fix, but it may not be new.

**Comment by BiomeBundle** [comment]
It's definitely new, it does not happen in 1.12.2 without regenerating chunks with something like worldedit as per your example.

**Comment by BiomeBundle** [comment]
Should have mentioned that it happens in a line indefinitely across the entire world:

![image](https://user-images.githubusercontent.com/23154920/117551750-95f19d80-b03f-11eb-8e4e-87da239a0916.png)

**Comment by jaskarth** [comment]
This is unfortunately a vanilla bug, and it happens most often when the world is closed and reopened. I don't think there's any good way around it.

**Comment by BiomeBundle** [comment]
Without looking into it I don't think it's possible to come to that conclusion. I'll have to make a reproducible example. 

The above screenshots were taken on a fresh world which hadn't been closed and reopened.

**Comment by PG85** [comment]
May be related to https://github.com/MinecraftForge/MinecraftForge/issues/7766, though that happens on exit/rejoin, still have to confirm.

**Comment by SXRWahrheit** [comment]
Can this be reproduced on 0.0.11? I can't find anything of this nature on either Forge or Spigot

**Comment by PG85** [comment]
See https://bugs.mojang.com/browse/MC-224729

**Comment by PG85** [comment]
Should be fixed for Forge via mixins, no solution for spigot/paper yet atm.

**Comment by PG85** [comment]
Closing this for now as there is no possibility for a solution on our end.
