### ISSUE TITLE
1.16 - BO3AtSpawn not working

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#625]
BO3AtSpawn in the worldconfig.ini is not spawning anything. 

The setting is necessary for the Skylands preset to prevent the player from falling into the void.

**Comment by PG85** [comment]
Also, this setting is necessary for the Void preset to prevent the player from falling into Skylands.

**Comment by PG85** [comment]
Fixed for 0.0.15.
