### ISSUE TITLE
1.16 - Piglin safe (and possibly other dimension settings)

### ISSUE THREAD

**Issue by authvin** [PG85/OpenTerrainGenerator#636]
We should expose the setting to make a dimension piglin-safe, and potentially the other dimension-specific settings as well

**Comment by PG85** [comment]
For 1.16.5 - 0.0.15, have added the following dimension settings to the worldconfig:

FixedTime - long - -1 (disabled)
HasSkyLight - boolean - true
HasCeiling - boolean - false
UltraWarm - boolean - false
Natural - boolean - true
CoordinateScale - double - 1.0
CreateDragonFight - boolean - false
PiglinSafe - boolean - false
BedWorks - boolean - true
RespawnAnchorWorks - boolean - false
HasRaids - boolean - true
LogicalHeight - int - 256
Infiniburn - resourcelocation - minecraft:infiniburn_overworld
EffectsLocation - resourcelocation - minecraft:overworld
AmbientLight - float - 0.0

Not sure if we'll be able to make them work for spigot, then again OTG dimension features never worked for spigot. Should make a separate issue for spigot dimensions features.
