### ISSUE TITLE
Bug: 1.16 - Vanilla structures not obeying config settings (paper/spigot only)

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#637]
Vanilla structures like shipwrecks, pillager outposts etc seem to spawn wherever they want in paperspigot worlds, even if they're not enabled in the worldconfig and/or biome

**Comment by Jishuna** [comment]
Can this be reproduced in 0.0.15?

**Comment by FrankTCA** [comment]
Fixed p0g
