### ISSUE TITLE
1.16 - Lava under Y10

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#638]
In vanilla, lava fills caves under Y10 - obviously you wouldn't want this in all OTG worlds, but it would be good to have an option for it in the worldconfig.

**Comment by authvin** [comment]
We currently should have this, but we do need an option to disable it - or potentially to specify a fill liquid, which defaults to lava.

**Comment by PG85** [comment]
For 0.0.15, added new options CarverLavaBlock and CarverLavaBlockHeight, only applies to OTG carvers.
