### ISSUE TITLE
[1.12.2] ForgeEssentials MultiWorld OTG new world bug

### ISSUE THREAD

**Issue by jcc10** [PG85/OpenTerrainGenerator#639]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [x] 1.12.2_V9.3
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
Forge 14.23.5.2854

#### What other plugins are you running?
[modlist.txt](https://github.com/PG85/OpenTerrainGenerator/files/6487547/modlist.txt)

#### Description
**Describe the bug**
Soft Crash when trying to create a new dimension.

**To Reproduce**

With `Open Terrain Generator` and `Traveler's Dream` (compact) both installed and enabled, try to create any kind of dimension (such as FLAT or OTG).
World Creation will fail part way through. (though it will try to back it up.)

**Expected behavior**
It shouldn't fail?

Related Issue: ForgeEssentials/ForgeEssentials#2588

**Comment by PG85** [comment]
Hey @jcc10 , if you want to create OTG dimensions for Forge, you can always use the in-game O menu to add/delete dimensions. You may have to remap the O button if it's already in use, for MP you need to be opped. I see the issue you've linked has also been responded to, if you still have problems, please try to remove any mods you can to narrow down the possible causes, and feel free to reopen this issue.

**Comment by jcc10** [comment]
I was unaware of that feature. Thank you.
