### ISSUE TITLE
JungleEdge not in BorderBiomes list

### ISSUE THREAD

**Issue by Graagh** [PG85/OpenTerrainGenerator#64]
Ok, last one for tonight I promise! And at least this is an easy one.  In a defalut-generated world written when you use an empty world folder, the JungleEdge biome is correctly coded as a border biome in the biome config file, but will not generate because it isn't in the BorderBiomes list in WorldConfig.ini.  Actually I haven't tested it.  I just assume it won't generate because it's missing from the list.

**Comment by MCPitman** [comment]
Yeah my bad I didn't include it when making the default world.

Not too big a deal, I'll try to get around to fixing it at some point.

**Comment by PG85** [comment]
Woops, still hadn't fixed this! Fixed it for v7, thanks for reporting!

**Comment by PG85** [comment]
*also JungleEdge M
