### ISSUE TITLE
1.16 - Add a datapack folder to the OTG config folder

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#641]
It would be nice if datapacks could be tied to / included in presets and loaded upon world creation, if OTG allowed a folder structure like this:

\config\OpenTerrainGenerator\Presets\Presetname\Datapacks

You could simply drop your datapacks in there and have them load every time a world is created using that preset

**Comment by PG85** [comment]
Forge allows mods to include datapack json files in an easy way, so they're automatically packaged as the mod's own datapack and enabled for worlds when the mod is installed. Hope Spigot can do the same, but this seems like an easy solution, people can include their datapack files in their worldpacker/presetpacker mod.

**Comment by PG85** [comment]
So preset creators can package datapacks via WorldPacker/PresetPacker. For the rest, we can allow people to configure some common things via the worldconfig. Doing that for Forge dimension settings atm, which automatically generates datapack files in the world save folder using worldconfig/world creation ui settings. Don't need an OTG flow for datapacks other than that I think, can rely on existing MC/Forge infrastructure?
