### ISSUE TITLE
More options for specifying mob spawns in biomes. 

### ISSUE THREAD

**Issue by I-am-mimic** [PG85/OpenTerrainGenerator#642]
So far I've loved OTG. I love the layout, the tools and the scripting. It just makes so much sense. However I noticed that when I was customizing the mob spawns for my biome I ran into a problem. I couldn't spawn in a creature with custom NBT data. This is problematic for my preset as I need Piglins to be able to spawn in the overworld without turning into zombie piglins. Fortunately Minecraft has a custom NBT tag you can apply to prevent this. But this NBT isn't applied to mobs when they spawn in naturally. Allowing us to spawn in monsters with custom NBT will allow expand our options for when it comes to spawning. 

Again keep up the amazing work. Your all doing an excellent job. :)

**Comment by SXRWahrheit** [comment]
This might be in scope for post-1.0 on 1.16, but you can also just use the API provided by OTG to handle mob spawning with another plugin or mod (which is what most people do).

**Comment by PG85** [comment]
"I love the layout, the tools and the scripting. It just makes so much sense." You are the first person who's ever said that, we do appreciate that ;).

**Comment by PG85** [comment]
Custom NBT for mobs can only be done when spawning Mobs as a part of customobjects/customstructures (bo3's/bo4), via the Entity() or Spawner() tag. Since we're using the vanilla flow for registering mobs to biomes, unfortunately we won't be able to add NBT there.
