### ISSUE TITLE
1.16 - GrassColor2 & FoliageColor2

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#648]
After discussing in discord it seems this has not carried over to 1.16 because it would require the mod client side. 

A possible solution could be to re-add it but have it so that the client mod is needed to be able to see it, and if not installed then things look as they do right now.

There are hundreds of biomes in Wildlands that make use of this feature so it would be super disappointing to not be able to carry that work over properly from 1.12.

**Comment by BiomeBundle** [comment]
Screenshot of what it does:
![2021-05-21_01 28 32](https://user-images.githubusercontent.com/23154920/119064794-131ff980-b9d4-11eb-9c54-a4bade00a2fd.png)

**Comment by PG85** [comment]
![2021-07-07_01 58 13](https://user-images.githubusercontent.com/6781444/124682518-3f7fce80-decb-11eb-919e-c54c836bb992.png)
Colors be back with 0.0.15, courtesy of Josh!
