### ISSUE TITLE
Settings within the WorldConfig.ini that do not work

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#65]
Here is a list of settings in the WorldConfig.ini that have serious problems or simply do not work:

TerrainMode: Default
TerrainMode: OldGenerator
BiomeMode: Default
BiomeMode: OldGenerator 
ImprovedRivers
UseTemperatureForSnowHeight

**Comment by Arcensoth** [comment]
I was about to report an issue with `ImprovedRivers`, but I'm glad I found this instead.

I'm getting weird chunk-error-like boundaries in select areas bordering water:

[Screenshot](https://imgur.com/iwNHrrn.png)

I've narrowed the problem down to `ImprovedRivers`, as everything works beautifully when this option is disabled.

I'm just getting into OTG, and my understanding so far tells me to manually change each of the river-type biomes' `ReplaceToBiomeName` to that of the containing biome. Would this be an effective work-around?

**Comment by PG85** [comment]
For v8_r3, I've disabled these settings, they are no longer read from or written to configs. @Arcensoth, I hope you've already found answers to your questions, please join us on the OTG Discord at #openterraingen if you have any more questions.
