### ISSUE TITLE
1.16 - bo3 customstructures too common

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#652]
Noticing that bo3 structures are way more common than in 1.12.

Will update this issue once ive made a test preset.

![image](https://user-images.githubusercontent.com/23154920/119038955-a5f86e00-b9ab-11eb-9b09-40c3629fa2f5.png)

**Comment by PG85** [comment]
For 1.16.5-0.0.15, added UseOldBO3StructureRarity to the worldconfig, disabled by default. Enable to use 2 rarities, one from the CustomStructure() tag and one from the BO3 file.
