### ISSUE TITLE
1.12.2 - Game Crash when trying to create a new OTG dimension

### ISSUE THREAD

**Issue by lawrencexli** [PG85/OpenTerrainGenerator#657]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] 1.12.2_v9.4_r1

#### Forge or Spigot Versions
forge 14.23.5.2855

#### Server/Client Log
Description: Updating screen events

java.lang.IllegalArgumentException: Invalid dimension id 2
    at net.minecraft.world.DimensionType.getById(DimensionType.java:77)
    at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:131)
    at com.pg85.otg.forge.dimensions.OTGDimensionManager.registerDimension(OTGDimensionManager.java:82)
    at com.pg85.otg.forge.dimensions.OTGDimensionManager.createDimension(OTGDimensionManager.java:217)
    at com.pg85.otg.forge.dimensions.OTGDimensionManager.createNewDimensionSP(OTGDimensionManager.java:696)
    at com.pg85.otg.forge.gui.dimensions.OTGGuiDimensionList.actionPerformed(OTGGuiDimensionList.java:528)
    at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:443)
    at com.pg85.otg.forge.gui.dimensions.OTGGuiDimensionList.mouseClicked(OTGGuiDimensionList.java:803)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533)
    at com.pg85.otg.forge.gui.dimensions.OTGGuiDimensionList.handleMouseInput(OTGGuiDimensionList.java:776)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

#### What other plugins are you running?
       | State  | ID                   | Version             | Source                                                    | Signature                                |
       |:------ |:-------------------- |:------------------- |:--------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft            | 1.12.2              | minecraft.jar                                             | None                                     |
       | LCHIJA | mcp                  | 9.42                | minecraft.jar                                             | None                                     |
       | LCHIJA | FML                  | 8.0.99.99           | forge-1.12.2-14.23.5.2855.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                | 14.23.5.2855        | forge-1.12.2-14.23.5.2855.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | entity_culling       | 4.1.4               | minecraft.jar                                             | None                                     |
       | LCHIJA | ivtoolkit            | 1.3.3-1.12          | minecraft.jar                                             | None                                     |
       | LCHIJA | otgcore              | 1.12.2-v9.4         | minecraft.jar                                             | None                                     |
       | LCHIJA | smoothfontcore       | mc1.12.2-2.1.2      | minecraft.jar                                             | None                                     |
       | LCHIJA | foamfixcore          | 7.7.4               | minecraft.jar                                             | None                                     |
       | LCHIJA | smoothfont           | mc1.12.2-2.1.2      | SmoothFont-mc1.12.2-2.1.2.jar                             | None                                     |
       | LCHIJA | aiimprovements       | 0.0.1.3             | AIImprovements-1.12-0.0.1b3.jar                           | None                                     |
       | LCHIJA | aireducer            | 0.2.1               | AIReducer-1.12.2-0.2.1.jar                                | None                                     |
       | LCHIJA | openterraingenerator | v9.4                | OpenTerrainGenerator-1.12.2-v9.4_r1 (1).jar               | None                                     |
       | LCHIJA | otgalienjungle       | 1.0                 | Alien_Jungle-1.12.2-v1.0.jar                              | None                                     |
       | LCHIJA | jei                  | 4.16.1.302          | jei_1.12.2-4.16.1.302.jar                                 | None                                     |
       | LCHIJA | quark                | r1.6-179            | Quark-r1.6-179.jar                                        | None                                     |
       | LCHIJA | autoreglib           | 1.3-32              | AutoRegLib-1.3-32.jar                                     | None                                     |
       | LCHIJA | bettercaves          | 1.12.2              | bettercaves-1.12.2-2.0.4.jar                              | None                                     |
       | LCHIJA | forgelin             | 1.8.4               | Forgelin-1.8.4.jar                                        | None                                     |
       | LCHIJA | betterfoliage        | 2.3.1               | BetterFoliage-MC1.12-2.3.2.jar                            | None                                     |
       | LCHIJA | bettermineshafts     | 1.12.2-2.2.1        | BetterMineshaftsForge-1.12.2-2.2.1.jar                    | None                                     |
       | LCHIJA | biomesoplenty        | 7.0.1.2444          | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar             | None                                     |
       | LCHIJA | bbop                 | 1.0                 | Biome_Bundle_O_Plenty-1.12.2_v1.0.jar                     | None                                     |
       | LCHIJA | collective           | 2.26                | collective-1.12.2-2.26.jar                                | None                                     |
       | LCHIJA | dldungeonsjbg        | 1.13.2              | DoomlikeDungeons-1.13.2-MC1.12.2.jar                      | None                                     |
       | LCHIJA | dregora              | 1.0                 | Dregora-1.12.2-v1.66.2.jar                                | None                                     |
       | LCHIJA | orelib               | 3.6.0.1             | OreLib-1.12.2-3.6.0.1.jar                                 | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround            | 3.6.2.1             | DynamicSurroundings-1.12.2-3.6.2.1.jar                    | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | foamfix              | 0.10.14-1.12.2      | foamfix-0.10.14-1.12.2.jar                                | None                                     |
       | LCHIJA | glaretorch           | 8.10                | GlareTorch_Ver.8.11_[MC1.12](forge-1.12-14.21.1.2387).jar | None                                     |
       | LCHIJA | llibrary             | 1.7.20              | llibrary-1.7.20-1.12.2.jar                                | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire           | 1.9.1               | iceandfire-1.9.1-1.12.2.jar                               | None                                     |
       | LCHIJA | lycanitesmobs        | 2.0.7.2 - MC 1.12.2 | lycanitesmobs-1.12.2-2.0.7.2.jar                          | None                                     |
       | LCHIJA | mowziesmobs          | 1.5.8               | mowziesmobs-1.5.8.jar                                     | None                                     |
       | LCHIJA | neat                 | 1.4-17              | Neat+1.4-17.jar                                           | None                                     |
       | LCHIJA | harvestcraft         | 1.12.2zb            | Pam's+HarvestCraft+1.12.2zg.jar                           | None                                     |
       | LCHIJA | performant           | 1.12.2-1.4          | performant-1.12.2-1.10.jar                                | None                                     |
       | LCHIJA | toroquest            | 1.12.2-5.3          | Quest-Revamped-04-22-2021.jar                             | None                                     |
       | LCHIJA | reccomplex           | 1.4.8.2             | RecurrentComplex-1.4.8.2.jar                              | None                                     |
       | LCHIJA | additionalstructures | 2.3.1               | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar          | None                                     |
       | LCHIJA | roguelike            | 1.8.0               | RoguelikeDungeons-1.12.2-1.8.0.jar                        | None                                     |
       | LCHIJA | ruins                | 17.2                | Ruins-1.12.2.jar                                          | None                                     |
       | LCHIJA | rustic               | 1.1.7               | rustic-1.1.7.jar                                          | None                                     |
       | LCHIJA | softerhaybales       | 1.3                 | softerhaybales_1.12.2-1.3.jar                             | None                                     |
       | LCHIJA | spark                | 1.5.2               | spark-forge1122.jar                                       | None                                     |
       | LCHIJA | surge                | 2.0.79              | Surge-1.12.2-2.0.79.jar                                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | texfix               | 4.0                 | TexFix+V-1.12-4.0.jar                                     | None                                     |
       | LCHIJA | torchmaster          | 1.8.4.84            | torchmaster_1.12.2-1.8.4.84.jar                           | 5e9a436b366831c8f54a7e80b015784da69278c6 |
       | LCHIJA | vanillafix           | 1.0.10-150          | VanillaFix-1.0.10-150.jar                                 | None                                     |
       | LCHIJA | phosphor-lighting    | 1.12.2-0.2.7        | phosphor-forge-mc1.12.2-0.2.7-universal.jar               | None                                     |

#### Description
When trying to create a new OTG dimension via the OTG in-game menu (pressing the O button in-game) and specify the dimension ID of that new OTG dimension, the Minecraft will crash and give a "Invalid dimension ID" error. 

The error occurs even the dimension ID is not conflicting with other dimensions.
However, when creating dimensions during creating the world, the game works fine. 

####Step to reproduce
1. Create and enter a new world
2. Press O to open the OTG menu
3. Create a new dimension with any OTG presets, and specify a dimension ID that is not conflicting with other dimensions.

Expected: The dimension is added
Actual: Game crashed with Invalid dimension ID error

**Comment by PG85** [comment]
Thanks for reporting this. As this is the only such report, I can only assume this must be caused by some combination of mods that affect dimensions. Could you track down which exact mods cause the issue? Is it ID 2 specifically?

**Comment by PG85** [comment]
Closing this due to lack of feedback, feel free to reopen if you're still having this issue.
