### ISSUE TITLE
Iceberg SAGC broken on spigot 1.16.5

### ISSUE THREAD

**Issue by AzureAqua** [PG85/OpenTerrainGenerator#658]
#### OTG Plugin or Mod
- [x] OTG Plugin for Spigot

#### OTG Version
- [x] Other - 1.16.5-0.0.11

#### Forge or Spigot Versions
paper-1.16.5-714.jar

#### What other plugins are you running?
![plugins](https://user-images.githubusercontent.com/41600194/120520953-52831880-c3cc-11eb-95c9-9541edb28d3f.png)

#### Description
Using the iceberg SAGC on spigot does not generate any icebergs and the groundblock is ignored, but using the same preset (default with 0.0.11) on forge it works fine.

**Comment by PG85** [comment]
Thanks for reporting this, will use #599 for this.

**Comment by PG85** [comment]
Should be fixed for 0.0.16, to be released on the Discord asap.
