### ISSUE TITLE
Water ambient creatures broken on spigot 1.16.5

### ISSUE THREAD

**Issue by AzureAqua** [PG85/OpenTerrainGenerator#659]
#### OTG Plugin or Mod
- [x] OTG Plugin for Spigot

#### OTG Version
- [x] Other - 1.16.5-0.0.11

#### Forge or Spigot Versions
paper-1.16.5-714.jar

#### What other plugins are you running?
![plugins](https://user-images.githubusercontent.com/41600194/120630223-860e8300-c45e-11eb-84ae-475184c284c4.png)

#### Description
Water ambient creatures don't spawn on spigot, but using the same preset on forge they work fine

**Comment by PG85** [comment]
Hey @AzureAqua , thanks for the feedback. Fixed some mob spawning problems for 0.0.15 that shuold hopefully solve this. Will release 1.16.5 - 0.0.15 on the Discord asap. If you're still seeing this with 0.0.15, feel free to reopen this issue.
