### ISSUE TITLE
Request: Create world with custom name

### ISSUE THREAD

**Issue by Dinolek** [PG85/OpenTerrainGenerator#66]
Hi,
Sorry for using issues for feature request.
I want to create 2 biome bundle worlds, first for creative testing and second for survival.
Can you implement this feature?

Thanks for great mod

**Comment by MCPitman** [comment]
You can already do this if you hit the clone button with Biome Bundle selected on the single player world creation screen.

**Comment by Dinolek** [comment]
Yea, you are right, but i want to change world name with same world settings without cloning.
I requesting that, because of end user experience with modpack.

Thanks for reply

**Comment by Dinolek** [comment]
Ok, i add this on my own by removing disabled state, adding isFocused and always using "Biome Bundle" as config folder
