### ISSUE TITLE
Bo4's Fail to spawn when in close proximity to one another (even if intended)

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#673]
#### OTG Plugin or Mod

- [X] OTG Plugin for Spigot

#### OTG Version
- [x] 1.12.2_v9.4_r1

#### Forge or Spigot Versions
1.12.2-R0.1

#### Description
Scenario: I have two Bo4 strings;

```
CustomStructure(GodlySpike,100.0)
CustomStructure(GodlySpikeCeiling,100.0)
```

For the first generation I will only put in the first: CustomStructure(GodlySpike,100.0) which result into this:
![afbeelding](https://user-images.githubusercontent.com/4073584/122567398-e994d500-d048-11eb-8f73-bf8fd4f461d2.png)

For the second generation I will delete Dregora/Region and Dregora/OpenTerrainGenerator and add CustomStructure(GodlySpikeCeiling,100.0) to the list to make a total of:
```
CustomStructure(GodlySpike,100.0)
CustomStructure(GodlySpikeCeiling,100.0)
```

This has the following result in which you clearly can see that a lot of "GodlySpike" had to make place for GodlySpikeCeiling for reasons that are unknown to me.
![afbeelding](https://user-images.githubusercontent.com/4073584/122567831-658f1d00-d049-11eb-922f-96f45e9a1497.png)

Both bo4's have the following parameters set;

```
Frequency: 0
OverrideChildSettings: true
CanOverride: true
BranchFrequency: 0
BO3Group: NewCrystals:0
```

So the conclusion here is that somehow these two custom structures are running interference with each other when in close proximity to one another.

**Comment by PG85** [comment]
The way BO4's work atm is that any number of branches of the same BO4 may override (if configured to do so), but branches of separate structures may not be in the same chunks. You'll have to find a way to make both floor and ceiling bo4's branches of the same structure. Fortunately you can override parent height on branches and make them do their own highestblock/highestsolidblock/randomY.

**Comment by NLBlackEagle** [comment]
Thats a mild inconvenience with 5 different customstructures at the same location but ill work it out, thanks for the clarification. issue closed

**Comment by PG85** [comment]
Word of warning btw, most Bo4 placement features were made for use on the surface. Things like highestblock/highestsolidblock won't work underground and BO4's don't support blockchecks atm, so you may have a hard time spawning them underground. Not sure how large the crystals are, but if theyre <32x32 you can just spawn them as customobjects? Can also discuss on disc in preset-dev-discussion btw.

**Comment by PG85** [comment]
*What you can do is just make a giant cave bo4 with everything included ofc ;). You can even make any above-ground branches use smoothing areas, and any underground parts not. Would advise a static branching layout to start with though, before getting into randomised branching patterns.
