### ISSUE TITLE
Feature: Add BO4s as an export option in 1.16

### ISSUE THREAD

**Issue by I-am-mimic** [PG85/OpenTerrainGenerator#674]
#### Is your feature request related to a problem? Please describe.
I always hear people talk about bo4s. They seem to be so much better then Bo3s for custom structures but there's one problem I can't export bo4s in 1.16. So if I could be allowed to export Bo4s it would be greatly appreciated.

**Comment by authvin** [comment]
This is in the works, but I've been a bit busy lately. It should be done soon, hopefully

**Comment by FrankTCA** [comment]
Already done. Not sure why we didn't close this already.
