### ISSUE TITLE
1.12 Mineshafts spawn despite being disabled (Only happens with forge)

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#675]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge

#### OTG Version
- [x] 1.12.2_v9.4_r1

#### Forge or Spigot Versions
Forge 1.12.2 14.23.5.2855

#### Description
Mineshafts are spawning even though they are disabled using:

```
MineshaftType: disabled
MineshaftRarity: 0.0

```

Files to reproduce;

Worldconfig; https://pastebin.com/BqrAprvA
BiomeConfig: https://pastebin.com/g4Ycfipv
Map;
![map](https://user-images.githubusercontent.com/4073584/122615145-524f7200-d088-11eb-9c53-8f4019006fe6.png)

**Comment by BiomeBundle** [comment]
Does it happen in 1.16?

**Comment by PG85** [comment]
Thanks for reporting this, for 1.12.2 this has been the same way for so long, don't think we'll fix this. If you have the same issue for 1.16, please make a new issue or rename/reopen this one. Thanks!
