### ISSUE TITLE
Border Biome generates in a between a biome, when it didn't exist before on reload. While also just spraying particles and changing the sky color, not affecting the blocks.

### ISSUE THREAD

**Issue by I-am-mimic** [PG85/OpenTerrainGenerator#676]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] 1.16.5-0.012

#### Forge or Spigot Versions
I am running forge 1.16.5-36.1.32

#### What other plugins are you running?
https://docs.google.com/document/d/18PodlrUTttVyKap7udTtCqoCHHPgzYw-ei2tTCbeLXk/edit?usp=sharing

#### Description
I was recreating worlds to debug my Swamp biome, and decided to change some more settings in the Swamp bc file, before reloading the world. Prior to the reload the So upon reloading a world, with Dev mode turned on, I noticed that the biome was being labeled as a void border. It had the particles and the sky color, but the blocks remained unchanged.
This is what it looks like when the border biome spawns in an already existing biome. Normally the void has little to no blocks in it, and there are smoke particles coming off of it. The water is also frozen. The photo is an improperly generated void biome inside the swamp biome. 
![2021-06-19_18 39 14](https://user-images.githubusercontent.com/74016811/122658868-54b8d700-d12f-11eb-904e-fa382333d4c6.png)

This is what it normally looks like
![2021-06-16_20 31 46](https://user-images.githubusercontent.com/74016811/122658918-b11bf680-d12f-11eb-97e5-f0cac615fed9.png)

This is difficult to replicate properly without the entire preset. However you could try creating a biome similar to this, add another biome to it, and use this as a border.
The swamp biome
Called Swamp Marsh
https://pastebin.com/9rL62pGY

(sorry but I couldn't get pastebin to work on the second link.)
This one is the void biome 

https://gist.github.com/PG85/90f75a5e3c56aa728ce1e081bb461fb5

**Comment by I-am-mimic** [comment]
I'm so sorry about the stupid pastebin not working on the second paste.

**Comment by PG85** [comment]
Thanks for reporting this, there are so many things going on though that it's hard to figure out what the original problem is (requires a specific biome setup, making changes on exit, rejoining etc). There may be a lot of different things that couldve gone wrong. Will need to find a way to reproduce this bug with simple steps, for example with a test preset using only a few biomes and a few steps. If you can narrow things down at all, please let me know.

**Comment by I-am-mimic** [comment]
Ok I’ll make a smaller and easier reproducible example tomorrow. Sorry about that.

**Comment by PG85** [comment]
Feel free to reopen this when you have a repro example, thanks! For any questions, ask on the Discord.
