### ISSUE TITLE
1.16 - Ores from other mods not spawning

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#677]
Installed [Create](https://www.curseforge.com/minecraft/mc-mods/create) which generates copper and zinc ores, however no ores generate in OTG worlds.

Comparison below between Wildlands and Biomes O Plenty with the same (default) Create configuration.

Wildlands:
![2021-06-20_14 30 56](https://user-images.githubusercontent.com/23154920/122676066-250fda80-d1d4-11eb-869e-eca4a405d908.png)

Biomes O Plenty:
![2021-06-20_14 28 57](https://user-images.githubusercontent.com/23154920/122676030-f691ff80-d1d3-11eb-934b-5413662ebb5a.png)

**Comment by Ezoteric** [comment]
I did got the ores from mekanism and libvulpes (advanced rocketry lib)with newest OTG, haven't checked other mods tho

**Comment by PG85** [comment]
Thanks for testing/feedback. For 0.0.13 I've added TemplateForBiome and made some changes to non-otg resource spawning (also for otg biomes). In theory, this should already have worked, but try 0.0.13 to be sure. If this doesn't work, that would indicate that Create doesn't spawn its ores via the normal/expected flow, and there's probably not much more we can do..

**Comment by BiomeBundle** [comment]
Just confirmed that changing developermode to false solves this problem
