### ISSUE TITLE
Bug: 1.16 - Strange and exciting results when using air as ground block in surface and ground control

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#678]
Here is what it looks like when only the SurfaceBlock air (SurfaceAndGroundControl: AIR,DIRT,0.0), it can be used to make some cool effects if the biome is exactly at sea level.

![2021-06-19_04 50 52](https://user-images.githubusercontent.com/23154920/122676451-1aeedb80-d1d6-11eb-822d-c508e6eae404.png)

Here is what happens when both SurfaceBlock and GroundBlock are air (SurfaceAndGroundControl: AIR,AIR,0.0)

![2021-06-19_04 51 49](https://user-images.githubusercontent.com/23154920/122676519-5be6f000-d1d6-11eb-9ca2-9c3d7bd43935.png)

**Comment by PG85** [comment]
For 1.16.5 - 0.0.15, any sagc block that is air (after replaceblocks) is set to waterblock when between waterlevelmin/max.
