### ISSUE TITLE
Caves generating air inside custom ocean fluids

### ISSUE THREAD

**Issue by I-am-mimic** [PG85/OpenTerrainGenerator#685]
#### OTG Plugin or Mod

- [ ] OTG Mod for Forge
- [x] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - 1.16.5-0.0.13

#### Forge or Spigot Versions
Forge 1.16.5-36.1.32
#### What other plugins are you running?
https://docs.google.com/document/d/18PodlrUTttVyKap7udTtCqoCHHPgzYw-ei2tTCbeLXk/edit?usp=sharing
#### Description
Caves seeming to generate inside of custom fluids set as the fluid for a ocean. 
![2021-06-24_21 04 42](https://user-images.githubusercontent.com/74016811/123449594-10975d80-d599-11eb-9785-7e6ae2e7fc97.png)
![2021-06-24_20 54 58](https://user-images.githubusercontent.com/74016811/123449618-1725d500-d599-11eb-8d5a-ec9f4f81ddbe.png)
![2021-06-24_20 55 25](https://user-images.githubusercontent.com/74016811/123449634-1bea8900-d599-11eb-9580-cd8436ebc57c.png)
![2021-06-24_21 04 39](https://user-images.githubusercontent.com/74016811/123449657-21e06a00-d599-11eb-91e1-e20e48b7c1fb.png)
 

Self explanatory. 

1. In the test bc put the custom fluid as lava
2. Set the sea level from 40,0.
3.  Results may vary depending on cave gen settings.

**Comment by PG85** [comment]
Thanks for reporting this, will take a look at making it avoid all liquids, not just water. I assume the carvers just aren't built for that since itd never happen normally. Could look at making it avoid the biome's WaterBlock, although that could cause some funky issues if some user tries to use solid blocks also used elsewhere as water.

**Comment by WACriminalG2** [comment]
> Thanks for reporting this, will take a look at making it avoid all liquids, not just water. I assume the carvers just aren't built for that since itd never happen normally. **Could look at making it avoid the biome's WaterBlock**, although that could cause some funky issues if some user tries to use solid blocks also used elsewhere as water.

For what it's worth, this sounds like the option that would be most useful to me as a preset dev.

**Comment by PG85** [comment]
Looks like vanilla uses different carvers for ocean/land, so may have to add more OTG carver types. Also still have to allow non-otg carvers. 

*Edit: Non-otg carvers have been added for 0.0.14, CavesEnabled/RavinesEnabled in the WorldConfig can be used to toggle OTG carvers on/off.

**Comment by PG85** [comment]
For 0.0.15 I've made OTG carvers check for liquids, rather than just water. To be released on the discord asap. Thanks for reporting!
