### ISSUE TITLE
The game crashed whilst exception in server tick loop Error: java.lang.ClassCastException: com.pg85.otg.forge.generator.structure.OTGVillageGen cannot be cast to net.minecraft.world.gen.structure.MapGenVillage Exit Code: -1

### ISSUE THREAD

**Issue by bogboybingles** [PG85/OpenTerrainGenerator#692]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge yes
- [ ] OTG Plugin for Spigot no

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x] 1.12.2_v8_r1    x
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
[The full Spigot Server or Forge versions that you are running]
forge 1.12.2
#### Server/Client Log
[The full latest.log file from your server or game client, especially important if you have a stack trace]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  FMLPlugin (albedo-1.12.2-1.1.0.jar)
  clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.2.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  OTGCorePlugin (OTG-Core.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 6/29/21 9:23 AM
Description: Exception in server tick loop

java.lang.ClassCastException: com.pg85.otg.forge.generator.structure.OTGVillageGen cannot be cast to net.minecraft.world.gen.structure.MapGenVillage
	at com.piggywiggy3.movillages.handlers.MapGenEventHandler.onMapGenInit(MapGenEventHandler.java:24)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1215_MapGenEventHandler_onMapGenInit_InitMapGenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.terraingen.TerrainGen.getModdedMapGen(TerrainGen.java:48)
	at com.pg85.otg.forge.world.ForgeWorld.provideWorldInstance(ForgeWorld.java:163)
	at com.pg85.otg.forge.world.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:367)
	at com.pg85.otg.forge.world.OTGWorldType.getBiomeProvider(OTGWorldType.java:158)
	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:58)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:40)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:116)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:121)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2431062448 bytes (2318 MB) / 6669991936 bytes (6361 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 124 mods loaded, 124 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                            | Version             | Source                                           | Signature                                |
	|:------ |:----------------------------- |:------------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft                     | 1.12.2              | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                           | 9.42                | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                           | 8.0.99.99           | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                         | 14.23.5.2855        | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | otgcore                       | 1.12.2-v9.3         | minecraft.jar                                    | None                                     |
	| LCHIJA | obfuscate                     | 0.4.2               | minecraft.jar                                    | None                                     |
	| LCHIJA | clothesline-hooks             | 1.12.2-0.0.1.2      | minecraft.jar                                    | None                                     |
	| LCHIJA | albedocore                    | 0.1                 | minecraft.jar                                    | None                                     |
	| LCHIJA | vclothes                      | 2.9.6               | [1.12.2] Valtiel s Clothes Mod-2.3.1.jar         | None                                     |
	| LCHIJA | bspkrscore                    | 8.0.0               | [1.12.2]bspkrscore-universal-8.0.1.jar           | None                                     |
	| LCHIJA | movillages                    | 1.5.4               | [1.12]MoVillages-1.5.4.jar                       | None                                     |
	| LCHIJA | treecapitator                 | 1.43.0              | [1.12]TreeCapitator-client-1.43.0.jar            | None                                     |
	| LCHIJA | albedotorches                 | 1.0.4               | AlbedoTorches-1.0.4.jar                          | None                                     |
	| LCHIJA | albedo                        | 1.0.0               | albedo-1.12.2-1.1.0.jar                          | None                                     |
	| LCHIJA | animalbikes                   | 1.11.2              | AnimalBikes_1.12.2(13Jan19).jar                  | None                                     |
	| LCHIJA | antiqueatlas                  | 4.6.3               | antiqueatlas-1.12.2-4.6.3.jar                    | None                                     |
	| LCHIJA | antiqueatlasoverlay           | 1.2                 | antiqueatlas-1.12.2-4.6.3.jar                    | None                                     |
	| LCHIJA | jei                           | 4.16.1.301          | jei_1.12.2-4.16.1.301.jar                        | None                                     |
	| LCHIJA | appleskin                     | 1.0.14              | AppleSkin-mc1.12-1.0.14.jar                      | None                                     |
	| LCHIJA | mantle                        | 1.12-1.3.3.55       | Mantle-1.12-1.3.3.55.jar                         | None                                     |
	| LCHIJA | ctm                           | MC1.12.2-1.0.2.31   | CTM-MC1.12.2-1.0.2.31.jar                        | None                                     |
	| LCHIJA | chisel                        | MC1.12.2-1.0.2.45   | Chisel-MC1.12.2-1.0.2.45.jar                     | None                                     |
	| LCHIJA | tombstone                     | 4.4.3               | tombstone-4.4.3-1.12.2.jar                       | None                                     |
	| LCHIJA | quark                         | r1.6-179            | Quark-r1.6-179.jar                               | None                                     |
	| LCHIJA | tconstruct                    | 1.12.2-2.13.0.183   | TConstruct-1.12.2-2.13.0.183.jar                 | None                                     |
	| LCHIJA | thedragonlib                  | 1.12.2-5.3.0        | thedragonlib-1.12.2-5.3.0.jar                    | None                                     |
	| LCHIJA | armorplus                     | 1.12.2-11.28.0.69   | armorplus-1.12.2-11.28.0.69.jar                  | None                                     |
	| LCHIJA | baubles                       | 1.5.2               | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCHIJA | artifacts                     | 1.12.2-1.2.3        | Artifacts-1.12.2-1.2.3.jar                       | None                                     |
	| LCHIJA | autoreglib                    | 1.3-32              | AutoRegLib-1.3-32.jar                            | None                                     |
	| LCHIJA | baublelicious                 | 1.4.0-4             | Baublelicious-1.4.0-4.jar                        | None                                     |
	| LCHIJA | baubleshulkerboxes            | 4r                  | BaubleShulkerBoxes-1.12.2-4r.jar                 | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | betterbuilderswands           | 0.11.1              | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar  | None                                     |
	| LCHIJA | bettercaves                   | 1.12.2              | bettercaves-1.12.2-2.0.4.jar                     | None                                     |
	| LCHIJA | bettermineshafts              | 1.12.2-2.2.1        | BetterMineshaftsForge-1.12.2-2.2.1.jar           | None                                     |
	| LCHIJA | bibliocraft                   | 2.4.5               | BiblioCraft[v2.4.5][MC1.12.2].jar                | None                                     |
	| LCHIJA | openterraingenerator          | v9.3                | OpenTerrainGenerator-1.12.2-v9.3.jar             | None                                     |
	| LCHIJA | biomebundle                   | 5.1                 | Biome_Bundle-1.12.2-v6.1.jar                     | None                                     |
	| LCHIJA | bonsaitrees                   | 1.1.4               | bonsaitrees-1.1.4-b170.jar                       | None                                     |
	| LCHIJA | capsule                       | 1.12.2-3.3.11       | Capsule-1.12.2-3.3.11.jar                        | None                                     |
	| LCHIJA | forestry                      | 5.8.2.387           | forestry_1.12.2-5.8.2.387.jar                    | None                                     |
	| LCHIJA | careerbees                    | 1.0                 | careerbees-0.4.0.jar                             | None                                     |
	| LCHIJA | cat                           | 0.1                 | CavesAndDungeonsMod.jar                          | None                                     |
	| LCHIJA | chameleon                     | 1.12-4.1.3          | Chameleon-1.12-4.1.3.jar                         | None                                     |
	| LCHIJA | chiselsandbits                | 14.33               | chiselsandbits-14.33.jar                         | None                                     |
	| LCHIJA | clothingmodbetav04bytitoo8899 | v.0.4               | Clothing Mod Beta v.0.4 by Titoo8899.jar         | None                                     |
	| LCHIJA | clumps                        | 3.1.2               | Clumps-3.1.2.jar                                 | None                                     |
	| LCHIJA | codechickenlib                | 3.2.3.358           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux                  | 2.1.1               | RedstoneFlux-1.12-2.1.1.1-universal.jar          | None                                     |
	| LCHIJA | cofhcore                      | 4.6.6               | CoFHCore-1.12.2-4.6.6.1-universal.jar            | None                                     |
	| LCHIJA | cofhworld                     | 1.4.0               | CoFHWorld-1.12.2-1.4.0.1-universal.jar           | None                                     |
	| LCHIJA | collective                    | 2.26                | collective-1.12.2-2.26.jar                       | None                                     |
	| LCHIJA | comforts                      | 1.4.1.3             | comforts-1.12.2-1.4.1.3.jar                      | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | conarm                        | 1.2.5.10            | conarm-1.12.2-1.2.5.10.jar                       | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHIJA | cookingforblockheads          | 6.5.0               | CookingForBlockheads_1.12.2-6.5.0.jar            | None                                     |
	| LCHIJA | cosmeticarmorreworked         | 1.12.2-v5a          | CosmeticArmorReworked-1.12.2-v5a.jar             | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | ptrmodellib                   | 1.0.5               | PTRLib-1.0.5.jar                                 | None                                     |
	| LCHIJA | props                         | 2.6.3.7             | Decocraft-2.6.3.7_1.12.2.jar                     | None                                     |
	| LCHIJA | ding                          | 1.0.2               | Ding-1.12.2-1.0.2.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | enchdesc                      | 1.1.15              | EnchantmentDescriptions-1.12.2-1.1.15.jar        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | extrautils2                   | 1.0                 | extrautils2-1.12-1.9.9.jar                       | None                                     |
	| LCHIJA | fairylights                   | 2.1.10              | fairylights-2.2.0-1.12.2.jar                     | None                                     |
	| LCHIJA | fancylamps                    | 1.2.1               | fancylamps-1.2.1.jar                             | None                                     |
	| LCHIJA | farmingforblockheads          | 3.1.28              | FarmingForBlockheads_1.12.2-3.1.28.jar           | None                                     |
	| LCHIJA | fastleafdecay                 | v14                 | FastLeafDecay-v14.jar                            | None                                     |
	| LCHIJA | cfm                           | 6.3.1               | furniture-6.3.1-1.12.2.jar                       | None                                     |
	| LCHIJA | hammerx                       | ${version}          | hammerx-1.12-1.1.4.jar                           | None                                     |
	| LCHIJA | waila                         | 1.8.26              | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LCHIJA | inventorypets                 | 2.0.15              | inventorypets-1.12-2.0.15.jar                    | None                                     |
	| LCHIJA | ironchest                     | 1.12.2-7.0.67.844   | ironchest-1.12.2-7.0.72.847.jar                  | None                                     |
	| LCHIJA | journeymap                    | 1.12.2-5.7.1        | journeymap-1.12.2-5.7.1.jar                      | None                                     |
	| LCHIJA | harvestcraft                  | 1.12.2zb            | Pam's HarvestCraft 1.12.2zg.jar                  | None                                     |
	| LCHIJA | jehc                          | 1.7.2               | just-enough-harvestcraft-1.12.2-1.7.2.jar        | None                                     |
	| LCHIJA | jeresources                   | 0.9.2.60            | JustEnoughResources-1.12.2-0.9.2.60.jar          | None                                     |
	| LCHIJA | sturcturemod                  | 0.1                 | Little_Structures_mod_1.12.2_v1.0.jar            | None                                     |
	| LCHIJA | mca                           | 6.1.0               | MCA-1.12.2-6.1.0-universal.jar                   | None                                     |
	| LCHIJA | mekanism                      | 1.12.2-9.8.3.390    | Mekanism-1.12.2-9.8.3.390.jar                    | None                                     |
	| LCHIJA | mekanismgenerators            | 1.12.2-9.8.3.390    | MekanismGenerators-1.12.2-9.8.3.390.jar          | None                                     |
	| LCHIJA | mekanismtools                 | 1.12.2-9.8.3.390    | MekanismTools-1.12.2-9.8.3.390.jar               | None                                     |
	| LCHIJA | end_overload_mod              | 1.3                 | minecraft_end_overload_v1.3.0_forge1.12.2.jar    | None                                     |
	| LCHIJA | mininghelmet                  | 1.0                 | MiningHelmet-1.3.jar                             | None                                     |
	| LCHIJA | mm_lib                        | 2.3.0               | MMLib-2.3.0.jar                                  | None                                     |
	| LCHIJA | mobends                       | 1.0.0-beta-20.06.20 | MoBends_1.12.2-1.0.0-beta-20.06.20.jar           | None                                     |
	| LCHIJA | modnametooltip                | 1.10.1              | modnametooltip_1.12.2-1.10.1.jar                 | None                                     |
	| LCHIJA | mousetweaks                   | 2.10                | MouseTweaks-2.10-mc1.12.2.jar                    | None                                     |
	| LCHIJA | naturescompass                | 1.8.5               | NaturesCompass-1.12.2-1.8.5.jar                  | None                                     |
	| LCHIJA | neid                          | 1.5.4.4             | NotEnoughIDs-1.5.4.4.jar                         | None                                     |
	| LCHIJA | notenoughroofs                | 0.8.0.1             | notenoughroofs-1.12.2-0.8.0.1.jar                | None                                     |
	| LCHIJA | openglider                    | @VERSION@           | OpenGlider-1.12.1-1.1.0.jar                      | None                                     |
	| LCHIJA | orespawn                      | 3.3.1               | OreSpawn-1.12-3.3.1.179.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | brewcraft                     | 1.12.2-1.0.2        | Pam's BrewCraft 1.12.2-1.0.2.jar                 | None                                     |
	| LCHIJA | pixelmon                      | 8.2.0               | Pixelmon-1.12.2-8.2.0-universal.jar              | None                                     |
	| LCHIJA | pixelmon_clothes              | 1.2.3               | pixelmonclothes-1.2.3.jar                        | None                                     |
	| LCHIJA | pixelmoninformation           | 0.3.9               | PixelmonInformation-1.12.2-8.2.0-0.3.9.jar       | None                                     |
	| LCHIJA | placebo                       | 1.6.0               | Placebo-1.12.2-1.6.0.jar                         | None                                     |
	| LCHIJA | pogosticks                    | 1.3.1               | PogoSticks-1.12.2-1.3.1.jar                      | None                                     |
	| LCHIJA | randomthings                  | 4.2.7.4             | RandomThings-MC1.12.2-4.2.7.4.jar                | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | reborncore                    | 3.19.5              | RebornCore-1.12.2-3.19.5-universal.jar           | None                                     |
	| LCHIJA | thermalfoundation             | 2.6.7               | ThermalFoundation-1.12.2-2.6.7.1-universal.jar   | None                                     |
	| LCHIJA | thermalexpansion              | 5.5.7               | ThermalExpansion-1.12.2-5.5.7.1-universal.jar    | None                                     |
	| LCHIJA | redstonearsenal               | 2.6.6               | RedstoneArsenal-1.12.2-2.6.6.1-universal.jar     | None                                     |
	| LCHIJA | xreliquary                    | 1.12.2-1.3.4.796    | Reliquary-1.12.2-1.3.4.796.jar                   | None                                     |
	| LCHIJA | additionalstructures          | 2.3.1               | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar | None                                     |
	| LCHIJA | runningshoesmod               | 1.2                 | runningshoesmod-1.2.jar                          | None                                     |
	| LCHIJA | rustic                        | 1.1.7               | rustic-1.1.7.jar                                 | None                                     |
	| LCHIJA | sakura                        | 1.0.7-1.12.2        | Sakura-1.0.7-1.12.2.jar                          | None                                     |
	| LCHIJA | savemystronghold              | 1.12.2-1.0.0        | savemystronghold-1.12.2-1.0.0.jar                | None                                     |
	| LCHIJA | sit                           | v1.3                | sit-1.12.2-v1.3.jar                              | None                                     |
	| LCHIJA | skyes_bakery                  | 2.1.1               | Skye's Bakery 2.1.1 for MC1.12.2.jar             | None                                     |
	| LCHIJA | stevescarts                   | 2.4.32.137          | StevesCarts-1.12.2-2.4.32.137.jar                | None                                     |
	| LCHIJA | storagedrawers                | 5.2.2               | StorageDrawers-1.12.2-5.4.2.jar                  | None                                     |
	| LCHIJA | sm                            | 1.1                 | Sunglasses and more 1.1.jar                      | None                                     |
	| LCHIJA | thermaldynamics               | 2.5.6               | ThermalDynamics-1.12.2-2.5.6.1-universal.jar     | None                                     |
	| LCHIJA | thermalinnovation             | 0.3.6               | ThermalInnovation-1.12.2-0.3.6.1-universal.jar   | None                                     |
	| LCHIJA | wild_area                     | 1.5.0               | TheWildArea_v1.5.0.jar                           | None                                     |
	| LCHIJA | tinkersjei                    | 1.2                 | tinkersjei-1.2.jar                               | None                                     |
	| LCHIJA | toastcontrol                  | 1.8.1               | Toast Control-1.12.2-1.8.1.jar                   | None                                     |
	| LCHIJA | underwater                    | 0.9.3               | underwater-0.9.3.1.jar                           | None                                     |
	| LCHIJA | vehicle                       | 0.44.1              | vehicle-mod-0.44.1-1.12.2.jar                    | None                                     |
	| LCHIJA | villagespawnpoint             | 1.5                 | villagespawnpoint_1.12.2-1.5.jar                 | None                                     |
	| LCHIJA | wawla                         | 2.6.275             | Wawla-1.12.2-2.6.275.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | weeeflowers                   | 1.12.2b             | Weee! Flowers 1.12.2b.jar                        | None                                     |
	| LCHIJA | yamda                         | 0.0.0.yamda         | YAMDA-1.0.2.jar                                  | None                                     |
	| LCHIJA | clothesline                   | 1.12.2-0.0.2.2      | clothesline-1.12.2-0.0.3.0-bundle.jar            | 3bae2d07b93a5971335cb2de15230c19c103db32 |

	Loaded coremods (and transformers): 
Plugin (NotEnoughIDs-1.5.4.4.jar)
  ru.fewizz.neid.asm.Transformer
LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  lumien.randomthings.asm.ClassTransformer
FMLPlugin (albedo-1.12.2-1.1.0.jar)
  elucent.albedo.asm.ASMTransformer
clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.2.jar)
  com.jamieswhiteshirt.clothesline.hooks.plugin.ClassTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.19.5
		Runtime Debofucsation 1
		Invalid fingerprint detected for RebornCore!
		RenderEngine: 0
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

#### What other plugins are you running?
[List of your Mods or Plugins installed, ideally with versions]
no plugins
#### Description
[What is happening? - Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures;)]
crashes when i create a world
[What did you expect to happen? - Explain what you expected to happen after performing the previously described steps]
create a world without it crashing
[Can you provide a Minimal, Reproducible Example? See here for details: https://stackoverflow.com/help/minimal-reproducible-example]
what?

And Delete the lines in square brackets!

**Comment by PG85** [comment]
Hey @bogboybingles , thanks for the report. This is a known issue, see https://github.com/PG85/OpenTerrainGenerator/issues/573. We won't be fixing this for 1.12.2, but you may be able to disable OTG's villages to solve the issue.

**Comment by bogboybingles** [comment]
ok
