### ISSUE TITLE
Mod cave gen not working

### ISSUE THREAD

**Issue by katarinamechanics** [PG85/OpenTerrainGenerator#698]
#### OTG Plugin or Mod
- [x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ x] Other - 1.16.5

#### Forge or Spigot Versions
forge 36.1.1.0

#### What other plugins are you running?
[List of your Mods or Plugins installed, ideally with versions]
Yungs Better caves 1.16.4-1.16.5 1.1.2

#### Description
Caves themselves are not generating, however underground structures (mineshafts etc) as well as lava pockets are generating.

To reproduce: Use an OTG preset with yungs better caves and generate a new world.

**Comment by PG85** [comment]
Hey @katarinamechanics , thanks for reporting. this has been fixed for 0.0.14, to be released on the OTG Discord asap.
