### ISSUE TITLE
1.16 source block tags

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#704]
https://docs.google.com/spreadsheets/d/1dqtJPEyaIlQeHmuAqijVP4WLcpFuTc_U53TLMRetUG4/edit?usp=sharing

**Comment by PG85** [comment]
Have been added for 0.0.15 for Forge, still need to look at spigot.

**Comment by PG85** [comment]
Have been added for 0.0.15 Spigot.
