### ISSUE TITLE
[Recurrent Complex compatibility] Generated structures in villages are abruptly chopped

### ISSUE THREAD

**Issue by Ivorforce** [PG85/OpenTerrainGenerator#71]
See https://github.com/BiomeBundle/BiomeBundle/issues/56

As I understand it, OTG does the gruntwork / generation for Biome Bundle and would thus be responsible for the behavior, correct?

I'd be interested in tracking this down and getting it fixed.

**Comment by MCPitman** [comment]
Yeah this would be a fix on the OTG side, joining our discord to talk to PG could be the quickest way to resolve this.

https://discord.gg/UXzdVTH

**Comment by Ivorforce** [comment]
Oh right, #26 exists as well. Closing this as a duplicate.
