### ISSUE TITLE
OTG + RC - Use IMC to register/unregister dimensions

### ISSUE THREAD

**Issue by PG85** [PG85/OpenTerrainGenerator#72]
https://github.com/Ivorforce/RecurrentComplex/blob/master/src/main/java/ivorius/reccomplex/RCCommunicationHandler.java#L94

With this implemented RC can use a different config for each dimension.

**Comment by Ivorforce** [comment]
Pre-Implemented version:

https://github.com/Ivorforce/RecurrentComplex/blob/master/src/main/java/ivorius/reccomplex/RCCommunicationAdapter.java#L40-L48

**Comment by PG85** [comment]
@Ivorforce I've made OTG call registerDimension and unregisterDimension as per your example, I'm not sure what I should pass in the types parameter though (null atm)?

**Comment by Ivorforce** [comment]
It's basically tags for your dimension - exactly the same as for the Biome Dictionary.

https://github.com/Ivorforce/RecurrentComplex/blob/master/src/main/java/ivorius/reccomplex/dimensions/DimensionDictionary.java 

Here are some examples of what I'm thinking of. It's basically information about the dimension itself (Has a floor? Has a sky? Atmosphere toxic gas? Has Gravity? etc.). The more specific you are, the easier it is for people to react based on your categorization :)

**Comment by PG85** [comment]
Ohh that's cool. I'll have to do some more work to make a proper system so users can provide some sensical tags for their worlds. If for the first version I just send null, will that be enough to test the basic functionality already (different RC config for each world/dim)?

**Comment by Ivorforce** [comment]
You can probably at least attach a generic OPEN_TERRAIN_GENERATOR tag to everything, as well as possibly one or two of the default tags :)

**Comment by PG85** [comment]
Have added the "OPEN_TERRAIN_GENERATOR" for the next release (1.12.2 v6 1.11.2 v10).
