### ISSUE TITLE
Server crash with com.pg85.otg.forge.ForgeWorld.setBlock

### ISSUE THREAD

**Issue by BakermanLP** [PG85/OpenTerrainGenerator#73]
Here is a complete CrashLog:
https://gist.github.com/DerOli82/11dc4b35c4e8f8073d10d2f7f03b736c

Used Versions are seen in this crash log.

The biome configs are BiomeBundle modified.

**Comment by PG85** [comment]
Thanks for reporting this, this should have been fixed with 1.12.2 v2 and / v1.11.2 v9 (release asap).
