### ISSUE TITLE
Feature: Update the command help text for "/OTG export" in 1.16

### ISSUE THREAD

**Issue by LordSmellyPants** [PG85/OpenTerrainGenerator#731]
Provide additional command descripton when initiating "/OTG Export" in game

i.e: Export <name> [centre_block] [-a include_air] [-t include_tile_entities] [-o override] [-bo4] [-b use branches]

(as shown in previous OTG version on attached image)

![image](https://user-images.githubusercontent.com/15055078/125174697-376fa980-e1bf-11eb-9017-66f6bb1b1c36.png)

**Comment by PG85** [comment]
Up to @authvin if he'd like to pick this up for 0.0.1 or 0.1.0.

**Comment by authvin** [comment]
I'll do this when the command is finalized, it's been in a state of flux as to which arguments come where. I can add a simple one for the next build though

**Comment by FrankTCA** [comment]
Is this one finished?

**Comment by authvin** [comment]
Needs another pass

**Comment by FrankTCA** [comment]
Has already been handled, just we forgot to close.
