### ISSUE TITLE
Lava source blocks ignoring block source and spawning wherever

### ISSUE THREAD

**Issue by I-am-mimic** [PG85/OpenTerrainGenerator#741]
#### OTG Plugin or Mod

- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] 1.16.5-0.0.15

#### Forge or Spigot Versions
Forge 36.1.25

#### What other plugins are you running?
https://docs.google.com/document/d/18PodlrUTttVyKap7udTtCqoCHHPgzYw-ei2tTCbeLXk/edit?usp=sharing

#### Description
The Liquid is ignoring the block source settings and replacing blocks.
The biomes this is occuring in so far
![2021-07-12_11 09 34](https://user-images.githubusercontent.com/74016811/125330161-a0603a00-e303-11eb-821f-595624d1cc4f.png)

https://hastebin.com/uqoyoyebep.apache
https://hastebin.com/fodalecila.apache
https://hastebin.com/ijevekecud.coffeescript

![2021-07-12_11 09 38](https://user-images.githubusercontent.com/74016811/125330171-a524ee00-e303-11eb-981e-4defc3474c31.png)
![2021-07-12_11 23 20](https://user-images.githubusercontent.com/74016811/125330185-a81fde80-e303-11eb-8924-5087ace13cda.png)

I did not expect lava source blocks to generate on surface

### Steps to Reproduce
1. In a bc file add the Liquid command
2. Set the parameters and the block source
3.  If done the correctly the lava should spawn anywhere in height range it was programmed in.

**Comment by I-am-mimic** [comment]
After some more testing I found out that the lava was even spawning in biomes that don't have liquid set up.

**Comment by PG85** [comment]
Hey @fjdlafjld, there is a know issue with carvers for 0.0.15, causing them to fill up with lava and sometimes spawning lava at the surface. You can disable carvers via the worldconfig (RavinesEnabled:false / CavesEnabled: false). Also disable any other resources / settings that use lava to make sure it's the Liquid resource causing the problem. If it is, please share your biomeconfig settings.

**Comment by I-am-mimic** [comment]
Thanks for letting me know. So far disabling carvers and ravines has fixed the problem. Does this mean that if I want caves that I'm gonna need to use a cave gen mod?

**Comment by Jishuna** [comment]
> 
> 
> Thanks for letting me know. So far disabling carvers and ravines has fixed the problem. Does this mean that if I want caves that I'm gonna need to use a cave gen mod?

This will be fixed in 0.0.16, to be released soon.
