### ISSUE TITLE
ReplaceBlock don’t work with blockstates

### ISSUE THREAD

**Issue by SpiderDeluxe** [PG85/OpenTerrainGenerator#743]
#### OTG Plugin or Mod
- [ ] OTG Mod for Forge
- [x] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] 1.16.5-0.0.15

#### Forge or Spigot Versions
1.16.5

#### What other plugins are you running?
Only Essentials, WorldGuard, WorldEdit, Essentials-Spawn

#### Description

When the plugin loads my biomes, Replace Blocks containing blocks that have custom blockstates don't work due to a formatting error:

Example:
[01:38:37 ERROR]: [otg] [Configs] The value "(minecraft:gravel,minecraft:sand,50,63),(minecraft:sandstone,minecraft:note_block[instrument=banjo,note=1,powered=false],64,256),(minecraft:gravel,minecraft:note_block[instrument=banjo,note=2,powered=false],64,255),(minecraft:note_block[instrument=banjo,note=1,powered=false],minecraft:stone,63,72)" is not valid for the setting ReplacedBlocks in SandyDunes on line 116: Replace parts must be in the format (from,to) or (from,to,minHeight,maxHeight)

I hope that the plugin considers blockstates without generating errors and that my biomes don't have this kind of hitch.

#### Steps to reproduce
1. Sets a replaceblock to a biome, which uses blocks with custom blockstates.

for example: (minecraft:sandstone,minecraft:note_block[instrument=banjo,note=1,powered=false],64,256)

2. Restart the server with scrive logs for Configs
3.  You will notice the format error in the console and that the replacedBlock will not work on the server

**Comment by PG85** [comment]
Hey @SpiderDeluxe , thanks for reporting this. I assume the comma's in the block data are causing the parsing issues, any OTG settings that use comma's may be affected. Will look at this for 0.0.16.

**Comment by PG85** [comment]
This may affect any setting that uses materials and comma's:
- ReplacedBlocks
- BiomeConfig resources
- SurfaceAndGroundControl
- BO functions (Block() etc)

**Comment by SpiderDeluxe** [comment]
> Hey @SpiderDeluxe , thanks for reporting this. I assume the comma's in the block data are causing the parsing issues, any OTG settings that use comma's may be affected. Will look at this for 0.0.16.

Thanks to you and the OTG team working on this great plugin, I look forward to new feedback

**Comment by PG85** [comment]
Will just keep this issue open until we fix the problem, thanks!

**Comment by PG85** [comment]
Should be fixed for 0.0.16, to be released on the discord asap.
