### ISSUE TITLE
Crash: 1.12.2 BO3 MinecraftObject causes crash

### ISSUE THREAD

**Issue by PersonTheCat** [PG85/OpenTerrainGenerator#75]
OTG-1.12.2-v1. Confirmed working in OTG-1.10.2-v16.

**Comment by PG85** [comment]
Hey, thanks for reporting this and congratulations, I think you're probably the first person to actually try and use MinecraftObject in a BO3 :o. Could you provide a crash log by any chance?

**Comment by PersonTheCat** [comment]
Sure thing. [Crash Report](https://pastebin.com/hKtrRfdZ), [sample BO3](https://pastebin.com/GhqD27HV).

**Comment by PG85** [comment]
Thanks! Looking at the code I think I solved this already with 1.12.2-v2 :).

**Comment by PersonTheCat** [comment]
Sadly, this bug is still around in v2 and v4. As of v4, the debug log now reports that MincraftObject() is an invalid resource. [Crash report](https://pastebin.com/0hUpY9u1)

**Comment by totemo** [comment]
Just a reminder that this is still broken in 1.12.2 - v6.

**Comment by totemo** [comment]
Good to see you're still working on this @PG85.

**Comment by PG85** [comment]
Seems like this has been broken for years and will cost some time to fix, will have to do this after 1.13 unfortunately.

**Comment by PersonTheCat** [comment]
Thanks. I've considered looking into this myself, but updating both of my mods to 1.14 has already taken me so long that I'm kind of at a stalemate. :/ Thanks for the update!

**Comment by PG85** [comment]
Won't be fixing this for 1.12.2, still have to see about implementing MinecarftObject for 1.16.
