### ISSUE TITLE
Bug: Liquid() does not work on spgiot 1.16.5

### ISSUE THREAD

**Issue by AzureAqua** [PG85/OpenTerrainGenerator#754]
#### OTG Plugin or Mod
- [x] OTG Plugin for Spigot

#### OTG Version
- [x] Other - OpenTerrainGenerator-1.16.5-0.0.16

#### Forge or Spigot Versions
paper-1.16.5-782.jar

#### What other plugins are you running?
![plugins](https://user-images.githubusercontent.com/41600194/126062010-6e86af4f-4786-4434-b8ac-ee77b7c4e0eb.png)

#### Description
Liquid resource does not work in spigot, but using the same preset in forge liquids spawn fine

**Comment by FrankTCA** [comment]
Patched this issue. Will be available next release.
