### ISSUE TITLE
Feature: FixedRotation setting for Bo4's

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#755]
#### Is your feature request related to a problem? Please describe.
Without the option to fix a rotation it is next to impossible to create bo4's that involve the direction of the sun or any bo4 that involves directional information (e.g. dungeon mazes with directives in books)

#### Describe the solution you'd like
A setting to fix the rotation.

#### Describe alternatives you've considered
placing biomes in a certain order to lock the object rotation. Theoretically due to the plotter plotting in rectangular shapes the structure would however still be able to flip on 1 axis

**Comment by PG85** [comment]
Added for 0.0.19
