### ISSUE TITLE
OTG + TF: Biome cast crash for 1.12.2 v2

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#76]
https://pastebin.com/u4WQbPx7

**Comment by PG85** [comment]
Looks like TF is making the assumption that the class of a biome it has a reference to is analogous to the vanilla forest biome's class, which in this case isn't true. Could fix that on the OTG end by making sure that any biome that replaces a vanilla biome uses a class that inherits from the vanilla biome's class. Would be a lot of work though and shouldn't really be necessary, it would be better if TF used another way to determine whether the biome it has a reference to is really a forest biome. I also wonder why TF needs to cast the biome to a Forest, that should only be necessary if the Forest class exposes members that its superclasses don't. Usually you can make due just refering to biomes as biomes, no need to be more specific, the biome class exposes all the necessary functions. Will take a look at TF's source code later to see what they're doing.

**Comment by Shadows-of-Fire** [comment]
If you are going to replace instances, you need to maintain hierarchy.  This is not something for TF to fix.

**Comment by fmohican** [comment]
Oh nice same problem tehre.
[Logs](https://gist.github.com/fmohican/3e84c842b94aa1573e9d9ed77cff5d5d)

**Comment by Alaberti** [comment]
Question: Is this being worked on here or there?

**Comment by PG85** [comment]
https://github.com/TeamTwilight/twilightforest/issues/348

**Comment by Wisecompany** [comment]
I'm having this issue too. Also wanting to know if a fix is being worked on.

**Comment by PG85** [comment]
Related to #104, will close this issue and continue there.
