### ISSUE TITLE
OTG in-game menu bug

### ISSUE THREAD

**Issue by Jeoxis36** [PG85/OpenTerrainGenerator#760]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - specify here 1.12.2_v9.3

#### Forge or Spigot Versions
[Playing on forge 14.23.5.2854]

#### What other plugins are you running?
[Playing with the modpack Roguelike Adventures and Dungeons]

#### Description
[I use the pregenerator for my solo map but when i'm tapping on my o key, (key for opening OTG in-game menu), to see the advance of the pregen, it doesn't work, nothing is happening. How can I fix it? btw my o key is only assigned to the OTG menu]

**Comment by Jishuna** [comment]
You must have cheats enabled in single-player or be OPed in multiplayer.

**Comment by Jeoxis36** [comment]
Oh that's works! thank you for the quick reply
