### ISSUE TITLE
Bug: 1.16.x - Mobs suffocating inside blocks

### ISSUE THREAD

**Issue by FrankTCA** [PG85/OpenTerrainGenerator#764]
Mobs are spawning and suffocating inside blocks, apparently belonging to resources.

[Screenshot](https://infotoast.org/ToastCDN/uploads/Frank/1627172643/InsideBlocks.png)

I spawned with a pig in a tree, then teleported to a village to see both an iron golem and a wolf inside of a block suffocating.

Seed: -2451338975745658751

**Comment by PG85** [comment]
Should find a way to reproduce reliably and debug. Should make sure this doesn't also happen for vanilla in similar circumstances, and check whether Forge has the same problem (haven't seen it myself recently).

**Comment by FrankTCA** [comment]
Tested this seed on Spigot vanilla. The same thing happens. So I'm gonna go ahead close this issue. It was a really strange occurrence tho.
