### ISSUE TITLE
1.16 - Iceberg resource

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#767]
Iceberg resource placement is uniformly one per chunk, with placement not randomised in any way.

`Totalchance` doesnt seem to work either, or at least, it doesnt work as i'd expect it to.

`Iceberg(minecraft:obsidian, minecraft:cobblestone, 33, minecraft:red_sand, minecraft:sandstone, 33, minecraft:grass_block, minecraft:dirt, 34, 150)`

I'd expect the above to give a 1/3 chance of spawning no iceberg but in fact it still places one per chunk.

https://cdn.discordapp.com/attachments/630666815533613057/868907449934032896/2021-07-25_18.27.44.png

**Comment by FrankTCA** [comment]
Seems to work normally. I'm gonna close this issue (for now) unless it rears its ugly head in later.
