### ISSUE TITLE
Bug - Skylands Lag/Server crashes after a time

### ISSUE THREAD

**Issue by tiarnia** [PG85/OpenTerrainGenerator#77]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  OTGASMPlugin (OTG ASM-1.12.2 - v1.jar)
  LoadingPlugin (Quark-r1.3-114.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.0.4.1.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.1.7.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar)
  AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  Extra Alchemy ASM (extraalchemy-0.3.6-release.jar)
  ComfortsLoadingPlugin (comforts-1.12.2-0.0.6.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 11/12/17 6:50 AM
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.remove(HashMap.java:1451)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:262)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:207)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.remove(HashMap.java:1451)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:262)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:207)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 143 Drop: 144
	Level seed: 1128511279172803584
	Level generator: ID 06 - OTG, ver 0. Features enabled: true
	Level generator options: OpenTerrainGenerator
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 882 game time, 882 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 118179 (now: false), thunder time: 98440 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows Server 2008 R2 (amd64) version 6.1
	Java Version: 1.8.0_112, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 728065056 bytes (694 MB) / 2245001216 bytes (2141 MB) up to 5637144576 bytes (5376 MB)
	JVM Flags: 1 total; -Xmx6048M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2528 81 mods loaded, 81 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version                  | Source                                    | Signature                                |
	|:--------- |:-------------------- |:------------------------ |:----------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2                   | minecraft.jar                             | None                                     |
	| UCHIJAAAA | mcp                  | 9.42                     | minecraft.jar                             | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99                | forgemod.jar                              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.0.2528             | forgemod.jar                              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | otgasm               | 1.12                     | minecraft.jar                             | None                                     |
	| UCHIJAAAA | bowinfinityfix       | rv5                      | minecraft.jar                             | e250ba31147feb059b86cfd74ee61a8aeb88fb9b |
	| UCHIJAAAA | applecore            | 2.2.2                    | AppleCore-mc1.12.2-2.2.2.jar              | None                                     |
	| UCHIJAAAA | jei                  | 4.8.0.105                | jei_1.12.2-4.8.0.105.jar                  | None                                     |
	| UCHIJAAAA | appleskin            | 1.0.8                    | AppleSkin-mc1.12-1.0.8.jar                | None                                     |
	| UCHIJAAAA | quark                | r1.3-114                 | Quark-r1.3-114.jar                        | None                                     |
	| UCHIJAAAA | autoreglib           | 1.3-14                   | AutoRegLib-1.3-14.jar                     | None                                     |
	| UCHIJAAAA | crafttweaker         | 4.0.9                    | CraftTweaker2-1.12-4.0.9.jar              | None                                     |
	| UCHIJAAAA | base                 | 3.4.0                    | base-1.12-3.4.0.jar                       | None                                     |
	| UCHIJAAAA | baubles              | 1.5.1                    | Baubles-1.12-1.5.1 (1).jar                | None                                     |
	| UCHIJAAAA | bedbugs              | @VERSION@                | BedBugs-1.12-1.0.1 (1).jar                | None                                     |
	| UCHIJAAAA | betterunderground    | 1.0.3                    | betterunderground-1.0.3.jar               | None                                     |
	| UCHIJAAAA | birdsfoods           | 2.5 [1.12]               | birdsfoods-1.12 - 2.5.jar                 | None                                     |
	| UCHIJAAAA | tile_booster         | 0.5                      | Block Booster-1.12.2-0.5.jar              | None                                     |
	| UCHIJAAAA | bloodmoon            | 1.5.2                    | Bloodmoon-MC1.12.2-1.5.2.jar              | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAA | bookshelf            | 2.2.489                  | Bookshelf-1.12.2-2.2.489.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | clumps               | 2.0.0                    | Clumps-3.0.0.jar                          | None                                     |
	| UCHIJAAAA | colytra              | 1.0.4.1                  | colytra-1.12.2-1.0.4.1.jar                | None                                     |
	| UCHIJAAAA | morpheus             | 1.12-3.3.2               | Morpheus-1.12-3.3.2 (1).jar               | None                                     |
	| UCHIJAAAA | comforts             | 0.0.6                    | comforts-1.12.2-0.0.6.jar                 | None                                     |
	| UCHIJAAAA | cookingforblockheads | 6.3.6                    | CookingForBlockheads_1.12.1-6.3.6 (1).jar | None                                     |
	| UCHIJAAAA | crafttweakerjei      | 2.0.0                    | CraftTweaker2-1.12-4.0.9.jar              | None                                     |
	| UCHIJAAAA | creepingnether       | 1.1                      | Creeping Nether-1.1.jar                   | None                                     |
	| UCHIJAAAA | diethopper           | 1.1                      | diethopper-1.1.jar                        | None                                     |
	| UCHIJAAAA | csb_ench_table       | 1.1.2                    | EnchantingTable-1.12-1.1.2.jar            | None                                     |
	| UCHIJAAAA | enderporter          | 1.0                      | EnderPorter-1.0.jar                       | None                                     |
	| UCHIJAAAA | extraalchemy         | 0.3.6-release            | extraalchemy-0.3.6-release.jar            | None                                     |
	| UCHIJAAAA | ftbl                 | 4.2.3                    | FTBLib-4.2.3.jar                          | None                                     |
	| UCHIJAAAA | ftbu                 | 4.2.2                    | FTBUtilities-4.2.2.jar                    | None                                     |
	| UCHIJAAAA | glass_shards         | 1.7                      | glass_shards_mc1.12-1.7.jar               | None                                     |
	| UCHIJAAAA | overlord             | 2.4.8                    | Overlord-1.12.2-2.4.8.jar                 | None                                     |
	| UCHIJAAAA | guideapi             | 1.12-2.1.4-57            | Guide-API-1.12-2.1.4-57.jar               | None                                     |
	| UCHIJAAAA | theoneprobe          | 1.4.18                   | theoneprobe-1.12-1.4.18 (1).jar           | None                                     |
	| UCHIJAAAA | horsepower           | 2.5.10                   | HorsePower-1.12.2-2.5.10.56.jar           | cd7e958342770a8b17c919055da42c24dfefd879 |
	| UCHIJAAAA | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironbackpacks        | @VERSION@                | IronBackpacks-1.12.2-3.0.0.jar            | None                                     |
	| UCHIJAAAA | ironchest            | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar           | None                                     |
	| UCHIJAAAA | journeymap           | 1.12.2-5.5.1             | journeymap-1.12.2-5.5.1.jar               | None                                     |
	| UCHIJAAAA | maille               | 2.0                      | Maille1.12.2-2.0 (1).jar                  | None                                     |
	| UCHIJAAAA | malisiscore          | 1.12.2-6.1.7             | malisiscore-1.12.2-6.1.7.jar              | None                                     |
	| UCHIJAAAA | malisisdoors         | 1.12.2-7.1.1             | malisisdoors-1.12.2-7.1.1.jar             | None                                     |
	| UCHIJAAAA | mantle               | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                  | None                                     |
	| UCHIJAAAA | natura               | 1.12-4.3.0.17            | Natura-1.12-4.3.0.17.jar                  | None                                     |
	| UCHIJAAAA | nex                  | 2.1.11.12                | NetherEx-1.12-2.1.11.12.jar               | None                                     |
	| UCHIJAAAA | netherportalfix      | 5.3.13                   | NetherPortalFix_1.12.1-5.3.13.jar         | None                                     |
	| UCHIJAAAA | nightmares           | 1.0.4                    | Nightmares-1.12.2-1.0.4.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | nmsot                | 1.2.1-mc1.12             | NoMobSpawningOnTrees-1.2.1-mc1.12.jar     | None                                     |
	| UCHIJAAAA | recipehandler        | 0.9                      | NoMoreRecipeConflict-0.9(1.12).jar        | None                                     |
	| UCHIJAAAA | openterraingenerator | v1                       | OpenTerrainGenerator-1.12.2 - v1.jar      | None                                     |
	| UCHIJAAAA | otgskylands          | 1.0                      | OTG-Skylands-1.12.2-v5.jar                | None                                     |
	| UCHIJAAAA | otgvoid              | 1.0                      | OTG-Void-1.12.2-v4.jar                    | None                                     |
	| UCHIJAAAA | quickleafdecay       | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar         | None                                     |
	| UCHIJAAAA | railsplus            | 1.0.0                    | railsplus-1.0.1.jar                       | None                                     |
	| UCHIJAAAA | redstonepaste        | 1.7.5                    | redstonepaste-mc1.12-1.7.5.jar            | None                                     |
	| UCHIJAAAA | secretroomsmod       | 2.0.0                    | secretroomsmod-2.0.0.jar                  | None                                     |
	| UCHIJAAAA | sit                  | v1.0                     | sit-1.12.x-v1.0.jar                       | None                                     |
	| UCHIJAAAA | spartanshields       | 1.3a                     | SpartanShields-1.12-1.3a (1).jar          | None                                     |
	| UCHIJAAAA | spawntemple          | 2.1                      | SpawnTemple-v.2.1-mc1.12.jar              | None                                     |
	| UCHIJAAAA | spiceoflife          | 1.3.11                   | SpiceOfLife-mc1.12-1.3.11.jar             | None                                     |
	| UCHIJAAAA | stg                  | 1.12-1.2.1               | stg-1.12-1.2.1 (2).jar                    | None                                     |
	| UCHIJAAAA | storageboats         | 1.6                      | StorageBoats-2.9.jar                      | None                                     |
	| UCHIJAAAA | supersoundmuffler    | 1.0.2.9                  | supersoundmuffler-1.12.1-1.0.2.9 (1).jar  | None                                     |
	| UCHIJAAAA | survivalist          | 2.1.4                    | Survivalist-1.12.2-2.1.4.jar              | None                                     |
	| UCHIJAAAA | switchbow            | 1.5                      | switchbow-1.5-1.12.2 (1).jar              | None                                     |
	| UCHIJAAAA | tammodized           | 0.15.3                   | TamModized-1.12.1-0.15.3.jar              | None                                     |
	| UCHIJAAAA | thutcore             | 5.11.8                   | thutcore-5.11.8.2.jar                     | None                                     |
	| UCHIJAAAA | thuttech             | 6.0.8                    | thuttech-6.0.8.2.jar                      | None                                     |
	| UCHIJAAAA | tombmanygraves       | @VERSION@                | TombManyGraves-1.12-4.0.2.jar             | None                                     |
	| UCHIJAAAA | xat                  | 0.11                     | Trinkets-and-Baubles-1.12.2-0.11.jar      | None                                     |
	| UCHIJAAAA | ultimate_unicorn_mod | 1.5.14                   | ultimate_unicorn_mod-1.12.2-1.5.14.jar    | None                                     |
	| UCHIJAAAA | vc                   | 5.0.10                   | ViesCraft-1.12.2-5.0.10.jar               | None                                     |
	| UCHIJAAAA | villagenames         | 2.0                      | VillageNames-1.12.2-2.0.jar               | None                                     |
	| UCHIJAAAA | voidcraft            | 0.26.7                   | VoidCraft-1.12.1-0.26.7.jar               | None                                     |
	| UCHIJAAAA | vtweaks              | 1.4.12b                  | VTweaks-1.12.2-1.4.12b.jar                | None                                     |
	| UCHIJAAAA | waystones            | 4.0.17                   | Waystones_1.12.1-4.0.17.jar               | None                                     |
	| UCHIJAAAA | wolfarmor            | 1.12.2-2.1.0-RELEASE     | wolfarmor-1.12.2-2.1.0.24-RELEASE.jar     | None                                     |
	| UCHIJAAAA | xnet                 | 1.4.1                    | xnet-1.12-1.4.1.jar                       | None                                     |

	Loaded coremods (and transformers): 
OTGASMPlugin (OTG ASM-1.12.2 - v1.jar)
  com.pg85.otg.asm.OTGClassTransformer
LoadingPlugin (Quark-r1.3-114.jar)
  vazkii.quark.base.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ColytraLoadingPlugin (colytra-1.12.2-1.0.4.1.jar)
  c4.colytra.core.asm.ElytraTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.1.7.jar)
  
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar)
  lumien.bloodmoon.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
Extra Alchemy ASM (extraalchemy-0.3.6-release.jar)
  zabi.minecraft.extraalchemy.asm.PotionTransformer
ComfortsLoadingPlugin (comforts-1.12.2-0.0.6.jar)
  c4.comforts.asm.SleepTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
  com.github.parker8283.bif.Transformer
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 0 / 10; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by PG85** [comment]
Thanks for reporting this. This one is hard to reproduce unfortunately, when you reboot the world can you continue playing without problems?

**Comment by tiarnia** [comment]
Once it reboots you can get back on but if you're in the sky land and you're moving around for more than a couple of minutes it crashes and reboots again I haven't tried just standing in the sky lands I'm not quite sure it's definitely eating a lot of my CPU but it was only set to pregenerate five chunks so I I have no idea

**Comment by tiarnia** [comment]
And it only seems to be the Skylands the void Dimension works fine as far as I can tell I flew around in it for quite a while and the regular Overworld Dimension I made works fine too it's just really weird

**Comment by tiarnia** [comment]
i'm fairly sure it's just using to much cpu and minecraft is just timing out from what i can tell but only with the skylands preset

**Comment by PG85** [comment]
Skylands is known to be quite laggy unfortunately, we still have to figure out what is causing that. The problem is it's the terrain itself that appears to be causing the lag, not OTG. If you load a Skylands world without OTG it still lags. So if you can find any clues as to which terrain features might be causing problems, please let me know.

**Comment by SXRWahrheit** [comment]
Just to try to be helpful - I'm running on a Kimsufi VPS (not much power at all) and it's enough to load the Skylands world without too much lag. You probably just need better hardware.

**Comment by PG85** [comment]
v8 contains a number of optimisations, so should provide better performance. I think the problem might be the Skylands terrain + MC itself causing the problem though, let me know if you're still having problems.
