### ISSUE TITLE
Bug: Forge Snow/rainfall in biomes doesn't display correctly

### ISSUE THREAD

**Issue by PG85** [PG85/OpenTerrainGenerator#79]
MCPitman: I found a (v1.12.2 v1)  bug to do with snow/rainfall in biomes
snow doesnt display correctly in forge
a cold taiga biome doesn't snow at sea level but then i remove OTG and go back into the map and it does
biome has replacetobiome cold taiga
and temp settings same as cold taiga vanilla

**Comment by PG85** [comment]
BiomeTemperature and replaceToBiomeName: minecraft:taiga_cold do appear to work, if I do /weather rain, it snows. So it looks like the temperature setting is okay, but the weather (rain) is behaving differently for OTG. Need to confirm if the weather behaves properly and if not, what's different.

**Comment by PG85** [comment]
Need more info.

**Comment by PG85** [comment]
Test git discord bot.. Show this in Discord!

**Comment by PG85** [comment]
Weather has been made independent for dims. Still need more info if it's not working as it should.

**Comment by PG85** [comment]
@MCPitman

**Comment by DamienBrittan** [comment]
i have the same problem with otg . It's only rains for some reason .

**Comment by PG85** [comment]
@MCPitman , can you confirm rain/snow is working as intended for v9? Thanks!

**Comment by PG85** [comment]
Won't be fixing this for 1.12.2 (if it is still a problem).
