### ISSUE TITLE
1.12.2 V9.3 Updating Screen Events Error

### ISSUE THREAD

**Issue by capio13** [PG85/OpenTerrainGenerator#792]
Been having this issue where I cannot generate a OTG world without it crashing and giving me an 
"The game crashed whilst updating screen events
Error: java.lang.NullPointerException: Updating screen events
Exit Code: -1"
I have tried increasing my ram, deleting OTG core, reinstalling it, same with BBOP and BOP as far as the presets. 
This is my crash report in detail if that helps.
[crash-2021-07-31_10.35.00-client.txt](https://github.com/PG85/OpenTerrainGenerator/files/6911611/crash-2021-07-31_10.35.00-client.txt)

**Comment by PG85** [comment]
Hey @capio13 , some of your preset files may have been corrupted. Try deleting your preset folders in the /mods/openterraingenerator/worlds/ folder, if you have the preset .jar files they should re-install automatically. Let me know if that works, cheers.

* If that does not solve the problem, please try to verify that there isn't a compatibility issue with other mods.

**Comment by capio13** [comment]
@PG85 It sadly did not work, gave me same error, I am going to try the good old install one mod at a time and see if that will help.

**Comment by capio13** [comment]
@PG85 I found the mod conflict, it was Fancymenu 1.7.1.0 by Keksuccino, I messaged him about it and hopefully it can be figured out.
