### ISSUE TITLE
IsSpawnPoint: True does not work for 1.16.5

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#795]
#### OTG Plugin or Mod
- [X] OTG Mod for Forge

#### OTG Version
OpenTerrainGenerator-1.16.5-0.0.17r1.jar

#### Forge or Spigot Versions
forge-1.16.5-36.2.2

#### What other plugins are you running?
None

#### Description
IsSpawnPoint: true does not work for Bo4's while CustomStructure(Exotic_Pillager-Ship,0.0) present.
Changing to CustomStructure(Exotic_Pillager-Ship,100.0) will spawn the structure every 10 chunks.

Simplified World & Bo4 included into following zip: 

[Debug.zip](https://github.com/PG85/OpenTerrainGenerator/files/6913033/Debug.zip)

**Comment by PG85** [comment]
![2021-08-05_17 44 08](https://user-images.githubusercontent.com/6781444/128380135-1d402081-7666-4953-af20-363eccbeeade.png)
Fixed for 0.0.18, you will have to add your BO4 to spawn biomes with rarity 0.0 though (should probably improve that in the future, move spawn bo4's settings to worldconfig).
