### ISSUE TITLE
WaterlevelMin: Does not work for 1.16.5

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#796]
#### OTG Plugin or Mod
- [X] OTG Mod for Forge

#### OTG Version
OpenTerrainGenerator-1.16.5-0.0.17r1.jar

#### Forge or Spigot Versions
forge-1.16.5-36.2.2

#### What other plugins are you running?
None

#### Description
WaterlevelMin: 50 & WaterlevelMax: 70 adds water from 0 to 70 Rather then 50 to 70 creating a pocket of air underneath.

(Pocket that should be air in world is between layer 27 and 10)
Simplified World included into following zip: 

[Debug.zip](https://github.com/PG85/OpenTerrainGenerator/files/6913074/Debug.zip)

**Comment by PG85** [comment]
Fixed for 0.0.18.
