### ISSUE TITLE
BlockCheck(Liquid/Stationary_Water wont work) 1.16.5

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#798]
#### OTG Plugin or Mod
- [X] OTG Mod for Forge

#### OTG Version
OpenTerrainGenerator-1.16.5-0.0.17r1.jar

#### Forge or Spigot Versions
forge-1.16.5-36.2.2

#### What other plugins are you running?
None

#### Description
BlockCheck() Liquid wont work. Legacy: Stationary_water, Flowing_Water & Water wont work either. (Possibly Stationary_Lava, Lava & Flowing_Lava neither.) Blockchecks with prefix minecraf: wont work either.

Simple Bo3: Just add CustomObject(TestBo3) and it should spawn.
Freq & Rarity set to 25. 

Legacy Bo3:
[TestBo3.zip](https://github.com/PG85/OpenTerrainGenerator/files/6913210/TestBo3.zip)

minecraft: prefix Bo3:
[TestBo3.zip](https://github.com/PG85/OpenTerrainGenerator/files/6913228/TestBo3.zip)

Here's a test world that includes the minecraft: prefix bo3
[Debug.zip](https://github.com/PG85/OpenTerrainGenerator/files/6918460/Debug.zip)

**Comment by FrankTCA** [comment]
Fixed this one.
