### ISSUE TITLE
New world shutdown

### ISSUE THREAD

**Issue by Beanius** [PG85/OpenTerrainGenerator#8]
Game initiates shutdown when trying to create a new world in SP with harvest festival installed B) [https://minecraft.curseforge.com/projects/harvest-festival](url) 

Does only happen when OpenTerrainGenerator is installed, otherwise my pack runs smooth with HF.

**Comment by Beanius** [comment]
https://gist.github.com/Beanius/5b3b2b6fb94afb0bad4a8039f0dc7c6b

this is the error i'm getting when the shutdown happens B)

edit: It's the same issue ruyanve reported: sun.reflect.generics.reflectiveObjects.NotImplementedException

**Comment by Beanius** [comment]
this might be the same issue Ruyanve reported.

**Comment by PG85** [comment]
Thanks for reporting this :)
