### ISSUE TITLE
Bug: Landrarity affects biome layout and landrarity0 spawns non-oceans

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#801]
This is with `OldGroupRarity: false`

Could it be something to do with `OceanBiomeSize`?

Either way, there needs to be a way to completely disable oceans.

**Comment by FrankTCA** [comment]
I will point out where you got this from was a Spigot server so this might just be a problem on Spigot but we'll have to do additional testing.

**Comment by BiomeBundle** [comment]
Nah it also happens on Forge, we've known about it for a while

**Comment by WACriminalG2** [comment]
I remember when this was happening to me, it was because under the default ocean biomes, I was referring to biomes that didn't actually exist in my preset (because I had copied over the Default world config to start editing, but never copied over the Ocean biome). Removing the references and leaving them blank didn't fix it, I had to actually move the biomes over into my preset. Presumably I could have also just referenced existing biomes that were already in my preset, but this seemed cleaner.

**Comment by PG85** [comment]
Should check this out for 0.1.0 to make sure biome groups are working properly, and also document the way new biome groups work.

**Comment by PG85** [comment]
Fixed LandRarity and OceanBiomeSize for 0.0.18, if there are still problems, feel free to reopen this issue.

**Comment by PG85** [comment]
For 0.0.18 LandRarity 1-100 now work ok, but LandRarity 0 changes biome layout and still does not spawn oceans only.

**Comment by PG85** [comment]
![afbeelding](https://user-images.githubusercontent.com/6781444/128603828-4e910850-94d3-4141-8fb1-e0d21e7a5266.png)

**Comment by BiomeBundle** [comment]
![image](https://user-images.githubusercontent.com/23154920/128604893-3240878d-3e79-4ead-b110-ee401a2cbf22.png)

**Comment by WACriminalG2** [comment]
> For 0.0.18 **LandRarity 1-100 now work ok**, but LandRarity 0 changes biome layout and still does not spawn oceans only.

Wait, is that what LandRarity 100 is supposed to look like? I thought it was meant to have no oceans. Unless those are large lakes.

**Comment by BiomeBundle** [comment]
> 
> 
> > For 0.0.18 **LandRarity 1-100 now work ok**, but LandRarity 0 changes biome layout and still does not spawn oceans only.
> 
> Wait, is that what LandRarity 100 is supposed to look like? I thought it was meant to have no oceans. Unless those are large lakes.

Those arent oceans, it's just the biomes going below sea level.

**Comment by FrankTCA** [comment]
We've decided not to fix this.

**Comment by SXRWahrheit** [comment]
We will not be fixing the biome layout issue for this release, but still need to fix the landrarity 0 issue.

**Comment by authvin** [comment]
The landrarity 0 issue is fixed two ways by https://github.com/PG85/OpenTerrainGenerator/commit/0fd4c9de600561a9041b47243009fa02ab127381

landrarity 0 now doesn't spawn any land
also added a setting ForceLandAtSpawn, which can be disabled to avoid forcing land around 0,0
