### ISSUE TITLE
FogDensity does not work in 1.16.5 Multiplayer.

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#802]
#### OTG Plugin or Mod
- [X] OTG Mod for Forge

#### OTG Version
OpenTerrainGenerator-1.16.5-0.0.17r1.jar

#### Forge or Spigot Versions
forge-1.16.5-36.2.2  (Both client as Server)

#### What other plugins are you running?
None

#### Description
Fog color, foilage color etc works but FogDensity: 1.0 does not work for Multiplayer and results in the picture shown below. Using the same values on single player will result in zero visibility like it should do.

![unknown](https://user-images.githubusercontent.com/4073584/127785040-099dc9a3-bc6c-4243-b36c-85a688aa1bac.png)

**Comment by Jishuna** [comment]
Fixed in next dev release.
