### ISSUE TITLE
Feature: A way to isolate the loggging features to one preset.

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#807]
#### Is your feature request related to a problem? Please describe.
Whenever I try to debug one preset but have 3 presets (default, debug, dregora) or even more the log becomes cluttered with config logs and the sorts on all of them rather then just the one I want to test. The only way to counter this is to remove all presets from the preset folder and this can become tedious real fast.

#### Describe the solution you'd like
logpresets: <array> in otg.ini

**Comment by FrankTCA** [comment]
Added this option to otg.ini
