### ISSUE TITLE
Legacy block: WOODEN_BUTTON not yet supported for 1.16.5

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#809]
#### OTG Plugin or Mod
- [X] OTG Mod for Forge

#### OTG Version
OpenTerrainGenerator-1.16.5-0.0.17r1.jar

#### Forge or Spigot Versions
forge-1.16.5-36.2.2

#### What other plugins are you running?
None

#### Description
The legacy name WOODEN_BUTTON does not work anymore. I would suggest defaulting this to minecraft:oak_button

**Comment by FrankTCA** [comment]
Will fix tomorrow morning. Should be simple fix.

**Comment by NLBlackEagle** [comment]
Found another one, WATERLILY  Hope you don't mind if I drop that in here :P

**Comment by FrankTCA** [comment]
No worries! The more the merrier!

**Comment by FrankTCA** [comment]
Got this done earlier. Forgot to close it.
