### ISSUE TITLE
(v1.12.2 v1) Lava "rivers" don't spawn underground anymore

### ISSUE THREAD

**Issue by KPWhiver** [PG85/OpenTerrainGenerator#81]
Normally, in the overworld all air blocks below y ~10 are replaced with lava blocks. In terrain (even default terrain) generated by OTG this doesn't happen.

This is using:

- Spigot: 1.12.2-b1442
- OTG: v1.12.2 v1

**Comment by PG85** [comment]
Hey there, this is intentional and not a bug. We changed the <10y lava layer, it has been replaced by lava lakes. Thanks for reporting though :).
