### ISSUE TITLE
Snow in modded biomes

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#815]
![2021-08-03_19 44 27](https://user-images.githubusercontent.com/23154920/128095245-fe71e69f-198c-4253-b27b-47bf68e06ca1.png)
![2021-08-03_20 47 39](https://user-images.githubusercontent.com/23154920/128095251-57155751-840e-49fd-a551-5eab1ea830e0.png)
![2021-08-03_23 25 47](https://user-images.githubusercontent.com/23154920/128095253-921cc225-f825-4e57-b2b8-6e349c307500.png)

**Comment by PG85** [comment]
Fixed for 0.0.18, though we may still have some artifacts on borders between otg/non-otg biomes. Should be fixed completely once we switch to 3x3.
