### ISSUE TITLE
Bug: /otg export preset Names encased with "" throws an error despite working in OTG 0.0.16 and earlier

### ISSUE THREAD

**Issue by I-am-mimic** [PG85/OpenTerrainGenerator#818]
#### OTG Plugin or Mod

- [x] OTG Mod for Forge

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] OTG 1.16 0.0.17

#### Forge or Spigot Versions
Forge 36.1.32
#### What other plugins are you running?
https://docs.google.com/document/d/18PodlrUTttVyKap7udTtCqoCHHPgzYw-ei2tTCbeLXk/edit?usp=sharing
#### Description
When attempting to export an object with a Preset name with "" in it throws a 
"Expected whitespace to end one argument, but found trailing data, ...ange_wool "When Realities Collide" BO3
What else is weird is that this worked in versions prior to 0.0.17. 
Fortunately I can get around this by removing the spaces in my Preset's name.

I expected however to be able to freely use my preset name without spaces with no issues.

#### Steps to reproduce
1. Name a preset with spaces
2. In a world select two points with /otg region mark
3. Then export the object, using the preset name as the target location for exporting
4. If done correctly you should get an error similar to this "Expected whitespace to end one argument, but found trailing data, ...ange_wool "When Realities Collide" BO3

**Comment by PG85** [comment]
Fixed by Frank for 0.0.18.
