### ISSUE TITLE
1.12.2 conflict with FoamFix

### ISSUE THREAD

**Issue by MadRatSRP** [PG85/OpenTerrainGenerator#82]
[crash-2017-11-28_01.25.23-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/1507814/crash-2017-11-28_01.25.23-server.txt)

**Comment by Alaberti** [comment]
That doesn't look like it has anything to do with OTG or FoamFix honestly.

**Comment by PG85** [comment]
I'm sorry, I can see nothing in here that indicates a problem with OTG, I also don't see anything that could help with your problem. Wish I could help, but all I can do is close this. Good luck!
