### ISSUE TITLE
1.16.x 0.1.0 final todo's

### ISSUE THREAD

**Issue by PG85** [PG85/OpenTerrainGenerator#823]
- Make sure biome groups work properly #801 
- Update default preset, add biome dictionary tags (overworld) and modded biome support
- Test with writing enabled
- Update all BB BO's and confirm success
- Finish presetpacker #586 
- Make preset jars
- Update wiki installation instructions
- Update Curse preset pages with 1.16 instructions/notice.

**Comment by FrankTCA** [comment]
All should be done and this milestone is complete.
