### ISSUE TITLE
1.16 - Landrarity is broken

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#828]
![image](https://user-images.githubusercontent.com/23154920/128583547-391fe41f-80fa-4bfd-b301-7300b62142d0.png)

**Comment by BiomeBundle** [comment]
Even worse, putting it to 100 appears to change the land biomes that generate:

![image](https://user-images.githubusercontent.com/23154920/128584478-8ad4837c-3f4c-4011-b859-cc50f5fa1980.png)

**Comment by PG85** [comment]
Fixed for 0.0.18.
