### ISSUE TITLE
1.16 - OceanBiomeSize appears to do nothing

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#829]
![image](https://user-images.githubusercontent.com/23154920/128584055-3623b0b5-c2a6-4c71-a88e-4607dbec7001.png)

**Comment by PG85** [comment]
Hopefully fixed for 0.0.18, though there may still be issues with oceans being used as isles/borders. Feel free to reopen and update if that's the case.
