### ISSUE TITLE
Bug: Vanilla structures spawn above bo3s if there is an overlapping x and z coordinates.

### ISSUE THREAD

**Issue by FrankTCA** [PG85/OpenTerrainGenerator#834]
#### OTG Plugin or Mod
- [ ] OTG Mod for Forge
- [x] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - specify here - OTG 1.16

#### Forge or Spigot Versions
purpur-1.16.5-1171

#### What other plugins are you running?
Chunky, CoordinatesHud, DeathHold, DiscordSRV, DropsOverhaul, dynmap, Dynmap-Essentials, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, ImageOnMap, LuckPerms, mcMMO, OldCombatMechanics, PlugMan, ProtocolLib, RealisticSeasons, SilkSpawners, Vault, VeinMiner, ViaVersion, Vivecraft-Spigot-Extensions, and, of course, OTG.

#### Description
We discovered a village farm that spawned on top of a tree. This leads me to believe that vanilla structures will spawn above bo3s.
![Screenshot](https://user-images.githubusercontent.com/19649826/128638429-f44c66b5-1b0a-44f2-84b2-211b685232e6.png)

I would say that most likely what should be happening is either the bo3 or the vanilla structure should be canceling.

Make a world with an endless supply of commonly occurring simple bo3s. Make sure villages and other structures are enabled and wait for it to occur.

**Comment by PG85** [comment]
Vanilla structures like villages actually affect base terrain generation and manipulate the noise to create platforms on which they can spawn, we refer to this as noise-based-smoothing for structures. Some vanilla structures (or parts of vanilla structures) apparently do height checks during decoration, in which case resource layering problems like this may occur. We'll see if this still happens after we switch to 3x3 decoration, I have a hunch it might still happen even then though.

**Comment by FrankTCA** [comment]
So that means this is a won't fix?

**Comment by FrankTCA** [comment]
Dead issue, will wait till we switch to 3x3 and see if it fixes, until then, this is won't fix.
