### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by Dark-Candy** [PG85/OpenTerrainGenerator#839]
[crash-2021-08-09_17.17.56-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/6954522/crash-2021-08-09_17.17.56-server.txt)

**Comment by PG85** [comment]
Hey @Dark-Candy , without more context all I can tell you is there appears to be a problem with one of your dimensionconfig yaml files. Either it has been corrupted or one of the presets it points to is missing/corrupted. Without more information about what happened before this, I can't help you.

**Comment by Dark-Candy** [comment]
> Hey @Dark-Candy , without more context all I can tell you is there appears to be a problem with one of your dimensionconfig yaml files. Either it has been corrupted or one of the presets it points to is missing/corrupted. Without more information about what happened before this, I can't help you.

Thank you for your reply
But the problem is fixed now, the issue was with the mods/config files, reinstalled the whole thing..
