### ISSUE TITLE
[1.12.2] Water and air

### ISSUE THREAD

**Issue by ghost** [PG85/OpenTerrainGenerator#84]
[fml-junk-earlystartup.log](https://github.com/PG85/OpenTerrainGenerator/files/1513548/fml-junk-earlystartup.log)
[fml-server-latest.log](https://github.com/PG85/OpenTerrainGenerator/files/1513549/fml-server-latest.log)

There are tons of air bubbles throughout ocean biomes;
![air](https://user-images.githubusercontent.com/4166113/33370687-352b2396-d4f0-11e7-8b3e-dbb3a94bb46a.png)

Plays havoc sounds and sounds like there's a river everywhere in the ocean, not to mention lots of splashing water particle effects.
Water does not flow down into crevices, nooks, and crannies as it should.
Randomly the squids are getting trapped in these air bubbles and suffocating to death, leaving their drops lurking around.
Doesn't make for a pretty map render.

I also have concerns over performance issues, both server side and client side that arise from this type of behaviour, especially if randomly the server decides to start flowing water through these air blocks.

Is this something OTG needs to fix or is there a setting somewhere that I can tweak to fix it?

**Comment by MCPitman** [comment]
Fixed in Biome Bundle v6.1. If continuing an existing v6 world make sure you delete the Biome Bundle folder from \mods\OpenTerrainGenerator\worlds as the v6.1 jar will not automatically overwrite your v6 configs.
