### ISSUE TITLE
Feature: 1.16.x - Spawn point settings

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#840]
#### OTG Plugin or Mod
- [X] OTG Mod for Forge

#### OTG Version
OpenTerrainGenerator-1.16.5-0.0.18.jar

#### Forge or Spigot Versions
forge-1.16.5-36.2.2

#### What other plugins are you running?
None

#### Description
OTG does not place the structure center on 0,0 with following options included at worldconfig:

```
With image size of 6000x6000
ImageXOffset: -3000
ImageZOffset: -3000
```

```
SpawnPointX: 0
SpawnPointY: 59
SpawnPointZ: 0
```

Simplified World & Bo4 included into following zip:
[Debug.zip](https://github.com/PG85/OpenTerrainGenerator/files/6913033/Debug.zip) (same as https://github.com/PG85/OpenTerrainGenerator/issues/795)

**Comment by PG85** [comment]
As I've explained, the problem is not IsSpawnPoint, it is that SpawnPointX/Y/Z do not exist for 1.16 atm.

**Comment by PG85** [comment]
Implemented FixedSpawnPoint: true/false, SpawnPointX/Y/Z for 0.0.19.

**Comment by NLBlackEagle** [comment]
I've had my doubts regarding Spawnpoint X/Y/Z being the issue as the structure in theory would then either spawn randomly as it did with the spawnpoint itself or it would attach itself to the spawnpoint that was crooked. 

I've tried to explain it before but I believe i didnt properly did so, so here's a image on what basically happened:
![afbeelding](https://user-images.githubusercontent.com/4073584/129483559-50a786a8-998f-4260-aea2-9574a08eae03.png)

And well, currently it still does not spawn at 0,0 so SpawnPoint x/y/z wasnt the issue but did a good job disguising it. 
![afbeelding](https://user-images.githubusercontent.com/4073584/129483572-e749d4be-6b37-4a25-8df9-af444ed16740.png)

**Comment by NLBlackEagle** [comment]
Found the cause of the structure not spawning correctly: SpawnPointSet: true changed to FixedSpawnPoint: true
