### ISSUE TITLE
Naming a file a in the dimensionconfig with the extension .yml does not work

### ISSUE THREAD

**Issue by I-am-mimic** [PG85/OpenTerrainGenerator#842]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] 1.16 - 0.0.18

#### Forge or Spigot Versions
36.2.0

#### Description

Naming a file a in the dimensionconfig with the extension .yml doesn't work right. The default vanilla world creation menu shows up instead of the custom one. However files ending in .yaml work fine.

####Steps to reproduce
1. In the OpenTerrainGenerator/dimensionconfigs folder create a file ending with .yml
2. Boot up Minecraft and create a new world.
3. If done correctly the default world creation menu will appear instead of OTG's one.

**Comment by FrankTCA** [comment]
Has anyone looked into this yet?

**Comment by I-am-mimic** [comment]
Closed since no one has looked into this and I think it was fixed in a later release.
