### ISSUE TITLE
1.12.2 terrible performance in the ocean

### ISSUE THREAD

**Issue by croftyraider** [PG85/OpenTerrainGenerator#85]
Minimal modpack with just:

Forge 1.12.2-14.23.1.2555
BiomeBundle 1.12.2-v6
OpenTerrainGenerator-1.12.2 - v2

Use the seed (get rid of the double quotes) "low hanging fruit" and see what I mean. Over land chunk update spam drops off, but over ocean it's awful and takes forever to generate the chunks.

**Comment by MCPitman** [comment]
Fixed in Biome Bundle v6.1.  If continuing an existing v6 world make sure you delete the Biome Bundle folder from \mods\OpenTerrainGenerator\worlds as the v6.1 jar will not automatically overwrite your v6 configs.

**Comment by croftyraider** [comment]
Ok, that was a huge fix. Not only did you solve the oceans issue but you also solved those biomes with the giant floating skyland sections. I used to avoid those because the chunk update spam was intense. Nice work.
