### ISSUE TITLE
crash : can't work with ancient warfare2

### ISSUE THREAD

**Issue by gta5plyaer** [PG85/OpenTerrainGenerator#850]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x] 1.12.2_v9.3
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
14.23.5.2855

#### Server/Client Log
[crash-2021-08-26_07.39.46-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/7055209/crash-2021-08-26_07.39.46-server.txt)
[crash-2021-08-25_16.43.46-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/7055222/crash-2021-08-25_16.43.46-server.txt)
[crash-2021-08-25_16.43.52-client.txt](https://github.com/PG85/OpenTerrainGenerator/files/7055241/crash-2021-08-25_16.43.52-client.txt)

#### Description
the ancient warfare2 cannot work on OTG world , but it can work on normal world correctly!

**Comment by PG85** [comment]
Hi @gta5plyaer , thanks for reporting this. I've tried AW myself a while ago and couldn't get it to work either unfortunately. We're working on OTG 1.16.x atm so we won't spend any significant amount of time/resources on 1.12.2, if someone proposes a solution or makes a pull request with a fix, would be happy to look at it ofc. Unfortunately the logs don't point to OTG code, so I can't offer you much advice.
