### ISSUE TITLE
Iceberg resource strange behaviour

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#856]
Parts of the iceberg resource spawn missing when on chunk boundaries (red line is the chunk border):

![image](https://user-images.githubusercontent.com/23154920/131372930-5b58e717-d099-40d5-ad40-b58dc73d44a6.png)

Using replaceblocks on it causes parts of it to spawn missing (replacing parts of it to blue ice in this screenshot):

![2021-08-30_17 22 46](https://user-images.githubusercontent.com/23154920/131372990-1a7a471b-a10a-4afe-923b-190118b0d7e1.png)

**Comment by PG85** [comment]
Replacedblocks weren't being picked up properly for Iceberg(), should be fixed for 0.0.19.
