### ISSUE TITLE
1.16 - Resource population not working correctly in biome smoothradius

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#879]
In the below screenshot you can see the Badlands biome on the left, and the Savanna biome on the right, the part in the middle is the smoothradius, which is Savanna biome and uses the savanna biome's surface blocks, however it uses the resource population settings of the Badlands biome (which is why there is no grass).

![image](https://user-images.githubusercontent.com/23154920/134773611-7ac8dd3c-9d28-4bb7-9dac-509fa13850a5.png)

**Comment by SXRWahrheit** [comment]
Is this 1.16 or 1.12?

**Comment by SXRWahrheit** [comment]
Reported in Discord that this is a 1.16 issue.

**Comment by FrankTCA** [comment]
Hehehehehehehehehehehe

Fixed.
