### ISSUE TITLE
OTG + JER + Loot Tables - World creation menu not showing

### ISSUE THREAD

**Issue by Scrayyg** [PG85/OpenTerrainGenerator#88]
Minecraft Version 1.12.2
Forge: 1.12.2 - 14.23.1.2555
Conflicting Mod: Just Enough Resources (JER)
Issue: Attempting to create a world with JER installed opens the normal world creation menu instead of the special OTG one.

**Comment by Scrayyg** [comment]
Did some messing around. OTG works fine when loaded with just JER. It seems like the conflict is caused if you load both JER and Additional Loot Tables. Both mods work fine with OTG individually but loading both together seems to cause the issue.

**Comment by PG85** [comment]
v7 has a new world creation menu, which also works ingame. Hopefully this fixes the problem.
