### ISSUE TITLE
Ore(coal_ore) unaffected by DisableOreGen setting.

### ISSUE THREAD

**Issue by aswheaton** [PG85/OpenTerrainGenerator#884]
#### OTG Plugin or Mod
- [ ] OTG Mod for Forge
- [x] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - 1.16.5-0.0.19

#### Forge or Spigot Versions
paper-1.16.5-788

#### What other plugins are you running?
None

#### Description
Coal ore spawns using the Ore() resource even when `DisableOreGen: true` in WorldConfig.ini. To reproduce, start the Paper server with OTG installed to generate the Default preset, and then stop the server. Open plugins/OpenTerrainGenerator/Presets/Default/WorldConfig.ini and set the line `DisableOreGen: false` to `DisableOreGen: true`. Delete chunks stored in the world/region/ directory and restart the server. Replacing all the stone blocks in a chunk with air reveals that coal still generates.

![2021-10-07_13 50 05](https://user-images.githubusercontent.com/34541330/136399902-07cf0a80-2539-4318-9c7a-c2fe1459d30e.png)

This issue does not appear to be reproducible in singleplayer Forge:

![2021-10-07_14 45 31](https://user-images.githubusercontent.com/34541330/136400054-abac8acc-b6b5-420c-b44c-75dc4bee5e8f.png)

Setting `DisableOreGen: true` should disable _all_ ore gen, including coal. On both platforms, dirt, gravel, andesite, diorite, and granite spawned with the Ore() resource all spawn regardless of the value of `DisableOreGen`. The WorldConfig comments say this setting "Disables Ore(), UnderWaterOre() and Vein() biome resources _that use any type of ore block_." (emphasis mine) so maybe the issue is that coal is not seen as an ore block on Paper?

**Comment by FrankTCA** [comment]
Ahhh, the world's foremost data-driven worldgen mod.

<img width="560" alt="Screen_Shot_2021-10-29_at_17 54 00" src="https://user-images.githubusercontent.com/19649826/139506767-3bc3bb4e-8035-4d64-9bc2-61411e3872e6.png">

(I fixed it, little mistake made by PG85 back in June.)
