### ISSUE TITLE
Add village size, seperation and spacing ?

### ISSUE THREAD

**Issue by Ezoteric** [PG85/OpenTerrainGenerator#885]
As topic suggest could you add village size and sep/spa to the preset config please :)

**Comment by PG85** [comment]
Thanks for reporting this. For 1.16, village size can be configured in BiomeConfigs. For separation/spacing logic would have to take another look at the MC code, don't see it at a glance. Will move to the 1.0.0 milestone for now.

**Comment by FrankTCA** [comment]
#887 was merged into this issue:

Basically: Have an option for spacing for every structure.

**Comment by PG85** [comment]
Thanks for reporting, added to worldconfig for 0.1.5.
