### ISSUE TITLE
Adding spacing and separation settings for pyramids 

### ISSUE THREAD

**Issue by Ezoteric** [PG85/OpenTerrainGenerator#887]
Would you please and be able to add spacing and separation settings for pyramids as they spawn quite a lot :)

Thnx in advance

**Comment by FrankTCA** [comment]
This is quite similar to #885 

We could probably find a way to kill 2 birds with one stone, as well as make this work for all structures.

**Comment by Ezoteric** [comment]
Yes but dont bundle them all under 1 pls :P

**Comment by FrankTCA** [comment]
Don't worry.

We're not evil.

**Comment by FrankTCA** [comment]
I'm going to close this issue and merge it with #885
