### ISSUE TITLE
[Bug] 1.16 - FixedTime does not accept -1 as a value in WorldConfig.ini

### ISSUE THREAD

**Issue by RnChan408** [PG85/OpenTerrainGenerator#889]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - 1.16.5-0.0.19

#### Forge Version
[36.2.8]

#### What other plugins are you running?
- abnormals_core-1.16.5-.3.30
- appleskin-forge-mc.1.16.x.2.1.0
- architectury-1.24.35-forge
- areas_1.16.5-2.8
- BetterStorageToo-1.16.5.6.1.1.0
- Bookshelf-Forge-1.16.5-10.3.29
- chiselsandbits-1.0.43
- cloth-config-4.11.26-forge
- collective-1.16.5-2.64
- configuration-1.16.5-1.2.1
- configured-1.2.0-1.16.3
- connectiblechains-1.2.0
- Contact-Forge-1.16.5-0.3.2-Beta
- createautomated-1.16.5-1.4.1
- create-mc1.16.5_v0.3.2f
- EnchantmentDescriptions-1.16.5-7.0.17
- FarmersDelight-1.16.5-0.5.1
- ferritecore-2.1.0-forge
- flywheel-1.16-0.2.3
- geckolib-forge-1.16.5-3.0.49
- grapplemod-1.16.5-v12
- incontrol-1.16-5.2.1
- jei-1.16.5-7.7.1.129
- kubejs-forge-1605.3.18-build.152
- MouseTweaks-2.14-mc1.16.2
- mutantmore-1.16.5-1.0.0
- Node-Wars-0.0.0 - Custom preset
- nopotionshift_1.16.4-1.6.1
- OpenTerrainGenerator-1.16.5-0.0.19
- OreTweaker-1.16.5-2.5.1
- Patchouli-1.16.4-53.2
- personality-1.16.5-1.0.2
- potionofbees-1.16.4-1.1.0.2
- ProperFiniteWater--mc1.16forge--1.01
- recall-1.3
- rhino-forge-1605.1.4-build.67
- shutupexperimentalsettings-1.0.3
- SilveroakOutpost-Forge-1.16.5-0.3.6-Beta
- smoothboot-forge-1.16.4-1.2.2
- swingthroughgrass-1.16.4-1.5.3
- the_bumblezone_forge-2.6.5+1.16.5
- twoplayersonehorse-1.16.4-2.0.2
- WorldEdit-CUI-FE3-1.16.5-3.0.9
- WorldEditExpressForge-1.16.5-36.1.0-1.3.1
- worldedit-mod-7.2.5-dist
- Xaeros_Minimap_21.21.0_Forge_1.16.5
- XaerosWorldMap_1.18.1_Forge_1.16.5

#### Description
The default value for FixedTime in WorldConfig.ini is 0 and does not accept -1.

The WriteAll comment says it defaults to -1 but does not accept -1.

1. Open and Navigate to a Preset WorldConfig.ini file.
2. Edit FixedTime setting to -1.
3. Boot up modded instance.
4. refresh or close and open the WorldConfig.ini file

**Comment by PG85** [comment]
Hey @Lucidcream , thanks for reporting this. We've already fixed this for 0.1.0, which will be released asap.
