### ISSUE TITLE
"CeilingBedrock: true" only goes up to 254

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#890]
For some reason the bedrock ceiling only extends to Y254 and normal surface blocks spawn on top of it, as well as mobs.

![2021-11-09_00 03 54](https://user-images.githubusercontent.com/23154920/140837516-f14dd0e4-fb0f-411a-b228-72f9a37e305d.png)

**Comment by FrankTCA** [comment]
Ah thx for adding this for me.

Josh said something about a comment being left as "won't fix" and a lighting issue.

**Comment by BiomeBundle** [comment]
There are still solid blocks at Y255 so I don't see how that can be an issue if its bedrock instead.

**Comment by Jishuna** [comment]
This is a comment from the source in 1.12
```
        // The "- 2" that appears in this method, comes from that heightCap -
        // 1 is the highest place where a block can be placed, and heightCap -
        // 2 is the highest place where bedrock can be generated to make sure
        // there are no light glitches - see #117
```
I believe the #117 mentioned is https://github.com/MCTCP/TerrainControl/issues/117

**Comment by BiomeBundle** [comment]
Not sure a 9 year old issue is the best indicator.

Does bedrock do something different with regards to lighting vs other solid blocks? Y255 is not empty, it's just surface blocks instead of bedrock.

**Comment by Jishuna** [comment]
Probably not, I imagine the issue was fixed some time in the last 9 years and we just never made the changes

**Comment by FrankTCA** [comment]
Should be a rather simple fix then. Lighting engine must've been changed a million times since the days of yore

**Comment by FrankTCA** [comment]
Should be resolved now.

**Comment by FrankTCA** [comment]
Also will mention no mobs spawn when the roof is filled with bedrock
