### ISSUE TITLE
Template biomes do not "inherit" the stone block from the biome they are imitating

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#892]
Example - Warped Forest is supposed to have Netherrack as its stone block. If you use a template biome to add the Warped Forest to an OTG world then it uses stone instead, with no way to configure it.

Vanilla Warped Forest:
![2021-11-09_22 23 25](https://user-images.githubusercontent.com/23154920/141014720-956930c4-3afc-462c-8d23-583740671a9b.png)

OTG Warped Forest (added with a template biome):
![2021-11-09_22 25 41](https://user-images.githubusercontent.com/23154920/141015300-3f74c805-2588-4ecc-bafd-1e166821d7b4.png)

**Comment by FrankTCA** [comment]
We good now.

**Comment by FrankTCA** [comment]
Will be fixed for 0.1.0
