### ISSUE TITLE
Misleading GUI

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#893]
In the forge single player world creation menu, leaving the overworld as "Non-OTG" and not clicking it to tell it what world to generate will generate an OTG world even though the GUI says "Non-OTG".

Example - go to create a world, assign an OTG world to the nether and then create the world. Overworld in the below example loaded as Skylands even though it said non-OTG:
![image](https://user-images.githubusercontent.com/23154920/141016708-7ba34c64-b50d-405e-a593-726144e87c0f.png)

Preferred behaviour would either be to prompt the user to set up the overworld generation properly, or to load the most logical non-OTG world (vanilla).

**Comment by FrankTCA** [comment]
Fixed.

**Comment by FrankTCA** [comment]
Will be fixed for 0.1.0
