### ISSUE TITLE
Template biomes not obeying worldconfig.ini settings for vanilla structures

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#894]
Modded and vanilla biomes added via templates do not allow you to disable vanilla structures, making it impossible to stop them from generating. This is a problem for skylands in particular.

MineshaftsEnabled: false
![image](https://user-images.githubusercontent.com/23154920/141017149-399ff624-0255-4708-9d8f-ae807444df41.png)

StrongholdsEnabled: false
![image](https://user-images.githubusercontent.com/23154920/141017230-b9337fac-2e60-4d09-ab16-a9f8dc01b310.png)

**Comment by FrankTCA** [comment]
Done.

**Comment by FrankTCA** [comment]
Will be fixed for 0.1.0
