### ISSUE TITLE
Template biomes dont work properly if the preset replaces the nether

### ISSUE THREAD

**Issue by BiomeBundle** [PG85/OpenTerrainGenerator#895]
If you load an OTG preset that uses template biomes as a nether replacement, the biomes will display properly in F3 but the whole world will be stone.

E.g. this is minecraft:crimson_forest
![2021-11-09_22 50 18](https://user-images.githubusercontent.com/23154920/141018922-d5e702c0-e60e-4513-87b4-9130e5ffd3d7.png)

The preset works fine if used as the overworld or as a dimension, just not if it is used as the nether.

**Comment by FrankTCA** [comment]
Good that this got fixed for my nether preset!

**Comment by FrankTCA** [comment]
Will be fixed for 0.1.0, thx pg
