### ISSUE TITLE
1.16 - Critical Bug with Moded Creature Spawning and Structures

### ISSUE THREAD

**Issue by Blunder-G** [PG85/OpenTerrainGenerator#896]
- [X] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [OTG for 1.16] Other - specify here

[Forge 36.2.8]

[Mod List: OTG, Far From Home, BYG, Alex's Creatures, Ice and Fire, Danny's Expension, Mowzie's Mobs, Optifine G8]

[Mobs from Vanilla and Mowzie's Mobs are spawn in OTG worlds but other moded creatures (Creatures from Danny's Expension, Alex's Mobs, Ice and Fire) not spawn. I tested with 4 presets (Biome Bundle, Vanilla Vistas, Dregora, Far From Home) and nothing is changed.]

[Also strcutures from Ice and Fire not generate as well.]

**Comment by PG85** [comment]
Hey @Blunder-G , 1.12.2 presets need to be updated for 1.16 before some of the features will work, see: https://openterraingen.fandom.com/wiki/Installation#Forge_Mod_Compatibility. Vanilla Vistas and Skylands will be available on curseforge soon, other presets are being updated.
