### ISSUE TITLE
Missing English translation file/names for some biomes

### ISSUE THREAD

**Issue by AngleWyrm10** [PG85/OpenTerrainGenerator#897]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - specify here 1.16.5-0.1.0

#### Forge or Spigot Versions
Forge v36.2.0

#### What other plugins are you running?
architectury-1.24.35-forge.jar
byg-1.3.5.jar
ftb-chunks-forge-1605.3.2-build.79.jar
ftb-library-forge-1605.3.4-build.81.jar
ftb-teams-forge-1605.2.3-build.38.jar
jei-1.16.5-7.7.1.130.jar
OpenTerrainGenerator-1.16.5-0.1.0.jar
OptiFine_1.16.5_HD_U_G8.jar

#### Description
Various biome names are displayed as variable names instead of biome names

![bug](https://user-images.githubusercontent.com/55937426/141670551-576d5694-ac43-4f5f-83b8-9d51412dbde6.png)

![bug](https://user-images.githubusercontent.com/55937426/141671161-405c3475-36c3-4b31-a8bc-e8a57d6d114d.png)

Here's a partial list screenshot from using [Nature's Compass](https://www.curseforge.com/minecraft/mc-mods/natures-compass) 
![bug](https://user-images.githubusercontent.com/55937426/141672008-c793efb9-1bc0-40ed-82ef-2722b5befb81.png)

**Comment by PG85** [comment]
Fixed for 0.1.1, available on CurseForge. We've also added instructions for preset developers using WorldPacker/PresetPacker.
