### ISSUE TITLE
[Forge] Recurrent Complex Crash on Startup (BiomeDict)

### ISSUE THREAD

**Issue by Sandriell** [PG85/OpenTerrainGenerator#9]
I am experiencing the following crash on startup

https://gist.github.com/Sandriell/5ee5113d7344dacbf038497866f7978d

It looks like this was reported about a month ago as well on both the [Recurrent Complex](https://github.com/Ivorforce/RecurrentComplex/issues/169) and [Terrain Control](https://github.com/MCTCP/TerrainControl/issues/518) githubs as well.

**Comment by PG85** [comment]
Hey, thanks for reporting this. Could you try v16 from https://minecraft.curseforge.com/projects/open-terrain-generator/files and tell me if that fixes the problem?

**Comment by Sandriell** [comment]
I removed Recurrent Complex from my pack, but i'm still getting the same kinds of crashes from other mods (BiomeDict related) using v16.

**Comment by PG85** [comment]
I've had multiple reports of the biomedict exception with different mods, have spent half a day testing but I cannot get it to crash. Do you know of a way to reproduce the bug?

**Comment by PG85** [comment]
Please try v17 at https://minecraft.curseforge.com/projects/open-terrain-generator/files/2413721 and tell me if that fixes the problem. Your existing worlds affected by the bug should work again with this build. Thanks!

**Comment by PG85** [comment]
Other users who were getting the same exception have reported it as being fixed by v17. Closing this issue, thanks for reporting!
