### ISSUE TITLE
BYG config datapack is not working in OTG worlds

### ISSUE THREAD

**Issue by Ezoteric** [PG85/OpenTerrainGenerator#900]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - specify here
1.16.5 0.1.0 (latest on curse)

#### Forge or Spigot Versions
Forge 1.16.5 36.2.0

#### What other plugins are you running?
Oh Biomes You Go 1.3.5 (latest)

#### Description
Using BYG own generated datapack where i cut down on the tree spawn (density) does not work when creating a world via OTG (tested with default and Vanilla Vistas( from curse)

[What did you expect to happen? - Explain what you expected to happen after performing the previously described steps]
Aspen forest should have no trees at all but it still gets its default config (not reading datapack it seems)

[Can you provide a Minimal, Reproducible Example? See here for details: https://stackoverflow.com/help/minimal-reproducible-example]
/gendata byg to get datapack (make sure you rework the directory cause it doesnt do that correctly) change tree count to 0, find biome you edited (i did aspen_forest) and check.

[And Delete the lines in square brackets!]
Default world with datapack:
![2021-11-15_06 51 11](https://user-images.githubusercontent.com/14137626/141731354-7d48ac87-c833-470d-88bc-39786e5a16d0.png)

OTG world with datapack:
![2021-11-15_07 10 06](https://user-images.githubusercontent.com/14137626/141731506-0f4178f1-ed13-4886-86b6-75c69c6c49be.png)

**Comment by Ezoteric** [comment]
Just to clarify, first pic is from my modpack, i did try with my modpack and without my modpack on OTG worlds but that doesnt change anything so i uploaded the OTG picture with a clean install with just OTG and BYG

**Comment by PG85** [comment]
Hey @Ezoteric , have done some testing and also can't get it to work. For OTG biomes, editing via datapack doesn't really make sense ofc, but for non-otg biomes used in OTG worlds that should work, will look at this asap.

**Comment by Ezoteric** [comment]
I know it wont work for OTG presets but this is the only way for BYG to edit their stuff, if this will never work via datapacks i have to file a issue to BYG so they can go back using normal configs like before datapacks were a thing.

That said, more stuff datapack related dont seem to work correctly, as i mentioned before the village overhaul datapacks also dont work as intended and neither does the settings for village distance via datapacks. 
Dont know if it would be related but there seems to be something fishy going on thats for sure ;)

Anyway take your time :)

**Comment by PG85** [comment]
Fixed for 0.1.2, to be released on the disc and/or curse asap. Let us know if it works for you, thanks!

**Comment by Ezoteric** [comment]
Fixed, thnx m8 :D
