### ISSUE TITLE
Mod ores dont spawn in template biomes (tested with VV)

### ISSUE THREAD

**Issue by Ezoteric** [PG85/OpenTerrainGenerator#901]
#### OTG Plugin or Mod
- [x] OTG Mod for Forge

#### OTG Version
- [x] Other - specify here
1.16.5 0.1.0

#### Forge or Spigot Versions
Forge 1.16.5 36.2.0

#### What other plugins are you running?
the ore mods are:
create-mc1.16.5_v0.3.2f
ImmersiveEngineering-1.16.5-5.0.4-139
dont spawn in biome mod:
byg-1.3.5 

#### Description

Mod ores dont spawn in VV's templated biomes that BYG uses

Launch VV use BYG and a mod that spawn ores and check any modded biome for mod ores

**Comment by PG85** [comment]
Hopefully this is fixed along with datapacks for 0.1.2 (to be released on the disc and/or curseforge asap). Give it a try and let us know if that fixes it, thanks!

**Comment by Ezoteric** [comment]
Fixed, thnx m8 :D
