### ISSUE TITLE
Big lag spike / fps drop when crossing chunks in non otg world.

### ISSUE THREAD

**Issue by SzczurekYT** [PG85/OpenTerrainGenerator#905]
#### OTG Plugin or Mod
- [ x ] OTG Mod for Forge

#### OTG Version
- [ latest 1.16.5 ] Other - specify here

#### Forge or Spigot Versions
forge 36.2.8

#### What other plugins are you running?
Dregora plugin
around 110 other mods. Can provide a list if needed

#### Description

Two things to note:
1. Not sure if it's dregora fault or otg fault so I will report the issue on both.
2.  The issue occurs in normal non otg worlds, any seed. Looks like in otg worlds it's fine.
I'm testing custom self made modpack and found an issue.
The thing is that when I cross chunks there is pretty big fps drop \ lag spike. Only in non otg worlds.
Removing the mod fixed the issue.

**Comment by PG85** [comment]
Hey @SzczurekYT, will need some more info, how exactly are you testing this? When you say it occurs in normal non-otg worlds, do you mean a world not created using the OTG world type / world creation menu? In that case, OTG shouldn't be doing anything ofcourse.

**Comment by SzczurekYT** [comment]
Exactly, I had set world type to default and passing chunks was laggy. I wasn't sure what mod causes this and one time I tried remioving otg and dregora and it worked. I can provide mods list or something else if need.

**Comment by PG85** [comment]
I've done some testing with Vanilla Vistas vs a default world and also without OTG installed, with a number of other mods installed. I don't see any difference in performance. In all cases, when exploring tps decreases until MC has caught up again generating chunks. I suspect this may be some interaction between specific mods, could you try to verify with just OTG and/or specific mod combinations? Thanks!

* You may also want to check if the log is spamming any errors.

**Comment by SzczurekYT** [comment]
Yes, that's very probable that it's specific mod combination, when I will be at my pc I will do some more testing and try to find informations that might be useful for you.
Thanks

**Comment by PG85** [comment]
If you can find steps to reproduce this, or find the specific mod combination causing the issue, feel free to reopen this issue.

*Lycanites+Repurposed structures has been reported to cause lag, presets need to be updated to exclude modded nether/end biomes to fix this. This should no longer be a problem once Lycanites updates.
