### ISSUE TITLE
Cannot turn off canyon generation

### ISSUE THREAD

**Issue by merino0404** [PG85/OpenTerrainGenerator#906]
#### OTG Plugin or Mod

- [x] OTG Mod for Forge

#### OTG Version

- [ 1.16.5-0.1.3 ] Other - specify here

#### Forge or Spigot Versions

forge 36.2.18

What other plugins are you running?

OpenTerrainGenerator only

#### Description

WorldConfig.ini
   RavinesEnabled: false

![2021-11-23_11 23 13](https://user-images.githubusercontent.com/94880848/142965438-05650d98-e155-434a-b0c2-0b01705e1310.png)

**Comment by PG85** [comment]
Hi @merino0404 , thanks for reporting. Looks like this bug was introduced with 0.1.2, will be fixed for 0.1.4, to be released a.s.a.p.
