### ISSUE TITLE
ContinueNormal (HybridMode) stopped working for 1.16.5

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#907]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [1.16.5-0.1.4] Other - specify here

#### Forge or Spigot Versions
Forge 36.2.2 for MC 1.16.5

#### Description
ContinueNormal does not work anymore.

Upon teleporting outside the edges of the map (e.g. 20.000 200 0) presents the user with the default ocean biome. The same happens when teleporting to area's where there are no biomes defined. In short, continue normal stopped working.

This issue is reproducible with any map that utilizes the continuenormal mode whilst using from image. E.G. Dregora which can be found here: https://www.curseforge.com/minecraft/mc-mods/dregora/files/3515674

**Comment by PG85** [comment]
Thanks for reporting, fixed for 0.1.6.
