### ISSUE TITLE
Missing/Incomplete Forge TerrainGen Events (Quark)

### ISSUE THREAD

**Issue by zakkgcm** [PG85/OpenTerrainGenerator#91]
Latest Affected Minecraft Version: 1.12.2
Latest Affected OTG Version: 1.12.2 v2

Some Forge terrain gen events aren't correctly fired by OTG during terrain generation. This currently breaks mods relying on these events. For example, _OreGenEvent.GenerateMinable_ isn't fired with the GRANITE, ANDESITE, or DIORITE types. This breaks Quark's marble, limestone, and revamped stone generation.
The main culprit looks to be _platforms/forge/src/main/java/com/pg85/otg/forge/events/OTGToForgeEventConverter.java_. Some additional logic here should fix the issue.

**Comment by PG85** [comment]
Hey, thanks for reporting this, that's very helpful :). Fixed in 1.12.2 v3 / 1.11.2 v9 (release asap).
