### ISSUE TITLE
Bug: /locate not working for some Forge mods

### ISSUE THREAD

**Issue by FrankTCA** [PG85/OpenTerrainGenerator#911]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x] 1.16.5
- [ ] 1.17.1
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
Forge 1.16.5 / 36.2.8

#### What other plugins are you running?
1) The Graveyard - 2.1
2) Awesome dungeons - 1.1.2
3) Illagers plus - 1.7.2

#### Description
A tester of ours, haeihaeihaei#4660, reported to the discord that he had experienced issues with structures.

Apparently, certain mods mess up the /locate command, presumably, it says where the structures would be located if this were vanilla, but they wind up being in different places entirely.

**Comment by PG85** [comment]
Vanilla apparently does this sometimes due to a bug. Without more information (mods/structures, repro steps) can't do much about this.
