### ISSUE TITLE
Problem while connecting on server

### ISSUE THREAD

**Issue by YohannFOS** [PG85/OpenTerrainGenerator#92]
Hi,

Sorry for my english, i'm french.

I use OTG and Biome Bundle without any problem since few hours. Now, it's stop working, and i'm back to vanilla rendering, with vanilla biome's colours, for exemple.

OTG seems to stop running when i connect to my server. The error message in MultiMC console is: **[13:38:22] [Netty Client IO #14/FATAL] [OTG]: Failed to receive packet .** I didn't find information about this message on internet.

The full message is:

> [13:38:22] [main/INFO]: Connecting to s67.location-minecraft.com., 26270
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Server protocol version 2
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Injecting existing registry data into this client instance
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:frozen_forest
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:forestsakurahills
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:swamplandspooky
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:autumnal_woods
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:webbed_forest
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:autumnal_woods_m
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:savannaedge
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:forestender
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:tundra
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:forestconifer
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:forestsakura
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:uplands
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:autumnal_woods_hills
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:tropical_savanna
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:temperateplainsautumnal
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:steppe
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Registry Biome: Found a missing id from the world openterraingenerator:forestenchanted
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Applying holder lookups
> [13:38:22] [Netty Client IO #14/INFO] [FML]: Holder lookups applied
> [13:38:22] [Netty Client IO #14/INFO] [FML]: [Netty Client IO #14] Client side modded connection established
> [13:38:22] [Netty Client IO #14/FATAL] [OTG]: Failed to receive packet
> [13:38:22] [Netty Client IO #14/FATAL] [OTG]: io.netty.util.IllegalReferenceCountException: refCnt: 0
> 	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408)
> 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1394)
> 	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687)
> 	at io.netty.buffer.ByteBufInputStream.read(ByteBufInputStream.java:168)
> 	at java.io.DataInputStream.readInt(Unknown Source)
> 	at com.pg85.otg.forge.network.DimensionSyncPacket$Handler.handleClientMessage(DimensionSyncPacket.java:56)
> 	at com.pg85.otg.forge.network.DimensionSyncPacket$Handler.handleClientMessage(DimensionSyncPacket.java:49)
> 	at com.pg85.otg.forge.network.AbstractMessageHandler.onMessage(AbstractMessageHandler.java:24)
> 	at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:56)
> 	at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:36)
> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
> 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
> 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:274)
> 	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:99)
> 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147)
> 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49)
> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleClientSideCustomPacket(NetworkDispatcher.java:383)
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:269)
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:72)
> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 	at java.lang.Thread.run(Unknown Source)
> 
> 
> [13:38:23] [main/INFO]: Loaded 122 advancements
> [13:38:41] [main/INFO] [FML]: Applying holder lookups
> [13:38:41] [main/INFO] [FML]: Holder lookups applied

There is a solution for this issue?

Thanks !

**Comment by BrainStone** [comment]
I'm having this issue too. It appeared when updating my client from an outdate build to the recommended Forge build.

**Comment by PG85** [comment]
Thanks for reporting this, fixed in 1.11.2 v9 / 1.12.2 v3 (will be released asap).
