### ISSUE TITLE
Biome Generation Issue

### ISSUE THREAD

**Issue by Geometrycraft68** [PG85/OpenTerrainGenerator#922]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.16.5
- [ ] 1.17.1
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [x] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
[The full Spigot Server or Forge versions that you are running]

#### What other plugins are you running?
[List of your Mods or Plugins installed, ideally with versions]

#### Description
[What is happening? - Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures;)]

[What did you expect to happen? - Explain what you expected to happen after performing the previously described steps]

[Can you provide a Minimal, Reproducible Example? See here for details: https://stackoverflow.com/help/minimal-reproducible-example]

[And Delete the lines in square brackets!]
An issue where only a small amount of biomes spawn when editing any file on forge 1.12.2-v6

**Comment by PG85** [comment]
Hey @Geometrycraft68 , for problems creating presets please join us on the Discord, the git is for technical issues/crashes. thanks!

Discord: https://discord.gg/UXzdVTH

**Comment by Geometrycraft68** [comment]
I was in your server but when I tried addressing this issue no one listened to me and said I was doing something wrong, so I left.

**Comment by BiomeBundle** [comment]
You were helped by multiple people and even said one of your issues was fixed (which was also a config issue).

What you described to us in the discord was not an OTG bug but an issue with how you had configured your preset.
