### ISSUE TITLE
Sponge support

### ISSUE THREAD

**Issue by mblob** [PG85/OpenTerrainGenerator#93]
Will you provide at some point some sponge support ?
Like Use OTG and presets as regular generator for sponge.

If installed it works but not alongside other generators.

**Comment by PG85** [comment]
Hey there, sorry to disappoint you but OTG does not work together with other biome mods. Concerning Sponge, OTG supports Forge so theoretically SpongeForge should have no problem with it. If it does then I assume that should be a problem with Sponge itself, not OTG. I can always take a look at bug reports ofc but there are currently no plans to support Sponge explicitly (I unfortunately don't have the time, can barely manage Forge and Bukkit).
