### ISSUE TITLE
Feature: New Mascot for OTG

### ISSUE THREAD

**Issue by FrankTCA** [PG85/OpenTerrainGenerator#932]
#### Is your feature request related to a problem? Please describe.
There is not a mascot for OTG currently.

#### Describe the solution you'd like
Introducing Bob: the talking, smiling Bob config.

#### Describe alternatives you've considered
Being boring and not having a mascot, but that would make Bob sad :(

#### Description aka Additional context
Bob:
![bob](https://user-images.githubusercontent.com/19649826/147411870-86756812-bf00-4613-a857-7fd1d9d7539e.png)

**Comment by SXRWahrheit** [comment]
pls no
