### ISSUE TITLE
Option to disable certain structures in a easy way.

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#934]
#### Is your feature request related to a problem? Please describe.
Several of Dregora's users asked me they wanted to disable certain structures.

#### Describe the solution you'd like
A way to easily disable structures, such as having a file with structures (one per line) e.g. Spawnhex when someone wants that structure disabled. This file can then be dropped beside worldconfig.ini or even higher up in the folder structure where the file would be named PresetDisabledStructures.
This will make it easier for modpack developers to make their modpacks. Preset developers can provide a file with commented out structures for ease of use and possibly short descriptions of these structures.

#### Describe alternatives you've considered
Guiding people to biomeconfigs and individually disabling each structure in each config,

**Comment by PG85** [comment]
Structure files present in the preset that are not used should ofcourse be removed by the preset creator to reduce filesize and startup/loading times. Creating a setting specifically for this creates an incentive for preset creators to create a mess, so not a huge fan of that idea :P. That being said, this would be possible using #590 .
