### ISSUE TITLE
Vampire forest isn't generate in OTG world

### ISSUE THREAD

**Issue by Skyere** [PG85/OpenTerrainGenerator#937]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.16.5
- [ ] 1.17.1
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [x] 1.12.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

[List of your Mods or Plugins installed, ideally with versions]
Vampirism-1.12.2-1.6.2.jar
OpenTerrainGenerator-1.12.2-v9.4.jar
Wildlands-1.12.2-alpha-0.1.jar

#### Description
[What is happening? - Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures;)]
Vampire forest from Vampirism mod isn't generate in OTG world

**Comment by Skyere** [comment]
Found this error
![image](https://user-images.githubusercontent.com/70713060/148650478-8d918d35-a945-441d-806f-fa575df34abc.png)

**Comment by Jishuna** [comment]
Modded biomes do not generate in OTG worlds unless you add your own version to the preset, making use of ReplaceToBiomeName. Alternatively you can use a vanilla overworld and add an OTG world as a dimension using the ‘O’ button in-game.
