### ISSUE TITLE
A Bug From Preset

### ISSUE THREAD

**Issue by ZDN1942** [PG85/OpenTerrainGenerator#938]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x] 1.16.5
- [ ] 1.17.1
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
[forge-1.16.5-36.2.20]

#### Server/Client Log
[[crash-2022-01-13_18.43.20-server.txt](https://github.com/PG85/OpenTerrainGenerator/files/7868394/crash-2022-01-13_18.43.20-server.txt)]

#### What other plugins are you running?
[byg-1.3.5&Far_From_Home-Premium-1.16.5-7.5]

#### Description
[The default structure will not be generated.It's triggered by users need to trade with the cartographer until they can sell structural maps or use the relevant locate command.]

[Game crash.]

[Unable to provide due to insufficient technology.]

**Comment by SXRWahrheit** [comment]
This is not an OTG bug.

**Comment by FrankTCA** [comment]
This _is_ an OTG bug, it was just explained badly.

I talked to the person on the FFH discord. Here's what's going on:

FFH has woodland mansions disabled because they look bad. Upon meeting a cartographer villager and trading for a woodland explorer map, the server crashes due to the lack of woodland mansions. We need to find a way to make woodland explorer maps not crash the game when mansions are disabled.

**Comment by FrankTCA** [comment]
This is a Mojang bug: https://www.reddit.com/r/Minecraft/comments/kkqxfj/our_server_crashes_when_trading_with_a/

We may add a try/catch for it in the future.

**Comment by SXRWahrheit** [comment]
The bug was a vanilla bug fixed in 1.18.1. We might add an OTG-sided solution for worlds with structures disabled in them in 1.16.5 and 1.17.1 to facilitate players using mods on those versions.

https://bugs.mojang.com/browse/MC-130449
