### ISSUE TITLE
OTG:Skylands with Astral Sorcery stuck on generating terrain

### ISSUE THREAD

**Issue by Dragnier** [PG85/OpenTerrainGenerator#95]
OTG - 1.12.2-v2
OTG:Skylands - 1.12.2-v5
Forge - 14.23.1.2562
Astral Sorcery - 1.12.2-1.8.3

I had to use task manager to end task and got this crash report: https://gist.github.com/Dragnier/bf3ffae0b96b09425ebadf4b3493ff51

Turning off Astral Sorcery allows the terrain to generate and the game to load.

**Comment by Dragnier** [comment]
Just noticed this also happens with OTG: The Void. If I turn off Astral Sorcery's world gen in the overworld, this doesn't happen... but then you also can't use Astral Sorcery crafting tables in the overworld at all.

I have set Astral Sorcery generation to work in the Aether Legacy dimension and it's just fine, so it has to be something about your mods that causes Astral Sorcery world gen not to work rather than something on their end.

**Comment by PG85** [comment]
Hey, thanks for reporting this, this is fixed in 1.12.2 v3 / 1.11.2 v9 (release asap).
