### ISSUE TITLE
[Bug]: The server does not start

### ISSUE THREAD

**Issue by Qeatrix** [PG85/OpenTerrainGenerator#958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

OTG does not allow the server to start and writes an error

### Expected Behavior

There will be no errors in OTG and the server will start

### Which platforms have you reproduced this issue using?

Forge Multiplayer

### OTG Version

OTG 1.16.5 0.1.10

### Platform Version

Java Verison: 17.0.3, N/A This server is running Magma version 1.16.5-36.2.33-7cf72f3c (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge Version 36.2.33-7cf72f3c)

### Steps To Reproduce

1. Create a server on the Magma core
2. Move Open Terrain Generator to the mods folder
3. Start the server

### Log file

https://paste.denizenscript.com/View/96394

### Anything else?

I'm trying to run a server with some other mods, including Dregora, which depends on Open Terrain Generator. (Without Open Terrain Generator and Dregora, the server starts normally). A log file that includes all mods: https://paste.denizenscript.com/View/96395
the sh script with which I start the server:
`java -Xms128M -Xmx8192M --add-exports=java.base/sun.security.util=ALL-UNNAMED --add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming --add-opens=java.base/java.util.jar=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -jar Forge.jar nogui`

**Comment by authvin** [comment]
We do not support hybrid servers
