### ISSUE TITLE
OTG:Biome Bundle, Compat with Abyssalcraft Biomes in Overworld?

### ISSUE THREAD

**Issue by KAfable** [PG85/OpenTerrainGenerator#96]
Abyssalcraft inserts Darklands Forest, Darklands Highland, Darklands Mountains, and Darklands Plains into the overworld. However it doesn't seem to generate with BiomeBundle, afaik Shinoow made it so that it will generate when detecting the Surface World Provider, is there a way to add biome compat for these two mods?

**Comment by PG85** [comment]
Hey, sorry to have to disappoint you but OTG does not support adding of other mod's biomes to OTG worlds. The feature has been requested many times but unfortunately it would be a lot of work and we just don't have the time for it.
