### ISSUE TITLE
[Bug]: my pp small

### ISSUE THREAD

**Issue by CockAndBallTortureFromWikipediaTheFree** [PG85/OpenTerrainGenerator#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Small

### Expected Behavior

Big

### Which platforms have you reproduced this issue using?

Forge Single Player, Forge Multiplayer, Spigot/Paper

### OTG Version

OTG 1.18.2 0.0.27

### Steps To Reproduce

1. Bed me
2. See result
3. Number 3
4. Number 4

### Log file

https://paste.denizenscript.com/View/101861

### Anything else?

Yes

**Comment by Erisfiregamer1** [comment]
yes
