### ISSUE TITLE
Bug - Crash Exception ticking world.

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [PG85/OpenTerrainGenerator#97]
Local Server Crash with`Exception ticking world` whilst standing still, looking at JourneyMap whilst the world pre-generated in SP, using BBv6.1

@PG85 This error does not happen with every seed I try, some seeds cause this to happen sooner than later so I am thinking there is an issue with a biome config.

[https://pastebin.com/aSF45J8t](url)

**Comment by PG85** [comment]
Hey thanks for reporting this, unfortunately this appears to be a threading/concurrency issue that occurs only rarely. I have not been able to find a cause for it yet. If you find a way to reliably reproduce this problem, please let me know.

**Comment by PG85** [comment]
Hoping this has already been fixed for v7, if not, feel free to open a new ticket.
