### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kasia1403** [PG85/OpenTerrainGenerator#983]
https://mclo.gs/AOcufXw
[latest.log](https://github.com/PG85/OpenTerrainGenerator/files/10460415/latest.log)

**Comment by authvin** [comment]
This crash is not immediately an OTG crash, it is not easy to see what is happening, there is little information about it, and there are far too many mods installed to begin trying to replicate the crash on our end. Plus, this is for 1.12.2. I don't think this is something we can look at without more concrete info, and ideally a minimal reproducible example.

**Comment by Kasia1403** [comment]
I posted the same crash on Misc Tweaks Github. And what is reproducible example ?
