### ISSUE TITLE
[Bug]: Not sure if bug; gravel generating in large patches in the middle of a wheat field

### ISSUE THREAD

**Issue by darchitectlp** [PG85/OpenTerrainGenerator#989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to understand why some biomes are generating a patch of gravel in the middle of them. I've seen this happen repeatedly in different areas. Using Biome_Bundle_O_Plenty-1.12.2_v1.0.jar

This is currently in:
TemperatePlainsOakGrove

![screenshot01](https://user-images.githubusercontent.com/36024900/219852095-24fc4665-8c27-4012-a89d-441e7234d18e.jpg)

### Expected Behavior

Not to have a gravel patch, but for the barley or grass to continue.

### Which platforms have you reproduced this issue using?

Forge Single Player

### OTG Version

OpenTerrainGenerator-1.12.2-v9.4

### Steps To Reproduce

Use Biome Bundle O'Plenty

### Log file

https://paste.denizenscript.com/View/106361

**Comment by darchitectlp** [comment]
Ok, feel free to close this, unless @MCPitman you want to fix the BC files. I sent you a PM over curse. Pasting it here in case you don't see that one:

> 
> Hey so I've been trying to figure out why the Pasture and Lavender Fields biomes keep getting ruined (subjectively) by these huge gravel and stone patches running through the middle of them. Turns out the TemperatePlainsOakgrove.bc and RockyPlainsSmall.bc still have their surface block set to gravel and stone, respectively. Don't know if you want to update, but I changed it to dirt in mine (and think it looks much better). I'm wondering if you did it intentionally, though, because the very first image you feature on your page is a BOP pasture with a huge gravel streak running through the middle of it. The border biomes for those two both use the correct "GRASS" surface block.
> 
>  
> 
> Just FYI. Thanks again for doing this! Also, do you know how to stop the crazy prismarine and diorite ocean islands from forming?

**Comment by authvin** [comment]
Glad you found a fix, I doubt it'll be updated since the project is quite old at this point but at least now someone can find the solution if they need it ^^
