### ISSUE TITLE
[Bug]: Crash to Desktop when generating preset as dimension using modded ores on Forge 1.12.2

### ISSUE THREAD

**Issue by jhammerberg** [PG85/OpenTerrainGenerator#998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Crash to desktop when generating preset as the dimension using modded ores on Forge 1.12.2. Specifically, I get this crash using the Just Stargate Mod version v4.11.0.8. If this is an issue that has to be fixed with that mod, tell me and I'll open an issue over there.

### Expected Behavior

The mod to not crash?

### Which platforms have you reproduced this issue using?

Forge Single Player, Forge Multiplayer

### OTG Version

OTG 1.12.2 v9.5

### Steps To Reproduce

1. Install the Just Stargate Mod and Open Terrain Generator
2. Using the OTG O menu, create a new dimension using any OTG preset that doesn't modify ore generation
3. TP to the dimension
4. Crash to desktop

### Log file

[2023-06-30-1.log](https://github.com/PG85/OpenTerrainGenerator/files/11913136/2023-06-30-1.log)

### Anything else?

The game doesn't crash when re-opening the world after the game crashes. I have tried disabling JSG ore generation but it doesn't seem to change anything at all.

**Comment by SXRWahrheit** [comment]
Please note that 1.12.2 is EOL and unlikely to receive support. This issue may be caused by a mod conflict and we recommend attempting to reproduce it with other mods to identify whether it is an OTG issue or an issue with a different mod, as no other reports of issues in this category have been submitted in quite some time.

**Comment by SXRWahrheit** [comment]
Additionally, the actual error here appears to be caused by the ore mod, not by OTG. We can't provide targeted support for modpacks on 1.12 at this point and you'll need to isolate the issue to demonstrate it is an OTG problem.

**Comment by SXRWahrheit** [comment]
Log for ease of access: https://paste.denizenscript.com/View/111739
